### ISSUE TITLE
Issue about the Chinese character

### ISSUE THREAD

**Issue by rylanchiu** [amueller/word_cloud#101]
Sorry for disturbing you again. But this time I really cannot help it. I try to call the method of generate_from_frequencies(frequencies) but still failed. What I get is : 
![fail](https://cloud.githubusercontent.com/assets/10586781/11211710/57ac8d6a-8d6c-11e5-9bc2-f17555e55640.png)
My code is as below: 
    

    d = path.dirname('raptle/rap_song/pic/')
    rapper_mask = np.array(Image.open(path.join(d, "default-rapper_0.png")))
    wc = WordCloud(background_color="white", max_words=2000, mask=rapper_mask)

    text = [('搞笑',3),('不要',2),('坏人',3),('变态',1),('哈哈',3),('快点',4)]
    wc.generate_from_frequencies(text)
    wc.to_file(path.join(d,"rapper1.png"))

Thank you very very much!

**Comment by amueller** [comment]
you need to use a font that supports your characters.
See http://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud

You need to pass the full absolute path to a ttf font as ``font_path``.

**Comment by rylanchiu** [comment]
@amueller  Yes! Now it works! Thank you for your great work!

**Comment by amueller** [comment]
:)

**Comment by brucewzp** [comment]
@rylanchiu can you tell me which font you choose?I tried but still problem.
