### ISSUE TITLE
got an unexpected keyword argument 'relative_scaling' from simple.py

### ISSUE THREAD

**Issue by qingkaikong** [amueller/word_cloud#102]
I installed from pip, and got the following error when I run the simple.py example, all the other examples works fine:
Traceback (most recent call last):
  File "./simple.py", line 26, in <module>
    wordcloud = WordCloud(max_font_size=40, relative_scaling=.5).generate(text)
TypeError: __init__() got an unexpected keyword argument 'relative_scaling'

**Comment by amueller** [comment]
That's because I didn't upload the current version to pipy yet. I'll do that.

**Comment by amueller** [comment]
try again :)

**Comment by qingkaikong** [comment]
Great, thanks, now it works!

On Wed, Nov 18, 2015 at 11:08 AM, Andreas Mueller <notifications@github.com>
wrote:

> try again :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amueller/word_cloud/issues/102#issuecomment-157825050>
> .
>



-- 
Qingkai KONG
Ph.D Candidate
Seismological Lab
289 McCone Hall
University of California, Berkeley
