### ISSUE TITLE
Not handling contractions properly

### ISSUE THREAD

**Issue by cpenepent** [amueller/word_cloud#104]
I've looked around but haven't been able to find anyone else with a similar issue, so I assume it's a problem with my code.  I could just strip out apostrophes entirely but I'd prefer not to if I don't have to.  This is what I'm getting:

![wordcloud](http://i.imgur.com/sciUOQK.png)

(Not sure what the white border is about, a matplotlib thing I'm guessing?)

I'm grabbing posts from the Tumblr API, my function input here is a list of "post" elements from "response" elements (see: https://www.tumblr.com/docs/en/api/v2#text-posts).  The API uses Unicode for everything (text posts, tags, even the dictionary keys for the JSON response object), hence the encoding.

```python
def get_text_posts(posts):
	text_posts = {}
	for p in posts:
		if u'body' in p:
			post_id = str(p[u'id'])
			text = p[u'body'].encode('utf-8','replace')
			if '`' in text: #standardize apostrophes
				text = text.replace('`','\'')
			text_posts[post_id] = str.lower(text)

#master_textposts is a dictionary mapping post ids to strings
def generate_wordcloud(master_textposts):
	text = '\n'.join(master_textposts.values())
	wordcloud = WordCloud().generate(text)
	plt.figure()
	plt.imshow(wordcloud)
	plt.axis("off")
	plt.show()
```

Could something with my text encoding chicanery here be causing problems when I send the posts to Wordcloud?  My comprehension of text encoding is admittedly shoddy at best.

**Comment by amueller** [comment]
So you want a contraction to be a single token? so ``I'm`` should stay ``I'm``?
Actually, It looks like it should.
The regex that is used is the following:
```python
import re
text = "Isn't it a great day?"
re.findall(r"\w[\w']*", text) 
```
> ["Isn't", 'it', 'a', 'great', 'day']

Can you give an example of a string that isn't processed properly?
You can try calling ``re.findall`` on it with the regex to see what's happening.

**Comment by cpenepent** [comment]
Yeah, after I posted this I wrote a few sentences with plenty of contractions and repeated words so I could test it, and everything was fine.  I'm thinking the issue is that the contractions I'm getting contain the Unicode character "RIGHT SINGLE QUOTATION MARK" (U+2019) and I just haven't managed to get those replaced with an apostrophe.

Test File:
```python
# -*- coding: utf-8 -*-
import re
text = "Isn’t it a great day?".decode('utf-8')
print re.findall(r"\w[\w']*", text)
```

Output:
```python
[u'Isn', u't', u'it', u'a', u'great', u'day']
```

**Comment by amueller** [comment]
hm can't you use ``replace``? or just add it into the ``[]``?

**Comment by cpenepent** [comment]
Looks like that solved it, and I think I finally get how Python does encoding stuff.  I feel like Neo at the end of the Matrix.

```python
# -*- coding: utf-8 -*-
#buncha other code here
if u'body' in p:
	post_id = str(p[u'id'])
	text = p[u'body']
	rsqm = '’'.decode('utf-8') #U+2019: right single quotation mark
	if rsqm in text:
		text = text.replace(rsqm,'\'')
	text_posts[post_id] = str.lower(text.encode('utf-8','replace'))
```

**Comment by amueller** [comment]
glad you figured it out :)
