### ISSUE TITLE
Failed building wheel for wordcloud

### ISSUE THREAD

**Issue by agarnitin86** [amueller/word_cloud#105]
Trying to install wordcloud on windows 7. Getting the following error
Failed to build wordcloud
Installing collected packages: wordcloud
  Running setup.py install for wordcloud
    Complete output from command C:\Users\nitin.agarwal\AppData\Local\Continuum\
Anaconda3\python.exe -c "import setuptools, tokenize;**file**='C:\Users\NITIN~
1.AGA\AppData\Local\Temp\pip-build-r2gzu169\wordcloud\setup.py';exec(compi
le(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **fil
e**, 'exec'))" install --record C:\Users\NITIN~1.AGA\AppData\Local\Temp\pip-gdv7
89h9-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building 'wordcloud.query_integral_image' extension
    error: [WinError 2] The system cannot find the file specified

```
----------------------------------------
```

Command "C:\Users\nitin.agarwal\AppData\Local\Continuum\Anaconda3\python.exe -c
"import setuptools, tokenize;**file**='C:\Users\NITIN~1.AGA\AppData\Local\T
emp\pip-build-r2gzu169\wordcloud\setup.py';exec(compile(getattr(tokenize, 'op
en', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install -
-record C:\Users\NITIN~1.AGA\AppData\Local\Temp\pip-gdv789h9-record\install-reco
rd.txt --single-version-externally-managed --compile" failed with error code 1 i
n C:\Users\NITIN~1.AGA\AppData\Local\Temp\pip-build-r2gzu169\wordcloud

**Comment by amueller** [comment]
How are you trying to install? ``pip install wordcloud`` ?

**Comment by agarnitin86** [comment]
I have tried two methods : 
1) pip install wordcloud
2)sudo pip install -r requirements.txt
   python setup.py install

**Comment by amueller** [comment]
And you get the same error both times? And the second method is with current master?

**Comment by agarnitin86** [comment]
Yes, I get the same error. I used the current master

**Comment by agarnitin86** [comment]
This is what i get when i use the second method:
What i understand is that the problem is same. I don't understand which file is missing.

running install
running build
running build_py
creating build
creating build\lib.win-amd64-3.5
creating build\lib.win-amd64-3.5\wordcloud
copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.5\wordcloud
copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.5\wordcloud
copying wordcloud\__init__.py -> build\lib.win-amd64-3.5\wordcloud
copying wordcloud\stopwords -> build\lib.win-amd64-3.5\wordcloud
copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.5\wordcloud
running build_ext
building 'wordcloud.query_integral_image' extension
error: [WinError 2] The system cannot find the file specified

**Comment by amueller** [comment]
Either the generated C file, or maybe a compiler? Do you have a C compiler installed?

**Comment by milonimrod** [comment]
I had the same error on Windows 7. The solution for me was to install: https://www.microsoft.com/en-us/download/confirmation.aspx?id=44266

**Comment by amueller** [comment]
Maybe we should add this to the installation instructions? That is a requirement for any "fast numerics" package, so I naively assumed people had that.

**Comment by agarnitin86** [comment]
I also tried downloading and installing vc for python (mentioned in the
link), but it is already installed their on my system.

Thanks

Nitin Agarwal
Analyst
Fractal Analytics

**Comment by amueller** [comment]
It is apparently not found, though. I'm not super familiar with windows packaging.

Maybe try to build a minimal cython file like here: http://stackoverflow.com/questions/24291506/building-minimal-cython-file-with-python-3-3-anaconda-under-windows-7

make sure the compiler is in the path. And google around?

**Comment by spiridonovpolytech** [comment]
If you are running Python 3.5 you need VS2015. When you install it you have to make sure you select "Common Tools for Visual C++ 2015" under Programming Languages/Visual C++. If you already installed VS2015, you need to do Change/Modify from Programs and Features under Control Panel. This worked for me. For reference, I'm running Anaconda3 2.4.1 with Python 3.5.1 x64. Hope this helped.

**Comment by freytheviking** [comment]
This happened to me too. Is there a detailed instructions of how to do it using Visual Studio?

**Comment by amueller** [comment]
How to upload a conda wheel or how to build wordcloud? First I don't know, second, not unless you like to write one ;)

**Comment by bishonen** [comment]
You'll find the wheel file over at : http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by atlrwt** [comment]
I just met the same problem when I want to install wordcloud to my python3.6 at win10, and after searching on the google I found a method which successfully solved my question: click the url "http://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud"  to download the wheel file which you want to install, and then use "pip install XXXXX" to install it.

**Comment by amueller** [comment]
readme suggests the gohlke wheels now.

**Comment by OsamaHamdyOsman** [comment]
same here for python 3.7 and windows 10

ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: pillow, wordcloud
  Running setup.py install for wordcloud: started
    Running setup.py install for wordcloud: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Semseman\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Semseman\\AppData\\Local\\Temp\\pip-req-build-wa0_ta4v\\setup.py'"'"'; __file__='"'"'C:\\Users\\Semseman\\AppData\\Local\\Temp\\pip-req-build-wa0_ta4v\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Semseman\AppData\Local\Temp\pip-record-rhqgbcsd\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Semseman\AppData\Local\Temp\pip-req-build-wa0_ta4v\
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\wordcloud
    copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.7\wordcloud
    copying wordcloud\tokenization.py -> build\lib.win-amd64-3.7\wordcloud
    copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.7\wordcloud
    copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.7\wordcloud
    copying wordcloud\_version.py -> build\lib.win-amd64-3.7\wordcloud
    copying wordcloud\__init__.py -> build\lib.win-amd64-3.7\wordcloud
    copying wordcloud\__main__.py -> build\lib.win-amd64-3.7\wordcloud
    copying wordcloud\stopwords -> build\lib.win-amd64-3.7\wordcloud
    copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.7\wordcloud
    UPDATING build\lib.win-amd64-3.7\wordcloud/_version.py
    set build\lib.win-amd64-3.7\wordcloud/_version.py to '1.5.0.post41+g32f5d2a'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Semseman\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Semseman\\AppData\\Local\\Temp\\pip-req-build-wa0_ta4v\\setup.py'"'"'; __file__='"'"'C:\\Users\\Semseman\\AppData\\Local\\Temp\\pip-req-build-wa0_ta4v\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Semseman\AppData\Local\Temp\pip-record-rhqgbcsd\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by Victor-Munoz-Albornoz** [comment]
The solution of **atlrwt** works!

**Comment by amueller** [comment]
@Victor-Munoz-Albornoz @OsamaHamdyOsman are you using 32 bit python? If so, why?

Though it looks like @OsamaHamdyOsman is using 64 bit. How did either of you try to install?

This issue is from 2015. We now have wheels for windows and this should definitely not happen if you try to pip install.

**Comment by Nurmukhamed1** [comment]
I do not know what to do after installing wordcloud from this page. Should I installed .whl file replace to somewhere?

**Comment by saktisundar** [comment]
**@atlrwt**  the package is not installing.

**Comment by NiyongaboEric** [comment]
This solution works from [lifesaver](https://lifesaver.codes/answer/importerror-cannot-import-name-wordcloud-123).  I assume python3 is already available. Using `homebrew` to install `python` works magically. 
`python3 -m pip install wordcloud`
