### ISSUE TITLE
Installation failed with Python 2.7.6 Mac OS X 10.10.4

### ISSUE THREAD

**Issue by hexingren** [amueller/word_cloud#108]
I tried both ways of installation. Basically, it pops out "error: could not create '/Library/Python/2.7/site-packages/wordcloud': Permission denied".
### pip install wordcloud

Collecting wordcloud
  Using cached wordcloud-1.2.tar.gz
Installing collected packages: wordcloud
  Running setup.py install for wordcloud
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;**file**='/private/var/folders/r7/r0s9p7v91sn34hn81cz8dzbw0000gn/T/pip-build-NMFj2T/wordcloud/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/r7/r0s9p7v91sn34hn81cz8dzbw0000gn/T/pip-Y4BZc6-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.10-intel-2.7
    creating build/lib.macosx-10.10-intel-2.7/wordcloud
    copying wordcloud/**init**.py -> build/lib.macosx-10.10-intel-2.7/wordcloud
    copying wordcloud/color_from_image.py -> build/lib.macosx-10.10-intel-2.7/wordcloud
    copying wordcloud/wordcloud.py -> build/lib.macosx-10.10-intel-2.7/wordcloud
    copying wordcloud/stopwords -> build/lib.macosx-10.10-intel-2.7/wordcloud
    copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.10-intel-2.7/wordcloud
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build/temp.macosx-10.10-intel-2.7
    creating build/temp.macosx-10.10-intel-2.7/wordcloud
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c wordcloud/query_integral_image.c -o build/temp.macosx-10.10-intel-2.7/wordcloud/query_integral_image.o
    wordcloud/query_integral_image.c:1411:16: warning: implicit conversion loses integer precision: 'Py_ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
      __pyx_v_x = (__pyx_v_integral_image.shape[0]);
                ~  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    wordcloud/query_integral_image.c:1420:16: warning: implicit conversion loses integer precision: 'Py_ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
      __pyx_v_y = (__pyx_v_integral_image.shape[1]);
                ~  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    wordcloud/query_integral_image.c:16230:32: warning: unused function '__Pyx_PyUnicode_FromString' [-Wunused-function]
    static CYTHON_INLINE PyObject\* __Pyx_PyUnicode_FromString(const char\* c_str) {
                                   ^
    wordcloud/query_integral_image.c:302:29: warning: unused function '__Pyx_Py_UNICODE_strlen' [-Wunused-function]
    static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE _u)
                                ^
    wordcloud/query_integral_image.c:16370:33: warning: unused function '__Pyx_PyInt_FromSize_t' [-Wunused-function]
    static CYTHON_INLINE PyObject \* __Pyx_PyInt_FromSize_t(size_t ival) {
                                    ^
    wordcloud/query_integral_image.c:14326:26: warning: unused function '__Pyx_GetBufferAndValidate' [-Wunused-function]
    static CYTHON_INLINE int __Pyx_GetBufferAndValidate(
                             ^
    wordcloud/query_integral_image.c:14360:27: warning: unused function '__Pyx_SafeReleaseBuffer' [-Wunused-function]
    static CYTHON_INLINE void __Pyx_SafeReleaseBuffer(Py_buffer_ info) {
                              ^
    wordcloud/query_integral_image.c:14433:1: warning: unused function '__pyx_add_acquisition_count_locked' [-Wunused-function]
    __pyx_add_acquisition_count_locked(__pyx_atomic_int _acquisition_count,
    ^
    wordcloud/query_integral_image.c:14443:1: warning: unused function '__pyx_sub_acquisition_count_locked' [-Wunused-function]
    __pyx_sub_acquisition_count_locked(__pyx_atomic_int *acquisition_count,
    ^
    wordcloud/query_integral_image.c:15021:32: warning: unused function '__Pyx_GetItemInt_List_Fast' [-Wunused-function]
    static CYTHON_INLINE PyObject *__Pyx_GetItemInt_List_Fast(PyObject *o, Py_ssize_t i,
                                   ^
    wordcloud/query_integral_image.c:15035:32: warning: unused function '__Pyx_GetItemInt_Tuple_Fast' [-Wunused-function]
    static CYTHON_INLINE PyObject *__Pyx_GetItemInt_Tuple_Fast(PyObject *o, Py_ssize_t i,
                                   ^
    wordcloud/query_integral_image.c:15995:27: warning: function '__Pyx_PyInt_As_char' is not needed and will not be emitted [-Wunneeded-internal-declaration]
    static CYTHON_INLINE char __Pyx_PyInt_As_char(PyObject *x) {
                              ^
    wordcloud/query_integral_image.c:16090:27: warning: function '__Pyx_PyInt_As_long' is not needed and will not be emitted [-Wunneeded-internal-declaration]
    static CYTHON_INLINE long __Pyx_PyInt_As_long(PyObject *x) {
                              ^
    13 warnings generated.
    wordcloud/query_integral_image.c:16230:32: warning: unused function '__Pyx_PyUnicode_FromString' [-Wunused-function]
    static CYTHON_INLINE PyObject_ __Pyx_PyUnicode_FromString(const char\* c_str) {
                                   ^
    wordcloud/query_integral_image.c:302:29: warning: unused function '__Pyx_Py_UNICODE_strlen' [-Wunused-function]
    static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen(const Py_UNICODE _u)
                                ^
    wordcloud/query_integral_image.c:16370:33: warning: unused function '__Pyx_PyInt_FromSize_t' [-Wunused-function]
    static CYTHON_INLINE PyObject \* __Pyx_PyInt_FromSize_t(size_t ival) {
                                    ^
    wordcloud/query_integral_image.c:14326:26: warning: unused function '__Pyx_GetBufferAndValidate' [-Wunused-function]
    static CYTHON_INLINE int __Pyx_GetBufferAndValidate(
                             ^
    wordcloud/query_integral_image.c:14360:27: warning: unused function '__Pyx_SafeReleaseBuffer' [-Wunused-function]
    static CYTHON_INLINE void __Pyx_SafeReleaseBuffer(Py_buffer_ info) {
                              ^
    wordcloud/query_integral_image.c:15021:32: warning: unused function '__Pyx_GetItemInt_List_Fast' [-Wunused-function]
    static CYTHON_INLINE PyObject *__Pyx_GetItemInt_List_Fast(PyObject *o, Py_ssize_t i,
                                   ^
    wordcloud/query_integral_image.c:15035:32: warning: unused function '__Pyx_GetItemInt_Tuple_Fast' [-Wunused-function]
    static CYTHON_INLINE PyObject *__Pyx_GetItemInt_Tuple_Fast(PyObject *o, Py_ssize_t i,
                                   ^
    wordcloud/query_integral_image.c:15995:27: warning: function '__Pyx_PyInt_As_char' is not needed and will not be emitted [-Wunneeded-internal-declaration]
    static CYTHON_INLINE char __Pyx_PyInt_As_char(PyObject *x) {
                              ^
    wordcloud/query_integral_image.c:16090:27: warning: function '__Pyx_PyInt_As_long' is not needed and will not be emitted [-Wunneeded-internal-declaration]
    static CYTHON_INLINE long __Pyx_PyInt_As_long(PyObject *x) {
                              ^
    9 warnings generated.
    cc -bundle -undefined dynamic_lookup -arch x86_64 -arch i386 -Wl,-F. build/temp.macosx-10.10-intel-2.7/wordcloud/query_integral_image.o -o build/lib.macosx-10.10-intel-2.7/wordcloud/query_integral_image.so
    running install_lib
    creating /Library/Python/2.7/site-packages/wordcloud
    error: could not create '/Library/Python/2.7/site-packages/wordcloud': Permission denied

```
----------------------------------------
```

Command "/usr/bin/python -c "import setuptools, tokenize;**file**='/private/var/folders/r7/r0s9p7v91sn34hn81cz8dzbw0000gn/T/pip-build-NMFj2T/wordcloud/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/r7/r0s9p7v91sn34hn81cz8dzbw0000gn/T/pip-Y4BZc6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/r7/r0s9p7v91sn34hn81cz8dzbw0000gn/T/pip-build-NMFj2T/wordcloud

**Comment by hexingren** [comment]
### python setup.py install ###
running install
running build
running build_py
running build_ext
running install_lib
creating /Library/Python/2.7/site-packages/wordcloud
error: could not create '/Library/Python/2.7/site-packages/wordcloud': Permission denied

**Comment by amueller** [comment]
You have to use sudo to do a system wide installation.

**Comment by hexingren** [comment]
Do you mean typing "sudo pip install -r requirements.txt" to manually install "wordcloud"? Actually I tried this and it succeeded in this step but still popped the error above when I use "python setup.py install". Could you further explain how to use sudo or give me specific command to install it in this situation? Thanks!

**Comment by amueller** [comment]
``sudo pip install wordcloud`` should install the released version without problem.

**Comment by hexingren** [comment]
Thanks! It really works!

**Comment by hexingren** [comment]
"Font path to the font that will be used (OTF or TTF). Defaults to DroidSansMono path on a Linux machine. If you are on another OS or don’t have this font, you need to adjust this path." In my case (Mac OS X 10.10.4), how should I change the path?

**Comment by amueller** [comment]
I think it should be fine now, I should fix the Readme. Let me know if you have any issues.

**Comment by TheMitchWorksPro** [comment]
Based on your readme file, I almost abandoned your site thinking it won't install on a mac.  It would be helpful if you add a section with with the exact installation lines for macintosh

**Comment by amueller** [comment]
@TheMitchWorksPro why did you think it won't install on mac. And the exact lines depend on whether you want to use conda, pip, brew or whatever other package manager.
Dependencies are matplotlib, pillow and numpy, as per the setup.py:
https://github.com/amueller/word_cloud/blob/master/setup.py

That should really be in the readme, though.

**Comment by amueller** [comment]
closing as original problem solved (and not wordcloud related)
