### ISSUE TITLE
Overlapping words with spaces in "words"

### ISSUE THREAD

**Issue by CodeBrauer** [amueller/word_cloud#109]
I've added the support, that words can contain space like in https://github.com/amueller/word_cloud/pull/85 but there seems to a problem.

The spaces are not correctly used and the words overlap. - Only on not monospaced fonts.

**Without spaces** *(LoremIpsum)*
![result](https://cloud.githubusercontent.com/assets/2059754/11627084/413b92de-9ce8-11e5-99a4-4785988ac4d4.png)

**With spaces** *(Lorem_Ipsum)*
![result-1](https://cloud.githubusercontent.com/assets/2059754/11627085/414f6bf6-9ce8-11e5-8bbe-f161f3982662.png)

- Font used: ["Bebas Neue"](http://www.fontsquirrel.com/fonts/bebas-NEUE)
- [Wordlist used](https://gist.githubusercontent.com/CodeBrauer/a93c14b8dd9d663cf2a8/raw/844e59d6cf526157bbc98e41744e2668bc9365a1/loremwc.txt)

My modifications in [wordcloud.py](https://github.com/amueller/word_cloud/blob/9aaf533788b1611bfd8b991e89f511d37ee7a886/wordcloud/wordcloud.py):
```
draw.setfont(transposed_font)
pos = (position[1] * self.scale, position[0] * self.scale)
- draw.text(pos, word, fill=color)
+  #draw.text(pos, word, fill=color)
+  draw.text(pos, word.replace('_',' '), fill=color)
return img
```

**Comment by CodeBrauer** [comment]
I tempfixed it using another regex selector:
```
for word in re.findall(r".*", text):
```

**Comment by amueller** [comment]
you can use "from_frequencies" instead and don't need to change any code ;). But then you don't get the tokenization at all. It would be good to make the regex a constructor parameter. PR welcome!

**Comment by CodeBrauer** [comment]
I'm not the python guy, but I can try it :+1:

**Comment by amueller** [comment]
good luck :) shouldn't be too hard!

**Comment by amueller** [comment]
check out this example: https://github.com/amueller/word_cloud/blob/master/examples/bigrams.py
