### ISSUE TITLE
String length bellow expected

### ISSUE THREAD

**Issue by dn5** [amueller/word_cloud#110]
Hello! @amueller, awesome implementation and I love it. Very easy library, plus great documentation.  
  
I'm interested in a way to multiply input if char length is bellow expected. For example, if I use custom mask image, and only input 10 words, the shape is not filled and recognized. How should I approach to the problem to fill shape in full.  
  
I've tried to multiply input several times (repeat input string) but that does not give end result (probably because it's also counted).
  
My dirty hack:
* Get random Japanese chars
* Put it in a string
* Concat string with expected input
* Call generation function

**Comment by amueller** [comment]
Sorry, I'm not sure I follow. So you want to repeat words?

**Comment by dn5** [comment]
@amueller Yes and no. I want to fill the wordcloud shape even if not enough words are set. Whats the best way to fill second example to make wordcloud shape recognizable?   
  
Example:  
* Shape visible and recognizable: http://i.imgur.com/v3xYMpZ.png
* Shape not recognizable (not enough words): http://i.imgur.com/mUO5KeO.png

**Comment by amueller** [comment]
that's more of a design than a programming question, right? I mean what do you want to fill it with?

**Comment by dn5** [comment]
How is that more of a design then a programming question? The library algorithm should expect that input is having less chars then expected for a filled shape mask. Not every user have set of words to fill whole shape.  
  
This is more of a software engineering question the programming question, but definitely not a design question.

**Comment by amueller** [comment]
well if you tell me how you want it to look, I can probably tell you how to code it. But I have no idea how you want it to look, so it is a design question.
