### ISSUE TITLE
import not working. unicodedecodeerror.

### ISSUE THREAD

**Issue by mandalsubhajit** [amueller/word_cloud#113]
Hi Andreas,

I am getting the following error when I try to import wordcloud.

C:\Users\subhajit\Anaconda3>python
Python 3.4.3 |Anaconda 2.2.0 (64-bit)| (default, Dec  1 2015, 11:39:45) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import wordcloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\subhajit\Anaconda3\lib\site-packages\wordcloud\__init__.py", line 1, in <module>
    from .wordcloud import WordCloud, STOPWORDS, random_color_func
  File "C:\Users\subhajit\Anaconda3\lib\site-packages\wordcloud\wordcloud.py", line 20, in <module>
    from .query_integral_image import query_integral_image
  File "stringsource", line 269, in init wordcloud.query_integral_image (wordcloud/query_integral_image.c:13415)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 1: invalid start byte
>>>

Tried to search the issue on the internet and made some changes in the query_integral_image.c at line 13415 too. But still the issue persists. No idea. Can you please help? Thanks in advance.

**Comment by amueller** [comment]
You didn't load your data with the correct encoding. What encoding does it have?

**Comment by mandalsubhajit** [comment]
This error is thrown at the import step itself, before even loading data.
So I guess the encoding has to do with some system variables, or directory
names. What is exactly happening in the C file?

On Friday, January 8, 2016, Andreas Mueller <notifications@github.com>
wrote:

> You didn't load your data with the correct encoding. What encoding does it
> have?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amueller/word_cloud/issues/113#issuecomment-170025996>
> .
>


-- 
_____________________________________________
*Subhajit Mandal* <http://www.linkedin.com/in/subhajitmandal>
<https://twitter.com/subhajit_mandal>
Quantitative Analyst, FRM
Master of Statistics (Indian Statistical Institute)
Hyderabad, India
mandalsubhajit@gmail.com
091 958 199 0087
_____________________________________________

**Comment by amueller** [comment]
oh, right, I misread the traceback.
How did you install?
What version of cython did you use? And what is in line 13415?

**Comment by mandalsubhajit** [comment]
I tried installing using pip and also directly from setup.py
I did not understand the c file much, so don't know what line 13415 does. But that line number is indicated in the error.

**Comment by mandalsubhajit** [comment]
I found a similar issue here: https://github.com/hmmlearn/hmmlearn/issues/28
and the solution worked for me as well.
Built it using cygwin compiler before installing.
>
python setup.py build --compiler=cygwin
python setup.py install
>
The issue can be closed.

**Comment by amueller** [comment]
glad you figured it out :)
