### ISSUE TITLE
Bokeh based wordcloud

### ISSUE THREAD

**Issue by swayson** [amueller/word_cloud#115]
Hi there,

Just want to gauge interest on having a [Bokeh](http://bokeh.pydata.org/en/latest/) based word-cloud. Is this something people would be interested in having? 

Main benefit would be interactivity.

**Comment by amueller** [comment]
I think it would be pretty sweet. But I'm not sure it's easy. It depends on how the coordinate system for drawing in Bokeh works. I tried to create a html version, but I didn't succeed.
If there is a way to get the exact bounding box a text would need in bokeh, then the PIL call for the text size could be replaced with a bokeh call. If the coordinates currently produced are easy to render correctly, that would be a simpler solution, though.

**Comment by smartinsightsfromdata** [comment]
+1 - A Bokeh word cloud would be great!

**Comment by jaideeppatel** [comment]
For sure, bokeh word cloud would be awesome for everyone working on any kind of natural language processing ...

**Comment by amueller** [comment]
@smartinsightsfromdata @jaideeppatel If either of you can tell me how to render text in bokeh, I'm happy to give it a go. Using ``Annotations``? http://bokeh.pydata.org/en/latest/docs/reference/models/annotations.html

**Comment by pierluigi-failla** [comment]
Maybe also `Label` (http://bokeh.pydata.org/en/latest/docs/reference/models/annotations.html#bokeh.models.annotations.Label) could be used for this purpose. It supports location `x`, `y` and also `text_font_size` and `text_alpha`. 
It would be great to attach the `hover` and `tap` tools to each word.

**Comment by pierluigi-failla** [comment]
I tried to make a stupid example (this is intended to run on Jupyter):

```
import bokeh
from bokeh.io import output_notebook
from bokeh.layouts import layout
from bokeh.models import Label
from bokeh.plotting import figure
from bokeh.plotting import show
output_notebook()
``` 
and
```
words = [
    ('hello', (10, 100), '12pt', 0.8),
    ('how', (20, 10), '14pt', 0.8),
    ('are', (100, 20), '16pt', 0.8),
    ('you', (50, 30), '18pt', 0.8),
    ('???', (100, 100), '18pt', 0.8),
]

fig = figure(plot_width=200, plot_height=200, title='test')

for word, loc, size, alpha in words:
    w = Label(x=loc[0], y=loc[1], x_units='screen', y_units='screen',
              text=word, render_mode='css', text_alpha=alpha, text_font_size=size)
    fig.add_layout(w)
    
show(fig)
```

We should wrap this in a proper high-level Bokeh class like `from bokeh.charts import Bar`.

**Comment by amueller** [comment]
@pierluigi-failla can you get the bounding-box size of the word after drawing?

**Comment by eddy-ojb** [comment]
+1 on word cloud i Bokeh!

**Comment by joranbeasley** [comment]
way late and feel free to remove i made a simple one based on https://wordcloud2-js.timdream.org

you can find it here

https://github.com/joranbeasley/bokeh_wordcloud2

currently the only example i have in place is `simple_counts_static_html.`  but i figure ill have more examples up soon...

Like i said its probably not super appropriate to post this here so feel free to remove it ... I just was using bokeh and really needed a wordcloud 
 
```
data = [
    ['susan',6],
    ['tom',3],
    ['frankie',8],
    ['roger',7],
    ['amy',9],
    ['nicole',10],
    ['joran',5],
    ['mark',4],
    ['brianne',7],
    ['michael',8],
    ['greg',4],
    ['adrian',6],
    ['drew',9]
]
names,weights = zip(*data)
test1 = ColumnDataSource({'names':names,'weights':weights})
sdp = WordCloud2(source=test1,wordCol="names",sizeCol="weights",colors=['pink','blue','green'])
show(sdp)
```
[see output here](https://joranbeasley.github.io/bokeh_wordcloud2/examples/simple_counts_static_html.html)

**Comment by magomar** [comment]
> way late and feel free to remove i made a simple one based on https://wordcloud2-js.timdream.org
> 
> you can find it here
> 
> https://github.com/joranbeasley/bokeh_wordcloud2

@joranbeasley  I'm trying to use your package, but whenever I try to show the wordcloud I get this error

`bokeh.core.property.descriptors.UnsetValueError: WordCloud2(id='1013', ...).hover doesn't have a value set`
