### ISSUE TITLE
Pass a list of words

### ISSUE THREAD

**Issue by abhigenie92** [amueller/word_cloud#121]
Can I pass a list of words if possible instead of a long string? Reason being the tokenization(https://github.com/amueller/word_cloud/blob/master/wordcloud/wordcloud.py#L386) is not upto the mark.

**Comment by amueller** [comment]
That's what the ``generate_from_frequencies`` function is for: http://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud.generate_from_frequencies

Though arguably taking a dict would be a better input format than the current list of tuples: #120
