### ISSUE TITLE
ImportError: cannot import name 'WordCloud'

### ISSUE THREAD

**Issue by qqqguo3** [amueller/word_cloud#123]
Python3.5 on mac.

Is PIL necessary for this project? I only have it in the python2.

**Comment by amueller** [comment]
pil or pillow is necessary.
But that is probably not your problem.

**Comment by kobe2452** [comment]
I use Python 2.7.9 with Pillow 3.1.1. Got the same error as you. (The wordcloud library was installed using pip, version 1.2.1)

**Comment by amueller** [comment]
the pip you installed word_cloud belongs to a different python environment than the python you tried to import it from.

**Comment by pritikavig** [comment]
How should this be installed then for python 3? I am 3.5.1.
I used pip install wordcloud in the 3.5.1 environment. I receive the same error. I have pillow. Is there a different pip command that should be used?

**Comment by amueller** [comment]
is it the pip that belongs to your python3 installation? depending on your configuration it might be called ``pip3``. Do ``which pip`` to see if you are using the correct pip. It's not an issue with dependencies.

**Comment by pritikavig** [comment]
yep! It looks like I have the correct download too - when I attempt a pip install again it says re
anaconda3/lib/python3.5/site-packages

**Comment by amueller** [comment]
and how are you running the program when you get the error message? ``python somefile.py`` ? Can you do ``which python``? Maybe you need to do ``python3 somefile.py``.

**Comment by ov3rt1me** [comment]
Hi there,
same issue:

from wordcloud import WordCloud, get_single_color_func
ImportError: cannot import name WordCloud


Ubuntu 
Python 2.7.10

**Comment by amueller** [comment]
again, are you sure it's the same python environment?

**Comment by ov3rt1me** [comment]
Sorry but, since i'm new in python, how can i check that?

**Comment by amueller** [comment]
maybe just try ``python -m pip install wordcloud`` and see if it works then

**Comment by ov3rt1me** [comment]
Requirement already satisfied (use --upgrade to upgrade): wordcloud in /usr/local/lib/python2.7/dist-packages

**Comment by amueller** [comment]
How are you running your program and what is the full traceback?

**Comment by ov3rt1me** [comment]
just try to run the test.

save the file as : wordcloud.py and launch as 

python wordcloud.py


then, this is the tracebak: 

 
Traceback (most recent call last):
  File "wordcloud.py", line 1, in <module>
    from wordcloud import WordCloud, get_single_color_func
  File "/home/h2g/Desktop/twittercsv/test/wordcloud.py", line 1, in <module>
    from wordcloud import WordCloud, get_single_color_func
ImportError: cannot import name WordCloud

**Comment by amueller** [comment]
don't save the file under this name. Literally any other name. ``numpy`` might also not work ;). This exact error came up yesterday lol.

**Comment by ov3rt1me** [comment]
Lol. Thanks for support. Everything works fine now. It's amazing how it works.

**Comment by QtRoS** [comment]
@amueller Thanks for exploration! Named my file 'wordcloud.py' too...

**Comment by piyushkhemka** [comment]
Holy! I made the exact same mistake. Thanks

**Comment by cbleck** [comment]
Thanks! same problem but now is solved.

**Comment by ZhangQi-7** [comment]
Thanks! same problem but now is solved

**Comment by WallfacerRZD** [comment]
Thanks! same problem but now is solved

**Comment by siarra** [comment]
The exact same mistake! Thanks a ton!! @amueller  👍 :)
