### ISSUE TITLE
Problem with query_integral_image + python 2

### ISSUE THREAD

**Issue by michelle-ye-zocdoc** [amueller/word_cloud#125]
I have read a similar issue [here](https://github.com/amueller/word_cloud/issues/31) and it was closed. But I still have this issue from mac OSX el capitan. I have the latest version from pip install for python 2.7, and the the worldcloud.py has `from .query_integral_image import query_integral_image`, and the package contains the file query_integral_image.so, but I have the error:

> Traceback (most recent call last):
> File "", line 1, in 
> File "wordcloud/init.py", line 1, in 
> from .wordcloud import WordCloud, STOPWORDS, random_color_func, get_single_color_func
> File "wordcloud/wordcloud.py", line 22, in 
> from .query_integral_image import query_integral_image
> ImportError: No module named query_integral_image

**Comment by amueller** [comment]
How did you install? It sounds like you didn't build the project. If you download it, you need to run ``python setup.py build_ext -i`` or ``python setup.py install``.

**Comment by michelle-ye-zocdoc** [comment]
I installed it by  `pip install wordcloud` in the terminal. Do I still need to build it?

**Comment by amueller** [comment]
no, that should work. That's odd.
Can you check what is in the wordcloud folder in your site-packages directory?

**Comment by amueller** [comment]
which version of wordcloud did you install?

**Comment by michelle-ye-zocdoc** [comment]
1.2

**Comment by michelle-ye-zocdoc** [comment]
contents of the folder: 
DroidSansMono.ttf	__init__.pyc		color_from_image.pyc	stopwords		wordcloud.pyc
__init__.py		color_from_image.py	query_integral_image.so	wordcloud.py

**Comment by michelle-ye-zocdoc** [comment]
So if this is a clue: I now try to install it by manually install instead. When I follow the step of `sudo pip install -r requirements.txt` I get the error: 

> The directory '/Users/myusername/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled.

Maybe a permission issue was also present in the pip install?

**Comment by amueller** [comment]
Hm... that is really odd, as you have ``query_integral_image.so`` in the folder...

**Comment by amueller** [comment]
can you try to ``import wordcloud`` in ipython, and then ``%debug`` and look at whether wordcloud is imported from the right path?

**Comment by michelle-ye-zocdoc** [comment]
Hmm that's a good suggestion. I looked in ipython, and it turns out it was importing wordcloud from the manual installation folder that I dowloaded (and didn't build, because I already have a pip installation), as that was my working directory. So I have deleted that folder and moved my working directory somewhere else, and it's now importing correctly. Thanks!

**Comment by dongjinguang-china** [comment]
Awesome solution by ipython tools:) 
Thanks a lot for amueller

**Comment by jcfr** [comment]
@dongjinguang-china it should indeed be possible to `pip install wordcloud` on all supported platform (without requiring the user to have a compiler), it is the approach you used ?

**Comment by dongjinguang-china** [comment]
@jcfr yeah,  you are right.

**Comment by AZAMNAZARI** [comment]
I have a problem to install wordcoud in python, I used pip install wordcloud in python but i always get error , can u help me
