### ISSUE TITLE
wordcloud fails to install with pip under ubuntu 15

### ISSUE THREAD

**Issue by ghost** [amueller/word_cloud#133]
rpagliari@sentimenttest:~$ sudo pip install wordcloud
The directory '/home/rpagliari/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/rpagliari/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting wordcloud
  Downloading wordcloud-1.2.1.tar.gz (165kB)
    100% |████████████████████████████████| 174kB 2.1MB/s 
Installing collected packages: wordcloud
  Running setup.py install for wordcloud ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-Ot6D6P/wordcloud/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-cHjfXz-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/wordcloud
    copying wordcloud/color_from_image.py -> build/lib.linux-x86_64-2.7/wordcloud
    copying wordcloud/**init**.py -> build/lib.linux-x86_64-2.7/wordcloud
    copying wordcloud/wordcloud.py -> build/lib.linux-x86_64-2.7/wordcloud
    copying wordcloud/wordcloud_cli.py -> build/lib.linux-x86_64-2.7/wordcloud
    copying wordcloud/stopwords -> build/lib.linux-x86_64-2.7/wordcloud
    copying wordcloud/DroidSansMono.ttf -> build/lib.linux-x86_64-2.7/wordcloud
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/wordcloud
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c wordcloud/query_integral_image.c -o build/temp.linux-x86_64-2.7/wordcloud/query_integral_image.o
    wordcloud/query_integral_image.c:8:22: fatal error: pyconfig.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```
----------------------------------------
```

Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-Ot6D6P/wordcloud/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-cHjfXz-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Ot6D6P/wordcloud/

**Comment by rpagliarix** [comment]
I was able to install it. Now, I'm getting this error:
```

    from wordcloud import WordCloud, STOPWORDS
    ImportError: cannot import name WordCloud
```

**Comment by amueller** [comment]
the first one was not having "python-dev" installed, as I guess your figured out.

The second one means that the python environment you are running the code with is not the name as the one to which you installed with pip.

**Comment by li-guest** [comment]
I met the problem too, do you solve it?

**Comment by li-guest** [comment]
Thank you, @amueller 
 If use python3, please try:
`sudo apt-get install python3-dev`

**Comment by ly-nina** [comment]
My python version is 3.6, but i execute 
```
sudo apt-get install python3-dev
```
still report error.Because it will install 3.5 version

```
sudo apt-get install python3.6-dev
```
so
```
pip3 install wordcloud
```
then could install successfully.

**Comment by amueller** [comment]
I recommend using conda-forge now.
