### ISSUE TITLE
picture issue

### ISSUE THREAD

**Issue by GreatHiggins** [amueller/word_cloud#143]
Always raise this :
 File "C:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 283, in generate_from_frequencies
width = mask.shape[1]
IndexError: tuple index out of range
Can you help me?

**Comment by amueller** [comment]
your image mask seems to be one-dimensional.

**Comment by GreatHiggins** [comment]
thanks verymuch!pillow is friendly to this and PIL maybe raise problems
