### ISSUE TITLE
Failed to import WordCloud from wordcloud

### ISSUE THREAD

**Issue by mgdlxd** [amueller/word_cloud#144]
Python2.7.9, Pillow 3.2, Linux 2.0

sudo pip install wordcloud

python wordcloud.py

using your example script to my text file..

my pip points to the correct python dist.. any ideas here?

**Comment by amueller** [comment]
``python wordcloud.py``? is that one of the example scripts?

Pretty sure it's not the right python ;)

try ``python -m pip install wordcloud``.

**Comment by mgdlxd** [comment]
I appreciate the speedy reply. I left out the line `cp simple.py wordcloud.py`

Unfortunately `python -m pip install wordcloud`  resulted in the same raised error when running the script. My python/pip ignorance is whats plaguing me here.

**Comment by amueller** [comment]
ohhh ... someone (not me) was silly with the examples. how did you run it? can you do ``python wordcloud.py``?

**Comment by mgdlxd** [comment]
Yeah running the script via `python wordcloud.py` ( im not that ignorant xD)

Throws me "ImportError: cannot import name WordCloud"

**Comment by amueller** [comment]
You could call it using ``./wordcloud.py`` which I wouldn't call ignorant.
and if you do
```python
python
import wordcloud
``
if this throws the error, do
```python
import sys
print(sys.path)
```
and check if that is the path that contains the package.

**Comment by mgdlxd** [comment]
Very True..

Does throw me the error and the path is there. It's the weirdest thing ever.

**Comment by amueller** [comment]
can you provide the output of the print(sys.path) and the output of an ``ls`` in the path and the full traceback?

**Comment by mgdlxd** [comment]
This issue can be closed. By default pythons import module looks in the current directory then moves to sys.path. Since my file was named the same as your module it was trying to import my file as the module. Appreciate your help. Beautiful wordclouds this produces.  Cheers!

**Comment by amueller** [comment]
ugh should have seen that...

**Comment by liufengID** [comment]
<module>, anaysis.py:12
execfile, _pydev_execfile.py:18
run, pydevd.py:1068
main, pydevd.py:1658
<module>, pydevd.py:1664

**Comment by mShaima1** [comment]
!pip install wordcloud
