### ISSUE TITLE
Some masks not recognized -> defaults to No mask?

### ISSUE THREAD

**Issue by matt-raporte** [amueller/word_cloud#146]
When I start with twitter mask as my mask, then switch to "dem-mask" or "rep-mask" before calling word_cloud I'm left with a rectangular mask (http://puu.sh/oubCj/d9611d8ccf.png).. is there a max size/specification for the mask images?

The values for my dem/rep masks are very similar to the twitter mask (which works fine if called by itself)
http://puu.sh/oubPo/6c33c6421d.png

**Comment by amueller** [comment]
Maybe the colors in the mask are wrong. As you can read in the [docs](http://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud), the entries of the mask that are #ffffff will be masked out. what is the color of the background in your images?

**Comment by amueller** [comment]
closing as no reply.
