### ISSUE TITLE
Adding support for accented characters

### ISSUE THREAD

**Issue by antortjim** [amueller/word_cloud#148]
This software is great! But unfortunately I am experiencing an issue with accented characters (á, é, ó...), which are extremely common in languages other than English, such as Spanish or French.

The problem is that accented words in the wordcloud are split in 2 by the place where the accented character is, i.e. instead of getting **proteína** or **plásmido**, I get _prote_ and _na_ separately, and so goes with _pl_ and _smido_, which are obviously nonsense in Spanish.
What can be done to fix that? I have already checked that the input file is indeed UTF-8 Unicode with the UNIX file utility.

![figure_2](https://cloud.githubusercontent.com/assets/13869571/14942612/27de9870-0fc2-11e6-9570-025d3b0bd80c.png)

PD: Is there a Spanish stopwords list free (as in speech) out there?

**Comment by amueller** [comment]
That's weird. Well it's not enough that the file is unicode, you should also check that the words are correctly represented. It could be that the regexp we are using causes this. Try out a single utf sentence from the document and apply the regexp. If it doesn't split the words properly, then there is the issue, and we can try a different regexp. It's more likely that the file is not read properly, though.

**Comment by amueller** [comment]
are you using the command line interface or the library?

**Comment by antortjim** [comment]
I tried it again with this file
```
café                                                                            
proteína
hola
mundo
camión
camiónes
coche
```

and this is the output I obtained

![sample](https://cloud.githubusercontent.com/assets/13869571/14999186/e818f98e-1187-11e6-9ba1-3acc8ccb36c9.png)

I am using the CLI. I downloaded your simple.py script and ran it with "./simple.py"

**Comment by amueller** [comment]
The ``simple.py`` script doesn't use the CLI. Well can you try using the regexp directly on your data?

Try ``re.findall(r"\w[\w']+", text)``.

Are you using Python2 or Python3?

**Comment by antortjim** [comment]
Aha, I thought that CLI meant using the terminal. I am using **Python 2.7.6**.
I don't know how to use the regexp on my data directly, though I'd love to learn to <:-). 
Where should I execute that instruction? I tried inserting it in simple.py but 're is not defined'.

**Comment by amueller** [comment]
``import re``

**Comment by antortjim** [comment]
This is what I got:

```
import re
...
>>> re.findall(r"\w[\w']+", text)
['caf', 'prote', 'na', 'hola', 'mundo', 'cami', 'cami', 'nes', 'coche']
```

**Comment by amueller** [comment]
what is ``type(text)``?
And ``re.findall(r"\w[\w']+", text, flags=re.UNICODE)``?

**Comment by amueller** [comment]
Because you're in python2 you should do
```
import codecs
content = codecs.open('file.txt', encoding='utf-8')
```

**Comment by antortjim** [comment]
You totally nailed it! The solution is indeed opening the file with **codecs.open()** and the argument **encoding = 'utf-8'** instead of regular open. I am getting a funny warning though:

```
/usr/local/lib/python2.7/dist-packages/wordcloud/wordcloud.py:391: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if word_lower in self.stopwords:
```

This is how I am reading the file

```
import codecs
...
text = codecs.open(input_file, encoding='utf-8').read()

```

Nothing had to be changed relating to matplotlib. So finally, I got this figure:

![figure_2](https://cloud.githubusercontent.com/assets/13869571/15033095/c52fc84a-1267-11e6-84e5-03619fe88e9d.png)

and this, which looks awesome. Thanks! :dancer: 
![figure_2](https://cloud.githubusercontent.com/assets/13869571/15033219/be48a17c-1268-11e6-9bea-34ed38dfd645.png)

**Comment by amueller** [comment]
glad you got it to work.

**Comment by kodymoodley** [comment]
Hi, thanks for the nice wordcloud library! I am having trouble with certain diacritic characters. E.g., the diacritic marks in the word `Kṛṣṇa` are not recognized. I get the following output:


<img width="624" alt="wordcloud-diacritics-krsna" src="https://user-images.githubusercontent.com/13569029/166220625-92c169da-c159-4ab2-b48f-4dc5cf30f80a.png">

This is my code:

```
text = ""
with open("test.txt", "r", encoding="utf-8") as f:
    text = f.read()
    
import wordcloud
from wordcloud import WordCloud
import matplotlib.pyplot as plt

wordcloud = WordCloud(width = 800, height = 800,
                background_color ='white',
                min_font_size = 10).generate(text)
                  
plt.figure(figsize = (8, 8), facecolor = None)
plt.imshow(wordcloud)
plt.axis("off")
plt.tight_layout(pad = 0)
plt.show()
```

I attach the test file test.txt as well:

[test.txt](https://github.com/amueller/word_cloud/files/8602294/test.txt)
