### ISSUE TITLE
errors during running examples

### ISSUE THREAD

**Issue by MaryNee** [amueller/word_cloud#151]
I'm trying to run the examples provided in the examples directory. But I met such problems:
When I run python examples/simple.py
Error: ImportError: No module named query_integral_image

Then I found that the file query_integral_image.pyx and changed it into query_integral_image.py, then the error becomes:   
File "D:\MasterGraduatePaper\code\word_cloud-master\wordcloud\query_integral_image.py", line 7
    def query_integral_image(unsigned int[:,:] integral_image, int size_x, int
                                        ^
SyntaxError: invalid syntax

**Comment by amueller** [comment]
well you shouldn't rename a file.
How did you install the package?

**Comment by MaryNee** [comment]
I used the fast install to install the package: pip install wordcloud
And it seemed to be installed successfully.

**Comment by amueller** [comment]
I think the problem is that you are in a folder that contains a ``wordcloud`` folder so the package is imported from there, and not from your installed version.

**Comment by MaryNee** [comment]
I solved the problem. Thank you very much!!!:)

**Comment by Sharmilinag** [comment]
How do you solve the problem?

**Comment by amueller** [comment]
@Sharmilinag what is your issue exactly? Please open a new issue with a precise description including traceback and what you have done.

**Comment by Sharmilinag** [comment]
I have opened a new issue. Please help me with solution.

**Comment by enfarose** [comment]
Issue number?
