### ISSUE TITLE
Not able to generate the image on Mac

### ISSUE THREAD

**Issue by rickjunli** [amueller/word_cloud#152]
Hi Andreas,

I am trying to use the simple example approach from WordCloud for just a few hundred words. For some reason, the word cloud image was not showing up. I am using Mac OX El Captain. The following is the code I used. It just sits there with the \* (using Ipython notebook) without returning anything or any errors. 'fc' contains the words I am trying to visualize. Do you have any suggestions? Thanks.

from wordcloud import WordCloud
import matplotlib.pyplot as plt
wordcloud = WordCloud(max_font_size=40, relative_scaling=.5).generate(fc)
plt.figure()
plt.imshow(wordcloud)
plt.axis("off")
plt.show()

**Comment by amueller** [comment]
What matplotlib backend are you using?
Can you open other matplotlib plots?

**Comment by rickjunli** [comment]
Yeah I can open other plots like hist, pie, or scatter, etc.

**Comment by rickjunli** [comment]
actually I just added %matplotlib inline. now the image is showing up in the notebook. thanks

**Comment by neka7449** [comment]
Hi Andreas,

I have a similar problem on Xubuntu 16.04 (and also 14.04). The program just seems to sit idle after running, no plot, no wordcloud image. As rickjunli said, running it with %matplotlib works fine, but then the wordclouds used to generate automatically (without the need for the inline statement) around a month or so ago, and then they just stopped showing up.

**Comment by amueller** [comment]
Can you provide the code you are using?

**Comment by neka7449** [comment]
It the simple.py script from the examples folder in your wordcloud repo
(I've run it on both Jupyter notebook and the terminal)

**Comment by amueller** [comment]
How did you run it from the terminal? And can you plot anything else on the terminal?

**Comment by neka7449** [comment]
No, nothing plots from the terminal. I just wanted to check for errors. But
ipython notebook used to output the word cloud some time ago without the
need to specify %inline matplotlib

**Comment by amueller** [comment]
I meant have you tried plotting a line or opening an empty plot form the
terminal?
If that doesn't work you broke your matplotlib install.

**Comment by neka7449** [comment]
Well, that could be the case. However I've installed matplotlib and all
dependencies using pip and the wordcloud used to get generated on the same
configuration. However, I will try to check if something is broken in the
install and maybe reinstall
