### ISSUE TITLE
width & height  working?

### ISSUE THREAD

**Issue by mesala** [amueller/word_cloud#153]
I'm still a bit confused about the hability to control the final size of the wordcloud file (width & height).

If I include the following parameters in the WordCloud function:

WordCloud(
                          font_path='../_Font/CabinSketch-Bold.ttf',
                          stopwords=STOPWORDS,
                          background_color='white',
                          width = 700,
                          height= 500,
                          mask=mask_image,
                          max_words=500
)

The output file seems to be always 1800x1200 no matter what mask I use, and what values width and height are setup to.

There also seems to be a big white space on top, bottom, left and right of the wordclide, which I have to create a further function to remove.

Is this a bug? can you give me some light on this?

Windows 10, Python 3.4, Andaconda.

Thanks,

**Comment by amueller** [comment]
the [docs say](http://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud) "If mask is not None, width and height will be ignored and the shape of mask will be used instead." This is in the docstring of the mask, not ``width`` and ``height`` though. Feel free to add a comment to their docstring and/or raise a warning if someone passes a mask and additional width or height.

**Comment by mesala** [comment]
Sorry, got obssesed expecting the answer to my issue to be in the width and height parameters docstring, not somewhere else.  My bad.

Yes, if something smart comes out of all my testing I hope to provide some code and I will include the warning as suggested.

Thanks a lot.

**Comment by amueller** [comment]
np.

**Comment by amueller** [comment]
closing for now as seems to be fixed.
