### ISSUE TITLE
Requirements not installed with pip3

### ISSUE THREAD

**Issue by pylipp** [amueller/word_cloud#154]
I installed wordcloud in a fresh virtualenv using pip3, however the requirements are not installed since no `txt` file is included in the package.
```
mkvirtualenv wordcloud -p /usr/bin/python3.4
pip3 install --no-cache-dir wordcloud
```
The output of the second command is: 
```
Collecting wordcloud
Installing collected packages: wordcloud
Successfully installed wordcloud-1.2.1
```
Requirements are not installed and lead to an import error.
```
python3
>>> import wordcloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pylipp/.virtualenvs/wordcloud/lib/python3.4/site-packages/wordcloud/__init__.py", line 1, in <module>
    from .wordcloud import WordCloud, STOPWORDS, random_color_func, get_single_color_func
  File "/home/pylipp/.virtualenvs/wordcloud/lib/python3.4/site-packages/wordcloud/wordcloud.py", line 14, in <module>
    import numpy as np
ImportError: No module named 'numpy'
```
I think the issue is the missing `requirements.txt` in the package. I downloaded the tar from https://pypi.python.org/pypi/wordcloud, it does not contain `requirements.txt`.
However, I succeeded to manually install the requirements and to use the package.

**Comment by amueller** [comment]
pipy doesn't actually use the requirements.txt IIRC, I should declare them in the setup.py

**Comment by a93ushakov** [comment]
Maybe this helps.
```docker
FROM debian:testing
MAINTAINER Alex Ushakov <a93ushakov@gmail.com>

RUN \
  apt update && \
  apt install \
    -y \
      git \
      ca-certificates \
      python-pip \
      wget \
      unzip \
      g++ \
      libjpeg-dev \
      zlib1g-dev \
      python-dev \
      libfreetype6-dev \
      libxft-dev \
      libjpeg62

WORKDIR /tmp
RUN wget https://github.com/amueller/word_cloud/archive/master.zip
RUN unzip master.zip
RUN rm master.zip

WORKDIR word_cloud-master
RUN pip install -r requirements.txt
RUN pip install wordcloud
RUN pip install pillow
RUN pip install matplotlib
```

And yes, installation quietly difficult.

**Comment by amueller** [comment]
if you hard-code the dependencies anyhow, there is no reason to check out the github repository.
Doing
```
pip install pillow numpy
pip install wordcloud
```
should be entirely sufficient.

**Comment by amueller** [comment]
Why do you say the installation is quite difficult? What kind of difficulties did you have?

**Comment by a93ushakov** [comment]
@amueller, look at my `dockerfile` above.

**Comment by amueller** [comment]
I don't often use docker. How is that different for installing any other python extension library?

**Comment by a93ushakov** [comment]
@amueller in ideal case it should be `apt install python-wordcloud` or `pip install wordcloud`

**Comment by amueller** [comment]
Feel free to create a launchpad repo and create the required build files for the .deb package, I'm not gonna do that.

The pip install was not really possible until quite recently (like a month ago?) when ``anylinux`` wheels were introduced. Ideally these should be used, but I didn't have time to repackage yet.

As I said above, you can currently ``pip install pillow numpy; pip install wordcloud``.
That gets rid of most of your docker config. Have you tried that?
I'm not sure how the anylinux build works, but I'd guess it does use shared libraries. Also you need pip.
So you can not get around installing python-pip  and libjpeg via apt.

You could use conda, which already has a binary package. So you could currently do ``conda install wordcloud`` IIRC.

**Comment by amueller** [comment]
fixed in master.
