### ISSUE TITLE
Newbie asking for help!

### ISSUE THREAD

**Issue by sherbn** [amueller/word_cloud#161]
New to python (heck, new to programming). Trying to get wordcloud to work.  Finally got it installed (Python 3.5 in windows 64 bit) and tried to run your test code.  (See below).  Could not find PIL so I installed Pillow 3.3. Correct or wrong step?  I get "no module named 'Pillow'".  Is my "from Pillow import image" line incorrect?  Please advise.
# !/usr/bin/env python

"""
# Masked wordcloud

Using a mask you can generate wordclouds in arbitrary shapes.
"""

from os import path
from Pillow import Image
import numpy as np
import matplotlib.pyplot as plt

from wordcloud import WordCloud, STOPWORDS

d = path.dirname(C/Desktop/cloudfiles)
# Read the whole text.

text = open(path.join(d, 'Premera.txt', 'WMP.txt')).read()
# read the mask image
# taken from
# http://www.stencilry.org/stencils/movies/alice%20in%20wonderland/255fk.jpg

alice_mask = np.array(Image.open(path.join(d, "alice_mask.png")))

stopwords = set(STOPWORDS)
stopwords.add("said")

wc = WordCloud(background_color="white", max_words=2000, mask=alice_mask,
               stopwords=stopwords)
# generate word cloud

wc.generate(text)
# store to file

wc.to_file(path.join(d, "alice.png"))
# show

plt.imshow(wc)
plt.axis("off")
plt.figure()
plt.imshow(alice_mask, cmap=plt.cm.gray)
plt.axis("off")
plt.show()

ERROR Message says 
 ...line 9, in <module>
    from Pillow import Image
ImportError: No module named 'Pillow'

**Comment by amueller** [comment]
yes. please change it back. It will work. pillow is the name of the package, but not the import.

**Comment by sherbn** [comment]
When I change it to PIL, I get:

    from PIL import Image
ImportError: No module named 'PIL'
>>>

**Comment by sherbn** [comment]
I do have "PIL" on my harddrive in a folder named "users/.../Python/Python35-32/Lib/site-packages.  Is it in the wrong spot, or is there a statement missing before the "from PIL import Image".  Sorry to keep bothering you with my issue, but I am at a loss.

**Comment by amueller** [comment]
How did you install pillow? What python environment are you using?
I suggest using the anaconda python environment.

**Comment by amueller** [comment]
closing as no reply
