### ISSUE TITLE
portuguese words / encoding

### ISSUE THREAD

**Issue by eloiup** [amueller/word_cloud#169]
hey!

have been trying to use it with portuguese words, cant get to display properly though

example:

"vit\xc3\xb3ria" shows up as "vit" "ria" at the wordcloud

wld like it to show up as "vitória"

not sure whats the best way to do this, tried some coding/decoding but not really my forte
(i am best at numpy/pandas/..)

maybe there is some in function solution at word_cloud but cldnt find it either

ty!

**Comment by amueller** [comment]
This should only depend on how you read/represent the string. wordcloud can do utf-8.
Can you provide the code?

**Comment by eloiup** [comment]
yeah sure

i was just trying:

WordCloud(background_color="white", max_font_size=40, relative_scaling=.5).generate(string)

where 

string='Muito me orgulha ter liderado o Brasil nessa vit\xc3\xb3ria hist\xc3\xb3rica.'

**Comment by amueller** [comment]
Which version of Python are you using?

**Comment by eloiup** [comment]
![python version](https://cloud.githubusercontent.com/assets/20978596/17671282/9f50273e-62ec-11e6-87f4-6ee90c5139c5.png)

**Comment by eloiup** [comment]
is it a version related issue?

**Comment by amueller** [comment]
well python2.7 and python3.x treat unicode very differently.
https://docs.python.org/2/howto/unicode.html

Try passing ``unicode(string, encoding="utf-8")``

**Comment by amueller** [comment]
```python
print(unicode(string, encoding="utf-8"))
```
> Muito me orgulha ter liderado o Brasil nessa vitória histórica.

**Comment by eloiup** [comment]
worked like a charm

ty very much!

**Comment by amueller** [comment]
np
