### ISSUE TITLE
ImportError: cannot import name 'WordCloud'

### ISSUE THREAD

**Issue by duongtrung** [amueller/word_cloud#174]
Dear all,
I followed the instruction to install WordCloud in two OS:
- Windows 10, Anaconda python 3.5
- Ubuntu 16.04 LTS, Anaconda python 3.5 
  In Ubuntu, I tried both pip and wget. The installation run smoothly.
  But I cannot import the library. Here is the error: ImportError: cannot import name 'WordCloud'

best,

**Comment by amueller** [comment]
did you name your script ``wordcloud.py``?

What is the full traceback? Are you sure the pip you used belongs to the same python environment?

**Comment by TaQini** [comment]
I met this problem too...

**Comment by GreatZP** [comment]
use "from wordcloud.wordcloud import WordCloud"

**Comment by pangyouzhen** [comment]
I also encounter this problem, the file isn't same with wordcloud:
this is my Traceback：

Traceback (most recent call last):
  File "C:/Users/pangyouzhen/Desktop/word_cloud_test.py", line 4, in <module>
    from wordcloud import WordCloud
ImportError: cannot import name 'WordCloud'

I also try to reinstall this module:

#All requested packages already installed.
#package in environment at　D:\software\Anaconda:
#wordcloud    1.2.1      py35_0   conda-forge

**Comment by chriys** [comment]
> did you name your script `wordcloud.py`?
> 
> What is the full traceback? Are you sure the pip you used belongs to the same python environment?

That fixes it for me. I named my script `wordcloud.py`. Renaming it fixed it. Thanks.

**Comment by alejoes** [comment]
Sorry, but do you mean by "name your script"? I am having the same issue and I don't know how to solve it. @amueller

**Comment by amueller** [comment]
What is the error message?
What I mean is the file name of the python file that contains your code.

**Comment by alejoes** [comment]
Andreas thanks for the response, I found the error, it was a silly one. 
It works fine. 

Regards.

**Comment by Abid-Tasleem** [comment]
Hi
what is the solution of this error ( cannot import name 'WordCloud' from 'wordcloud')

**Comment by AfaqKh** [comment]
> use "from wordcloud.wordcloud import WordCloud"

This works for me - Thanks
