### ISSUE TITLE
Issue with Python3.5 Mac OSX

### ISSUE THREAD

**Issue by matthieuhum** [amueller/word_cloud#177]
Hello,

I tried to install the package wordcloud using pip, conda or the manual process and each time it fails.

When I try with pip I get the following message :
 Collecting wordcloud
  Using cached wordcloud-1.2.1.tar.gz
Building wheels for collected packages: wordcloud
  Running setup.py bdist_wheel for wordcloud ... error
  Complete output from command /Users/matthieuhum/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/22/4dq53m5n6s31008n2dw9jmnc0000gn/T/pip-build-6slxg5k3/wordcloud/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/22/4dq53m5n6s31008n2dw9jmnc0000gn/T/tmp_4zp_cm7pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-3.5
  creating build/lib.macosx-10.6-x86_64-3.5/wordcloud
  copying wordcloud/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/wordcloud
  copying wordcloud/color_from_image.py -> build/lib.macosx-10.6-x86_64-3.5/wordcloud
  copying wordcloud/wordcloud.py -> build/lib.macosx-10.6-x86_64-3.5/wordcloud
  copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.6-x86_64-3.5/wordcloud
  copying wordcloud/stopwords -> build/lib.macosx-10.6-x86_64-3.5/wordcloud
  copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.6-x86_64-3.5/wordcloud
  running build_ext
  building 'wordcloud.query_integral_image' extension
  creating build/temp.macosx-10.6-x86_64-3.5
  creating build/temp.macosx-10.6-x86_64-3.5/wordcloud
  /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/matthieuhum/anaconda/include -arch x86_64 -I/Users/matthieuhum/anaconda/include/python3.5m -c wordcloud/query_integral_image.c -o build/temp.macosx-10.6-x86_64-3.5/wordcloud/query_integral_image.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud
  Running setup.py install for wordcloud ... error
    Complete output from command /Users/matthieuhum/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/22/4dq53m5n6s31008n2dw9jmnc0000gn/T/pip-build-6slxg5k3/wordcloud/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/22/4dq53m5n6s31008n2dw9jmnc0000gn/T/pip-1sei2gzl-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-x86_64-3.5
    creating build/lib.macosx-10.6-x86_64-3.5/wordcloud
    copying wordcloud/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/wordcloud
    copying wordcloud/color_from_image.py -> build/lib.macosx-10.6-x86_64-3.5/wordcloud
    copying wordcloud/wordcloud.py -> build/lib.macosx-10.6-x86_64-3.5/wordcloud
    copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.6-x86_64-3.5/wordcloud
    copying wordcloud/stopwords -> build/lib.macosx-10.6-x86_64-3.5/wordcloud
    copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.6-x86_64-3.5/wordcloud
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build/temp.macosx-10.6-x86_64-3.5
    creating build/temp.macosx-10.6-x86_64-3.5/wordcloud
    /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/matthieuhum/anaconda/include -arch x86_64 -I/Users/matthieuhum/anaconda/include/python3.5m -c wordcloud/query_integral_image.c -o build/temp.macosx-10.6-x86_64-3.5/wordcloud/query_integral_image.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/matthieuhum/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/22/4dq53m5n6s31008n2dw9jmnc0000gn/T/pip-build-6slxg5k3/wordcloud/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/22/4dq53m5n6s31008n2dw9jmnc0000gn/T/pip-1sei2gzl-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/22/4dq53m5n6s31008n2dw9jmnc0000gn/T/pip-build-6slxg5k3/wordcloud/

Could you please assist ?
Best,

**Comment by amueller** [comment]
Looks like an issue with your xcode installation:
>  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

**Comment by matthieuhum** [comment]
Ok. It seems that it is a common problem with the latest update of Mac OS :  http://tips.tutorialhorizon.com/2015/10/01/xcrun-error-invalid-active-developer-path-library-developer-commandline-tools-missing-xcrun/

Thank you very much for your quick help !
