### ISSUE TITLE
Important "s" at the end of words removed

### ISSUE THREAD

**Issue by MasterScrat** [amueller/word_cloud#180]
Hello,

I'm working on chat log analysis, and I used word_cloud to do some visualisations:
https://github.com/MasterScrat/ChatShape

It works great I really love the results :D

Unfortunately in French, the final "-s" in many words is important and cannot be removed. word_cloud removes it in an attempt I guess to use the singular form. But it leads to very ugly results! Eg Paris -> pari

Maybe there could be a flag to disable this behaviour?

Cheers,
Florian

**Comment by amueller** [comment]
Looks sweet! Yes, there should be a flag.
It's a bit weird, it only removed the ``s`` if the word without ``s`` appears. So ``pari`` is a word?

Btw, would you mind trying out the new version in master? I did some changes to the default settings and I would love to get some feedback.

**Comment by MasterScrat** [comment]
Yes actually it's a bad example since pari and Paris are both words (pari = bet). However a lot of people get "ouai" instead of "ouais", and "ouai" definitely doesn't exist. In the context of chat logs though it's probable people mistyped it at some point.

Great for the update, I will check!

**Comment by amueller** [comment]
the update also includes pairs of words, which i like quite a bit. Do you want to make a pull request for adding the flag?

**Comment by amueller** [comment]
It's an option in master now. let me know if that works for you.

**Comment by MasterScrat** [comment]
Yay, looks awesome :D

**Comment by MasterScrat** [comment]
However I don't see as much bigrams as I'd like, it'd be cool to have a parameter to fine-tune this...

**Comment by amueller** [comment]
PR welcome, the threshold is pretty arbitrary right now.
