### ISSUE TITLE
ImportError: No module named wordcloud

### ISSUE THREAD

**Issue by ghost** [amueller/word_cloud#181]
Hi there, 

I am attempting to use your wordcloud package but am having some trouble importing into my Python Notebook (I'm using Anaconda on Mac btw).

I use the pip install wordcloud command and everything seems to run smoothly. It shows up in my /anaconda/lib/python2.7/site-packages folder. 

Now, when I go to my python notebook, I try to run `import wordcloud` and it gives me the error shown in the title.

Any help would be much appreciated.

**Comment by amueller** [comment]
the notebook you're using is probably not the one associated with this pip.
In the notebook, try
```python
import os
os.path
```
That should show the folder that you listed. Otherwise it's a different environment.

**Comment by madsthaks** [comment]
Well, the wordcloud folder is showing up in the same folder as the rest of my packages but its still not working.

**Comment by amueller** [comment]
That doesn't really answer my question. What is the content of ``os.path`` if you run it from the notebook that you can't import ``wordcloud`` from?

**Comment by madsthaks** [comment]
it is showing: '/Users/madhavthaker/anaconda/lib/python2.7/posixpath.pyc' which where the package is being installed. Is there a way for me the change that?

**Comment by amueller** [comment]
Sorry, I meant ``sys.path``.
And when you said ``/anaconda/lib/python2.7/site-packages `` earlier, you meant ``/Users/madhavthaker/anaconda/lib/python2.7/``

**Comment by madsthaks** [comment]
So, there are about 14 paths that show:

['',
 '/Users/madhavthaker/anaconda/lib/python27.zip',
 '/Users/madhavthaker/anaconda/lib/python2.7',
 '/Users/madhavthaker/anaconda/lib/python2.7/plat-darwin',
 '/Users/madhavthaker/anaconda/lib/python2.7/plat-mac',
 '/Users/madhavthaker/anaconda/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/madhavthaker/anaconda/lib/python2.7/lib-tk',
 '/Users/madhavthaker/anaconda/lib/python2.7/lib-old',
 '/Users/madhavthaker/anaconda/lib/python2.7/lib-dynload',
 '/Users/madhavthaker/anaconda/lib/python2.7/site-packages/Sphinx-1.3.5-py2.7.egg',
 '/Users/madhavthaker/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg',
 '/Users/madhavthaker/anaconda/lib/python2.7/site-packages',
 '/Users/madhavthaker/anaconda/lib/python2.7/site-packages/aeosa',
 '/Users/madhavthaker/anaconda/lib/python2.7/site-packages/IPython/extensions',
 '/Users/madhavthaker/.ipython']

**Comment by amueller** [comment]
so the notebook is part of your anaconda python2.7 environment. You need to install wordcloud (and its dependencies) in that environment to use it.

**Comment by saranyalogu** [comment]
@amueller 
Hi ,
i am trying to make a wordcloud in jupyter notebook using python .i got the error 'no module name wordcloud'.i import a wordcloud in python again i get the same error.

i am using,
  (python 2.7.12 32bit)
how can i clear this issue?
please help me

**Comment by amueller** [comment]
@saranyalogu how did you install wordcloud? How are you starting jupyter? You can look at ``sys.path`` as I suggested above to see which python environment jupyter is using. You can either add the environment into which you installed wordcloud as a jupyter kernel, or install wordcloud into that environment.

**Comment by vsathwikm** [comment]
Hi amueller,

I have the exact same issue. I have installed the wordcloud module in python 3.6 environment, using conda install command. The Jupyter notebook, I am working on also in inside the 3.6 environment only. The error still shows up. Please help. I have attached some images for your confirmation.

![image](https://user-images.githubusercontent.com/11830096/31395832-b757a258-adaf-11e7-842d-4aa4aa4188b6.png)

![image](https://user-images.githubusercontent.com/11830096/31395851-c6cf2378-adaf-11e7-957a-dbe4e4aca1e4.png)

**Comment by amueller** [comment]
@vsathwikm that screenshot doesn't really say much. Can you show ``sys.path`` in the jupyter notebook, as I said above? Also can you list the installation path that was used with conda.

**Comment by vsathwikm** [comment]
@amueller  I have attached the images

![image](https://user-images.githubusercontent.com/11830096/31397411-f5ea58cc-adb3-11e7-8f78-e1bccfa7c53f.png)

![image](https://user-images.githubusercontent.com/11830096/31397475-255f23c6-adb4-11e7-8ded-e540322943bf.png)

**Comment by amueller** [comment]
that looks weird indeed. Can you check whether wordcloud is in ``C:\Users\sathw\anaconda3\lib\site-packages``?

**Comment by vsathwikm** [comment]
This must be it. I don't see wordcloud in site packages folder. Please tell me, how to solve this?

**Comment by vsathwikm** [comment]
I found wordcloud in this path C:\Users\sathw\Anaconda3\pkgs\wordcloud-1.2.1-py36_0\lib\python3.6\site-packages

**Comment by amueller** [comment]
sorry, that seems like an environment issue, but I don't know what the solution is.

**Comment by vsathwikm** [comment]
No problem @amueller . I'll try to see what I can do and post a solution if I find one.

**Comment by saranyalogu** [comment]
@amueller 
i installed 2.7.12 (32 bit)python .

jupyter path:
C:\Users\ADMIN\Anaconda3
python 3.6.1 :: Anaconda 4.4.0 (64-bit)

 jupyter:
sys.path
['',
 'C:\\Users\\ADMIN\\Anaconda3\\python36.zip',
 'C:\\Users\\ADMIN\\Anaconda3\\DLLs',
 'C:\\Users\\ADMIN\\Anaconda3\\lib',
 'C:\\Users\\ADMIN\\Anaconda3',
 'C:\\Users\\ADMIN\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\ADMIN\\Anaconda3\\lib\\site-packages\\Sphinx-1.5.6-py3.6.egg',
 'C:\\Users\\ADMIN\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\ADMIN\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\ADMIN\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\ADMIN\\Anaconda3\\lib\\site-packages\\setuptools-27.2.0-py3.6.egg',
 'C:\\Users\\ADMIN\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\ADMIN\\.ipython']

Actually python and anoconda version is different so again i installed 64 bit python (Python 3.5.4)in My System .I am trying to import a wordcloud in 64 bit python but it shows already satisfied .

I have no wordcloud in Anaconda sitepackages .i think this issue is same as above mentioned .what i will do?

**Comment by saranyalogu** [comment]
@amueller 
I want to make a wordcloud in jupyter which version i will prefer and where it is placed(Jupyter Anaconda and Python)??

**Comment by amueller** [comment]
you should use the python 3.6.1 that comes with anaconda. Get the wheel from http://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud
 and do a "pip install" on it from the anaconda console.

**Comment by saranyalogu** [comment]
@amueller 
Thank you for your response .

**Comment by saranyalogu** [comment]
@amueller
How to read a text file while using navie bayes classifier in movie_reviews??

**Comment by amueller** [comment]
@saranyalogu how is that related to this issue? Closing as the original issue is solved.

**Comment by saranyalogu** [comment]
@amueller 
When i am using training data and test data as my own data
 i got the error (ValueError: not enough values to unpack (expected 2, got 1))

**Comment by amueller** [comment]
@saranyalogu It's completely unclear to me what you are asking about or if it relates to this issue.
https://blog.redpanthers.co/debugging-and-how-to-ask-questions/

**Comment by saranyalogu** [comment]
@amueller 
sorry for my mistakes...
 i open my issue following,

import nltk.classify.util
from nltk.classify import NaiveBayesClassifier
from nltk.corpus import movie_reviews
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

def word_feats(words):
    return dict([(word, True) for word in words])
negids = movie_reviews.fileids('neg')
posids = movie_reviews.fileids('pos')
negfeats = [(word_feats(movie_reviews.words(fileids=[f])), 'neg') for f in negids]
posfeats = [(word_feats(movie_reviews.words(fileids=[f])), 'pos') for f in posids]
trainfeats = negfeats[:100] + posfeats[:100]
testfeats =negfeats[100:] + posfeats[100:]

classifier = NaiveBayesClassifier.train(trainfeats)
print ('accuracy:', nltk.classify.util.accuracy(classifier, testfeats))
classifier.show_most_informative_features(15)
  
using this program i can classify training and test feats .
Movie_reviews have the list of default pos and neg text files,take it as a trainfeats.

Now i want to classify and find accuracy for our comments,
in this program can i add my (youtube extracted comments )text file in movie_reviews ?
if it is possible?

please help me.

**Comment by amueller** [comment]
I don't think you read the link. This doesn't seem to have anything to do with the wordcloud library. It's an NLP or maybe more specifically an NLTK question.
