### ISSUE TITLE
Key Error 'aces' issue (Windows 10 64-bit, Python2.7)

### ISSUE THREAD

**Issue by JoeData892** [amueller/word_cloud#183]
So I think I've installed everything correctly, but whenever I try to run the code, I get the following error (attached is my code and the text file I am referencing).  What am I doing wrong? thank you so much in advance for the help

C:\Python27\python.exe C:/Python27/Visuals/wordcloudJRO.py
Traceback (most recent call last):
  File "C:/Python27/Visuals/wordcloudJRO.py", line 30, in <module>
    wc.generate(text)
  File "C:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 544, in generate
    return self.generate_from_text(text)
  File "C:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 529, in generate_from_text
    words = self.process_text(text)
  File "C:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 510, in process_text
    word_counts = unigrams_and_bigrams(words)
  File "C:\Python27\lib\site-packages\wordcloud\tokenization.py", line 41, in unigrams_and_bigrams
    counts_unigrams, standard_form = process_tokens(words)
  File "C:\Python27\lib\site-packages\wordcloud\tokenization.py", line 120, in process_tokens
    standard_cases[plural] = standard_cases[singular.lower()]
KeyError: 'aces'

Process finished with exit code 1

[code1ofwordcloud.txt](https://github.com/amueller/word_cloud/files/566763/code1ofwordcloud.txt)
[final_mod_text.txt](https://github.com/amueller/word_cloud/files/566764/final_mod_text.txt)

**Comment by JoeData892** [comment]
Ok.  So I've figured out that there is an issue with my text, but I'm not sure what.  I just grabbed some text off the internet, re-ran the code, and it worked fine.  Not sure why the text I actually need isn't working.  Is it because it is one word per line?

**Comment by amueller** [comment]
Hey. How and when did you install?
This might be bug in my most recent version (~2 weeks old) - it looks like you're using that.
I'm a bit surprised by your text. Each word only appears once, right? So how are the words supposed to be ranked? I don't think you'll get a nice output for this input. Still, this seems to be a bug.

**Comment by amueller** [comment]
(I'll try to run / fix this later today but I'm crazy busy)

**Comment by JoeData892** [comment]
Sorry yes!  I posted the wrong text file!  I had done a unique output just to see what the words were.  Attached is the real file
[output_mod_file.txt](https://github.com/amueller/word_cloud/files/566847/output_mod_file.txt)

**Comment by JoeData892** [comment]
Hello:  Sorry I want to answer your questions.  I installed this morning.  So yes it is the most recent version.  I'm not sure you have a bug, as I went and grabbed a few 1000 words off of a webpage and it worked fine.  I'm not sure if that means there is something wrong with my text or not.  Thank you again for being responsive! that is awesome of you

**Comment by amueller** [comment]
it should be fixed now. There was an issue if there is a word-stem which can end with no "s", one "s" or two "s".

**Comment by amueller** [comment]
if you sort the words like in the file you provided, you might want to set "collocations=False". Otherwise you get garbage. If you don't sort, it should be fine.
