### ISSUE TITLE
Simple way to include one single color without any function

### ISSUE THREAD

**Issue by methodds** [amueller/word_cloud#185]
Hi,

maybe I missed it, but is there an easy way to set the color for every word without using any extra functions? I know that the algorithm you use for word placement is quite different, but I'm basically looking for the easiest way to make the wordclouds look similar to those produced in R. An example can be found at http://datascienceplus.com/building-wordclouds-in-r/:

![](http://datascienceplus.com/wp-content/uploads/2015/08/Screen-Shot-2015-09-04-at-11.24.58-AM.png)

Thanks =)

**Comment by amueller** [comment]
It's not documented that well, but you can do ``Worcloud(color_func=get_single_color_func(black))``

**Comment by methodds** [comment]
Thanks for the hint. Now everything works except that the saturation for words still varies at random instead of "pure" black:

http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/idvwbe1af9y9dw5/WordCloud%20Single%20Color.ipynb

**Comment by amueller** [comment]
oh, right. Sorry. Just do
```python
WordCloud(color_func=lambda **kwargs: "black")
```

**Comment by amueller** [comment]
it would be nice to add something like that to the docs, though.

**Comment by maifeng** [comment]
The correct argument value should be 
`      color_func=lambda *args, **kwargs: "black"
`
