### ISSUE TITLE
How to create a transparent WordCloud?

### ISSUE THREAD

**Issue by martinjevans** [amueller/word_cloud#186]
It is all working really well, but I am having trouble trying to specify a transparent background?  Looking at the color specification it implies it accepts an alpha channel.

I have tried:  `background_color="rgba(255, 255, 255, 0)"` for a transparent white background. 

When saving using `wc.to_file()` the resulting PNG background remains just white.

Any ideas?  Thanks

**Comment by amueller** [comment]
if you to to_array, does the array have four channels or three?

**Comment by martinjevans** [comment]
Only 3, `a.ndim` gives `3` and `a.shape` gives `(2420L, 2024L, 3L)`.

**Comment by martinjevans** [comment]
To answer my own question, it appears the following should work:

    background_color="rgba(255, 255, 255, 0)", mode="RGBA"

**Comment by amueller** [comment]
glad you figured it out!
