### ISSUE TITLE
Mention the command-line interface

### ISSUE THREAD

**Issue by foobuzz** [amueller/word_cloud#187]
Hello!

I've just used word_cloud on the command-line and it works very well. However, the README and the site don't mention this command-line tool and I had to look at the source directory to see that there was a `wordcloud_cli.py` file and that it was installed with the library.

Is there a reason this tool is not mentioned anywhere (like is it unstable or something?) If that's not the case then it would be a nice idea to write a few words about it in the README, so that people know it exists.

**Comment by amueller** [comment]
Hey.
No reason (except that the pull request for the CLI didn't include changes to the docs).
Please submit a pull request adding a mention to the readme.
