### ISSUE TITLE
Small, low-resolution blurry images

### ISSUE THREAD

**Issue by aarondesk** [amueller/word_cloud#188]
I have installed word_cloud on my mac, and it seems to work fine in generating word cloud images (such as simple.py or masked.py) using matplotlib. But the generated images seem to have low resolution. They look fine as small plots, but once I try to zoom in to create larger plots the resolution is terrible and all text looks blurry. I've tried playing around with different matplotlib commands to generate word clouds of bigger size/resolution, but have failed. I'm not sure if this is the issue or not with matplotlib or the word_cloud code.

Any ideas?

**Comment by amueller** [comment]
there are "width", "height" and "scale" parameters in the WordCloud class to adjust the resolution.

**Comment by aarondesk** [comment]
Thank you. I'm still python newbie, so still learning. I looked under wordcloud/wordcloud.py and found/changed this below under class WordCloud(object). Not sure if this is right. I tried various combinations of width, height, font_path, and scale, but I more or less get the same results. Word clouds that have much blurrier fonts than the example files provided on github/examples. See example below with 'n.png' that I created.

![n](https://cloud.githubusercontent.com/assets/16135778/20254979/3f8eeb0c-aa39-11e6-8743-06cd058c436f.png)


    class WordCloud(object):

    def __init__(self, font_path='/Users/aarondesk/Library/Fonts', width=1600, height=800, margin=2,
        ranks_only=None, prefer_horizontal=.9, mask=None, scale=3,

**Comment by amueller** [comment]
You don't need to change the word_cloud code. Just change it in your call to the ``WordCloud`` class.

**Comment by aarondesk** [comment]
Thank you. Works great.

**Comment by AddendaDan** [comment]
I'm having the same problem (and I'm also new Python, so there's probably a simple fix).  Essentially, all my outputs, regardless of how I change width, height, and scale in the WordCloud class call, are images with 640x480 as the dimensions (I've tried upping width height variables to 15k x 8k, I've messed with scale, same deal).

I actually first saw images on reddit of a WordCloud bot, so I'm trying to figure out how to get the quality of the example image below with "fox," to my own outputs.

![7kxnr1w](https://cloud.githubusercontent.com/assets/26714890/24367608/27ce99be-1315-11e7-94ed-dc7f500ebbce.png)
![hirestest3](https://cloud.githubusercontent.com/assets/26714890/24367613/29d11b6a-1315-11e7-8ed1-82bdc9543df9.png)

**Comment by amueller** [comment]
As a note to others: Matplotlib v2 doesn't do image interpolation for imshow any more. Please make sure you specify the ``interpolation`` parameter (eg ``interpolation="bilinear"``) if you use ``imshow`` to display results.

**Comment by amueller** [comment]
On 03/27/2017 12:45 PM, AddendaDan wrote:
>
> I'm having the same problem (and I'm also new Python, so there's 
> probably a simple fix). Essentially, all my outputs, regardless of how 
> I change width, height, and scale in the WordCloud class call, are 
> images with 640x480 as the dimensions (I've tried upping width height 
> variables to 15k x 8k, I've messed with scale, same deal).
>
Do you specify a mask image? If so, the dimensions of the mask are used.
>
> I actually first saw images on reddit of a WordCloud bot, so I'm 
> trying to figure out how to get the quality of the example image below 
> with "fox," to my own outputs.
>
You're using WordCloud 1.3, right? I see the "hound dog" there which 
wasn't possible before.
You might want to change ``max_font_size`` to something smaller. "fox" 
is likely to be overrepresented in your current cloud.
Try setting it to "None".

**Comment by AddendaDan** [comment]
HI, apologies for the confusion.  I fixed the problem I was having by specifying matplotlib "plt.figure" with variables.  Tried to delete my comment because I somehow found the workaround pretty quick after I commented.  Thanks for your quick response!

plt.figure(figsize=(24,14), dpi=1200).
