### ISSUE TITLE
Import Error 

### ISSUE THREAD

**Issue by ankurgulati** [amueller/word_cloud#193]
While using this : 
`from wordcloud import WordCloud, STOPWORDS`
I get the following error:

> ImportError:
 /mapr/projects/sna/twitter/packages/wordcloud/query_integral_image.pyd: invalid ELF header

And as suggested in other Issues I did this : 
`from .query_integral_image import query_integral_image`

and got this error: 

> ImportError: /mapr/projects/sna/twitter/packages/wordcloud/query_integral_image.pyd: invalid ELF header

Any Resolution?

**Comment by amueller** [comment]
recompile?

**Comment by ankurgulati** [comment]
I restarted many a times. 
But dont know how exactly we recompile.?

**Comment by amueller** [comment]
how did you install wordcloud?

**Comment by ankurgulati** [comment]
Using easy_install

**Comment by amueller** [comment]
these days you should probably be using ``pip``. Try to uninstall ``WordCloud`` and make sure the folder is completely deleted and try installing again.

**Comment by amueller** [comment]
closing as no reply.
