### ISSUE TITLE
Plotting words size following the order of .txt file

### ISSUE THREAD

**Issue by rcruzgar** [amueller/word_cloud#194]
Hi!
Is it possible to plot the size of the words depending on the order in the txt file?
(I'm creating the txt file manually, just with the words I want to include)

Cheers,
Rubén.

**Comment by amueller** [comment]
Yeah you can call "generate_from_frequencies" with a dictionary from words to floats.
The relative scaling of the words depends on the other parameters you pass and the relative magnitudes of the floats you use. Something simple would be (not tested, I always forget if readlines contains a "\n" or not)
```python
words = {}
with open("myfile.txt") as f:
    for i, w in f.readlines():
        words[w] = 1. / i
WordCloud().generate_from_frequencies(words)
```
