### ISSUE TITLE
[Request Feature] Timeline

### ISSUE THREAD

**Issue by minimalisticMe** [amueller/word_cloud#195]
Hey,

this is quite some awesome code you put together. I would like to propose an improvement:

Assuming the following scenario: 
I have data from three years and I would like to divide them into three parts, so in the end I have a word cloud with the upper 33% being from data from the first year, the middle 33% from the second year and the bottom 33% being words from the third year and in between the data there is a smooth transition of words.

Currently I'm doing this by creating a word cloud applying the years to three different masks (the top, middle and bottom 33%) and put it together into a full cloud, leaving visible seperation marks in the result (between the slices).

So I thought, I can code this by my own, but I cant. However I thought of three possible ways to do this:

1. Input a `list of tuples` or a `dataframe` with the left part containing a string and the right part a datetime.
2. Input as a list of `n` parts, e.g. `n=3` like above, so it looks like this `[[a, b, a, f], [g, e, a], [b, b, g, a]]`.
3. Input as normal and defining a number `n` and the input gets evenly divided into `n` parts (assuming that each time-period has the same amount of words).

I think option 2 might be the best, as option 1 and 3 might require some preprocessing first.

**Comment by amueller** [comment]
Your options seem to be options of what the input would be, but I'm not entirely sure what you want the output to be.

I think it hinges on what you mean by "smooth transition".
This should be relatively doable (probably with the existing code) once you make clear what the constraints should be. Should the y axis be strictly sorted by datetime or only by date or only by year (so on what granularity should there be a sorting)? Should that apply to the top, center or bottom of the word? Or the whole word?

**Comment by minimalisticMe** [comment]
Sorry for the late reply. I have attached an image for clarification

![unbenannt-1](https://cloud.githubusercontent.com/assets/13404680/21728471/acd60a6a-d446-11e6-89c6-545e6a1a8c96.png)

part (1) shows exemplary what I have, a shape, here a circle and a word of lists containing only _Hello_. I now want (like you stated) a timeline in y-axis, but with the possibility to repeat words. For example in part (2) I defined three slices. Each slide has different words (from that time range).

Currently I'm slicing the shape into different pieces and run the wordcloud on the time range like in part (2), leading to a hard edge, when combining the pieces into a single shape again.

My question for a _smooth transition_ between the edges, so instead of a clear cut line, there es some kind of blur (words overlapping from the upper slice into the lower slice).

**Comment by amueller** [comment]
Sorry for the late reply, too ;)
You didn't really answer the questions I raised.

>  Should the y axis be strictly sorted by datetime or only by date or only by year (so on what granularity should there be a sorting)? Should that apply to the top, center or bottom of the word? Or the whole word?

Like I don't know how you would want to arrange the words. Given a set of documents with dates, what do you want to do?

**Comment by minimalisticMe** [comment]
> Should the y axis be strictly sorted by datetime or only by date or only by year (so on what granularity should there be a sorting)? Should that apply to the top, center or bottom of the word? Or the whole word?

It should be sorted by time interval or date-range, like `1st May 2017` till `31st May 2017` for the upper part of the y-axis and `1st April 2017` till `30th April 2017` for the second part of the y-axis and so on.

**Comment by amueller** [comment]
Ok but if you run the algorithms separately for different time intervals, you'll get no overlap in words.

**Comment by minimalisticMe** [comment]
So I will always have a clean (visible) cut instead of an overlapping?

**Comment by amueller** [comment]
I honestly don't understand what the desired outcome is. Can you provide a minimal example of what you'd like to happen?
You just said 

>  like 1st May 2017 till 31st May 2017 for the upper part of the y-axis and 1st April 2017 till 30th April 2017

That means there's no overlap, right? These are disjoint areas for disjoint time frames.

**Comment by minimalisticMe** [comment]
I'll try with another image

![overlap](https://cloud.githubusercontent.com/assets/13404680/24079718/b953c144-0c8e-11e7-9810-327b09bcf0e8.png)

> like 1st May 2017 till 31st May 2017 for the upper part of the y-axis and 1st April 2017 till 30th April 2017

and in between the two time frames, there is no clean cut but an overlapping between both time frames

**Comment by amueller** [comment]
Can you fill in actual words and give an example of data?
Let's look at only one word. Lets say it occurs throughout all dates. How often is it represented? Once, twice, three times?

Can you write down an algorithm on what you want to happen with the words and time-stamps?
