### ISSUE TITLE
Add option to save to io.BytesIO

### ISSUE THREAD

**Issue by martmists** [amueller/word_cloud#196]

**Comment by amueller** [comment]
Can you elaborate?

**Comment by martmists** [comment]
As of right now, a WordCloud object has the `to_file` method, saving it to
the given filename. Is there a way to save the image to a BytesIO instead
of a file?

**Comment by amueller** [comment]
That doesn't really explain what you'd like to achieve ;)

You can get the array out with ``to_array()`` and that is probably a much better object to manipulate in Python than a ``BytesIO``.

**Comment by martmists** [comment]
I eventually just used `to_image` and saved that to a BytesIO
