### ISSUE TITLE
Emojis Tag-Cloud

### ISSUE THREAD

**Issue by ndrmahmoudi** [amueller/word_cloud#197]
Hi,

First of all, I would like to congratulate you for this great package. It is very useful module. Actually I sent you this via email, but I posted it here to help others who may have same problem. I am trying to generate a masked emoji (emoticons+unicode characters) tag-cloud with your package. You may find the a subset of emojis with frequency. I would like to mask tag-cloud to a bull as below:
![bull](https://cloud.githubusercontent.com/assets/22900001/20653627/9ca5758c-b564-11e6-9ac5-64cfcbcb0609.jpg)

![bull_wc](https://cloud.githubusercontent.com/assets/22900001/20653629/a633411a-b564-11e6-81b0-ce5e3baa9da0.png)
But, I am not able to get suitble tag cloud because it cannot handle unicode characters. Can you please let me know how to resolve this issue? 

FYI, I am using python 3 on Ubuntu OS. 

Regards,
Nader

('p:', 884859)
('p;', 241480)
(':)', 132245)
(';d', 34760)
(';)', 33790)
('🚀', 28962)
(':-)', 23547)
('😂', 16772)
('👍', 11986)
('💰', 11595)
('d:', 10955)
(':D', 9664)
(';-)', 8452)
(':(', 7241)
('d=', 6675)
('o:', 6611)
(';p', 6165)
('😎', 4257)
('D:', 4027)
(';o', 3953)
('😉', 3798)
(';D', 3732)
(';P', 3729)
('🏻', 3574)
('💸', 3567)
('💵', 3437)
('🏼', 3382)
('=p', 3233)
('=)', 3151)
(':P', 2935)
('😆', 2930)
(':o)', 2883)
('😀', 2676)
('😁', 2673)

**Comment by amueller** [comment]
I prefer issues here, it makes it easier to track than per mail, so thanks for posting it.
Can you show me what your input is like? WordCloud does handle unicode characters, so it's likely a problem with how you read your input or how the input is formatted.

**Comment by ndrmahmoudi** [comment]
I read tweets from a json file with "utf-8" encoding and input the tuples of (emoji, frequency) to the WordCloud. Probably the problem is related to my system font (it may not support unicode character). I could resolve the issue for emojis by changing the font path to [EmojiOne Color Font](http://www.omgubuntu.co.uk/2016/03/enable-color-emoji-linux-svg-font) which completely is based on emojis. But this time, the emoticons are not shown in the plot. However it might be out-of-scope question, do you know a font in Linux that supports both unicode and normal characters?

**Comment by amueller** [comment]
I think it's totally in scope to do emoji with the library. If you google "fonts including emoji" you get this https://github.com/MorbZ/OpenSansEmoji

**Comment by ndrmahmoudi** [comment]
Thanks Andreas, This resolve the issue. However, there are a few emojis that this font does not support. But, I got general idea how to solve this issue.

Many thanks again,
Cheers,
Nader

**Comment by amueller** [comment]
glad you worked it out :)
