### ISSUE TITLE
Can't install on Mac OS using Anaconda

### ISSUE THREAD

**Issue by tsando** [amueller/word_cloud#200]
I am getting the following error when I run the conda install command:

```
$ conda install -c https://conda.anaconda.org/amueller wordcloud
Fetching package metadata .........
Solving package specifications: .
PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels: 
  - wordcloud

You can search for packages on anaconda.org with

    anaconda search -t conda wordcloud
```

Can anyone help? Thanks.

**Comment by tsando** [comment]
Just to update, the only way I got it to work on my Mac was to use `pip install wordcloud`, although this isn't ideal, given I am using conda to control my environment...

**Comment by amueller** [comment]
There is nothing wrong with pip-installing packages in conda-environments, though using conda packages is preferred if they are available.
You can help by updating the conda built instructions for the channel.

**Comment by theod07** [comment]
I also couldn't install via anaconda, so I installed via `pip install wordcloud`. however, when i tried to import wordcloud, I received error 
```---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-19391e9a4d25> in <module>()
----> 1 import wordcloud as wc

/Users/wonder/projects/word_cloud/wordcloud/__init__.py in <module>()
----> 1 from .wordcloud import WordCloud, STOPWORDS, random_color_func, get_single_color_func
      2 from .color_from_image import ImageColorGenerator
      3
      4 __all__ = ['WordCloud', 'STOPWORDS', 'random_color_func', 'get_single_color_func', 'ImageColorGenerator']

/Users/wonder/projects/word_cloud/wordcloud/wordcloud.py in <module>()
     22 from PIL import ImageFont
     23
---> 24 from .query_integral_image import query_integral_image
     25 from .tokenization import unigrams_and_bigrams, process_tokens
     26

ImportError: No module named query_integral_image
```

I searched through the issues, and saw that someone answered >>the import should be `from .query_integral_image import query_integral_image` 

Any suggestions?

**Comment by amueller** [comment]
how did you ``pip install wordcloud``? With ``-e``? The import you're seeing there is not from your installation. After you installed, exit the project folder.

**Comment by theod07** [comment]
I was able to run it after leaving the project folder. Thanks for your
response! I didn't realize that I couldn't run it from within the project.

**Comment by amueller** [comment]
closing, replacing by #232.

**Comment by nandhakumarm** [comment]
==== Installation of wordcloud package ====
1. download wordcloud‑1.3.2‑cp36‑cp36m‑win_amd64.whl from http://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud 
2. Copy the file to your current working directory
3. Open command prompt from Tools
4. python -m pip install wordcloud-1.3.2-cp36-cp36m-win_amd64.whl

**Comment by helixg** [comment]
when I used pip install worcloud on my MacBookPro , it returens this
`Collecting wordcloud
  Using cached wordcloud-1.3.1.tar.gz
Requirement already satisfied: matplotlib in ./anaconda2/anaconda/lib/python2.7/site-packages (from wordcloud)
Requirement already satisfied: numpy>=1.6.1 in ./anaconda2/anaconda/lib/python2.7/site-packages (from wordcloud)
Requirement already satisfied: pillow in ./anaconda2/anaconda/lib/python2.7/site-packages (from wordcloud)
Requirement already satisfied: six>=1.10 in ./anaconda2/anaconda/lib/python2.7/site-packages (from matplotlib->wordcloud)
Requirement already satisfied: python-dateutil in ./anaconda2/anaconda/lib/python2.7/site-packages (from matplotlib->wordcloud)
Requirement already satisfied: functools32 in ./anaconda2/anaconda/lib/python2.7/site-packages (from matplotlib->wordcloud)
Requirement already satisfied: subprocess32 in ./anaconda2/anaconda/lib/python2.7/site-packages (from matplotlib->wordcloud)
Requirement already satisfied: pytz in ./anaconda2/anaconda/lib/python2.7/site-packages (from matplotlib->wordcloud)
Requirement already satisfied: cycler>=0.10 in ./anaconda2/anaconda/lib/python2.7/site-packages (from matplotlib->wordcloud)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in ./anaconda2/anaconda/lib/python2.7/site-packages (from matplotlib->wordcloud)
Requirement already satisfied: olefile in ./anaconda2/anaconda/lib/python2.7/site-packages (from pillow->wordcloud)
Building wheels for collected packages: wordcloud
  Running setup.py bdist_wheel for wordcloud ... error
  Complete output from command /Users/apple/anaconda2/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/rj/38frrc5s1ysgsvjn3lmwztlw0000gn/T/pip-build-0szc4p/wordcloud/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/rj/38frrc5s1ysgsvjn3lmwztlw0000gn/T/tmpHK79wppip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-2.7
  creating build/lib.macosx-10.7-x86_64-2.7/wordcloud
  copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
  copying wordcloud/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
  copying wordcloud/tokenization.py -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
  copying wordcloud/wordcloud.py -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
  copying wordcloud/color_from_image.py -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
  copying wordcloud/stopwords -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
  copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
  running build_ext
  building 'wordcloud.query_integral_image' extension
  creating build/temp.macosx-10.7-x86_64-2.7
  creating build/temp.macosx-10.7-x86_64-2.7/wordcloud
  gcc -fno-strict-aliasing -I/Users/apple/anaconda2/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/apple/anaconda2/anaconda/include/python2.7 -c wordcloud/query_integral_image.c -o build/temp.macosx-10.7-x86_64-2.7/wordcloud/query_integral_image.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud
  Running setup.py install for wordcloud ... error
    Complete output from command /Users/apple/anaconda2/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/rj/38frrc5s1ysgsvjn3lmwztlw0000gn/T/pip-build-0szc4p/wordcloud/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/rj/38frrc5s1ysgsvjn3lmwztlw0000gn/T/pip-OGxPl0-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-2.7
    creating build/lib.macosx-10.7-x86_64-2.7/wordcloud
    copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
    copying wordcloud/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
    copying wordcloud/tokenization.py -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
    copying wordcloud/wordcloud.py -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
    copying wordcloud/color_from_image.py -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
    copying wordcloud/stopwords -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
    copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.7-x86_64-2.7/wordcloud
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build/temp.macosx-10.7-x86_64-2.7
    creating build/temp.macosx-10.7-x86_64-2.7/wordcloud
    gcc -fno-strict-aliasing -I/Users/apple/anaconda2/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/apple/anaconda2/anaconda/include/python2.7 -c wordcloud/query_integral_image.c -o build/temp.macosx-10.7-x86_64-2.7/wordcloud/query_integral_image.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1`
and the conda install wordcloud is also useless, what can i do.....

**Comment by amueller** [comment]
@helixg google shows this solution: http://tips.tutorialhorizon.com/2015/10/01/xcrun-error-invalid-active-developer-path-library-developer-commandline-tools-missing-xcrun/

**Comment by repellentrian7** [comment]
@amueller https://hubert-ambassador.github.io/aws-lambda-layers4/
