### ISSUE TITLE
Checking 'frequencies' list in function WordCloud.generate_from_frequencies()

### ISSUE THREAD

**Issue by leferrad** [amueller/word_cloud#201]
I'm having an issue related to the generation of the word_cloud from a list of frequencies per word. As you can see below, the function is trying to retrieve the max frequency from a list 'frecuencies', but it doesn't check before if there is some element in that list:

https://github.com/amueller/word_cloud/blob/master/wordcloud/wordcloud.py#L350

That kind of check is done after, in the following snippet (but it's too late, because we already tried to access to the first element on a probably empty list):

https://github.com/amueller/word_cloud/blob/master/wordcloud/wordcloud.py#L360-L362

In my own version, I've done the following correction related to the first snippet in order to avoid some crashes (just as an example):

``` 
        try:
            max_frequency = float(frequencies[0][1])
        except:
            print "ERROR with list 'frecuencies'=", frequencies
```

Best regards!

**Comment by amueller** [comment]
Ah, the check is indeed in the wrong place. Feel free to submit a PR with the check moved and a test that the right error is raised.
I'm not sure why you want to print and continue, though, because the list is empty, right?

**Comment by leferrad** [comment]
Yeah you're right! I just give an example to avoid a crash in the max_frequency calc, but for surely it's not the solution. Maybe the best solution is to make the check first, and if it's True then I can proceed with the rest of the function, and if not I just skip and return 'self' object. I'm not sure because I'm not familiar with the full code, but give me time and I will try to PR a worthwhile correction on that.
