### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by anderl80** [amueller/word_cloud#203]
Thanks for the great implementation!! Can you briefly comment on performance on large texts. How big could a text file possibly be?

**Comment by amueller** [comment]
The size of the text is not that big a problem, the rendering of the image takes more time usually (and depends on the resolution).
If you run it on all of project Gutenberg or all of wikipedia it will be a while. But your average book should be instantaneous. If it's too slow, try disabling collocations and see if that helps.
