### ISSUE TITLE
Words appearing twice

### ISSUE THREAD

**Issue by kakakhan2016** [amueller/word_cloud#206]
First of all thanks for your great and awesome project. I am complete beginner in python but some how after lots of trial and error finally successfully created wordclouds from example. I already have some process data text files which contain one word per line, which are sorted alphabetcally. Using this text file create wordcloud in which words are appearing two time. But after randomizing lines in text processing software, there are no repetition of words. How can it be done in wordcloud without going for randomizing lines. 
I am attaching sample text and result for easy reference. Thanks in advance
![result](https://cloud.githubusercontent.com/assets/24565108/21179758/4b81c420-c217-11e6-84aa-894bd8dc7947.jpg)

**Comment by amueller** [comment]
The order of the words shouldn't matter really. Can you post your code? You should use ``generate_from_text``, and that should work well on the sorted ones with the duplicates.

**Comment by kakakhan2016** [comment]
Thanks a lot for your prompt help. It works like charm.
