### ISSUE TITLE
Wordcloud generation with frequencies

### ISSUE THREAD

**Issue by kakakhan2016** [amueller/word_cloud#207]
I am using following code for generating wordcloud from frequencies

from wordcloud import WordCloud
from PIL import Image
import matplotlib.pyplot as plt

MyData=(('Hello',4), ('Two', 2), ('Three',6), ('Final',10))
wc = WordCloud().generate_from_frequencies(MyData)

figure(figsize=(12,4))
subplot(1,2,1)
imshow(wc)

but getting following error
Traceback (most recent call last):
  File "D:\word_cloud-master\frequencies.py", line 15, in <module>
    wc = WordCloud().generate_from_frequencies(MyData)
  File "C:\Python27\lib\site-packages\wordcloud-1.2.1-py2.7-win32.egg\wordcloud\wordcloud.py", line 347, in generate_from_frequencies
    frequencies = sorted(frequencies.items(), key=item1, reverse=True)
AttributeError: 'tuple' object has no attribute 'items'

**Comment by amueller** [comment]
the interface changed in the laster version (as you can see from the docstrings).
do ``MyData = dict(MyData)``

**Comment by kakakhan2016** [comment]
Thanks again for solution. Code is working now.
