### ISSUE TITLE
problem installing package with conda command line

### ISSUE THREAD

**Issue by CyclingFoodManPA** [amueller/word_cloud#214]
I utilized the command line recommended to install via conda and received the error message:
Error:  HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/win-64/.

Any ideas on what caused this as it is bugging me as I really want to get you package working.

**Comment by amueller** [comment]
Maybe try pip. I haven't really worked on the conda packages and don't have time for them now.
Are you on windows? There is no conda package for windows right now, I think.

**Comment by amueller** [comment]
You're more than welcome to help with packaging if you like, but I think pip is the easiest, if your compiler is set up correctly.

**Comment by CyclingFoodManPA** [comment]
Ok, I used pip once to install something on Anaconda and I was not able to do a conda install xyz again.  Had to reinstall Anaconda2.  THEN I found somewhere on the web that said NOT to use pip with Anaconda.  There is a pip in Anaconda2 in the Lib\site-packages\pip directory so I have to figure out how to use it.  I am a newbie to Analytics and Python/R (have been developing for 30 years as a C, VB.NET, C#, etc. dev) so I am having fun and frustrations with the Analytics/Python/R world.  But it keeps me out of trouble :).  I am on Windows - 7 at work and 10 at home.  Started playing with Ubuntu but there is too much stuff to learn at once when adding in the Analytics stuff.

**Comment by amueller** [comment]
don't try to upgrade something with pip that you installed with conda, or the other way around.
It's totally fine to install something with pip into a conda environment. But if you want to use conda on it, remove it first (entirely).

**Comment by CyclingFoodManPA** [comment]
OK, I got things to work :):)  I updated pip within the conda environment and then installed wordcloud with pip.  I then had to install VCForPython27.msi as the install for wordcloud didn't work as I needed the VC compiler.  FYI, I am using Windows 10 Pro, with Anaconda 2 and updated pandas, scikit-learn, matplotlib to the most current libraries.

**Comment by amueller** [comment]
glad you got it working. I should really create wheels and conda packages but I'm way swamped.

**Comment by CyclingFoodManPA** [comment]
No problem, that is why I specified what I did so anyone reading this thread will have a clue what to do.  I am an experienced dev (COBOL, C, C++, C#, VB.NET, etc) and am getting into Analytics and lovin' it.  I enjoy trying to figure things out like this.  Getting into R and Python now to compare and contrast the languages and possibly use both, easy and fast string processing in Python, and the ease of doing other things in R.  Love your library when I got it working!

**Comment by amueller** [comment]
<plug>[buy my book!](https://www.amazon.com/Introduction-Machine-Learning-Python-Scientists/dp/1449369413/ref=sr_1_1?ie=UTF8&qid=1479485017&sr=8-1&keywords=introduction+to+machine+learning+with+python) It's for developers that want to learn machine learning in python</plug>

**Comment by CyclingFoodManPA** [comment]
Ok, looks good.  I have to finish the book I am reading now which is "Data Science for Business" as I just started that today.  Just finished "Data Analytics Made Accessible" and am re-writing all the R code in Python for Dr. Maheshwari as I finished his book two weeks ago.  Being in IT for so many years, I have had to adopt the discipline to finish the book I am reading before I get another book.  Yea, when I stared learning C# I bought boatloads of books, only read a couple of chapters of each.  I do plan on taking the edx.org certification program in Data Science as I already have a Masters Degree in Computer Science and have NO desire for a PhD :).  Thanks for the recommendation as I will add that to my Python - Data Science wish list for Amazon as it looks awesome.

**Comment by amueller** [comment]
Data Science for Business is definitely a great choice, too. I met Foster at NYU ;)

**Comment by CyclingFoodManPA** [comment]
Awesome - that book was recommended to me by Dr. Cynthia Rudin and Dr. Stephen Elston who taught a course on Microsoft Virtual Academy on Data Science.  Started reading it during Jury Duty this week!  Hope to get it finished in the next week or so.  Glad there was another recommendation from you and must be cool to have met someone of Foster's caliber.

**Comment by amueller** [comment]
Closing, replacing by #232. The conda packaging needs fixing and we should build wheels.
