### ISSUE TITLE
Only one word wordcloud

### ISSUE THREAD

**Issue by kakakhan2016** [amueller/word_cloud#216]
Is it possible to create wordcloud of one or only few words suppose using only 5 words using frequecies. For e.g following is sample list with frequencies
Cat 8
Cat 4
Dog 4
Dog 3
Dog 1

**Comment by amueller** [comment]
I'm not sure I understand the question. You can provide arbitrary dictionaries to ``generate_from_frequencies``

**Comment by kakakhan2016** [comment]
How can we create wordcloud with only one word data. For example only one word CAT should be used to create wordcloud.  Following is sample which I created in illustrator. 
![catonly](https://cloud.githubusercontent.com/assets/24565108/21756380/6f7df40e-d642-11e6-968b-861b8dbdccfd.jpg)

I tried MyData=dict([ ('CAT',6),('CAT',2),('CAT',1),('CAT',3),('CAT',7) ]) this which create only one word CAT. 

It mean cat with 7 frequency is taken and remaining are ignore. 
I am beginner in pyhton, is my above code is using an arbitrary dictionary?
Will you please guide me in right direction regarding arbitrary dictionary.

**Comment by amueller** [comment]
Well, dictionaries have unique keys. I guess that is a use-case that I didn't take into account when moving from tuples to dictionaries in the interface.

You can use the multidict library, I guess?
```python
import numpy as np
from wordcloud import WordCloud
import multidict

words = multidict.MultiDict()
for i in range(100):
    words.add('cat', np.random.randint(1, 10))
wc = WordCloud(max_font_size=20).generate_from_frequencies(words)
```
If that works for you, it would be great if you could add an example to the repository.

**Comment by kakakhan2016** [comment]
Thanks for reply. I am getting multidict import error. Downloaded wheel multidict-2.1.2-cp27-cp27m-win32.whl and pip install showing unsupported platform. I am using windows 7, python 2.7.

**Comment by amueller** [comment]
If you have problems installing multidict, please ask them for help.

**Comment by JamesTing** [comment]
Can you keep the tuples parameter?

**Comment by amueller** [comment]
@JamesTing please open another issue. Do you have a suggested fix? Is there a reason why multidict doesn't work for you? Can you maybe try pandas Series?

**Comment by JamesTing** [comment]
I'm a  python newbie, could you give a "pandas+wordcloud" example?
Thanks very much!

**Comment by amueller** [comment]
try passing a pandas Series to ``generate_from_frequencies`` - I haven't tested it but it should work.

**Comment by JamesTing** [comment]
Here is my code:
```
import pandas
words = pandas.Series({'cat':1000,'cat':4,'cat':3,'cat':2,'cat':1})
wordcloud = WordCloud().fit_words(words)
```
I get this error message
'Series' object has no attribute 'items'
![2017-03-25 23 53 44](https://cloud.githubusercontent.com/assets/1875508/24323811/8af01546-11b6-11e7-9525-7e0a9bc65edd.png)

**Comment by amueller** [comment]
That code runs for me. Though that's not what you want. You are specifying it as a dict, which can only have unique keys. ``{'cat':1000,'cat':4,'cat':3,'cat':2,'cat':1}`` evaluates to ``{'cat':1}``.
You could do
```python
words = pandas.Series(data=[1000, 4, 3, 2, 1], index=['cat'] * 5)
```
though there seems to be some other issues.. hm...

**Comment by amueller** [comment]
It's a bit tricky

**Comment by vfulco** [comment]
+1 for the tuple return, Some downstream code from another author broke on me while experimenting and I am not facile enough in python to fix.  Thx for considering and the great code set itself.

**Comment by amueller** [comment]
@vfulco PR welcome for a fix, though I'd rather not go backwords on the current public interface. changing the internal structure would be fine with me, though, or maybe adding a property and doing a deprecation?
