### ISSUE TITLE
n-gram word clouds?

### ISSUE THREAD

**Issue by nishitd** [amueller/word_cloud#217]
Is it possible to facilitate n-gram in the word cloud such as "good call", "bad data" from the corpus, for say 2 to 3 or even more words?

**Comment by amueller** [comment]
The current version on github uses bigrams and unigrams by default.
I suspect you want also unigrams, not only bigrams or trigrams.
The problem with doing this straight-up (which you can easily do with generate_from_frequencies), is that the unigrams will always be more frequent then the bigrams. So my star wars cloud would have "Death", "Star" and "Death Star". I didn't like that. So I detected collocations, that is common bigrams, and then subtracted the frequency of the bigram from the frequencies of the unigrams.
That's a hacky heuristic but the result looks good to me.
I didn't implement collocations for three words, but that would be easy to do. Feel free to create a PR (and / or write docs for what's happening now lol)
Code is at https://github.com/amueller/word_cloud/blob/master/wordcloud/tokenization.py#L36

**Comment by amueller** [comment]
Closing as I think this solves the issue. Feel free to reopen.
