### ISSUE TITLE
 prefer_horizontal value for making all words horizontal

### ISSUE THREAD

**Issue by kakakhan2016** [amueller/word_cloud#218]
Mixture of Horizontal and Vertical like wordle looks great and in my opinion  your wordcloud result is far better then wordle with masking feature.  

I want my wordcloud words to be horizontal only and have tried  prefer_horizontal value from 1 to 100 but  there are always many words appearing vertically.  
wordcloud code tell that prefer_horizontal is the ratio of times to try horizontal fitting as opposed to vertical and has default=0.90 value.

**Comment by amueller** [comment]
Hm, I recently changed the algorithm and that's when that broke. ``prefer_horiziontal`` should be between 0 and 1. I just pushed a patch that should only give you horizontal words with ``prefer_horizontal=1``.

The algorithms for rotating is pretty bad right now, I'm not sure if there's a better heuristic.

**Comment by kakakhan2016** [comment]
Thanks amueller for quick fix. Now prefer_horizontal=1 making all words perfectly horizontal.
