### ISSUE TITLE
Problems building query_integral_image

### ISSUE THREAD

**Issue by IgorAPM** [amueller/word_cloud#220]
Hello, Andy.

I'm having the same problem posted here:
https://github.com/amueller/word_cloud/issues/125

but this time it's on windows. Whenever I try building only the extension manually, I get the following output

_C:\Users\IGORAPM\Downloads\Compressed\word_cloud-master\word_cloud-master>python setup.py build_ext -i
running build_ext
building 'wordcloud.query_integral_image' extension
C:\Users\IGORAPM\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python2732\include -IC:\Python2732\PC /Tcwordcloud/query_integral_image.c /Fobuild\temp.win32-2.7\Release\wordcloud/query_integral_image.obj
query_integral_image.c
C:\Users\IGORAPM\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Python2732\libs /LIBPATH:C:\Python2732\PCbuild /EXPORT:initquery_integral_image build\temp.win32-2.7\Release\wordcloud/query_integral_image.obj /OUT:build\lib.win32-2.7\wordcloud\query_integral_image.pyd /IMPLIB:build\temp.win32-2.7\Release\wordcloud\query_integral_image.lib /MANIFESTFILE:build\temp.win32-2.7\Release\wordcloud\query_integral_image.pyd.manifest
error: can't copy 'build\lib.win32-2.7\wordcloud\query_integral_image.pyd': doesn't exist or not a regular file_

I tried using pip three times and it didn't work, and it showed no errors.
It might just be me being a noob, but I can't figure out what went wrong.

**Comment by amueller** [comment]
This seems to be a different issue. Unfortunately I haven't built wheels so pip will try to compile the package, and there seems to be some issue with your compilation.
Have you checked out the online tutorials for building cython with visual studio?

**Comment by IgorAPM** [comment]
I spent the whole day trying to figure this out but it did not help. I think I got a little balder. I looked everywhere for a solution, looked over the documentation, it did not help at all. I even modified your setup,py code to include some lines that other people recommended. It looks like this now:

from setuptools import setup
from setuptools.extension import Extension
from Cython.Distutils import build_ext

ext_modules = [Extension("wordcloud.query_integral_image",
                           ["wordcloud/query_integral_image.pyx"])]

setup(
    author="Andreas Mueller",
    author_email="t3kcit+wordcloud@gmail.com",
    name='wordcloud',
    version='1.2.1',
    url='https://github.com/amueller/word_cloud',
    description='A little word cloud generator',
    license='MIT',
    install_requires=['matplotlib', 'numpy>=1.6.1', 'pillow'],
    cmdclass = {'build_ext': build_ext},
    ext_modules = ext_modules,
    scripts=['wordcloud/wordcloud_cli.py'],
    packages=['wordcloud'],
    package_data={'wordcloud': ['stopwords', 'DroidSansMono.ttf']}
)


The error actually disappeared, however, I can't for the life of me figure out where the heck did the compiler throw the file. The new output looks like this:

C:\Users\IGORAPM\Downloads\Compressed\word_cloud-master\word_cloud-master>python setup.py build_ext --inplace
running build_ext
skipping 'wordcloud\query_integral_image.c' Cython extension (up-to-date)
building 'wordcloud.query_integral_image' extension
C:\Users\IGORAPM\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python2732\include -IC:\Python2732\PC /Tcwordcloud\query_integral_image.c /Fobuild\temp.win32-2.7\Release\wordcloud\query_integral_image.obj
query_integral_image.c
C:\Users\IGORAPM\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Python2732\libs /LIBPATH:C:\Python2732\PCbuild /EXPORT:initquery_integral_image build\temp.win32-2.7\Release\wordcloud\query_integral_image.obj /OUT:C:\Users\IGORAPM\Downloads\Compressed\word_cloud-master\word_cloud-master\wordcloud\query_integral_image.pyd /IMPLIB:build\temp.win32-2.7\Release\wordcloud\query_integral_image.lib /MANIFESTFILE:build\temp.win32-2.7\Release\wordcloud\query_integral_image.pyd.manifest

The folders indicated there are empty, the only file that it managed to create was the query_integral_image.obj

**Comment by IgorAPM** [comment]
Well, I don't know what I got wrong there but I found another solution, I found a page with a bunch of whl files, one of them happened to be wordcloud, somebody else must have built wheels for it, here is the link if you want to share this on your page, it's your project after all.

http://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud

thank you for the help. these tools are helping me a lot :)

**Comment by amueller** [comment]
Awesome! Gohlke does build a bunch of packages for windows. @IgorAPM do you want to create a PR mentioning this in the readme? This library needs some love but currently I don't have the time :-/
