### ISSUE TITLE
Word Frequency and displayed size not correctly proportional

### ISSUE THREAD

**Issue by DKWoods** [amueller/word_cloud#222]
I'm trying to integrate word_cloud into my app, but the resulting images seem to be consistently misleading.

I've attached a file with simple python code and the resulting image.  Looking at the code, you'll see that the two most frequent words are "this" and "romney", both with a frequency of 5 occurrences.  So I would expect them to be represented as words in the same font size, or perhaps with the same overall area in the display, or at least some way that would visually indicate the "sameness" of their frequency.  Instead, the word "this" is presented with font_size of 470 and "romney" with font_size of 220, so that "this" looks MUCH more important than "romney."

"what", "here", "question", "we're", "crowley", and "have" all have a frequency of 4, but font sizes varying from 152 to 58 (and not correlated with word length).

(The custom color function isn't strictly necessary, but I found it was an easy way to see what the font sizes were of the different words in the cloud.)

Am I missing something in how the Word Cloud is supposed to work?  Am I mis-using some setting?

David

[WordCloud.zip](https://github.com/amueller/word_cloud/files/717785/WordCloud.zip)

**Comment by amueller** [comment]
Try the new version on github, it will represent the relative frequencies better.
Also, you can try setting ``max_font_size`` smaller and ``relative_scaling=1``.
