### ISSUE TITLE
regexp cli argument for wordclout_cli.py

### ISSUE THREAD

**Issue by rubienr** [amueller/word_cloud#224]
I faced some limitations when using wordcloud_cli.py. The default regexp  \w[\w']+ does not match i.e. "c" "c++", "R", "µC", see [1].  I would recommend to register a new optional command line argument and pass it to the WordCloud constructor.

```
parser.add_argument('--regexp', metavar='regexpression', default="\w[\w']+",
help="specify an explicit regular expression, default is \w[\w']+")
wordcloud = wc.WordCloud(..., regexp=regexpression).generate(args.text)
```
[1] http://fiddle.re/60e26n

**Comment by amueller** [comment]
PR welcome though I'm a bit slow with reviews right now.
I'm surprised it didn't match µC (also what's that?)

**Comment by rubienr** [comment]
I tried to use your tool for generating a word cloud for my CV, thus the more technical terms (µC - abbreviation for Microcontroller). But I think using the API instead of wordcloud_cli.py is more suitable for my needs, since I need terms consisting of more that one word, i.e.  "real-time protocol" or "Android service":
```
termsToWeights = readTermsFromCsvFile("filename.txt")
self.generate_from_frequencies(termsToWeights)
```
In general I think it is still a good idea to keep the regexp exchange-able using the CLI wrapper, although I would classify the priority as low.

**Comment by amueller** [comment]
Ah, thought it was a programming language because the other terms were ;)
If you use the current github version, it will find words like "Android service" automatically. If you adjust the regex "real-time protocol" will be two words and then it'll find it, too. It's currently limited to two words.

**Comment by rubienr** [comment]
Thank you for the hint. I would still face the this issue: "1-Wire" will not match.
My **workaround**: Read terms and weights from CSV not using wordcloud_cli.py, then apply:
```
wc.generate_from_frequencies(termToWeightTupleList)
``` 
In case you find the feature request irrelevant, simply close this issue.

tnx,
r²
