### ISSUE TITLE
ImportError: The _imaging extension was built for another version of Pillow or PIL

### ISSUE THREAD

**Issue by thakursc1** [amueller/word_cloud#225]
Getting this error while Installing

**Comment by amueller** [comment]
This means you are mixing environments and your installation of the imaging module is broken.

**Comment by thakursc1** [comment]
Solved. I was installing Pillow when I was supposed to install Image library

**Comment by thakursc1** [comment]
It would be good if you put up a requirements.txt 
Also I love your package.

**Comment by amueller** [comment]
installing pillow is perfectly fine. Packages don't need to have a requirements file, that wouldn't really help. All the requirements need to be declared in setup.py.

**Comment by jonokay1** [comment]
**SOLVED:** python version 3.6 
__imaging is imported as core, so_

Edit the image.py file located in your PIL folder. 

1. File Location: C:\ProgramData\Anaconda3\Lib\site-packages\PIL
2. Find 
if PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
        raise ImportError("The _imaging extension was built for another "
                          "version of Pillow or PIL:\n"
                          "Core version: %s\n"
                          "Pillow version: %s" %
                          (getattr(core, 'PILLOW_VERSION', None),
                           PILLOW_VERSION))

3. Add **_core._** before PILLOW_VERSION to make it _core.PILLOW_VERSIO_N i.e.
if **core.PILLOW_VERSION** != getattr(core, 'PILLOW_VERSION', None):
        raise ImportError("The _imaging extension was built for another "
                          "version of Pillow or PIL:\n"
                          "Core version: %s\n"
                          "Pillow version: %s" %
                          (getattr(core, 'PILLOW_VERSION', None),
                           PILLOW_VERSION))
4. Save file
5. Good to go 👍

**Comment by amueller** [comment]
Installing pillow is the recommended way to install ``Image``, but if it works for you that's fine.
@jonokay1 that seems like a very strange fix. There is probably some other issue with your setup.

**Comment by jonokay1** [comment]
@amueller I tried installing the pillow as an exe, with pip, and with conda, all failed to solve the issue, but this worked.

**Comment by amueller** [comment]
As long as it works. I was just saying that this is not a fix anyone else should be using. Debugging what your actual issue is would probably involve a bit of digging and not sure that's worth it.

**Comment by michaelhall005** [comment]
Im having the same issue trying to run:
from PIL import Image

I dont have PIL to uninstall. I have tried uninstalling Pillow and re-installing the latest version, version 4.1.1, version 5.0.0 and nothing seems to work. 

------------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-60-b7f01c2f8cfe> in <module>()
----> 1 from PIL import Image

~\AppData\Local\Continuum\anaconda3\lib\site-packages\PIL\Image.py in <module>()
     65                           "Pillow version: %s" %
     66                           (getattr(core, 'PILLOW_VERSION', None),
---> 67                            PILLOW_VERSION))
     68 
     69 except ImportError as v:

ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: 4.1.1
Pillow version: 5.0.0

**Comment by jonokay1** [comment]
@michaelhall005 try the solution I posted earlier and see if that works for you. I had a similar issue to what you have

**Comment by amueller** [comment]
@michaelhall005 how did you install pil? Try uninstalling, make sure it's completely removed from your system (check if the folder still exists) and then install using conda. That should work.

**Comment by michaelhall005** [comment]
@amueller I tried to uninstall PIL however it said it did not exist. I took @jonokay1 tip and added "core" to the image file and it works now. Thanks both
