### ISSUE TITLE
ImportError: No module named wordclould

### ISSUE THREAD

**Issue by deepakm925** [amueller/word_cloud#228]
Hello @amueller I am trying to get wordcloud to work on Anaconda 2.7 on my Mac. However i keep getting the error 
`ImportError: No module named wordclould`

I did pip install wordclould in terminal. It installed successfully but i still receive the same error
I also tried your conda install method still does not work. 
I have given my import codes below. Help would be appreciated thanks

import os
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from nltk.corpus import stopwords 
pd.set_option("display.max_rows", 999)
pd.set_option('max_colwidth',100)
from IPython.display import display
%matplotlib inline

**Comment by amueller** [comment]
Is your file called "wordcloud.py"?

**Comment by deepakm925** [comment]
No it is called "rough code.ipynb" its a I python notebook file

**Comment by amueller** [comment]
Did ``pip install wordcloud`` succeed? Then it was installed. Maybe your pip does not belong to the same environment as the juptyer you are using. Make sure you use the right pip for this environment.

**Comment by deepakm925** [comment]
ok so i re installed  it within my anaconda environment within this directory 
Deepaks-MacBook-Pro:~ Deepak$ cd /Users/Deepak/anaconda/lib/python2.7 

It still does not work

**Comment by amueller** [comment]
in your jupyter notebook, what is in "os.path"? Is this folder included?

**Comment by deepakm925** [comment]
OK when i input os.path i get:<module
` 'posixpath' from '/Users/Deepak/anaconda/lib/python2.7/posixpath.pyc'

its the same path I am installing it on

**Comment by amueller** [comment]
I meant call ``os.path()``.

**Comment by deepakm925** [comment]
yes thats the output i get when i call it 

`os.path`

**Comment by amueller** [comment]
It's a function. That's not the output you get when you call the function (see the parenthesis).

**Comment by deepakm925** [comment]
ok this what im doing 
```
import os
os.path()
```

**Comment by amueller** [comment]
see fixed comment.

**Comment by deepakm925** [comment]
i still get the error 
TypeError: 'module' object is not callable

**Comment by amueller** [comment]
``sys.path`` should be a list not a module.

**Comment by deepakm925** [comment]
ok yes i got that to work here's what it generates below:
import os
import sys
sys.path

Output : `['',
 '/Users/Deepak/anaconda/lib/python27.zip',
 '/Users/Deepak/anaconda/lib/python2.7',
 '/Users/Deepak/anaconda/lib/python2.7/plat-darwin',
 '/Users/Deepak/anaconda/lib/python2.7/plat-mac',
 '/Users/Deepak/anaconda/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/Deepak/anaconda/lib/python2.7/lib-tk',
 '/Users/Deepak/anaconda/lib/python2.7/lib-old',
 '/Users/Deepak/anaconda/lib/python2.7/lib-dynload',
 '/Users/Deepak/anaconda/lib/python2.7/site-packages',
 '/Users/Deepak/anaconda/lib/python2.7/site-packages/Sphinx-1.4.6-py2.7.egg',
 '/Users/Deepak/anaconda/lib/python2.7/site-packages/aeosa',
 '/Users/Deepak/anaconda/lib/python2.7/site-packages/geopy-1.10.0-py2.7.egg',
 '/Users/Deepak/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg',
 '/Users/Deepak/anaconda/lib/python2.7/site-packages/IPython/extensions',
 '/Users/Deepak/.ipython']

**Comment by amueller** [comment]
and does ``/Users/Deepak/anaconda/lib/python2.7/site-packages/`` contain wordcloud?

**Comment by deepakm925** [comment]
ok i un installed wordcloud and cd into that directory and re installed it in that directory. I re started anaconda and re ran the : 
import sys
sys.path

I still do not see wordcloud within that list

**Comment by amueller** [comment]
what do you mean by "installed in in that directory"?
You should install it with the pip that is associated with this python environment.
And I wasn't asking if it was in this list, but if it was in that folder.
You can make sure you use the right pip by calling
``/Users/Deepak/anaconda/bin/pip install wordcloud``

**Comment by deepakm925** [comment]
Oh boy . That was the issue. 
I have never really needed to uses pip install for my modules because Anaconda has most of them. So i usually just conda install....

Now i know for future pip installs how to and whee to save them 
 Thanks a lot for the help! 

![screen shot 2017-02-01 at 6 58 11 pm](https://cloud.githubusercontent.com/assets/19829858/22531735/de233510-e8b0-11e6-921b-3ebcd3257d43.png)

**Comment by amueller** [comment]
np, glad you got it figured out.

**Comment by leslietang** [comment]
I also have same problem

Collecting wordcloud
  Using cached https://files.pythonhosted.org/packages/23/4e/1254d26ce5d36facdcbb5820e7e434328aed68e99938c75c9d4e2fee5efb/wordcloud-1.5.0-cp37-cp37m-win_amd64.whl
Requirement already satisfied: pillow in d:\python\lib\site-packages (from wordcloud) (5.4.1)
Requirement already satisfied: numpy>=1.6.1 in d:\python\lib\site-packages (from wordcloud) (1.16.2)
Installing collected packages: wordcloud
Successfully installed wordcloud-1.5.0


i have install wordcloud successfully

but i still get this 

Traceback (most recent call last):
  File "D:/Python学习/11.19.py", line 3, in <module>
    import wordcloud
ImportError: No module named 'wordcloud'
>>>

**Comment by leslietang** [comment]
I also have same problem

Collecting wordcloud
  Using cached https://files.pythonhosted.org/packages/23/4e/1254d26ce5d36facdcbb5820e7e434328aed68e99938c75c9d4e2fee5efb/wordcloud-1.5.0-cp37-cp37m-win_amd64.whl
Requirement already satisfied: pillow in d:\python\lib\site-packages (from wordcloud) (5.4.1)
Requirement already satisfied: numpy>=1.6.1 in d:\python\lib\site-packages (from wordcloud) (1.16.2)
Installing collected packages: wordcloud
Successfully installed wordcloud-1.5.0


i have install wordcloud successfully

but i still get this 

Traceback (most recent call last):
  File "D:/Python学习/11.19.py", line 3, in <module>
    import wordcloud
ImportError: No module named 'wordcloud'
>>>

**Comment by amueller** [comment]
@leslietang the python that you're using is likely not in the same environment as the pip you used to install. Check ``sys.path`` and see if it includes ``d:\python\lib\site-packages``
