### ISSUE TITLE
The figure seems to have burs, how can I debur to make the image clear?

### ISSUE THREAD

**Issue by loveQt** [amueller/word_cloud#229]
I tried to generate a test image using default settings but got unsatisfying result.

I have used this lib before on my laptop and it works fine, but on my new PC it can't get the perfect figure.

What probably be the point? How can I debur the image?

I tested both Python 3.5 and Python 2.7, got the same result.

![fig1](https://cloud.githubusercontent.com/assets/12681955/22918874/91229c1c-f2c7-11e6-8bf3-5bb598c42e10.png)
![figure_2](https://cloud.githubusercontent.com/assets/12681955/22918877/9a345070-f2c7-11e6-8a60-224c2ee02312.png)

**Comment by amueller** [comment]
you need to up the width and height if you want higher resolution.

**Comment by sun8134** [comment]
WordCloud(font_path='fzzk.ttf',background_color="white",**scale =2**).generate(text)
我觉得你肯定能看懂中文我就直接说中文了...
直接把比例调大看看效果
可能是你词太少生成的图片太小了，放大后出现马赛克

加上 scale =2 试试吧

这个还是很好用的

![241ad1f0-ecfc-11e6-8169-005056870322](https://cloud.githubusercontent.com/assets/3926568/22933730/788d4f7c-f307-11e6-835e-3c3aa4a69d4f.png)
![2c1ba61e-db8d-11e6-9800-005056870322](https://cloud.githubusercontent.com/assets/3926568/22933754/85072e26-f307-11e6-804f-0414eb6af97a.png)

**Comment by amueller** [comment]
using a mask means the resolution of the mask is used. I'm not sure what you're saying as I don't speak Chinese.

**Comment by loveQt** [comment]
@sun8134 我试了不行，我不觉得是这个的问题，就很奇怪，同样的代码放其他地方就是好的。我怀疑是我本地哪个库有问题。我手头一个笔记本，一个台式，一个服务器，笔记本和服务器都正常，台式有这样的毛刺。

@amueller He offers me to set the scale value but doesn't work as well. It's confusing that the same code gets different results on my laptop and PC. I wonder maybe something on my PC is wrong but  I don't know what's wrong.

**Comment by amueller** [comment]
the same code will yield the same result if it's the same version of wordcloud.
Can you provide the code that gives you a problem?
And have you tried setting the resolution higher as I just suggested?

**Comment by loveQt** [comment]
`from wordcloud import WordCloud
import matplotlib.pyplot as plt
frequencies = [(u'world', 5), (u'freeze', 4), (u'winter', 3), (u'happy', 2), (u'test', 1)]
wordcloud = WordCloud().fit_words(frequencies)
plt.imshow(wordcloud)
plt.axis("off")
wordcloud = WordCloud(max_font_size=20, relative_scaling=1,scale=2,width=1000,height=500).fit_words(frequencies)
plt.figure()
plt.imshow(wordcloud)
plt.axis("off")
plt.show()`

simple test code.
wordcloud version 1.2.1. I used .whl file to setup.


![Uploading 微信截图_20170214231245.png…]()

**Comment by amueller** [comment]
```python
from wordcloud import WordCloud
import matplotlib.pyplot as plt
frequencies = [(u'world', 5), (u'freeze', 4), (u'winter', 3), (u'happy', 2), (u'test', 1)]
wordcloud = WordCloud().fit_words(frequencies)
plt.imshow(wordcloud)
wordcloud.to_file("test1.png")

plt.axis("off")
wordcloud = WordCloud(width=1000,height=500).fit_words(frequencies)
plt.figure()
plt.imshow(wordcloud)
wordcloud.to_file("test2.png")
plt.axis("off")
plt.show()
```

It' looks a bit weird in the notebook but if you look at the stored png files, test2.png looks good to me. test1.png has a relatively low resolution, which is why it doesn't look as good.

**Comment by loveQt** [comment]
from wordcloud import WordCloud
frequencies = [(u'world', 5), (u'freeze', 4), (u'winter', 3), (u'happy', 2), (u'test', 1)]
wordcloud = WordCloud().fit_words(frequencies)
import matplotlib.pyplot as plt
plt.imshow(wordcloud)
plt.axis("off")
wordcloud = WordCloud(max_font_size=20, relative_scaling=1,scale=2,width=1000,height=500).fit_words(frequencies)
plt.figure()
plt.imshow(wordcloud)
plt.axis("off")
plt.show()





simple test code.
wordcloud version 1.2.1. I used .whl file to setup.

the same code yields different results as shown.

![_20170214231245](https://cloud.githubusercontent.com/assets/12681955/22934926/be11cb1e-f30b-11e6-80cb-40d2a10ec915.png)
![_20170214232342](https://cloud.githubusercontent.com/assets/12681955/22935206/db41cb16-f30c-11e6-8c59-9a86cbd8b15f.png)

**Comment by loveQt** [comment]
Solved.

I degraed my matplotlib from 2.0 to 1.5.3, which is the old version on my laptop. Now they seem to be the same resolution.

and then i update the matplotlib on my old laptop to 2.0.0, rerun the script and got the bad resolution again.

But why the latest matplotlib could result in such bad resolution?

**Comment by amueller** [comment]
imshow doesn't do interpolation by default any more. You can set ``interpolation="bilinear"``.
