### ISSUE TITLE
TypeError?

### ISSUE THREAD

**Issue by melissakly** [amueller/word_cloud#239]
Hi Andreas!

I found your really cool world_cloud project on Github and I wanted to create my own word cloud. I pip installed the word cloud and ran the command line  "wordcloud_cli.py --text mytext.txt --imagefile wordcloud.png", where my .txt was a file with various decoding methods used for genomes. But it generated an "empty" .png and gave me the error "TypeError: integer argument expected, got float". Is this because I haven't specified a path for fonts, colors, etc? If it is that, then how do I specify the path from my terminal? Else, do you know how I can fix this? Thank you for all the help!

Sincerely, 
Melissa Ly

<img width="705" alt="screen shot 2017-03-20 at 1 28 38 pm" src="https://cloud.githubusercontent.com/assets/21248091/24120345/7fde0d82-0d71-11e7-80cb-8d222d112f3c.png">

**Comment by amueller** [comment]
Ah, sorry just saw your mail.
Which version of wordcloud do you have? Try ``pip install -U wordcloud`` to update.

**Comment by melissakly** [comment]
I pip installed it a week ago. I tried the -U to update but I got this error and I still keep getting an empty .png file. 
<img width="741" alt="screen shot 2017-03-20 at 3 24 44 pm" src="https://cloud.githubusercontent.com/assets/21248091/24124548/7ab50be8-0d81-11e7-9f62-4c4e67accce1.png">

**Comment by melissakly** [comment]
I have python 3 but I don't think that should affect anything.

**Comment by amueller** [comment]
you're definitely using your python2.7 right now, but that doesn't really matter. Can you try uninstalling and reinstalling wordcloud?

**Comment by melissakly** [comment]
Oops sorry, ya I'm on python2.7! Even the uninstallation does not work? 
<img width="768" alt="screen shot 2017-03-20 at 3 34 27 pm" src="https://cloud.githubusercontent.com/assets/21248091/24124859/e741fe1e-0d82-11e7-92d2-4bd8674e4516.png">

**Comment by amueller** [comment]
you installed it with ``sudo``, so then you need to uninstall it with ``sudo``, too.

**Comment by melissakly** [comment]
Thanks! I successfully uninstalled and then I ran `pip install wordcloud` to get this 
<img width="763" alt="screen shot 2017-03-20 at 3 51 10 pm" src="https://cloud.githubusercontent.com/assets/21248091/24125275/277f35e4-0d85-11e7-8e0f-22748ab410e0.png">

**Comment by melissakly** [comment]
running `pip install -U wordcloud`gets me the same Exception as above where there is a traceback error

**Comment by amueller** [comment]
you should try ``pip install wordcloud`` either with ``sudo pip install wordcloud`` or ``pip install --user wordcloud``

**Comment by melissakly** [comment]
Ahh sorry for bothering you so much Andreas. Thank you for all the help. I'm still getting this type error when I run `wordcloud_cli.py --text mytext.txt --imagefile wordcloud.png`
<img width="754" alt="screen shot 2017-03-20 at 5 20 54 pm" src="https://cloud.githubusercontent.com/assets/21248091/24127463/0a86e772-0d92-11e7-9657-c9c5a28a7b50.png">

**Comment by cjmay** [comment]
I am also seeing this issue.  Python 2.7, tried uninstalling and reinstalling wordcloud to no avail.

**Comment by cjmay** [comment]
Same thing on Python 3.5.

**Comment by cjmay** [comment]
In both cases I was getting wordcloud 1.3 from pypi.  Installing from master (which also installs as wordcloud 1.3) makes the issue go away.

**Comment by melissakly** [comment]
What do you mean installing from master?

**Comment by amueller** [comment]
He meant installing the version from github. I thought I had included this fix in the last release, but I did not :( #199

Give me 10 minutes, I'll update the pipy version with the fix. So Just update again then.

**Comment by amueller** [comment]
took me an our instead, whoops. Student came in ;) You should be able to update to 1.3.1 now and that should work.

**Comment by melissakly** [comment]
Resolved! Thank you :)
