### ISSUE TITLE
Some text distributions yield duplicate words in image

### ISSUE THREAD

**Issue by cjmay** [amueller/word_cloud#241]
As a workaround for #226 I tried generating text according to the desired distribution: [food.txt](https://github.com/amueller/word_cloud/files/858596/food.txt)

Note in particular there are few word types but relatively high number of tokens per type compared to natural language.  Tokens of each word type are also grouped.  (My guess would be one or both of these properties are causing the issue.)

However, `wordcloud_cli.py` (from master) on this generated text file, with default options, yielded a word cloud with each word duplicated conspicuously: ![food](https://cloud.githubusercontent.com/assets/457238/24154620/126cef40-0e28-11e7-8946-4e6284ceffae.png)

**Comment by amueller** [comment]
You can shuffle the data to get rid of this. This is not really natural text so I'm ok with this yielding weird results (though I can also see the argument for the other side). From the library side you can just use ``generate_from_frequencies``
