### ISSUE TITLE
Regex to not split hyphenated words.

### ISSUE THREAD

**Issue by quasistar** [amueller/word_cloud#245]
Hello,
  I've tried a few different regex that would allow me to keep hyphenated words as a single word (they're reddit usernames, so splitting them up is counter-intuitive). Unfortunately, everything I've tried has resulted in errors being tossed. I've tried r'(\w+(?:-\w+)+' as well as r'\w+[\w-]+' and a few others. I've tried \\\\ in place of the singular, to no avail. I'm not fully versed in python, so the issue is probably something small and on my part, but any assistance with this would be appreciated. The error is as follows:

> Traceback (most recent call last):
  File "L:\Langs\python\scripts\generatewc.py", line 84, in <module>
    wc.generate(text)
  File "L:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 556, in generate
    return self.generate_from_text(text)
  File "L:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 541, in generate_from_text
    words = self.process_text(text)
  File "L:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 512, in process_text
    words = re.findall(regexp, text, flags)
  File "L:\Python27\lib\re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
  File "L:\Python27\lib\re.py", line 237, in _compile
    p, loc = _cache[cachekey]
TypeError: unhashable type: 'list'

Line 84 from my code is as described above. It's actually just the non-colored alice example, repurposed. The only changes to your code are substitution of hard-coded stuff with variables, and the addition of parameters to the WordCloud call (ie: regexp=myRegexp). 

With the exception of this minor error, I absolutely love this.. and so do the fans of St. Louis Blues who visit the sub on reddit!

Thanks in advance!

Edit: Also, when you add words to the stopwords, are those regex or flat? Trying to figure a way to remove all instances of reddit links because linking a hockey sub in many hockey subs will show the flair for that team (ie: \[](\/r/stlouisblues) will show up as a blue note) .. so they're used a bit often.

**Comment by amueller** [comment]
Currently the stopwords are just words, no regexp. You an do a regex match on the text before and just remove all occurrences from the text.

**Comment by amueller** [comment]
`` r'\w[\w-]+'`` should do it, I think (or maybe you need to escape the dash.

**Comment by quasistar** [comment]
Hey, thanks for the quick reply! I tried your suggestion, and at first it didn't work. It was an issue in what I was doing (forgot that the variable was an array, doh!). I think I'm going to have to do this a different way, because hard-coding the regex works fine, but if I pass it in a variable (non-array), I get an index out of range error now on line 556 (wordcloud.py). Since this is the only regex I plan on using, I think what I'll do is just make the variable boolean.. and use a different WordCloud call based on the value.

Thanks for your help!

**Comment by amueller** [comment]
Sorry, i'm not sure I follow...

**Comment by quasistar** [comment]
If I try to set the regexp to a non-array variable (I was passing an array previously, without realizing it), it gives an error. If I hard-code it, there is no error. With this in mind, I'll just use the variable as a boolean. If true, call without the regex. If false, call with the regex hard-coded.

**Comment by amueller** [comment]
Well if hard-coding it is different than passing it as a variable, then that means the content of your variable is not right.

**Comment by quasistar** [comment]
`print(myregexp)`

`wc = WordCloud(background_color=bgcolor, max_words=maxwords, mask=alice_mask, stopwords=stopwords, mode=bgmode, regexp=myregexp)`

`wc.generate(text)`


>myregexp = r'\w[\w-]+'
Traceback (most recent call last):
  File "L:\Langs\python\apps\generatewc.py", line 103, in <module>
    wc.generate(text)
  File "L:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 556, in generate
    return self.generate_from_text(text)
  File "L:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 542, in generate_from_text
    self.generate_from_frequencies(words)
  File "L:\Python27\lib\site-packages\wordcloud\wordcloud.py", line 353, in generate_from_frequencies
    max_frequency = float(frequencies[0][1])
IndexError: list index out of range

Looks the same to me. It's alright, I've found a method that works.
