### ISSUE TITLE
Can't conda install wordcloud on fresh Python 3.6 conda environment

### ISSUE THREAD

**Issue by bklaas** [amueller/word_cloud#246]
The meta.yml file in the conda.recipe/ doesn't appear to have an issue with Python 3.6 but I can't successfully install wordcloud in a python 3.6 environment. This is on 64bit linux

# packages in environment at /home/benklaas/anaconda3/envs/wordcloud:
#
openssl                   1.0.2k                        1  
pip                       9.0.1                    py36_1  
python                    3.6.1                         0  
readline                  6.2                           2  
setuptools                27.2.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py36_0  
xz                        5.2.2                         1  
zlib                      1.2.8                         3  

[benklaas@iconoclast ~]$ source activate wordcloud
(wordcloud) [benklaas@iconoclast ~]$ conda install -c https://conda.anaconda.org/amueller wordcloud
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - wordcloud -> python 3.5*
Use "conda info <package>" to see the dependencies for each package.

**Comment by bklaas** [comment]
I should note, no problem installing in a Python 3.5 environment, which is fine for my purposes. Just reporting the issue...

**Comment by amueller** [comment]
Thanks, do you want to submit a PR to fix it?

**Comment by bklaas** [comment]
I would if I could figure out how to resolve it. 

To my eyes, the meta.yaml file that references python without version for both build and run sections should be fine, so I don't know why it's throwing the UnsatisfiableError exception.

For what it's worth I also tested against a python 3.4 conda environment and it failed there too. For some reason I can't figure out, wordcloud is insisting the 3.x version be 3.5.

**Comment by amueller** [comment]
thanks for investigating - unfortunately I can't look into it myself for now :-/

**Comment by thepurpleowl** [comment]
I am also facing the same problem. Have you find any solution ?? @bklaas

**Comment by amueller** [comment]
@thepurpleowl using pip ;)

**Comment by bklaas** [comment]
I just created a new conda environment with python=3.5 and wordcloud
installed. There isn't anything I needed in python 3.6, so that was an
acceptable solution for me.

**Comment by xenu256** [comment]
I have installed on conda/ Python 3.6 with:

```text
python setup.py build
python setup.py install
```
for both Windows and Linux without problems. Windows required a small fix though (not wordcloud related): https://stackoverflow.com/questions/43858836/python-installing-clarifai-vs14-0-link-exe-failed-with-exit-status-1158/44563421#44563421

**Comment by sudhirnl7** [comment]
Use below command to install wordcload for python 3.6
conda install -c https://conda.anaconda.org/amueller wordcloud

**Comment by spcmet** [comment]
Hi sudhirnl7, using the link to install wordcloud for python 3.6, i got below response

C:\Users\mehtaab>conda install -c https://conda.anaconda.org/amueller wordcloud
Fetching package metadata .................

PackageNotFoundError: Packages missing in current channels:

  - wordcloud

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/amueller/win-64
  - https://conda.anaconda.org/amueller/noarch
  - https://conda.anaconda.org/anaconda-fusion/win-64
  - https://conda.anaconda.org/anaconda-fusion/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

**Comment by amueller** [comment]
should be fixed now on conda forge
