### ISSUE TITLE
Building word clouds our of LDA 

### ISSUE THREAD

**Issue by Areejno** [amueller/word_cloud#247]
Hello
Thank you so much for this. I'm building the word clouds successfully out of text but I get an error when I try to use LDA output as follow:
plt.imshow(WordCloud().fit_words(ldamodel.show_topics(t,3)))

error >>>
______________________
File "C:\Users\A\AppData\Local\Continuum\Anaconda3\lib\site-packages\wordcloud-1.3.1-py3.6-win-amd64.egg\wordcloud\wordcloud.py", line 331, in fit_words
    return self.generate_from_frequencies(frequencies)

  File "C:\Users\A\AppData\Local\Continuum\Anaconda3\lib\site-packages\wordcloud-1.3.1-py3.6-win-amd64.egg\wordcloud\wordcloud.py", line 350, in generate_from_frequencies
    frequencies = sorted(frequencies.items(), key=item1, reverse=True)

AttributeError: 'list' object has no attribute 'items'
______________________

I'm using Python3.
Your help is much appreciated. 
Areej.

**Comment by amueller** [comment]
Hey.
The ``fit_words`` method now takes a dictionary. I'm not sure what the result of ``show_topics`` is.
You need to pass a dictionary from words to numbers. It might be enough to just call ``dict()`` on the output of ``show_topics`` but it depends.

**Comment by Areejno** [comment]
Hello
Thanks the previous error is gone now but another one shows up
ldamodel.show_topics(t,3) return the following
---- show topics without dict  [(3, '0.160*"sugar"'), (1, '0.075*"father"'), (2, '0.075*"pressure"'), (0, '0.063*"sister"'), (4, '0.029*"sister"')]
dict(ldamodel.show_topics(t,3)) return the following
---- show topics with dict  {1: '0.075*"father"', 0: '0.063*"sister"', 4: '0.029*"sister"', 2: '0.075*"pressure"', 3: '0.160*"sugar"'}
and I get this error -->
_______
 max_frequency = float(frequencies[0][1])
ValueError: could not convert string to float: '0.160*"sugar" + 0.060*"consume" + 0.060*"bad"'
_____
I'm sorry if my question doesn't seem right, I'm new to python,
I have attached the whole code just in case I have failed to mention something
[ldacloud.txt](https://github.com/amueller/word_cloud/files/889606/ldacloud.txt)

Much appreciated, thanks.

**Comment by amueller** [comment]
The dictionary needs to be from words to frequencies, your input is still not in the right format.

**Comment by Areejno** [comment]
You are right I was sending wrong format to the method, now its working. Thank you.

**Comment by amueller** [comment]
Glad you worked it out!

**Comment by duong4996** [comment]
Hi guys. How do you fix this problem? I have the same but i don't know the solutions. Please help me. Thank you !

**Comment by Areejno** [comment]
Hi,
fit_words(topic) method takes **topic** which is a list of term+probability for a specific topic.
For example:  [["car",0.07],["motor", 0.06]].
so you will have to loop through the topic list returned from the topic model and rewrite it in a new list in the right format for fit_words. Hope I'm making sense.

**Comment by duong4996** [comment]
I understanded the idea. It's better if you can visualize by some code because i'm a very python beginner. Anw, thank you so much <3

**Comment by Areejno** [comment]
I'm sorry, totally forgot about this.
take a look at this blog post, I think you can find your answer here
http://www.peculiarparity.com/using-gensim-with-andreas-muellers-word-cloud/

**Comment by amueller** [comment]
@Areejno Thanks, and I also appreciate the disclaimer that this should not be taken as a scientific representation of the data - I wholeheartedly agree.

**Comment by farazsid35** [comment]
@Areejno your link to corrected code has expired, can you please provide it again?
