### ISSUE TITLE
How do i get a dictionary object instead of a list in generate_from_frequencies

### ISSUE THREAD

**Issue by aj0271** [amueller/word_cloud#249]
Traceback (most recent call last):

  File "<ipython-input-37-b10ccab33346>", line 71, in <module>
    for word,score in top_words])

  File "C:\Users\RAJENDRAGHORPADE\Anaconda2\lib\site-packages\wordcloud\wordcloud.py", line 331, in fit_words
    return self.generate_from_frequencies(frequencies)

  File "C:\Users\RAJENDRAGHORPADE\Anaconda2\lib\site-packages\wordcloud\wordcloud.py", line 350, in generate_from_frequencies
    frequencies = sorted(frequencies.items(), key=item1, reverse=True)

AttributeError: 'list' object has no attribute 'items'

**Comment by amueller** [comment]
frequencies needs to be a dictionary in newer versions

**Comment by kumarniraj1994** [comment]
How can i get top 10 most frequent words .

**Comment by pybokeh** [comment]
@kumarniraj1994 wordcloud.process_text(str) returns a dict with words as keys and their respective frequencies as values. To sort the dict by values in descending order, used sorted() method which will return a list with key-value pairs saved as tuples:

```python
import operator
word_freq = wc.process_text(text)
top10 = sorted(A.items(), key=operator.itemgetter(1), reverse=True)[:10]
```

**Comment by amueller** [comment]
closing as I think @aj0271's issue is resolved (and they didn't comment) and @kumarniraj1994 issue is unrelated.
