### ISSUE TITLE
 generate_from_frequencies() missing 1 required positional argument: 'frequencies' 

### ISSUE THREAD

**Issue by YashwanthGithub** [amueller/word_cloud#250]
I am trying to build an wordcloud using below commands. However error keep coming even after defining self & frequencies. Kindly help
        
String | Frequency
------------ | -------------
DANNON ACTIVIA BREAKFAST BLEND  |  924
STONYFIELD FARM  |  640
YOPLAIT DESPICABLE ME  |  622

Code is as follows

    import wordcloud
    tuples = [tuple(x) for x in df.values]
    df_wordcloud = wordcloud.WordCloud.generate_from_frequencies(tuples)

Error is,

    Traceback (most recent call last):
      File "<pyshell#2>", line 1, in <module>
        wordcloud.WordCloud.generate_from_frequencies(tuples)
    TypeError: generate_from_frequencies() missing 1 required positional argument: 'frequencies' 

Thanks in advance!!!

**Comment by amueller** [comment]
You're missing parenthesis after ``WordCloud``. You're calling a method on the class.

**Comment by YashwanthGithub** [comment]
I corrected it, Working fine. Thanks.
