### ISSUE TITLE
pip installs wordcloud, import fails

### ISSUE THREAD

**Issue by makeyourowntextminingtoolkit** [amueller/word_cloud#252]
I use anaconda python and wordcloud is/was not part of the distribution. So I had to use

`pip install word cloud`

And it all worked well. 

But now with the latest and current Anaconda Python 3.6 on macosx this doesn't work.

Installing seems to work ok - here is the verbose output:

```
pip install wordcloud
Collecting wordcloud
Requirement already satisfied: pillow in ./anaconda3/lib/python3.6/site-packages (from wordcloud)
Requirement already satisfied: matplotlib in ./anaconda3/lib/python3.6/site-packages (from wordcloud)
Requirement already satisfied: numpy>=1.6.1 in ./anaconda3/lib/python3.6/site-packages (from wordcloud)
Requirement already satisfied: olefile in ./anaconda3/lib/python3.6/site-packages (from pillow->wordcloud)
Requirement already satisfied: six>=1.10 in ./anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud)
Requirement already satisfied: python-dateutil in ./anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud)
Requirement already satisfied: pytz in ./anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in ./anaconda3/lib/python3.6/site-packages (from matplotlib->wordcloud)
Installing collected packages: wordcloud
Successfully installed wordcloud-1.3.1
```

Now run python... you can see which version it is ...

```
python
Python 3.6.0 |Anaconda custom (x86_64)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

Now import word cloud .. and bang! It fails.

```
import wordcloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tariq/anaconda3/lib/python3.6/site-packages/wordcloud/__init__.py", line 1, in <module>
    from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
  File "/Users/tariq/anaconda3/lib/python3.6/site-packages/wordcloud/wordcloud.py", line 19, in <module>
    from PIL import Image
  File "/Users/tariq/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/tariq/anaconda3/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _PySlice_AdjustIndices
  Referenced from: /Users/tariq/anaconda3/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/tariq/anaconda3/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so
```

I'm not an expert - and am struggling to work out what the problem is. PIL symbols missing? Does that mean PIL is not installed? It seems to be .. it's the pillow fork that comes with anaconda. Maybe this is an incompatibility between PIL and pillow?

**Comment by amueller** [comment]
you might be mixing pip and conda? Uninstall pillow, make sure the PIL folder is entirely gone, install it with conda, try again.

You can not upgrade packages that are installed with conda using pip, and that might have happened here for some reason?

**Comment by makeyourowntextminingtoolkit** [comment]
Thanks for the suggestion but I would prefer it if wordcloud could be made to work over a standard anaconda install .. so

1. fresh OS install - here it is macos
2. install anaconda python
3. since anaconda python doesn't have wordcloud install it

I've always used `pip install wordcloud` to install word cloud, not `conda install -c https://conda.anaconda.org/amueller wordcloud`. But now neither of these works.

The pip is definitely the one from anaconda because `which pip` confirms it.

---

Let me know if you think I've misunderstood your suggestion. 

Thanks for the great work btw!

**Comment by amueller** [comment]
I'm not sure what you mean. The pillow module you have installed on your system is not working. That means something went wrong either with installing anaconda or afterwards.
Try ``from PIL import Image`` and you'll see that the error is independent of using the wordcloud package.

**Comment by makeyourowntextminingtoolkit** [comment]
Ok - so looks like anaconda isn't installing it's own pillow properly. I will let them know

For reference here is the error from `from PIL import Image`
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tariq/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/tariq/anaconda3/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Symbol not found: _PySlice_AdjustIndices
  Referenced from: /Users/tariq/anaconda3/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/tariq/anaconda3/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so
```

**Comment by makeyourowntextminingtoolkit** [comment]
they've updated python to 3.6.1 in anaconda python and suddenly the problem has gone away

please close
