### ISSUE TITLE
WordCloud doesn't support unicode stopwords

### ISSUE THREAD

**Issue by icyblade** [amueller/word_cloud#253]
When unicode stopwords are passed into `WordCloud`, error will be raised:

    TypeError: descriptor 'lower' requires a 'str' object but received a 'unicode'

**Comment by amueller** [comment]
Are you on python2 or python3? On Python3 this should work without issue.

**Comment by icyblade** [comment]
I'm using python 2.7. In python 2, `unicode` is different from `str` which leads to this problem.

**Comment by jb6** [comment]
I have the same problem as icyblade, how was that resolved ? My stopwords in French are not being stopped (I did transform the unicode words in a set of strings, but the words are still added to the worldcloud). Any suggestion ?

**Comment by amueller** [comment]
@jb6 Can you open a new issue and provide code to reproduce? The easiest way it probably to upgrade to  Python3.

**Comment by jb6** [comment]
yes sure, will do. Just to let you know that I have just tried on Python 3 and it does work nicely. The issue therefore concerns specific stopwords (for example words with accents) that are not "stopped" and appear in the cloud when running **Python 2.7** .
