### ISSUE TITLE
 No module named 'wordcloud.query_integral_image'

### ISSUE THREAD

**Issue by Kunchao** [amueller/word_cloud#255]
Firstly, i choose fast install . then i input import wordcloud on python shell that notes no module named wordcloud. so i choose another way that a manual install get this package you mention in github. Problems are as follows(The versionof wordcloud is 1.3.1.)：

Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wordcloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vapor/下载/word_cloud-master/wordcloud/__init__.py", line 1, in <module>
    from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
  File "/home/vapor/下载/word_cloud-master/wordcloud/wordcloud.py", line 24, in <module>
    from .query_integral_image import query_integral_image
ImportError: No module named 'wordcloud.query_integral_image'

**Comment by amueller** [comment]
You need to give more details on how you installed it.
The easiest way is to do ``pip install wordcloud``. You need to make sure that the ``pip`` belongs to the same python environment as your python shell.

You can probably fix your "manual" installation by running ``python setup.py build_ext -i" in the  ``/home/vapor/下载/word_cloud-master/`` folder.

**Comment by Kunchao** [comment]
Thank you so much!!! I fix it. I found that my filename called wordcloud.py. Maybe computer can't figure out whichone is the true wordcloud. When i change another name , everything is okay!

**Comment by vsathwikm** [comment]
@Kunchao  I am facing the same issue. Can you explain exactly what you changed? Filename? Did you change wordcloud.py to something else? or did you change .query_integral_image file?

**Comment by vsathwikm** [comment]
@amueller I installed wordcloud using "conda install -c https://conda.anaconda.org/amueller wordcloud" command. And my console returned "# All requested packages already installed." When I ran "from wordcloud import WordCloud, STOPWORDS" command in Jupyter notebook (Python 3 notebook), the above error was returned.

**Comment by leohuangyy** [comment]
I install worldcloud by  using "setup.py install" but  meet thee mistake as follows：
“
running install
running bdist_egg
running egg_info
writing requirements to wordcloud.egg-info\requires.txt
writing dependency_links to wordcloud.egg-info\dependency_links.txt
writing top-level names to wordcloud.egg-info\top_level.txt
writing wordcloud.egg-info\PKG-INFO
reading manifest file 'wordcloud.egg-info\SOURCES.txt'
writing manifest file 'wordcloud.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
running build_ext
building 'wordcloud.query_integral_image' extension error:
[WinErro 3] 系统找不到指定的路径。 ：C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\PlatformSDK\lib'  
”
how can I solve this problem?

**Comment by amueller** [comment]
install using conda instead.

**Comment by semonsong** [comment]
I had fixed it,but when i run it, it says "No module named 'worldcloud' ".  I  don' t know why. Just can ' t find  
reason.

**Comment by amueller** [comment]
@semonsong see https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/.
Also this is a usage question, please use stackoverflow for those.

**Comment by JordanTreDaniel** [comment]
I am having the same error on AWS Lambda, using Zappa for deployment. The package works fine on my machine, but it crashes once it gets to the cloud. Whyyyyyyy????

I **DID** use python 3.8, (I notice there is no guarantee for working) but as I said, it worked fine on my machine. (Mac Catalina)

I am currently trying to get it deployed with 3.7, but I worry I will have the SAME problem.

**Comment by JulianAntonioMurillo** [comment]
I'm still getting the ModuleNotFoundError:` No module named 'wordcloud.query_integral_image' error` when trying to run:
`from wordcloud import WordCloud`. Not sure what to do as I have the most recent versions of pip, python and installed latest wordcloud? I used pip installation. Running in Jupyter Notebooks.
