### ISSUE TITLE
wordcloud can not increase max_words 

### ISSUE THREAD

**Issue by yqkslh** [amueller/word_cloud#259]
Hi everyone, I try to use max_words to increase the words in wordcloud.
like the follow code.
```
for i in range(800): 
        k[table.cell(i,0).value]=table.cell(i,1).value 
wc = WordCloud( background_color = 'white',     
                mask = backgroud_Image,       
                max_words = 800,         
                )
wc.fit_words(k)
```
I got the errors:
 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-64-1b0a19caa3a5> in <module>()
     34                 )
     35 
---> 36 wc.fit_words(k)
     37 #wc.generate_from_frequencies(k)
     38 import matplotlib.pyplot as plt

C:\ProgramData\Anaconda3\lib\site-packages\wordcloud\wordcloud.py in fit_words(self, frequencies)
    329         self
    330         """
--> 331         return self.generate_from_frequencies(frequencies)
    332 
    333     def generate_from_frequencies(self, frequencies, max_font_size=None):

C:\ProgramData\Anaconda3\lib\site-packages\wordcloud\wordcloud.py in generate_from_frequencies(self, frequencies, max_font_size)
    435                     font, orientation=orientation)
    436                 # get size of resulting text
--> 437                 box_size = draw.textsize(word, font=transposed_font)
    438                 # find possible places using integral image:
    439                 result = occupancy.sample_position(box_size[1] + self.margin,

C:\ProgramData\Anaconda3\lib\site-packages\PIL\ImageDraw.py in textsize(self, text, font, *args, **kwargs)
    266     def textsize(self, text, font=None, *args, **kwargs):
    267         """Get the size of a given string, in pixels."""
--> 268         if self._multiline_check(text):
    269             return self.multiline_textsize(text, font, *args, **kwargs)
    270 

C:\ProgramData\Anaconda3\lib\site-packages\PIL\ImageDraw.py in _multiline_check(self, text)
    211         split_character = "\n" if isinstance(text, str) else b"\n"
    212 
--> 213         return split_character in text
    214 
    215     def _multiline_split(self, text):

TypeError: argument of type 'float' is not iterable

But if i change max_words to 200. The program is correct. 

Can anyone help me? Thanks very much.

**Comment by yqkslh** [comment]
I realy have 800 words in my excel files.

**Comment by amueller** [comment]
I suspect one of the entries of ``table.cell(i,0).value`` is a float. Can you check that?
