### ISSUE TITLE
wordcloud.wordcloud.fit_words() has wrong(not-updated?) doc string

### ISSUE THREAD

**Issue by Westwoodmayim** [amueller/word_cloud#260]
def fit_words(self, frequencies):
        """Create a word_cloud from words and frequencies.
        Alias to generate_from_frequencies.
        Parameters
        ----------
        frequencies : array of tuples
            A tuple contains the word and its frequency.
        Returns
        -------
        self
        """
        return self.generate_from_frequencies(frequencies)

In fact, the frequencies paramenter should be a dict from string to float, see below:

    def generate_from_frequencies(self, frequencies, max_font_size=None):
        """Create a word_cloud from words and frequencies.
        Parameters
        ----------
        frequencies : dict from string to float
            A contains words and associated frequency.
        max_font_size : int
            Use this font-size instead of self.max_font_size
        Returns
        -------
        self
        """

**Comment by amueller** [comment]
thanks, fixed in https://github.com/amueller/word_cloud/commit/fad662dc1bf9d5fa1f5d38228ecf5f49997485a5
