### ISSUE TITLE
Export wordcloud in vectorial format

### ISSUE THREAD

**Issue by ybayle** [amueller/word_cloud#262]
Hi, thank you for your awesome project!
I would like to export the generated wordcloud into eps, svg, pdf or whatever vectorial format.
But when I `plt.savefig("wordcloud.svg")`, the generated image is still blurry. This issue is close to #188. Is there a way to export a wordcloud in SVG currently?

**Comment by amueller** [comment]
Unfortunately not, as everything is done by PIL in pixel space. Not related to #188 which is a change in defaults in matplotlib, but to #58. There's a link to a c++ library that uses cairo for drawing and so it can export vector graphics. Happy to take PRs for reimplementing this with cairo, though it might be a bit of work.

**Comment by ybayle** [comment]
Ok, I'll try later to help on #58, thank you for your fast answer!

**Comment by Keramatfar** [comment]
So, what is the to_svg() method?

**Comment by amueller** [comment]
It stores the wordcloud as vector image.

**Comment by Keramatfar** [comment]
Thanks, I know that, but i got this error:
AttributeError: 'WordCloud' object has no attribute 'to_svg'
Installed by pip.

**Comment by amueller** [comment]
That is because it's not released on pypi yet. You can install it from github though.

**Comment by danwyry** [comment]
> That is because it's not released on pypi yet. You can install it from github though.

is that stable already ?

**Comment by amueller** [comment]
As stable as if I'd upload it to pypi ;)

**Comment by lijie97** [comment]
> pypi

Following the new features
