### ISSUE TITLE
ImportError: No module named '_tkinter'

### ISSUE THREAD

**Issue by turicas** [amueller/word_cloud#264]
This will happen on Heroku, since tkinter is not available there (tested on `cedar-14`).

**Comment by turicas** [comment]
I've tried to change matplotlib's backend to `Agg` before importing `wordcloud` and it worked.

```python
import matplotlib
matplotlib.use('Agg')
from wordcloud import WordCloud
```

Is there any way we can fix this inside wordcloud so we don't need this hack?

> Note: AFAIK this issue is probably going to happen only on Ubuntu, since they splitted out tkinter from the base Python package.

**Comment by amueller** [comment]
This is not a hack and unrelated to wordcloud as far as I can tell. WordCloud doesn't even import matplotlib (unless you don't specify a color function, in which case it will try to use viridis).
Are you using matplotlib for plotting? If you are, then this is exactly what you need to do to use matplotlib on a machine without X or similar.
If you don't use matplotlib, you can provide a color_func and you won't need matplotlib at all.

**Comment by lardissone** [comment]
Having the same problem using Dokku (a heroku open source clone using Docker).

**Comment by amueller** [comment]
@lardissone see the solution and comment above. Really this is unrelated to WordCloud. are you importing matplotlib? If so, you need to choose a backend that works with your setup.

**Comment by lardissone** [comment]
@amueller yes, I've just used a custom `color_func` and got it solved. Just intended to leave a comment for people searching for the same issue with dokku. Thanks.
