### ISSUE TITLE
feature request: run on list of strings?

### ISSUE THREAD

**Issue by ianhoolihan** [amueller/word_cloud#27]
I.e. say of have a list of names "John Doe", "Jane Doe". At the moment, I join them into one string to get the wordcloud, however this results with three elements i.e. "John", "Jane", "Doe". I'm hoping it's relatively easy to change this so that instead I just pass the above list, and my final word cloud displays "John Doe" and "Jane Doe". Does my use case make sense?

I can have a look at implementing this later, but you may have a better idea of how to do so.

**Comment by D8AM1N3R** [comment]
Hey Andreas--we implemented a way to accept either a custom tokenized list (for ngrams) or use the default long string and it seems to be working well.  Currently it uses the WordNetLemmatizer from the NLTK package, but if you want to see the code let me know and I'll share it (if not, no worries, just wanted to offer).  Thanks again for the WC package.

**Comment by amueller** [comment]
I probably don't want to depend on NLTK by default but having it as an option might be nice. If you like you can create a PR and I'll have a look.

**Comment by az0** [comment]
I had a related issue where I wanted to plot the topic from an LDA model from gensim, and it would be handy if wordcloud had a simple function that accepts a list of (word, weight) tuples and then calls fit_words.

**Comment by amueller** [comment]
@az0 Cool I've mean meaning to do that for ever. You can use the topics to color the words btw ;)
So didn't the thing I mentioned above work for you:
> You can manually set the words_ attribute of the wordcloud object and then call fit_words_. Does that work for you?
Or you you mean you'd like to have a single method to do that, so that it is more easily visible?

**Comment by az0** [comment]
@amueller : Yes, it did work for me, but it would be easier to find as its own function.

(BTW, I made a separate word cloud for each topic, and some words overlap between topics.)

**Comment by amueller** [comment]
I agree. I'll open it as it's own issue.
You could use hue to indicate topics... but I guess with many topics that might not be super informative. Do you have links to your plots?

**Comment by amueller** [comment]
fyi @az0 PR welcome (with test + doc ;)

**Comment by amueller** [comment]
there is now ``generate_from_frequencies``
