### ISSUE TITLE
Word duplicates word cloud

### ISSUE THREAD

**Issue by koljamaier** [amueller/word_cloud#273]
Hi!

When feeding WordCloud a text like shown in [1], the generated plot mentions the most common words (movie, film) twice.
From [this](https://github.com/amueller/word_cloud/blob/master/examples/masked.py) example I thought there is no more preprocessing needed (like normalizing counts). Or do I make wrong use of the pyplot library? 

Cheers

---

```python
wordcloud = WordCloud().generate(text)
plt.imshow(wordcloud)
plt.axis("off")
plt.show()
plt.savefig("terms2")
plt.close()
```
``[1] text = "film film film film film film film film film film film movie movie movie movie movie movie movie movie movie movie movie like like like like like like like charact charact charact charact charact charact time time time time time time just just just just just just good good good good good make make make make make play play play play play look look look look look"``

**Comment by amueller** [comment]
yes, you don't give it natural text. because "film film" appears very often, it detects it as a common collocation. You can set `collocations=False`` to not detect collocations.

**Comment by KhanAyesha** [comment]
same problem. Even after setting collocations to false I get repeated words in wordcloud. Please help

**Comment by KhanAyesha** [comment]
@amueller

**Comment by amueller** [comment]
@KhanAyesha please provide a minimum example to reproduce https://stackoverflow.com/help/minimal-reproducible-example

**Comment by KhanAyesha** [comment]
![wordcloud](https://user-images.githubusercontent.com/63223968/79138912-32c50700-7d6a-11ea-8a06-6d5b51af5035.png)
text = d1.tweet_text.values
wordcloud = WordCloud(
    width = 3000,
    height = 2000, collocations=False,
    background_color = 'black').generate(str(text))
fig = plt.figure(
    figsize = (40, 30),
    facecolor = 'k',
    edgecolor = 'k')
plt.imshow(wordcloud )

**Comment by amueller** [comment]
There's no duplicate words, but some of the words end with an apostrophe. That's a bit weird and looks like a recent regression. Can you please open a new issue for that?
Maybe a workaround would be to use ``regex=r"\w[\w']*\w+"`` though because we're stripping off trailing ``s`` is could still be an issue.

**Comment by amueller** [comment]
Hm I actually can't reproduce:
```python
from wordcloud import WordCloud
import matplotlib.pyplot as plt


text = ["humanity", "humanity's"] * 1000
text = " ".join(text)

wc = WordCloud(collocations=False).generate(text)
# Plot
plt.figure()
plt.imshow(wc, interpolation="bilinear")
plt.axis("off")
plt.show()
```
![image](https://user-images.githubusercontent.com/449558/79140146-86911980-7d85-11ea-92c5-817faf851873.png)

Can you please provide a self-contained example so I can run it? Which version of wordcloud are you using?

**Comment by KhanAyesha** [comment]
Thank you !
It worked.

**Comment by erfelipe** [comment]
Thanks for "collocations=False" - Works fine now. Great lib @amueller

**Comment by elcintimur** [comment]
"collocations=False". Great help, thanks...
