### ISSUE TITLE
How to include Special Characters

### ISSUE THREAD

**Issue by hcuny** [amueller/word_cloud#275]
I want to include some specified characters like “♂”, but I guess it was filtered out automatically, any way to change that? Thanks.

**Comment by amueller** [comment]
Likely by changing the regular expression. I have no idea how to match that particular one.
You can try to do something like
```python
import re
regexp = r"\w[\w']+"
re.findall(regexp, text)
```
with whatever text you have, and see how you need to change the regexp to match it the way you want.
