### ISSUE TITLE
unexpected occurrence of 'temp' in resulting cloud

### ISSUE THREAD

**Issue by Bkyn** [amueller/word_cloud#281]
I have a final_text string quite large, including only two times the word 'temp ':
`len(final_text.split(' '))`
1936942

`final_text.count('temp ')`
2  

I create the cloud:
`wordcloud = WordCloud(max_words=1000, mask=mask, margin=3,
               random_state=1, background_color="white").generate(final_text)`

And I will obtain a picture with a big "temp" on it.  

If I inspect wordcloud.word_, I can see that 'temp' is considered the third most frequent word:
`{'faire': 1.0,
 'vraiment': 0.5821658462703522,
 'temp': 0.5519689511548656,`

Now if I run:
`final_text = final_text.replace('temp','')`

And re-generate the cloud, then it works fine and 'temp' is gone.

**Comment by amueller** [comment]
In
``final_text.count('temp ')``
you have a space after ``temp``. Remove that and try the count again.

**Comment by amueller** [comment]
You can also try matching using a regular expression. WordCloud is not only splitting on whitespace but also on punctuation for example.

**Comment by amueller** [comment]
closing as no reply
