### ISSUE TITLE
word cloud error

### ISSUE THREAD

**Issue by aniketbhunia007** [amueller/word_cloud#286]
No module named 'wordcloud'
It is showing this.
While installing through conda, this error is shown.
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - wordcloud -> python 3.4*

**Comment by amueller** [comment]
Which conda channel are you using? If this is the main channel, we can ask the conda folks to update. If it's conda-forge I (or someone else) needs to update the feedstock to build with python 3.6

**Comment by amueller** [comment]
closing as duplicate of #232.
