### ISSUE TITLE
conda-forge version error

### ISSUE THREAD

**Issue by taozi926494** [amueller/word_cloud#290]
Hi, I have the same code on Ubuntu(wordcloud installed by pip) and Windows(wordcloud install by conda-forge), then Ubuntu works and Windows doesn't. what happened?

Ubuntu: wordcloud (1.3.1)  python(3.5.2)
Windows: wordcloud 1.2.1-py35_0 conda(4.33.25-py35_0)

The error:
  Traceback(most recent call last):
  File "jiebaDemo.py" line 70 <module>
     max_font_size = 40, width =1200, height = 800, background_color = 
     "white").generate_from_frequencies(wordfreq)
   max_frequency = float(frequencies[0][1])
ValueError: could not convert string to float: '高'

I read the generate_from_frequencies()'s source code and write max_frequency(). yet it can get max_frequency.(see annotation in __main__). 
The issue confused me long time, help...

There are my code:
```python
#!/usr/bin/env python3
#encoding=utf-8

import docx
import jieba
import jieba.posseg as pseg
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import PIL
import numpy as np
from operator import itemgetter

class DocxFreqWord(object):

	def __init__(self, docurl):
		self.docurl = docurl

	def wordsFromDocx(self):
		document = docx.Document(self.docurl)
		docText = ''
		for paragraph in document.paragraphs:
			docText += paragraph.text

		words = list(pseg.cut(docText))
		
		filted_arr = []
		filter_key = ['x', 'uj', 'c', 'a', 'p', 'ul', 'c', 'f', 'p', 'm', 'r', 'd', 'u']
		for word in words:
			# word: pair('Hadoop', 'eng') --> 'hadoop': word.word ; 'eng' : word.flag
			if word.flag in filter_key or len(word.word) < 2:
				pass
			else:
				filted_arr.append(word.word)
		return filted_arr

	def getWordFreq(self, words_arr):
		d = dict()
		for word in words_arr:
			if d.get(word) is None:
				d[word] = 1
			else:
				d[word] = d[word] + 1
		return d

	
if __name__ == '__main__':
	docxFreqWord = DocxFreqWord('research_report.docx')
	wordarr = docxFreqWord.wordsFromDocx()
	wordfreq = docxFreqWord.getWordFreq(wordarr)

	# frequencies = sorted(wordfreq.items(), key = itemgetter(1), reverse = True)
	# frequencies = frequencies[:20]
	# max_frequency = float(frequencies[0][1])
	# frequencies = [(word, freq / max_frequency) for word, freq in frequencies]
	# print(frequencies)
	
	fontpath = r'wqy-zenhei.ttc'
	alice_mask = np.array(PIL.Image.open('bigdata.jpg'))
	my_wordcloud = WordCloud(font_path = fontpath, max_words = 2000, mask = alice_mask, 
		max_font_size = 40, width = 1200, height = 800, background_color = "white").generate_from_frequencies(wordfreq)
	my_wordcloud.to_file("re.jpg")
	plt.imshow(my_wordcloud)
	plt.axis("off")
	plt.show()

```

**Comment by amueller** [comment]
What's the content of ``wordfreq``?
As you noted, you're using different versions of wordcloud, which have slightly different interfaces. ``generate_from_frequencies`` takes a dict in newer versions, not an iterable of tuples, as you can see from the docstring and the code.

**Comment by taozi926494** [comment]
@amueller Thanks for your reply. The content of wordfreq is {'Really': 2, 'Convolution': 1, 'Category': 1, 'reduce': 6 ... ...}. It is dict. Besides, I mocked a dict data,  generate_from_frequencies still get the same error.

**Comment by amueller** [comment]
@taozi926494 for which version of wordcloud does that give an error? You said Windows gives an error which is version 1.2.1. As I said, this changed so this older version is expected to give an error. Upgrade the windows installation.

**Comment by taozi926494** [comment]
@amueller Thanks, I have upgraded wordcloud from 1.2.1 to 1.3.1 and it worked.

**Comment by taozi926494** [comment]
@amueller The default version of wordcloud in conda-forge is 1.2.1

**Comment by amueller** [comment]
hm ok that needs to be updated then....

**Comment by amueller** [comment]
fixed
