### ISSUE TITLE
Image details isssue

### ISSUE THREAD

**Issue by RedNoo** [amueller/word_cloud#301]
Hello,

I am trying to convert this image : https://yadi.sk/d/0Kf5Q7Ob3N5nwv
and I am getting this result : https://yadi.sk/i/B_xn3yAK3N5o5C

My image has a very big resolution (4512x2516px) but face details and such in my image doesn't show in word tagged image. How can I increase details in the word tagged image?
Best
Onder

**Comment by amueller** [comment]
what parameters have you used? Maybe try increasing the maximum number of words.

**Comment by RedNoo** [comment]
I am using following code : 
wc = WordCloud(background_color="white",max_words=2000000, mask=mask, stopwords=stopwords, margin=10,
               random_state=1).generate(text)

**Comment by amueller** [comment]
What's the resolution of the resulting Image? And how large is the
vocabulary?

**Comment by RedNoo** [comment]
50 paragraphs, 4242 words, 28428 bytes

**Comment by amueller** [comment]
4242 unique words or words in total?
What's ``len(wc.words_)``?

**Comment by RedNoo** [comment]
It was not unique. But I changed with 100000+ unique words.
But It's not good enough. You can see the result in the following link:
https://yadi.sk/i/yTooKAwP3N6BkX

**Comment by amueller** [comment]
It looks like the other detail is too fine too fit words in it. So what
would you like to happen there?

**Comment by amueller** [comment]
You can decrease min font size and you can try modifying the mask image.
You can get much better results if you do some blurring and thresholding, I
have no logic built in about that.

**Comment by amueller** [comment]
The font size in Wordcloud is picked such that you can read the words. In
the screenshot you send, you can't read the words any more. Not sure what
the point of using words is, then. You could always add the detail from the
original mask back into the image.

**Comment by RedNoo** [comment]
Yes I am trying to add old image to generated image with %10 opacity.

**Comment by RedNoo** [comment]
It's  perfect now. 
Thanks for your help.
Best
Onder
