### ISSUE TITLE
save/show word cloud error ! ( ubuntu without GUI )

### ISSUE THREAD

**Issue by ananan** [amueller/word_cloud#302]
my code is like below:

> import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
from wordcloud import WordCloud
a = 'this is a wordcloud show test'
wc = WordCloud().generate(a)
wc.to_file('wc.jpg')
plt.imshow(wc)
plt.axis('off')
plt.savefig('plt.png')

the code runs well and not exception show up, the images has been created, but it was messy code !

> root@iZwz90sbbc0mkmgrlohm9gZ:~/code# ls
plt.png  wc.jpg  wc.py

I am using ubuntu 16.04.4 and without GUI, all libs require has been installed and no error show, the picture can generate but it shows like messy code, also i test it in a debian with GUI and it works fine ! 

so i am wondering if i have to install a GUI like xwindows on my ubuntu to use this project ?

**Comment by amueller** [comment]
No, this should work. What do you mean by "shows messy code"?
Can you post the picture? And which version of wordcloud are you using?

**Comment by amueller** [comment]
closing as no reply. feel free to reopen.
