### ISSUE TITLE
Conda issues

### ISSUE THREAD

**Issue by vaastav** [amueller/word_cloud#305]
So, I looked around a little bit to see why conda doesn't install properly and I found the following issues:

1. The package uploaded by @amueller  on Anaconda only has linux64 listed as a platform and it only has the packages for python 3.5 and python 3.6 You can take a look here for more details https://anaconda.org/amueller/wordcloud/files

2. The packages maintained by conda-forge on Anaconda are the ones that people are using as they are available for all major platforms. However, the issue is that they don't seem to have been updated in a while as it is still using 1.2.1 version of wordcloud instead of 1.3.1 Also it is lacking the package for python 3.6 which is the reason why I believe it is giving so many issues to people. Here is the link https://anaconda.org/conda-forge/wordcloud/files . I think updating the recipe and the version on conda-forge should do the trick and solve the issues.

**Comment by amueller** [comment]
Should we take down the anaconda.org/amueller channel then?

**Comment by vaastav** [comment]
We should probably take it down once the versions and packages have been updated on conda-forge.

**Comment by amueller** [comment]
We can also post to anaconda recipies, so it'll be updated in the main
channel.

**Comment by amueller** [comment]
done.
