### ISSUE TITLE
TF-IDF (feature request)

### ISSUE THREAD

**Issue by alexrichert** [amueller/word_cloud#314]
It would be great if the program could be provided with a comparison file to quantify word uniqueness with term frequency-inverse document frequency (words get higher weight not only for being found more often in a document, but for being found less often in a comparison document). So it would be a matter of reading in the second file, getting word frequencies from that file (only for words that appear in the first file), and modifying term frequencies in the main document accordingly.

**Comment by amueller** [comment]
that's pretty easy to do with ``generate_from_frequencies``. Just use that in conjunction with any tf-idf tool like sklearns ``TfidfVectorizer``.
