### ISSUE TITLE
Corrupted Arabic words

### ISSUE THREAD

**Issue by mzeidhassan** [amueller/word_cloud#316]
I managed to read an Arabic file that is in UTF-8 encoding, but after creating the image, all characters are corrupted. Can you please let me know how to resolve this issue?

I followed your example code @ https://github.com/amueller/word_cloud/blob/master/examples/simple.py

Thanks in advance for your support!

![ar_word_cloud_issue](https://user-images.githubusercontent.com/7589948/32263041-a2552c26-bee0-11e7-93ee-1498f7dcab26.PNG)

**Comment by amueller** [comment]
See #315 and #70. You need to pick a different font.

**Comment by mzeidhassan** [comment]
Thank you so much! I managed to fix it :-)
