### ISSUE TITLE
Error when a list of words is passed

### ISSUE THREAD

**Issue by LeenaShekhar** [amueller/word_cloud#319]
Two suggestions:
1. Could this be handled more gracefully by showing a message? 
"Currently it throws this error:TypeError: expected string or buffer"
It is probably not a big thing, but just good to have. 
2. How to get high resolution images? 

If it helps someone, in case you don't want stopwords to be removed (I didnt want to get rid of them) then you can instantiate WordCloud as below:
"wordcloud = WordCloud(**stopwords=set()**, collocations=collocations, max_words=max_words)"

Thank you for this. It is wonderful.

**Comment by LeenaShekhar** [comment]
Thank you for getting back. 

1. My bad, I completely missed to point that out. When I use wordcloud.generate(input) method. When input is a list it throws that error. 

2. I will try that.

**Comment by amueller** [comment]
No worries. And definitely feel free to send a PR with a better error message, it's much appreciated.

**Comment by LeenaShekhar** [comment]
Great. Let me do that.
