### ISSUE TITLE
Does not work with fonts that change character's shape and size depending on the word they are in.

### ISSUE THREAD

**Issue by Delta-Sigma** [amueller/word_cloud#321]
I have been trying to make Urdu wordclouds. Faced the same issues as mentioned in #70 . Did workarounds mentioned. They worked but only for monospaced fonts. Or fonts that do not change the character's size, shape and placement depending on the whole word (instead of just what's immediately ahead and behind). The workaround of replacing characters with context-based unicode characters will not work in these cases. To demonstrate, I am going to write a word 'مسئلہ' (issue) in Segoe UI and Jameel Noori Nastaleeq, letter by letter.

Segoe UI first:
![issue2](https://user-images.githubusercontent.com/26012911/32984004-babbbd4c-ccbf-11e7-8334-bc39d4623af3.png)

Using unicode (but not necessarily linguistically correct), the word is formed from 5 characters. Meem (م), Seen (س), (Yeh with) Hamza, (ئ), Laam (ل) and Heh (ہ).

1 contains meem's isolated form only. The rest contain joined beginning form of meem. Notice how all meems (coloured green) are the same. Also notice seen (coloured red). 3, 4 and 5 contain joining middle form of seen. Again, all same. However, this is not how usually Urdu (or even Arabic) is written or easily understood by native readers. Urdu uses Nastaleeq script. Arabic uses Naskh (I think). (Both of them change character's shapes. But I think it's much much less of a problem with Arabic.) Now using Nastaleeq script (i.e. Jameel Noori Nastaleeq font):

![issue](https://user-images.githubusercontent.com/26012911/32984082-f57008fc-ccc0-11e7-99b6-fb1ddf6b2f8a.png)

Again see meem (green) in 2-5. Although the shape is same, the height changes even though these are the same (beginning joining) form of meem. Seen (red) is also the same form in 3-5, however it's shape as well as the position changes.

These fonts do not usually explicitly contain glyphs (?) for unicode code points for explicit forms, the kind that the library arabic_reshaper gives. This is because it serves no purpose. There is no single way to display a form. (Sorry if I am a bit wrong about the technicalities.)

Some languages like Urdu, Farsi, Sindhi, Pashto, etc and a host of other languages most commonly use Nastaleeq script. Is there any way you can do something about it? It seems the underlying image processing makes decisions based on character's width and height etc. Is it possible to see how a complete word is rendered and then decision made accordingly. (Sorry if I am wrong about this. haven't yet been able to understand how it works.)

**Comment by Delta-Sigma** [comment]
What happens when I use Nastaleeq fonts is that I get images containing blank images with maybe one letter in each image (repeated as many times as it repeated). This is when I use the workaround in #70. When i don't I only get isolated letters as shown in https://github.com/amueller/word_cloud/issues/70#issuecomment-105000770 of #70.

**Comment by amueller** [comment]
Can you please provide a self-contained example and output image? The information about the character size comes from pillow, there could be an issue there (or at many other places).

You can also try to render your text just using pillow, and see whether that works, and if the bounding boxes are computed correctly.

**Comment by Delta-Sigma** [comment]
Thank you very much for your response.

It seems the problem is with pillow:

`from PIL import Image, ImageFont, ImageDraw

from matplotlib import pyplot as plt
import numpy as np
import cv2

text_string = u'تصوير'

img = Image.new('RGB', (200, 150))
draw = ImageDraw.Draw(img)
font = ImageFont.truetype('jameel.ttf', 50)

draw.text((25,40), text_string, fill='white', font=font)

img.show()
`

What it should render: 
![ideal](https://user-images.githubusercontent.com/26012911/33224587-f09ec978-d18c-11e7-9d1a-d342a4eccb26.PNG)

What it renders:
![test](https://user-images.githubusercontent.com/26012911/33224591-f771e9d8-d18c-11e7-849e-9a4af76e5724.PNG)

Here's a self-contained example using only two words:
`# -*- coding = utf-8 -*-
from wordcloud import WordCloud
text_string = u'بناؤ تصوير'
img = WordCloud('UrdType.ttf', width=1024, height=576).generate(text_string)
img.to_file('out.png')`

output: 
![out](https://user-images.githubusercontent.com/26012911/33224796-310eb7e6-d18f-11e7-8948-42bd31b8cfbe.png)

But I'm afraid then this makes it the same as issue#70. Using the workaround given in #70 and #315:
`# -*- coding = utf-8 -*-

from wordcloud import WordCloud
from bidi.algorithm import get_display
from arabic_reshaper import reshape

text_string = u'بناؤ تصوير'

text_string = get_display(reshape(text_string))
img = WordCloud('UrdType.ttf', width=1024, height=576).generate(text_string)

img.to_file('out.png')
`
output: 
![out](https://user-images.githubusercontent.com/26012911/33224846-a1ce836c-d18f-11e7-992c-adc96809c300.png)


P.S. Sorry for long comments. New to github and opensource.

**Comment by Delta-Sigma** [comment]
Why I opened this issue was to indicate that using arabic_reshaper and python-bidi works only in cases which use one certain kind of writing style. It does not with other styles used by some languages.

**Comment by amueller** [comment]
Thanks for your investigation. The last example not working seems more likely to be an issue with not using the appropriate font. Can you try again with ``arabic_reshaper`` and ``python-bidi`` with a font that supports the characters you need?

**Comment by amueller** [comment]
Does this look right?
```python
from PIL import Image, ImageFont, ImageDraw

from matplotlib import pyplot as plt
import numpy as np
from bidi.algorithm import get_display
from arabic_reshaper import reshape

text_string = u'تصوير'
text_string = get_display(reshape(text_string))

img = Image.new('RGB', (200, 150))
draw = ImageDraw.Draw(img)
font = ImageFont.truetype("Dropbox/NotoNaskhArabic-merged.otf", 50)

draw.text((25,40), text_string, fill='white', font=font)

img.show()
```

![bla](https://user-images.githubusercontent.com/449558/33227054-334b0274-d169-11e7-8e92-24c3c6e8fb8a.png)

**Comment by Delta-Sigma** [comment]
Sorry about the late reply. Yes, it does, but it's a 'Naskh' font, not a 'Taleeq' or 'Nastaleeq' font. They do include characters/glyphs as output by the 'arabic_reshaper'. Taleeq and Nastaleeq don't, because they can't. I tried to explain WHY they can't in the first post.

Btw, I found out that pillow displays complex text correctly if you have 'libraqm' installed on a Linux. I am trying to make it work. Haven't been able to do so.

**Comment by amueller** [comment]
ok, but so this is entirely unrelated to wordcloud, right? It's a pillow issue and/or possibly a ``arabic_reshaper`` issue. My snippet above doesn't work with ``NotoNastaliqUrdu-Regular.ttf``, which I guess was your point. I'm happy to include a solution in the arabic example, but it looks like there's nothing wrong from my side.

**Comment by amueller** [comment]
You should really try to work on this using my snippet and not using wordcloud. There might be something odd happening in wordcloud, but you should first try to fix it outside of it.

**Comment by Delta-Sigma** [comment]
Yes, it's a pillow issue, not exactly a wordcloud issue. And I don't have any suggestions (using another library, etc.) for resolving this problem either. :/

**Comment by Delta-Sigma** [comment]
I guess I should probably close this?

**Comment by amueller** [comment]
Unfortunately I don't really think there's something we can do. Except to move away from pillow to something that can do it, but I don't know what that would be.

**Comment by jwnder** [comment]
The problem that you have is caused because of a reshape issue.

What you need is a library like this:
https://github.com/mpcabd/python-arabic-reshaper
