### ISSUE TITLE
Error when i install wordcloud in my jupyter notebook

### ISSUE THREAD

**Issue by nhokconan** [amueller/word_cloud#322]
Anyone help me fix error.
This error :"
File "C:\Users\Thor\Anaconda3\lib\distutils\cygwinccompiler.py", line 129, in __init__
        if self.ld_version >= "2.10.90":
 TypeError: '>=' not supported between instances of 'NoneType' and 'str'`**
Failed building wheel for wordcloud
Command "C:\Users\Thor\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Thor\\AppData\\Local\\Temp\\pip-build-e4kcabmx\\wordcloud\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Thor\AppData\Local\Temp\pip-flcn7ifd-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Thor\AppData\Local\Temp\pip-build-e4kcabmx\wordcloud\

**Comment by amueller** [comment]
can you provide the full traceback and the command you executed? This is likely unrelated to wordcloud, but an issue with your C compiler setup.

**Comment by nhokconan** [comment]
Here is full traceback 
https://pastebin.com/bmt0eUU1

**Comment by amueller** [comment]
If you google the error messages you can find a bunch of solutions. It's unrelated to wordcloud.
