### ISSUE TITLE
Python WordCloud meet AttributeError: 'map' object has no attribute 'items

### ISSUE THREAD

**Issue by leonpun** [amueller/word_cloud#323]
`AttributeError                            Traceback (most recent call last)
<ipython-input-3-a14fa030f0d5> in <module>()
     11 a = words_stat.head(4000).itertuples(index=False)
     12 print(a)
---> 13 wordcloud=wordcloud.fit_words(words_stat.head(4000).itertuples(index=False)) #词频排名前多少的放到图里
     14 bimgColors=ImageColorGenerator(bimg)
     15 plt.figure()

c:\users\p58082465\appdata\local\programs\python\python35\lib\site-packages\wordcloud\wordcloud.py in fit_words(self, frequencies)
    329         self
    330         """
--> 331         return self.generate_from_frequencies(frequencies)
    332 
    333     def generate_from_frequencies(self, frequencies, max_font_size=None):

c:\users\p58082465\appdata\local\programs\python\python35\lib\site-packages\wordcloud\wordcloud.py in generate_from_frequencies(self, frequencies, max_font_size)
    348         """
    349         # make sure frequencies are sorted and normalized
--> 350         frequencies = sorted(frequencies.items(), key=item1, reverse=True)
    351         if len(frequencies) <= 0:
    352             raise ValueError("We need at least 1 word to plot a word cloud, "

AttributeError: 'map' object has no attribute 'items'
`

**Comment by amueller** [comment]
Hey. Sorry, I thought I had replied to this. Did you figure it out?

**Comment by leonpun** [comment]
Yes. thanks a lot!
