### ISSUE TITLE
windows 64 version not available

### ISSUE THREAD

**Issue by elapustulka** [amueller/word_cloud#327]
(C:\ProgramData\Anaconda3) C:\Users\admin>conda install -c https://conda.anaconda.org/amueller wordcloud
Fetching package metadata .............

PackageNotFoundError: Package missing in current win-64 channels:
  - wordcloud

**Comment by amueller** [comment]
Can you try the main anaconda channel or condaforge?

**Comment by amueller** [comment]
see #305. The conda forge version is not up to date, though :-/

**Comment by elapustulka** [comment]
not sure what I can do here. It would be nice to have. I am not a conda expert.

**Comment by amueller** [comment]
if you have a compiler installed, you can build from source. Sorry, I didn't have the time to update the conda forge build. You can use the older version or send a PR to update the conda forge recipe.

**Comment by elapustulka** [comment]
thanks, I will do a PR, best wishes Ela
