### ISSUE TITLE
ImportError: dynamic module does not define module export function

### ISSUE THREAD

**Issue by pypyrate** [amueller/word_cloud#328]
Apologies in advance if what follows below does meet normal expectations. I'm new to python and new to GitHub. Please let me know anything further you require and I will endeavor to provide it. Thanks in advance.

#### Description
Can't seem to import wordcloud
Run this:
`from wordcloud import WordCloud, STOPWORDS`

Get this error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-12da445271f7> in <module>()
----> 1 from wordcloud import WordCloud, STOPWORDS

C:\ProgramData\Anaconda3\lib\site-packages\wordcloud\__init__.py in <module>()
----> 1 from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
      2                         get_single_color_func)
      3 from .color_from_image import ImageColorGenerator
      4 
      5 __all__ = ['WordCloud', 'STOPWORDS', 'random_color_func',

C:\ProgramData\Anaconda3\lib\site-packages\wordcloud\wordcloud.py in <module>()
     22 from PIL import ImageFont
     23 
---> 24 from .query_integral_image import query_integral_image
     25 from .tokenization import unigrams_and_bigrams, process_tokens
     26 

ImportError: dynamic module does not define module export function (PyInit_query_integral_image)
```

#### Steps/Code to Reproduce
1. Running python 3.6  (Anaconda 5.0.1 distribution) installed in the last week onto a Windows 10 64-bit PC.
2. Using Jupyter Notebook.
3. Installed wordcloud from local file downloaded from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud). Used `pip install wordcloud-1.3.2-cp36-cp36m-win_amd64.whl`
(using `conda install wordcloud` or `pip install wordcloud` is blocked by network security so had to download file).
4. Open Jupyter Notebook in Edge browser.
5. run `from wordcloud import WordCloud, STOPWORDS`

#### Expected Results
WordCloud and STOPWORDS are imported.

#### Actual Results
error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-12da445271f7> in <module>()
----> 1 from wordcloud import WordCloud, STOPWORDS

C:\ProgramData\Anaconda3\lib\site-packages\wordcloud\__init__.py in <module>()
----> 1 from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
      2                         get_single_color_func)
      3 from .color_from_image import ImageColorGenerator
      4 
      5 __all__ = ['WordCloud', 'STOPWORDS', 'random_color_func',

C:\ProgramData\Anaconda3\lib\site-packages\wordcloud\wordcloud.py in <module>()
     22 from PIL import ImageFont
     23 
---> 24 from .query_integral_image import query_integral_image
     25 from .tokenization import unigrams_and_bigrams, process_tokens
     26 

ImportError: dynamic module does not define module export function (PyInit_query_integral_image)
```

#### Versions
Windows-10-10.0.15063-SP0
Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
NumPy 1.13.3
matplotlib 2.1.0
Obviously can't successfully run `import wordcloud; print("wordcoud", wordcloud.__version__)`

**Comment by amueller** [comment]
Hi.
Unfortunately I'm not sure what's happening. It seems to be an issue with the wheel you downloaded. This is not created by me, but generously provided by Christoph Gohlke.

**Comment by pypyrate** [comment]
Apologies for the delay as I have been on annual leave over Christmas. Appreciate the response. I'll attempt to Chris and post an update in this thread.

**Comment by amueller** [comment]
closing as no reply. let me know if you have an update.
