### ISSUE TITLE
Word Cloud Installation Error - Conflict with zope

### ISSUE THREAD

**Issue by brian1985** [amueller/word_cloud#330]
#### Steps/Code to Reproduce

opened windows command terminal (Windows 10) and typed:
conda install -c conda-forge wordcloud

Error message:
SOlving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
-wordcloud
-zope

Use conda info <package> to see the dependencies for each package.

#### Versions

Please run the following snippet and paste the output below.
Windows-10-10.0.16299-SP0
Python 3.6.3 |Anaconda custom (32-bit)| (default, Nov  8 2017, 15:12:41) [MSC v.1900 32 bit (Intel)]
NumPy 1.13.3
matplotlib 2.1.1
[NOT INSTALLED]import wordcloud; print("wordcoud", wordcloud.__version__)

**Comment by amueller** [comment]
can you do conda info? What's the conflicting dependency?

**Comment by amueller** [comment]
can you do conda info? What's the conflicting dependency?

**Comment by brian1985** [comment]
For 'conda info wordcloud' nothing is returned since it isn't installed (the problem I have)

For the two commands 
'conda info' and 'conda info zope I get:

C:\Users\NAME\Documents>conda info

     active environment : base
    active env location : C:\Anaconda3
       user config file : C:\Users\NAME\.condarc
 populated config files : C:\Users\NAME\.condarc
          conda version : 4.4.6
    conda-build version : 0+unknown
         python version : 3.6.3.final.0
       base environment : C:\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-32
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\NAME\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda3\envs
                          C:\Users\NAME\AppData\Local\conda\conda\envs
                          C:\Users\NAME\.conda\envs
               platform : win-32
             user-agent : conda/4.4.6 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False


C:\Users\NAME\Documents>conda info zope

zope 1.0 py27_0
---------------
file name   : zope-1.0-py27_0.tar.bz2
name        : zope
version     : 1.0
build string: py27_0
build number: 0
channel     : https://repo.continuum.io/pkgs/free
size        : 804 B
arch        : x86
constrains  : ()
date        : 2016-07-15
license     : BSD
md5         : e4b881deb93a7c117cb7d66fadbf0cca
platform    : win32
subdir      : win-32
url         : https://repo.continuum.io/pkgs/free/win-32/zope-1.0-py27_0.tar.bz2
dependencies:
    python 2.7*

zope 1.0 py34_0
---------------
file name   : zope-1.0-py34_0.tar.bz2
name        : zope
version     : 1.0
build string: py34_0
build number: 0
channel     : https://repo.continuum.io/pkgs/free
size        : 834 B
arch        : x86
constrains  : ()
date        : 2016-07-15
license     : BSD
md5         : 611d84093d0fdc10c6be3d72ece9b5d8
platform    : win32
subdir      : win-32
url         : https://repo.continuum.io/pkgs/free/win-32/zope-1.0-py34_0.tar.bz2
dependencies:
    python 3.4*

zope 1.0 py35_0
---------------
file name   : zope-1.0-py35_0.tar.bz2
name        : zope
version     : 1.0
build string: py35_0
build number: 0
channel     : https://repo.continuum.io/pkgs/free
size        : 839 B
arch        : x86
constrains  : ()
date        : 2016-07-15
license     : BSD
md5         : f7a813b12307ca6cf6693f90871707e1
platform    : win32
subdir      : win-32
url         : https://repo.continuum.io/pkgs/free/win-32/zope-1.0-py35_0.tar.bz2
dependencies:
    python 3.5*

zope 1.0 py36_0
---------------
file name   : zope-1.0-py36_0.tar.bz2
name        : zope
version     : 1.0
build string: py36_0
build number: 0
channel     : https://repo.continuum.io/pkgs/free
size        : 3 KB
arch        : x86
constrains  : ()
date        : 2016-12-24
license     : BSD
md5         : afdcf4422b94cb2de307ca0a669179a9
platform    : win32
subdir      : win-32
url         : https://repo.continuum.io/pkgs/free/win-32/zope-1.0-py36_0.tar.bz2
dependencies:
    python 3.6*


I am new to python and this is pretty much the base install of Anaconda and programming in Windows is new for me in general. I probably should just install anaconda onto my Linux boot, but it would be nice to have in on this setup too.

Anything else you would like me to send? Thanks for getting back.
Brian

**Comment by dfesenko** [comment]
I have similar problem. I am not able to install wordcloud. I get:

UnsatisfiableError: The following specifications were found to be in conflict:
  - wordcloud
  - xlrd


Also, before I had the conflict with xlsxwriter, and I uninstall it, but now there is another conflict.

**Comment by amueller** [comment]
The important part is to figure out which of the packages actually creates the conflict.
See https://conda.io/docs/user-guide/troubleshooting.html

There is likely to be a version mismatch between the requirements of wordcloud and the other package.

**Comment by amueller** [comment]
closing as no reply. Generally this is a packaging issue and maybe should be tracked on the conda-forge package.  I don't have time to investigate what the conflict might be and without  the specifics it can't be fixed (also it requires a fix in the conda recipe not the package).
