### ISSUE TITLE
Python 2.7: Some specific stopwords -ex: with accents- appear in the wordcloud  

### ISSUE THREAD

**Issue by jb6** [amueller/word_cloud#332]
#### Description
On Python 2.7., some of my stopwords (in French) appeared in the wordcloud. 
(Worked nicely on Python3)

#### Steps/Code to Reproduce
import nltk
from nltk.corpus import stopwords

#text in French (foolish: dont pay attention to it)
text= u"Bonjour j'ai très fin aujourd'hui et donc je vais manger énormement. 
Nous avons très très envie de venir mais nous ne viendrons pas.\\
Il parait qu'il fait très chaud aujourd'hui: être ou ne pas être telle est la question;
\\ à la maison il fait bon vivre.la la la le le le il je vous"

stopwords = stopwords.words('french')
print stopwords

#creating a proper string (convertion from unicode to str) required for the wordcloud method
set_of_srt_stopwords = set()
for word in stopwords:
     word_str= word.encode("utf-8")
     set_of_srt_stopwords.add(word_str) 
      
#adding 2 new stopwords to my set of stopwords strings
set_of_srt_stopwords.add("très")
set_of_srt_stopwords.add("être")

wordcloud = WordCloud(background_color="white",  max_words=100, stopwords= set_of_srt_stopwords).generate(text)

#Display the wordcloud
import matplotlib.pyplot as plt
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()

#### Expected Results
#french stopwords
[u'au', u'aux', u'avec', u'ce', u'ces', u'dans', u'de', u'des', u'du', u'elle', u'en', u'et', u'eux', u'il', u'je', u'la', u'le', u'leur', u'lui', u'ma', u'mais', u'me', u'm\xeame', u'mes', u'moi', u'mon', u'ne', u'nos', u'notre', u'nous', u'on', u'ou', u'par', u'pas', u'pour', u'qu', u'que', u'qui', u'sa', u'se', u'ses', u'son', u'sur', u'ta', u'te', u'tes', u'toi', u'ton', u'tu', u'un', u'une', u'vos', u'votre', u'vous', u'c', u'd', u'j', u'l', u'\xe0', u'm', u'n', u's', u't', u'y', u'\xe9t\xe9', u'\xe9t\xe9e', u'\xe9t\xe9es', u'\xe9t\xe9s', u'\xe9tant', u'\xe9tante', u'\xe9tants', u'\xe9tantes', u'suis', u'es', u'est', u'sommes', u'\xeates', u'sont', u'serai', u'seras', u'sera', u'serons', u'serez', u'seront', u'serais', u'serait', u'serions', u'seriez', u'seraient', u'\xe9tais', u'\xe9tait', u'\xe9tions', u'\xe9tiez', u'\xe9taient', u'fus', u'fut', u'f\xfbmes', u'f\xfbtes', u'furent', u'sois', u'soit', u'soyons', u'soyez', u'soient', u'fusse', u'fusses', u'f\xfbt', u'fussions', u'fussiez', u'fussent', u'ayant', u'ayante', u'ayantes', u'ayants', u'eu', u'eue', u'eues', u'eus', u'ai', u'as', u'avons', u'avez', u'ont', u'aurai', u'auras', u'aura', u'aurons', u'aurez', u'auront', u'aurais', u'aurait', u'aurions', u'auriez', u'auraient', u'avais', u'avait', u'avions', u'aviez', u'avaient', u'eut', u'e\xfbmes', u'e\xfbtes', u'eurent', u'aie', u'aies', u'ait', u'ayons', u'ayez', u'aient', u'eusse', u'eusses', u'e\xfbt', u'eussions', u'eussiez', u'eussent']

A cloud of words without the defined stopwords in French (from NLTK) and without the two I added.

#### Actual Results
The stopwords "très" and "être" appeared in the wordcloud, they should not.

#### Versions
Python 2.7.14

![figure_1](https://user-images.githubusercontent.com/6653886/35052153-3081f2d8-fba7-11e7-816e-578d6e3ac279.png)

**Comment by amueller** [comment]
Thanks for reporting. It's probably an issue with using strings in python2 and we should be using unicode. Not sure when I'll have time to fix this. Moving to python3 should probably fix it.

**Comment by jb6** [comment]
I did move immediately to Python 3, as mentioned in post,it works like a
charm on Python3;) thank you for sharing your wonderful wordcloud!

Le 18 janv. 2018 5:30 PM, "Andreas Mueller" <notifications@github.com> a
écrit :
