### ISSUE TITLE
wordcloud:intallation problem :

### ISSUE THREAD

**Issue by triptiawasthi** [amueller/word_cloud#333]

**Comment by amueller** [comment]
please provide more information.

**Comment by triptiawasthi** [comment]
i have installed wordcloud ... but while importing it into my python code it is generating an ImportModuleError...otherthan this wordcloud all other while files like numpy , PIL and matplotlib
do exist in my system
downloaded it by....
pip install wordcloud
suggest me what next should i supposed to do for to get it!!!

**Comment by amueller** [comment]
Please post the traceback of the error message. Is your file called ``wordcloud.py``?
