### ISSUE TITLE
Why not store all the locations?

### ISSUE THREAD

**Issue by XanthusL** [amueller/word_cloud#339]
https://github.com/amueller/word_cloud/blob/07dadf519dd1f347887aa9336be0d14f88282cf8/wordcloud/query_integral_image.pyx#L20

Store all valid locations and pick one of them randomly  would be faster.
I just think it's worthy of costing some memory for speed

**Comment by amueller** [comment]
I don't think it would be faster, but I'm happy to be proven wrong!
Do you want to provide a benchmark?

**Comment by amueller** [comment]
actually, I guess it would be about 1.5x faster on average if you do it smartly. Maybe I was just too lazy back then? You need to preallocate an array and probably grow it using the doubling trick, which feels like a hassle but might be worth it.

**Comment by XanthusL** [comment]
I know little about Python, and afraid of bring bugs. So I can't contribute a PR.

**Comment by XanthusL** [comment]
I had a try, but it doesn't get faster. Maybe this issue should be closed
Here are the changes:
1.
```py
    cdef int *x_results = <int *> malloc(x * sizeof(int))
    cdef int *y_results = <int *> malloc(y * sizeof(int))
```
2.
```py
            if not area:
                x_results[hits] = i
                y_results[hits] = j
                hits += 1
```
3.
```py
    i = x_results[goal]
    j = y_results[goal]
    free(x_results)
    free(y_results)
    return i, j
```
