### ISSUE TITLE
Help in creating stopwords set

### ISSUE THREAD

**Issue by Lotemn102** [amueller/word_cloud#340]
Hey,
I'm new to python and trying to create wordcloud in arabic. The wordcloud works fine but i can't figure out why the stopword function doesn't work. 

I've used this stopword:
https://github.com/Alir3z4/python-stop-words

This is my code:
https://gist.github.com/Lotemn102/3997e511b1c6ded42b82febaded5aa88#file-wordcloud

Thanks

**Comment by amueller** [comment]
are you using Python2? There are some issues with using unicode stopwords in python2.

**Comment by Lotemn102** [comment]
Hey,

Thanks for your answer, i'm using python 3

**Comment by amueller** [comment]
can you provide a self-contained example and output?

**Comment by Lotemn102** [comment]
Yes, i've used this text:
[text.docx](https://github.com/amueller/word_cloud/files/1720946/text.docx)

This is the word cloud i got using my code:
<img width="667" alt="wc" src="https://user-images.githubusercontent.com/35609587/36164495-2a96fa04-10f5-11e8-8f12-322f8328d3fd.png">

The marked words are included in the arabic stop words i've used and shouldn't appear.

**Comment by amueller** [comment]
that's not really a minimum self-contained example... can you reproduce that without using the stopwords library and create a single python file that contains all necessary data/code?

**Comment by amueller** [comment]
https://stackoverflow.com/help/mcve

**Comment by Lotemn102** [comment]
sorry, i'm new to this  whole coding thing.

is this alright?:
[Example.zip](https://github.com/amueller/word_cloud/files/1720988/Example.zip)

i've removed the stopword from the code

**Comment by amueller** [comment]
it would have been simpler to encode a single line of the input in the code...

**Comment by amueller** [comment]
Wait, but the code you provided doesn't use any stopwords, so it doesn't reproduce the issue? ...

**Comment by amueller** [comment]
Basically what I'd like is a single piece of code that shows the problem and is as simple as possible, like 
```python
from wordcloud import WordCloud
from arabic_reshaper import arabic_reshaper
from bidi.algorithm import get_display

text = "بينما يشير الديمقراطيون إلى أن هدف المذكّرة هو تقويض التحقيق الذي يُجريه المدعي الخاص روبرت مولر بشأن العلاقات بين مساعدي ترامب والروس، حيث يعتقدون أنها باتت على وشك كشف معلومات خطيرة بعدما وصل التحقيق إلى الدائرة الضيّقة المُحيطة بترامب كإبنه وصهره جارد كوشنر."

stopwords = {'whatever', 'they', 'should', 'be'}
wc =WordCloud(stopwords=stopwords)

text = arabic_reshaper.reshape(text)
text = get_display(text)
wc.generate(text)
```

**Comment by Lotemn102** [comment]
ok thanks!

i've included the words that shouldn't appear in this wordcloud from this text:
[Example.zip](https://github.com/amueller/word_cloud/files/1721134/Example.zip)

**Comment by amueller** [comment]
I think the arabic reshaper changes the representation of the words, so they don't correspond to how the stop words are represented. If you remove the lines with the arabic reshaper and get_dispay, does the stop word removal work?

**Comment by Lotemn102** [comment]
Yes!!

when i remove both of them the stopwords removal works. when i use only one of them (arabic reshaper or get_display) the stopword removal doesn't work.

but you can't read the arabic words in the cloud without both arabic reshaper and get_display. you have any idea how to fix this?

**Comment by amueller** [comment]
How about if you only remove one of them?
you can probably apply the reshaper to the stopwords before giving them to WordCloud. Maybe ask at the reshaper and / or bidi people?

**Comment by Lotemn102** [comment]
Thanks for your help!

**Comment by amueller** [comment]
did you find out something?

**Comment by Lotemn102** [comment]
Hey,

I first removed the stopwords from the text using this lexicon:
https://pypi.org/project/stop-words/
(without using the wordcloud's stopwords option)

Then i gave the "clean" text to wordcloud.
Inside my create_wordcloud function i used bidi and arabic_reshaper and they worked fine.

**Comment by amueller** [comment]
that makes sense. thanks for following up.
