### ISSUE TITLE
Using the word cloud in Qt app

### ISSUE THREAD

**Issue by Lotemn102** [amueller/word_cloud#341]
Hey,

You've helped me in using wordcloud in Arabic, and i eventually managed to solve it by deleting the stopwords from the text before giving it to the wordcloud function. Thanks!!!

I'm having another problem that has nothing to do with Arabic:
I can't use the wordcloud function i wrote properly  as a function in QT app i wrote.

the wordcloud function is here:
[help.zip](https://github.com/amueller/word_cloud/files/1737772/help.zip)

 and when i use it i get this cloud:
![goodcloud](https://user-images.githubusercontent.com/35609587/36391301-a1d9039c-15ae-11e8-9f1e-10820443399e.png)

the QT app with the wordcloud function is here:
[help2.zip](https://github.com/amueller/word_cloud/files/1737774/help2.zip)

and when i use it with the same text i get this cloud:
![badcloud](https://user-images.githubusercontent.com/35609587/36391315-ab29e344-15ae-11e8-829c-23a16b55d0f6.png)

i can't figure out why the number of words in the wordcloud changed.
Do you know what i did wrong?

Thanks for your help!!!

**Comment by amueller** [comment]
that's more a usage question than an actual issue with the library. Try stackoverflow.
