### ISSUE TITLE
Instagram Word Cloud

### ISSUE THREAD

**Issue by realdennis** [amueller/word_cloud#343]
Hey! 

# I write a Word Cloud app -- igcloud.
https://github.com/realdennis/igcloud
Only use word_cloud and jieba (for Chinese)
![](https://raw.githubusercontent.com/realdennis/igcloud/master/demo.gif)

**igcloud** is a tool which generates Word Cloud for Instagram user's post contents (public profile) . 

If you are interesting to yourself(or someone)  word usage frequency on Instagram , it's an easy way to sort out through an image .

## For example 

Jay Chou's Instagram wordcloud
![](https://raw.githubusercontent.com/realdennis/igcloud/master/example/jaychou.png)

Ed Sheeran's Instagram wordcloud
![](https://raw.githubusercontent.com/realdennis/igcloud/master/example/teddysphotos.png)

## Both English and Chinese supports

**Comment by amueller** [comment]
that's not really an issue, is it?

**Comment by realdennis** [comment]
Sorry for bothering you,

In a readme: "Send a pull request to add yours here."

I use wordcloud lib in my repo, I would like to politely tell you, or should I send pr directly?

**Comment by amueller** [comment]
No worries. Actually given how widely it is used now, I think I'll remove that from the readme (I hadn't added it myself anyway).
