### ISSUE TITLE
Handling acronyms

### ISSUE THREAD

**Issue by xuhdev** [amueller/word_cloud#347]
Currently, acronyms are not specially handled. However, this can cause multiple issues.

- If both the expanded form of a word and its acronym are frequent, we see both of them in the word cloud.
- If only the acronym is frequent, it's sometimes better to display the expanded form in the cloud.

I would suggest to allow users to specify mapping between expanded forms and acronyms.

**Comment by amueller** [comment]
Why don't you preprocess the text to do that?

**Comment by xuhdev** [comment]
That's a good idea! Thanks!
