### ISSUE TITLE
Expose the regex option to CLI

### ISSUE THREAD

**Issue by xuhdev** [amueller/word_cloud#349]
Currently a custom regex option is available in #139 . However, this option is not exposed to CLI option. It would be great if it is available there.

**Comment by amueller** [comment]
it is: https://github.com/amueller/word_cloud/blob/master/wordcloud/wordcloud_cli.py#L94

**Comment by xuhdev** [comment]
@amueller Thanks! Then I guess the version on PyPI is too outdated... Can you upload a newer version?

**Comment by amueller** [comment]
done.
