### ISSUE TITLE
Crash on SystemError: Parent module '' not loaded, cannot perform relative import in wordcloud pip package 1.4

### ISSUE THREAD

**Issue by clippermadness** [amueller/word_cloud#353]
#### Description
Crash on SystemError: Parent module '' not loaded, cannot perform relative import in wordcloud pip package 1.4

#### Steps/Code to Reproduce
install like this:
pip3 install wordcloud --upgrade --user

verify version 1.4 (1.3.1 is fine)
pip3 freeze | grep wordcloud
==> wordcloud==1.4

run and see crash:
wordcloud_cli.py 

```
Traceback (most recent call last):
  File "/home/user/.local/bin/wordcloud_cli.py", line 17, in <module>
    from . import __version__
SystemError: Parent module '' not loaded, cannot perform relative import
```

#### Expected Results
Don't crash. :)

#### Actual Results
Crash - as above.

#### Versions
python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-4.4.0-1052-aws-x86_64-with-Ubuntu-16.04-xenial
>>> import sys; print("Python", sys.version)
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.14.1
>>> import matplotlib; print("matplotlib", matplotlib.__version__)
matplotlib 2.2.0
>>> import wordcloud; print("wordcoud", wordcloud.__version__)
wordcoud 1.4

**Comment by amueller** [comment]
see #351

**Comment by amueller** [comment]
fixed now.
