### ISSUE TITLE
Missing parameter contour_width in 1.4.1 (but used in the examples)

### ISSUE THREAD

**Issue by pythononwheels** [amueller/word_cloud#355]
#### Description
I installed from pypi (pip install wordcloud) which results in a version 1.4.1 (as of March 28 2018)

If I run the mask example I get an error: 
`TypeError: __init__() got an unexpected keyword argument 'contour_width'`

#### Steps/Code to Reproduce

Just install from pypi (1.4.1) and [run the masked.py example from ](https://github.com/amueller/word_cloud/blob/master/examples/masked.py)

Also see line **contour_width** 29/30 in examples/masked.py source:

```
wc = WordCloud(background_color="white", max_words=2000, mask=alice_mask,
stopwords=stopwords, contour_width=3, contour_color='steelblue')
```

And compare the `WordCloud __init__` from 1.4.1 where there seems to be no parameter `contour_width` defined

```
def __init__(self, font_path=None, width=400, height=200, margin=2,
                 ranks_only=None, prefer_horizontal=.9, mask=None, scale=1,
                 color_func=None, max_words=200, min_font_size=4,
                 stopwords=None, random_state=None, background_color='black',
                 max_font_size=None, font_step=1, mode="RGB",
                 relative_scaling=.5, regexp=None, collocations=True,
                 colormap=None, normalize_plurals=True):
```
#### Expected Results
Probably change / adapt the example or add the parameter with a default to 1.4.1

#### Actual Results
`TypeError: __init__() got an unexpected keyword argument 'contour_width'`

#### Versions

Windows-7-6.1.7601-SP1
Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
NumPy 1.14.2
matplotlib 2.2.2
wordcoud 1.4.1

**Comment by pythononwheels** [comment]
Ok, this also seems to apply to` contour_color`.
Also usedn in masked.py and not defined in` WordCloud.__init__ ` for 1.4.1

**Comment by amueller** [comment]
well that's because they were introduced after 1.4.1

**Comment by pythononwheels** [comment]
Ok. So the examples dont run with the current pypi version ? Since 1.4.1 is the version I get using pip.

**Comment by amueller** [comment]
The examples on github run with the version on github. You can look at the version of the examples at the 1.4.1 tag, they will run with 1.4.1. Sorry for the inconvenience, there is no separate place that stores the examples for the last release version.

**Comment by amueller** [comment]
See https://github.com/amueller/word_cloud/tree/aa9b9d23b9abc6ccbb290b9395006e083f9c3575 for example

**Comment by pythononwheels** [comment]
ok. thanks for the info. Good option to checkout the tag. this is not a big issue at all but a little confusing when you follow the Readme, as I did. Which goes: pip install .... check the examples with a link to the current git source, which then dont run. 
Maybe it helps people to add a short info to the Readme.. (just guessing)

**Comment by amueller** [comment]
I can see how it's confusing. It's pretty rare that the examples break, though, and that is the only example that breaks, because it shows off a new feature.
The real solution would be to have the documentation rendered for the stable version (including examples) and link to that. That's on my todo list but I'm pretty busy.
Any help is appreciated ;)

**Comment by pythononwheels** [comment]
You mean linking to the top version in releases ? Dunno if / how thats possible ... but I'll give it a try.
Maybe the Wiki (unused) could be a valid option ?

**Comment by amueller** [comment]
No I meant the website. Having the website show the release documentation. I need to set up a CircleCI that tracks release tags and updates the website if I tag...

**Comment by sharmaeshaan** [comment]
Faced the same issue when I installed via `conda`

Installing directly from the master branch sorted it though!

**Comment by amueller** [comment]
install from github.

**Comment by rsgoldfarb** [comment]
I just tried to install from github but it didn't work.  Here are my steps:

1. I went to the master branch and copied https://github.com/amueller/word_cloud.git
2. I then went to the terminal and ran git clone https://github.com/amueller/word_cloud.git
3. I changed to the word_cloud directory using cd word_cloud
4. I then made sure I was in the desired virtual environment with source activate venv
5. I then ran python setup.py install

I got a lot of warning messages similar to this one:
wordcloud/query_integral_image.c:14715:26: warning: unused function '__Pyx_PyBytes_Equals' [-Wunused-function]
static CYTHON_INLINE int __Pyx_PyBytes_Equals(PyObject* s1, PyObject* s2, int equals) {

However, the rest of the install appeared to run smoothly.  But, when I used pip show wordcloud to confirm the version, it says that 1.4.1 is installed.  Is that the latest version with the countour options?  It doesn't seem like it - the two countour variables (width and color) are not available.

**Comment by amueller** [comment]
@rsgoldfarb  These warnings are fine. And unfortunately the current master branch also has 1.4.1 as version number. But you can try uninstalling with pip and then reinstalling. Or you might be not installing it in the right python environment.

**Comment by rsgoldfarb** [comment]
Andreas - Thank you.  It is working now.  I think it was an error on my end.

But can I ask you something else?  I am using the attached file as an image mask and it is producing the image below, which has very jagged edges:

[cid:355266ED-E0BD-45AE-A044-6896494085B0][cid:4714EEC3-0D0A-4AAB-A07E-6E9B200DA354]
Is there a setting to make the contour smoother?

Richard


On Jun 17, 2018, at 1:15 PM, Andreas Mueller <notifications@github.com<mailto:notifications@github.com>> wrote:


@rsgoldfarb<https://github.com/rsgoldfarb> These warnings are fine. And unfortunately the current master branch also has 1.4.1 as version number. But you can try uninstalling with pip and then reinstalling. Or you might be not installing it in the right python environment.

**Comment by amueller** [comment]
That's possibly because there's artifacts in the image. Try thresholding at a value that's not pure white.

**Comment by rsgoldfarb** [comment]
Andreas - Thanks for taking the time to respond.  I now understand that this can be controlled using PIL.Image.  I am unfamiliar with the technical details, but a quick review of the PILLOW documentation suggests that the function to use is:

`class PIL.ImageFilter.UnsharpMask(radius=2, percent=150, threshold=3)`

Does that seem right?  Any suggestions on how to set the parameters for the example guitar image I pasted above?  And, more importantly, how to do something similar if it is a color image of a person, as in this one: 
![image](https://user-images.githubusercontent.com/7215528/41549221-20f72d88-72f3-11e8-9e39-93644466b00f.png)

**Comment by jcfr** [comment]
xref #365

**Comment by jcfr** [comment]
Closing. This will be fixed in upcoming release.
