### ISSUE TITLE
Failed to import wordcloud - DLL load failed

### ISSUE THREAD

**Issue by dushmshr** [amueller/word_cloud#356]
Hey, 

I am getting the error as below:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-14-dc1828f2a80e> in <module>()
----> 1 import wordcloud

~\AppData\Local\Continuum\anaconda3\lib\site-packages\wordcloud\__init__.py in <module>()
----> 1 from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
      2                         get_single_color_func)
      3 from .color_from_image import ImageColorGenerator
      4 
      5 __all__ = ['WordCloud', 'STOPWORDS', 'random_color_func',

~\AppData\Local\Continuum\anaconda3\lib\site-packages\wordcloud\wordcloud.py in <module>()
     17 from operator import itemgetter
     18 
---> 19 from PIL import Image
     20 from PIL import ImageColor
     21 from PIL import ImageDraw

~\AppData\Local\Continuum\anaconda3\lib\site-packages\PIL\Image.py in <module>()
     56     # Also note that Image.core is not a publicly documented interface,
     57     # and should be considered private and subject to change.
---> 58     from . import _imaging as core
     59     if PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
     60         raise ImportError("The _imaging extension was built for another "

ImportError: DLL load failed: The specified module could not be found.
```

**Comment by balistof** [comment]
some thing here

**Comment by amueller** [comment]
Can you run "from PIL import Image"? Can you do "import Image"?

**Comment by jerinv** [comment]
Having this same issue.

**Comment by amueller** [comment]
@jerinv well can you do these imports?

**Comment by jerinv** [comment]
@amueller No, I cannot do either of those imports. For "from PIL import Image" I get 
`ImportError: DLL load failed: The specified module could not be found.` For "import Image", I get `ModuleNotFoundError: No module named 'Image'`

**Comment by amueller** [comment]
That means your installation of pil/pillow is broken, not wordcloud. You
should ask the pillow maintainers or possible conda who is packaging it.

**Comment by steremma** [comment]
The fix proposed in [this discussion](https://github.com/python-pillow/Pillow/issues/2945) is to get a specific version of `Pillow` using pip. This fixes the issue for me, however when I then try to install `wordcloud`  the broken version of Pillow overrides the existing installation. 

This is only a windows-conda problem by the way, I don't have any issue on Linux.

**Comment by amueller** [comment]
Is the broken version of pil from conda-forge or the main conda repo?

**Comment by steremma** [comment]
Its from `conda-forge`. When I hit `conda install -c conda-forge wordcloud` the confirmation message includes these lines:
```
The following NEW packages will be INSTALLED:

    pillow:          5.1.0-py36_0      conda-forge
    wordcloud:       1.4.1-py36_0      conda-forge
```

**Comment by amueller** [comment]
Can you please report in the conda-forge issue I linked above?

**Comment by HBouch** [comment]
I just solve it by specifying wordcloud=1.3
It uses pillow 5.1.0 but does not seem to have the same error ...

**Comment by amueller** [comment]
@HBouch with conda? Did that change the version of pillow installed?

**Comment by HBouch** [comment]
No, I think it was the same 5.1.0 ...

**Comment by amueller** [comment]
That's really weird.... would be cool if you could reproduce that somehow.

**Comment by suryaprakash10t** [comment]
I'm facing the same issue. As HBouch mentioned, I also installed wordcloud=1.3 but the issue still persists. (I'm using Anaconda 4.4.8) BTW, I was able to use "wordcloud" for the first time but when I increased the resolution of wordcloud, the kernel crashed. From then onwards I am unable to import "wordcloud".

**Comment by amueller** [comment]
@suryaprakash10t See https://github.com/conda-forge/pillow-feedstock/issues/45 as I said above. Remove pillow, ensure it's completely gone, and reinstall with conda.

**Comment by amueller** [comment]
I'll reopen for visibility.

**Comment by jcfr** [comment]
After #403 is integrated, `pip install wordcloud` should work out of the box.

**Comment by kushal9090** [comment]
> some thing here



> Hey,
> 
> I am getting the error as below:
> 
> ```
> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-14-dc1828f2a80e> in <module>()
> ----> 1 import wordcloud
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\wordcloud\__init__.py in <module>()
> ----> 1 from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
>       2                         get_single_color_func)
>       3 from .color_from_image import ImageColorGenerator
>       4 
>       5 __all__ = ['WordCloud', 'STOPWORDS', 'random_color_func',
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\wordcloud\wordcloud.py in <module>()
>      17 from operator import itemgetter
>      18 
> ---> 19 from PIL import Image
>      20 from PIL import ImageColor
>      21 from PIL import ImageDraw
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\PIL\Image.py in <module>()
>      56     # Also note that Image.core is not a publicly documented interface,
>      57     # and should be considered private and subject to change.
> ---> 58     from . import _imaging as core
>      59     if PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
>      60         raise ImportError("The _imaging extension was built for another "
> 
> ImportError: DLL load failed: The specified module could not be found.
> ```

open anaconda prompt 
first remove both pillow and wordcloud package 
conda remove pillow
conda remove wordcloud

and then again install wordcloud
conda install -c conda-forge wordcloud
'(this will install both pillow and wordcloud again )

works for me you can try it :-)

**Comment by sud2902** [comment]
Hi 
I too getting below error - 
Traceback (most recent call last):
  File "/Users/richa/PycharmProjects/wordcloud/venv/wordcloud.py", line 2, in <module>
    from wordcloud import WordCloud, STOPWORDS
  File "/Users/richa/PycharmProjects/wordcloud/venv/wordcloud.py", line 2, in <module>
    from wordcloud import WordCloud, STOPWORDS
ImportError: cannot import name 'WordCloud' from partially initialized module 'wordcloud' (most likely due to a circular import) (/Users/richa/PycharmProjects/wordcloud/

When ran wordcloud.py - got error for .query_integral_image
Traceback (most recent call last):
  File "/Users/richa/PycharmProjects/wordcloud/venv/lib/python3.8/site-packages/wordcloud/wordcloud.py", line 26, in <module>
    from .query_integral_image import query_integral_image
ImportError: attempted relative import with no known parent package

Please help

**Comment by amueller** [comment]
@sud2902 how did you install the package? looks like you might not have built it properly.

**Comment by sud2902** [comment]
Hi Amuller,
Thanks for replying. I am using Pycharm and there i installed wordcloud package using pip interpreter. I also tried running the same script via terminal but there also i got same error. On terminal too i installed using PIP3. 
I doubt it is missing c compiler probably but don't know how to resolve. 
Note: I am using Python 3.8 version.
Thank you,Sudhanshu 
    On Monday, 11 May, 2020, 12:17:43 am IST, Andreas Mueller <notifications@github.com> wrote:  
 
 


@sud2902 how did you install the package? looks like you might not have built it properly.

**Comment by amueller** [comment]
it's because your file is called ``wordcloud.py``.
