### ISSUE TITLE
Able to show letters? 

### ISSUE THREAD

**Issue by aallex14** [amueller/word_cloud#361]
#### Description

I would like to say thanks first for creating this package. It really makes my work easier. 
I am dealing with a document which includes lots of single-letter words, like "y" which represents "why". When I create my wordcloud they are disappeared. I would like to display them on the wordcloud. I didn't see any example wordclouds online showing single letters. I believe this package might not be designed to support this use case. I am just curious if there is something I can modify to show one-letter words. 

#### Steps/Code to Reproduce
Here is the line of my code to set up the wordcloud: 

wc = WordCloud(collocations=False,
              background_color='white',
              font_path=font,
              mask=color_mask).generate(words)     
img_color = ImageColorGenerator(color_mask)
wc.recolor(color_func=img_color)

**Comment by amueller** [comment]
You can easily do that by changing the regular expression used for tokenization. Right now it requires each word to have two letters. just remove one of the ``\w``s.

**Comment by aallex14** [comment]
It worked! Thanks!
