### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [amueller/word_cloud#362]
Hello Sir. I'm a UI/UX and Graphics Designer. I want propose a logo for you. Would you mind if I propose logo for your application as my Open Source Contribution?

Thanks before.

**Comment by amueller** [comment]
Sure, though I can't guarantee I'll accept it ;)
Actually this is a very valuable contribution, though. If you're familiar with web design, you could also have a look at scikit-learn.org and see what you think of it. We're not gonna change the logo for that, but I think the website could use some polish.

**Comment by anharismail** [comment]
Hello Sir. This is the logo design I proposed for your application.

Version 1.
![wordcloud ver 1](https://user-images.githubusercontent.com/37614260/38763332-62150bae-3fc3-11e8-8089-ee6540835a45.png)

Version 2.
![wordcloud ver 2](https://user-images.githubusercontent.com/37614260/38763333-7207c510-3fc3-11e8-807d-3373577271cf.png)

If you like my contribution and will use it, I'll provide all editable files and all sizes you needed.

Thanks before and hope you like it.

**Comment by anharismail** [comment]
Hi Sir, How about my proposal? Will you accepted or not?

**Comment by amueller** [comment]
Hi @anharismail that looks pretty cool. I don't have a lot of time to spend on this right now, though. I'll get back to you. How would you incorporate it into the website?

**Comment by anharismail** [comment]
Which website did you mean sir? 

Is this logo will place on that website?

**Comment by amueller** [comment]
the wordcloud website, linked to in the readme.

**Comment by anharismail** [comment]
Hello, Sir. Now I provide the interface how the logo incorporate into the website.

![sample web 1](https://user-images.githubusercontent.com/37614260/39226216-41449474-487b-11e8-9520-e8b979c77a78.png)

![sample web 2](https://user-images.githubusercontent.com/37614260/39226228-51827946-487b-11e8-806c-8fc7f13ef6f4.png)

Please, Tell me if there any revision @amueller.

**Comment by anharismail** [comment]
Hello Sir @amueller , Is there any progress about my logo proposal? :)
