### ISSUE TITLE
countour_width, contour_color attributes not available

### ISSUE THREAD

**Issue by ghost** [amueller/word_cloud#365]
Getting following error for countour_width & contour_color attributes (version 1.4.1):

`TypeError: __init__() got an unexpected keyword argument 'contour_color'`
TypeError: __init__() got an unexpected keyword argument 'contour_width'

```
Name: wordcloud
Version: 1.4.1
Summary: A little word cloud generator
Home-page: https://github.com/amueller/word_cloud
```

**Comment by amueller** [comment]
these are new in the development version and not in the release version yet.

**Comment by jcfr** [comment]
Closing. This will be fixed with upcoming release.
