### ISSUE TITLE
How to avoid error when installing wordcloud in Ubuntu?

### ISSUE THREAD

**Issue by reichaves** [amueller/word_cloud#376]
In Python3 and Ubuntu I tried to install worcloud:

    pip install wordcloud

But I have this error:

    Collecting wordcloud
      Using cached https://files.pythonhosted.org/packages/bc/e8/cab8479b25297b3847cfb55e85a5014e8c53b80e513eaf1ba58c7b3a6acd/wordcloud-1.4.1.tar.gz
    Requirement already satisfied: matplotlib in /home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages (from wordcloud) (2.1.0)
    Requirement already satisfied: numpy>=1.6.1 in /home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages (from wordcloud) (1.13.3)
    Requirement already satisfied: pillow in /home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages (from wordcloud) (5.1.0)
    Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages (from matplotlib->wordcloud) (2.2.0)
    Requirement already satisfied: python-dateutil>=2.0 in /home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages (from matplotlib->wordcloud) (2.6.1)
    Requirement already satisfied: pytz in /home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages (from matplotlib->wordcloud) (2017.3)
    Requirement already satisfied: six>=1.10 in /home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages (from matplotlib->wordcloud) (1.11.0)
    Requirement already satisfied: cycler>=0.10 in /home/reinaldo/Documentos/Code/raspa/lib/python3.6/site-packages (from matplotlib->wordcloud) (0.10.0)
    Building wheels for collected packages: wordcloud
      Running setup.py bdist_wheel for wordcloud ... error
      Complete output from command /home/reinaldo/Documentos/Code/raspa/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-aw9hfg0x/wordcloud/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-8o6g1aqe --python-tag cp36:
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.6
      creating build/lib.linux-x86_64-3.6/wordcloud
      copying wordcloud/__init__.py -> build/lib.linux-x86_64-3.6/wordcloud
      copying wordcloud/wordcloud_cli.py -> build/lib.linux-x86_64-3.6/wordcloud
      copying wordcloud/wordcloud.py -> build/lib.linux-x86_64-3.6/wordcloud
      copying wordcloud/tokenization.py -> build/lib.linux-x86_64-3.6/wordcloud
      copying wordcloud/color_from_image.py -> build/lib.linux-x86_64-3.6/wordcloud
      copying wordcloud/stopwords -> build/lib.linux-x86_64-3.6/wordcloud
      copying wordcloud/DroidSansMono.ttf -> build/lib.linux-x86_64-3.6/wordcloud
      running build_ext
      building 'wordcloud.query_integral_image' extension
      creating build/temp.linux-x86_64-3.6
      creating build/temp.linux-x86_64-3.6/wordcloud
      x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/reinaldo/Documentos/Code/raspa/include/python3.6m -c wordcloud/query_integral_image.c -o build/temp.linux-x86_64-3.6/wordcloud/query_integral_image.o
      wordcloud/query_integral_image.c:8:22: fatal error: pyconfig.h: Arquivo ou diretório não encontrado
      compilation terminated.
      error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
      
      ----------------------------------------
      Failed building wheel for wordcloud
      Running setup.py clean for wordcloud
    Failed to build wordcloud
    Installing collected packages: wordcloud
      Running setup.py install for wordcloud ... error
        Complete output from command /home/reinaldo/Documentos/Code/raspa/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-aw9hfg0x/wordcloud/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-l0oiuaja/install-record.txt --single-version-externally-managed --compile --install-headers /home/reinaldo/Documentos/Code/raspa/include/site/python3.6/wordcloud:
        running install
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-3.6
        creating build/lib.linux-x86_64-3.6/wordcloud
        copying wordcloud/__init__.py -> build/lib.linux-x86_64-3.6/wordcloud
        copying wordcloud/wordcloud_cli.py -> build/lib.linux-x86_64-3.6/wordcloud
        copying wordcloud/wordcloud.py -> build/lib.linux-x86_64-3.6/wordcloud
        copying wordcloud/tokenization.py -> build/lib.linux-x86_64-3.6/wordcloud
        copying wordcloud/color_from_image.py -> build/lib.linux-x86_64-3.6/wordcloud
        copying wordcloud/stopwords -> build/lib.linux-x86_64-3.6/wordcloud
        copying wordcloud/DroidSansMono.ttf -> build/lib.linux-x86_64-3.6/wordcloud
        running build_ext
        building 'wordcloud.query_integral_image' extension
        creating build/temp.linux-x86_64-3.6
        creating build/temp.linux-x86_64-3.6/wordcloud
        x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/reinaldo/Documentos/Code/raspa/include/python3.6m -c wordcloud/query_integral_image.c -o build/temp.linux-x86_64-3.6/wordcloud/query_integral_image.o
        wordcloud/query_integral_image.c:8:22: fatal error: pyconfig.h: Arquivo ou diretório não encontrado
        compilation terminated.
        error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
        
        ----------------------------------------
    Command "/home/reinaldo/Documentos/Code/raspa/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-aw9hfg0x/wordcloud/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-l0oiuaja/install-record.txt --single-version-externally-managed --compile --install-headers /home/reinaldo/Documentos/Code/raspa/include/site/python3.6/wordcloud" failed with error code 1 in /tmp/pip-install-aw9hfg0x/wordcloud/

Please, does anyone know how I can solve it?

P.S.: I tried, but it did not work later
sudo apt-get install python3-dev

Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
python3-dev is already the newest version (3.5.1-3).
Os seguintes pacotes foram instalados automaticamente e já não são necessários:
  gcc-5-base:i386 libbsd0:i386 libedit2:i386 libffi6:i386 libglib2.0-0:i386
  libgstreamer-plugins-base0.10-0 libgstreamer-plugins-base0.10-0:i386
  libgstreamer0.10-0 libgstreamer0.10-0:i386 libicu55:i386 libjpeg62:i386
  liborc-0.4-0:i386 libssl1.0.0:i386 libstdc++6:i386 libxml2:i386
  linux-headers-4.4.0-112 linux-headers-4.4.0-112-generic
  linux-headers-4.4.0-116 linux-headers-4.4.0-116-generic
  linux-headers-4.4.0-119 linux-headers-4.4.0-119-generic
  linux-image-4.4.0-112-generic linux-image-4.4.0-116-generic
  linux-image-4.4.0-119-generic linux-image-extra-4.4.0-112-generic
  linux-image-extra-4.4.0-116-generic linux-image-extra-4.4.0-119-generic
  linux-signed-image-4.4.0-112-generic linux-signed-image-4.4.0-116-generic
  linux-signed-image-4.4.0-119-generic linux-tools-4.4.0-112
  linux-tools-4.4.0-112-generic linux-tools-4.4.0-116
  linux-tools-4.4.0-116-generic linux-tools-4.4.0-119
  linux-tools-4.4.0-119-generic
Utilize 'sudo apt autoremove' para os remover.
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 231 não atualizados.

**Comment by reichaves** [comment]
Now it worked, with the command for Python 3.6:

sudo apt-get install python3.6-dev

and

pip3 install wordcloud

:)

**Comment by amueller** [comment]
glad you figured it out :)
