### ISSUE TITLE
Distributable .exe that imports WordCloud fails because of missing file

### ISSUE THREAD

**Issue by Michael-E-Rose** [amueller/word_cloud#381]
#### Description
I compiled a python3.5 script that includes WordCloud using pyinstaller on Windows 10 in order to have a distributable exe file. The exe fails because it is looking for a file stopwords in folder Wordcloud in the user's temp directory. The script runs all fine when exectued in script or bash mode. The file is being looked up in a folder with cryptic name, which changes on every run. The foldername always starts with _MEI followed by some numbers.

#### Steps/Code to Reproduce
Compile python script on windows with pyinstaller and include line ``from wordcloud import WordCloud`

#### Error message
```
C:\Users\w6504hk\Downloads\Oblaka\dist>Oblaka
Traceback (most recent call last):
  File "Oblaka.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\program files\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\wordcloud\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "c:\program files\python35\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\wordcloud\wordcloud.py", line 29, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\w6504hk\\AppData\\Local\\Temp\\_MEI52242\\wordcloud\\stopwords'
```
I think this behaviour is not intended. It is related to wordcloud or might it be caused by pyinstaller?

**Comment by amueller** [comment]
There is a file called stopwords in wordcloud that it reads It seems pyinstaller doesn't bundle that correctly. A simple but hacky way to work around this would be to include the stopwords in the py file.

**Comment by Michael-E-Rose** [comment]
That's correct, it doesn't bundle that.  The question for me however is: Why does wordcloud require this file, if I use my own precompiled words?

from wordcloud import WordCloud

tuples = ...  # my own list of (wordfreq, word)-tuples
wordcloud = WordCloud(normalize_plurals=False)
wordcloud.generate_from_frequencies(tuples)

It doesn't need the stopwords.  It seems to me from the source code that STOPWORDS is being read anyways, regardless of whether they are being used or not.  A better solution, to my mind, would be to only load the STOPWORDS file if they are actually being used.  I can write a PR on that, if you agree.

**Comment by amueller** [comment]
Yes, loading in init seems fine. Though you might still have issues with the font unless you use a different one.

**Comment by Michael-E-Rose** [comment]
PR is live. We can do the same with the font if you deem it relevant.  On my distributable I had no problems with the font but loading the fontfile only when needed seems safer.

**Comment by amueller** [comment]
The font is only loaded when it's needed.

**Comment by amueller** [comment]
Here's instructions on how you have to use pyinstaller: https://pyinstaller.readthedocs.io/en/v3.3.1/spec-files.html#adding-files-to-the-bundle

**Comment by king-mountain** [comment]
find the stopwords file in folder env\lib\site-packages\wordcloud\ 
copy it to your script folder,then,
You can edit the spec file of  your python script,as below:
datas+=[ ('stopwords', 'wordcloud') ]
for me it works.

**Comment by philip928lin** [comment]
> find the stopwords file in folder env\lib\site-packages\wordcloud\
> copy it to your script folder,then,
> You can edit the spec file of your python script,as below:
> datas+=[ ('stopwords', 'wordcloud') ]
> for me it works.

I am not familiar with spec file. What do you mean "You can edit the spec file of your python script,as below:
datas+=[ ('stopwords', 'wordcloud') ]"
Could you please provide me step-wise solution?

**Comment by amueller** [comment]
@philip928lin I linked it above.

**Comment by vickypappu** [comment]
a good fix given here https://www.programmersought.com/article/5635871566/

**Comment by amueller** [comment]
It looks like there's some issue with the font path. If not, I would check with pyinstaller, as this is a pyinstaller usage issue.
