### ISSUE TITLE
No module named 'wordcloud.query_integral_image'

### ISSUE THREAD

**Issue by haoqicherish** [amueller/word_cloud#382]
#### Description
I was installed wordcloud  on my machine (ubuntu 16.04) successfully ,  when i run 'import wordcloud', the commond line show me an error, just like the title, who can tell me how to solve this problem,i have been tried many ways , but no one seems works!

#### Actual Results
>>> import wordcloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/workspace/word_cloud-master/wordcloud/__init__.py", line 1, in <module>
    from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
  File "/root/workspace/word_cloud-master/wordcloud/wordcloud.py", line 25, in <module>
    from .query_integral_image import query_integral_image
ImportError: No module named 'wordcloud.query_integral_image'

#### The install log

> `running install
running bdist_egg
running egg_info
creating wordcloud.egg-info
writing requirements to wordcloud.egg-info/requires.txt
writing top-level names to wordcloud.egg-info/top_level.txt
writing dependency_links to wordcloud.egg-info/dependency_links.txt
writing wordcloud.egg-info/PKG-INFO
writing manifest file 'wordcloud.egg-info/SOURCES.txt'
reading manifest file 'wordcloud.egg-info/SOURCES.txt'
writing manifest file 'wordcloud.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/wordcloud
copying wordcloud/wordcloud.py -> build/lib.linux-x86_64-3.5/wordcloud
copying wordcloud/__init__.py -> build/lib.linux-x86_64-3.5/wordcloud
copying wordcloud/tokenization.py -> build/lib.linux-x86_64-3.5/wordcloud
copying wordcloud/wordcloud_cli.py -> build/lib.linux-x86_64-3.5/wordcloud
copying wordcloud/color_from_image.py -> build/lib.linux-x86_64-3.5/wordcloud
copying wordcloud/stopwords -> build/lib.linux-x86_64-3.5/wordcloud
copying wordcloud/DroidSansMono.ttf -> build/lib.linux-x86_64-3.5/wordcloud
running build_ext
building 'wordcloud.query_integral_image' extension
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/wordcloud
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python3.5m -c wordcloud/query_integral_image.c -o build/temp.linux-x86_64-3.5/wordcloud/query_integral_image.o
gcc -pthread -shared build/temp.linux-x86_64-3.5/wordcloud/query_integral_image.o -o build/lib.linux-x86_64-3.5/wordcloud/query_integral_image.cpython-35m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/wordcloud
copying build/lib.linux-x86_64-3.5/wordcloud/wordcloud.py -> build/bdist.linux-x86_64/egg/wordcloud
copying build/lib.linux-x86_64-3.5/wordcloud/__init__.py -> build/bdist.linux-x86_64/egg/wordcloud
copying build/lib.linux-x86_64-3.5/wordcloud/tokenization.py -> build/bdist.linux-x86_64/egg/wordcloud
copying build/lib.linux-x86_64-3.5/wordcloud/wordcloud_cli.py -> build/bdist.linux-x86_64/egg/wordcloud
copying build/lib.linux-x86_64-3.5/wordcloud/DroidSansMono.ttf -> build/bdist.linux-x86_64/egg/wordcloud
copying build/lib.linux-x86_64-3.5/wordcloud/stopwords -> build/bdist.linux-x86_64/egg/wordcloud
copying build/lib.linux-x86_64-3.5/wordcloud/query_integral_image.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/wordcloud
copying build/lib.linux-x86_64-3.5/wordcloud/color_from_image.py -> build/bdist.linux-x86_64/egg/wordcloud
byte-compiling build/bdist.linux-x86_64/egg/wordcloud/wordcloud.py to wordcloud.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/wordcloud/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/wordcloud/tokenization.py to tokenization.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/wordcloud/wordcloud_cli.py to wordcloud_cli.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/wordcloud/color_from_image.py to color_from_image.cpython-35.pyc
creating stub loader for wordcloud/query_integral_image.cpython-35m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/wordcloud/query_integral_image.py to query_integral_image.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-3.5
copying and adjusting wordcloud/wordcloud_cli.py -> build/scripts-3.5
changing mode of build/scripts-3.5/wordcloud_cli.py from 644 to 755
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.5/wordcloud_cli.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/wordcloud_cli.py to 755
copying wordcloud.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wordcloud.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wordcloud.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wordcloud.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wordcloud.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
wordcloud.__pycache__.query_integral_image.cpython-35: module references __file__
wordcloud.__pycache__.wordcloud.cpython-35: module references __file__
creating dist
creating 'dist/wordcloud-1.4.1-py3.5-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing wordcloud-1.4.1-py3.5-linux-x86_64.egg
creating /usr/local/lib/python3.5/site-packages/wordcloud-1.4.1-py3.5-linux-x86_64.egg
Extracting wordcloud-1.4.1-py3.5-linux-x86_64.egg to /usr/local/lib/python3.5/site-packages
Adding wordcloud 1.4.1 to easy-install.pth file
Installing wordcloud_cli.py script to /usr/local/bin

Installed /usr/local/lib/python3.5/site-packages/wordcloud-1.4.1-py3.5-linux-x86_64.egg
Processing dependencies for wordcloud==1.4.1
Searching for Pillow==5.1.0
Best match: Pillow 5.1.0
Adding Pillow 5.1.0 to easy-install.pth file

Using /usr/local/lib/python3.5/site-packages
Searching for numpy==1.14.3
Best match: numpy 1.14.3
Adding numpy 1.14.3 to easy-install.pth file

Using /usr/local/lib/python3.5/site-packages
Searching for matplotlib==2.2.2
Best match: matplotlib 2.2.2
Adding matplotlib 2.2.2 to easy-install.pth file

Using /usr/local/lib/python3.5/site-packages
Searching for pytz==2018.4
Best match: pytz 2018.4
Adding pytz 2018.4 to easy-install.pth file

Using /usr/local/lib/python3.5/site-packages
Searching for kiwisolver==1.0.1
Best match: kiwisolver 1.0.1
Adding kiwisolver 1.0.1 to easy-install.pth file

Using /usr/local/lib/python3.5/site-packages
Searching for python-dateutil==2.7.3
Best match: python-dateutil 2.7.3
Adding python-dateutil 2.7.3 to easy-install.pth file

Using /usr/local/lib/python3.5/site-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /usr/local/lib/python3.5/site-packages
Searching for pyparsing==2.2.0
Best match: pyparsing 2.2.0
Adding pyparsing 2.2.0 to easy-install.pth file

Using /usr/local/lib/python3.5/site-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using /usr/local/lib/python3.5/site-packages
Searching for setuptools==39.2.0
Best match: setuptools 39.2.0
Processing setuptools-39.2.0-py3.5.egg
setuptools 39.2.0 is already the active version in easy-install.pth
Installing easy_install-3.6 script to /usr/local/bin
Installing easy_install script to /usr/local/bin

Using /usr/local/lib/python3.5/site-packages/setuptools-39.2.0-py3.5.egg
Finished processing dependencies for wordcloud==1.4.1`

#### Versions
wordcloud 1.4.1
ubutu 16.04
python 3.5

**Comment by haoqicherish** [comment]
![Uploading 微信截图_20180528155551.jpg…]()

I  was used this way to install wordcloud

**Comment by amueller** [comment]
I recommend you use conda instead.

**Comment by jcfr** [comment]
This should be fixed by #403 

xref #386

**Comment by jcfr** [comment]
Closing. This will be fixed with the upcoming release proving [wheels](https://pythonwheels.com/) for python 2.7, 3.4, 3.5, 3.6 and 3.7.
