### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by rushivrox** [amueller/word_cloud#383]
OSError                                   Traceback (most recent call last)
<ipython-input-25-cdbfa27c8894> in <module>()
      5                             background_color = 'black',
      6                             width = 1200,
----> 7                             height = 1000).generate(file_content)
      8 
      9 plt.imshow(wordcloud)

~\Anaconda3\lib\site-packages\wordcloud\wordcloud.py in generate(self, text)
    569         self
    570         """
--> 571         return self.generate_from_text(text)
    572 
    573     def _check_generated(self):

~\Anaconda3\lib\site-packages\wordcloud\wordcloud.py in generate_from_text(self, text)
    551         """
    552         words = self.process_text(text)
--> 553         self.generate_from_frequencies(words)
    554         return self
    555 

~\Anaconda3\lib\site-packages\wordcloud\wordcloud.py in generate_from_frequencies(self, frequencies, max_font_size)
    403             else:
    404                 self.generate_from_frequencies(dict(frequencies[:2]),
--> 405                                                max_font_size=self.height)
    406                 # find font sizes
    407                 sizes = [x[1] for x in self.layout_]

~\Anaconda3\lib\site-packages\wordcloud\wordcloud.py in generate_from_frequencies(self, frequencies, max_font_size)
    437             while True:
    438                 # try to find a position
--> 439                 font = ImageFont.truetype(self.font_path, font_size)
    440                 # transpose font optionally
    441                 transposed_font = ImageFont.TransposedFont(

~\Anaconda3\lib\site-packages\PIL\ImageFont.py in truetype(font, size, index, encoding, layout_engine)
    259 
    260     try:
--> 261         return FreeTypeFont(font, size, index, encoding, layout_engine)
    262     except IOError:
    263         ttf_filename = os.path.basename(font)

~\Anaconda3\lib\site-packages\PIL\ImageFont.py in __init__(self, font, size, index, encoding, layout_engine)
    142 
    143         if isPath(font):
--> 144             self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine)
    145         else:
    146             self.font_bytes = font.read()

OSError: cannot open resource

Please help!

**Comment by amueller** [comment]
See #356 this is an issue with PIL. Also see https://github.com/conda-forge/pillow-feedstock/issues/45

**Comment by rushivrox** [comment]
thanks for the previous response, i managed to fix it by uninstalling PIL and Pillow. I am still getting an error though, with the wordcloud. Have been trying to generate a wordcloud for a few hours now.

**Comment by amueller** [comment]
@rushivrox without providing the error and code to reproduce there's no way anyone can help you.

**Comment by rushivrox** [comment]
i figured it out. sorry for the bother! and great work with wordcloud. :)
