### ISSUE TITLE
some questions about this package

### ISSUE THREAD

**Issue by deerabby123** [amueller/word_cloud#384]
hello sir. I want to do some research about word cloud，when using your package，I found that there are some questions I can't solve。

firstly，I found that the layout of your word cloud is random，because i‘m new for python and not so
good at coding，I don‘t know how to change the layout，putting the biggest words in the center of the cloud, and then the second big words around the biggest one ，the smallest words are in the edge of the word cloud, it means the position based on the frequency.

another question is that, when the number of words is not too much, the space between each word is too big, not  close each other. when I change the parameter margin, it is not work.

Is there some methods to solve these questions?

looking forward to your reply!

**Comment by amueller** [comment]
There is no way to change the placement with the current algorithm. You can fill the space more by setting max_font_size to something larger. But the algorithm is really meant to fill the space, which is different from what wordl does. It allows you to do wordclouds in arbitrary shapes like this:
https://raw.githubusercontent.com/amueller/word_cloud/master/examples/alice.png

But it doesn't allow to achieve the things you want easily. You can maybe try using a circle as shape, but it'll really try to fill the shape. So it might not be a great tool if you only have very few words.

**Comment by deerabby123** [comment]
appreciate for your reply！this is really a good advice for me.
