### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by wecanfuture** [amueller/word_cloud#385]
Scrapping link:  https://www.instagram.com/p/BcIdJZ1jiF_/?taken-by=me122122122
0  comments.

 2 / 4

Scrapping link:  https://www.instagram.com/p/BbC9RUWjPeE/?taken-by=me122122122
Traceback (most recent call last):
  File "crawl_profile.py", line 33, in <module>
    information, user_commented_list = extract_information(browser, username, limit_amount)
  File "/root/Bots/instagram-profilecrawl/util/extractor.py", line 225, in extract_information
    caption, location_url, location_name, location_id, lat, lng, img, tags, likes, comments, date, user_commented_list = extract_post_info(browser)
TypeError: 'NoneType' object is not iterable
root@ubuntu-server:~/Bots/instagram-profilecrawl# 'NoneType' object is not iterable
NoneType: command not found

Script stops running.

**Comment by amueller** [comment]
I don't see how this is related to wordcloud.

**Comment by wecanfuture** [comment]
sorry wrong project
