### ISSUE TITLE
ImportError: No module named query_integral_image

### ISSUE THREAD

**Issue by gredercar** [amueller/word_cloud#386]
#### Description
I tried to download the wordcloud project, to rewrite some parts and add features.
I'm using Pycharm as IDE.
Actually it doesn't recognize the query_integral_image import.

This is the line:
from .query_integral_image import query_integral_image

And this is the error:
ImportError: No module named query_integral_image

#### Steps/Code to Reproduce

Download wordcloud project, put files in a folder, try to use the library with the defualt example.

#### Versions
Windows-10-10.0.10240
('Python', '2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]')
('NumPy', '1.14.3')
('matplotlib', '2.2.2')

**Comment by amueller** [comment]
you need to build the library. For example running ``pip install -e .`` in the repository. You need to make sure you install it in the environment you are running your python in, though.

**Comment by jcfr** [comment]
This should be fixed by #403

**Comment by jcfr** [comment]
Closing. This will be fixed with the upcoming release proving [wheels](https://pythonwheels.com/) for python 2.7, 3.4, 3.5, 3.6 and 3.7.
