### ISSUE TITLE
Filling out shapes out of few words

### ISSUE THREAD

**Issue by goranristic123** [amueller/word_cloud#388]
Hello,

I have a question that I couldn't find answer to by reading examples. When trying to fill a shape with few words lets say 5 - 10. It doesn't reuse them to fill all remaining space, it uses them only once ? Is there any way to solve this problem or bypass it somehow ?

Thanks

**Comment by amueller** [comment]
See discussion at #216. Please comment there. I welcome a solution that doesn't alter the current public API. We could also add another method if there is no other way.
