### ISSUE TITLE
Issue of ModuleNotFoundError: No module named '__main__.query_integral_image'; '__main__' is not a package

### ISSUE THREAD

**Issue by muu4649** [amueller/word_cloud#392]
Hi !I have a probelm.
I changed a sentece ’ from query_integral_image import query_integral_image'→’ from .query_integral_image import query_integral_image'. But next error happened .

python word_cloud.py
Traceback (most recent call last):
  File "word_cloud.py", line 7, in <module>
    from .query_integral_image import query_integral_image
ModuleNotFoundError: No module named '__main__.query_integral_image'; '__main__' is not a package

Please answer if you care. Thank you.

**Comment by amueller** [comment]
Hi.
What exactly are you trying to do? Is ``word_cloud.py`` your own script or the library?
If it's the library, it doesn't really make sense to call ``python word_cloud.py``.

**Comment by muu4649** [comment]
My code is bellow.
# coding:utf-8
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from bs4 import BeautifulSoup
import requests
import MeCab as mc
from .query_integral_image import query_integral_image



def mecab_analysis(text):
    t = mc.Tagger('-Ochasen -d /usr/local/Cellar/mecab/0.996/lib/mecab/dic/mecab-ipadic-neologd/')
    enc_text = text.encode('utf-8')
    node = t.parseToNode(enc_text)
    output = []
    while(node):
        if node.surface != "":  # ヘッダとフッタを除外
            word_type = node.feature.split(",")[0]
            if word_type in ["形容詞", "動詞","名詞", "副詞"]:
                output.append(node.surface)
        node = node.next
        if node is None:
            break
    return output


def get_wordlist_from_QiitaURL(url):
    res = requests.get(url)
    soup = BeautifulSoup(res.text)

    text = soup.body.section.get_text().replace('\n','').replace('\t','')
    return mecab_analysis(text)

def create_wordcloud(text):

    # 環境に合わせてフォントのパスを指定する。
    #fpath = "/System/Library/Fonts/HelveticaNeue-UltraLight.otf"
    fpath = "/Library/Fonts/ヒラギノ角ゴ Pro W3.otf"

    # ストップワードの設定
    stop_words = [ u'てる', u'いる', u'なる', u'れる', u'する', u'ある', u'こと', u'これ', u'さん', u'して', \
             u'くれる', u'やる', u'くださる', u'そう', u'せる', u'した',  u'思う',  \
             u'それ', u'ここ', u'ちゃん', u'くん', u'', u'て',u'に',u'を',u'は',u'の', u'が', u'と', u'た', u'し', u'で', \
             u'ない', u'も', u'な', u'い', u'か', u'ので', u'よう', u'']

    wordcloud = WordCloud(background_color="white",font_path=fpath, width=900, height=500, \
                          stopwords=set(stop_words)).generate(text)

    plt.figure(figsize=(15,12))
    plt.imshow(wordcloud)
    plt.axis("off")
    plt.show()

url = "http://qiita.com/t_saeko/items/2b475b8657c826abc114"
wordlist = get_wordlist_from_QiitaURL(url)
create_wordcloud(" ".join(wordlist).decode('utf-8'))

Implementing this code, I use 'python   word_cloud.py' ,right?
Is my code wrong sentence?

**Comment by amueller** [comment]
There is no reason to import ``query_integral_image``.

Also, readability can be greatly improved if you [format](https://help.github.com/articles/creating-and-highlighting-code-blocks/) your code snippets and complete error messages appropriately. For example:

    ```python
    print(something)
    ```
generates:
```python
print(something)
```
And:

    ```pytb
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named 'hello'
    ```
generates:
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'hello'
```
You can edit your issue descriptions and comments at any time to improve readability. This helps maintainers a lot. Thanks!

**Comment by muu4649** [comment]
Thank you so much!

**Comment by jcfr** [comment]
@amueller I suggest we close this issue.

**Comment by PEE8** [comment]
keras_retinanet/preprocessing/generator.py", line 24, in <module>
    from .utils.anchors import anchor_targets_bbox

ModuleNotFoundError: No module named '__main__.utils'; '__main__' is not a package

Why am i getting error. I am trying to import anchor module which is in utils in keras_retinanet while the code generator.py is in preprocessing. 
Please can you suggest if the path i gave is not correct.
I tried different ways like 
from utils import anchors
from .utils.anchors import anchor_targets_bbox
   or 
import utils 
from .utils.anchors import anchor_targets_bbox

it gives :

ModuleNotFoundError: No module named 'utils'
