### ISSUE TITLE
I cant install word cloud using Jupyter! Please advice

### ISSUE THREAD

**Issue by Lsa1991** [amueller/word_cloud#395]

**Comment by LuckyPigeon** [comment]
Can you add some description in this PR? Perhaps your error message?

**Comment by Lsa1991** [comment]
Thank you for your reply. I am trying to import word cloud in Jupyter notebook but it did not work. Also, I tried to install the package but it did not work too. Please find below screen shots of the errors. I really appreciate your support.
![capture](https://user-images.githubusercontent.com/40171020/41281290-ad5726c0-6e39-11e8-8925-08fe842511c6.PNG)
![capture 1](https://user-images.githubusercontent.com/40171020/41281291-ad7b2ff2-6e39-11e8-9618-c6230503ca26.PNG)

**Comment by amueller** [comment]
See http://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

Also this is not an issue with the package and so not really appropriate for the issue tracker.
The message in In[43] tells you exactly what to do, btw.

**Comment by Lsa1991** [comment]
Thank you brother, you helped me a lot. I really appreciate it.
