### ISSUE TITLE
CI takes long?

### ISSUE THREAD

**Issue by amueller** [amueller/word_cloud#398]
I'm surprised with how long the CI takes. The conda one takes much longer because of all the downloads. There's probably some caching on Travis that I should be using.

**Comment by jcfr** [comment]
This is addressed by #403

**Comment by jcfr** [comment]
Closing.

Here are the timing (all include building sdist, wheel and running the tests for Python 2.7, 3.4, 3.5, 3.6 and 3.7:
* Appveyor: ~8.5mins
* CircleCI: ~5mins  (this also include building and deploying the website)
* TravisCI: 9.5mins
