### ISSUE TITLE
Angle Enhancement

### ISSUE THREAD

**Issue by ashokgadri** [amueller/word_cloud#40]
@amueller I want a enhancement in word cloud. I want to show text in different angles also. Have u planned to add any features like this. or any idea to do so.

**Comment by amueller** [comment]
Hi ashokgardi. It is super simple by just drawing orientations here: https://github.com/amueller/word_cloud/blob/master/wordcloud/wordcloud.py#L182. This will probably not be a very tight spacing but might work. For having as tight a spacing as currently, the algorithm needs to be rewritten,  I think. You can just play with the simple option and see how it looks. I don't have time to work on this at the moment.

**Comment by ashokgadri** [comment]
@amueller I Already tried with this thing but pil only transpose text with 90, 180, 270 degrees. For rotating image we have to rotate complete image. I'm trying to rewrite the algorithm but having an issue on finding free space. your query_integral_image function only finds the free rectangle in the image.

**Comment by amueller** [comment]
Indeed. That is why I meant that spacing will not be as tight. The free space will be used up later, but it will always try to find a complete bounding rectangle. You can rewrite the query, though.
