### ISSUE TITLE
Installing wordcloud on MS command prompt

### ISSUE THREAD

**Issue by Fightforjustice** [amueller/word_cloud#400]
I'm trying to install a version of Wordcloud via Command Prompt. I run it as admin, I have python 3.6 installed, and I have VS 14.0 Build Tools installed. Here's what I get:

![cli_wrdcld_error](https://user-images.githubusercontent.com/11139285/41811741-4bd69c20-76e3-11e8-8e53-5712ff0d04a8.JPG)
![cli_wrdcld_error1](https://user-images.githubusercontent.com/11139285/41811742-52953b66-76e3-11e8-831e-12bb8d693768.JPG)

Any insights?

**Comment by amueller** [comment]
Sorry for being slow to reply. Did you work it out? I recommend installing using conda.

**Comment by Fightforjustice** [comment]
Yes; I ended up adding a new program to my path variables and copying some
needed files to my VS folder.

Thanks!
