### ISSUE TITLE
How can I install wordcloud for python3.7 in mac osx? I cant install wordcloud via pip3 install

### ISSUE THREAD

**Issue by honhosing** [amueller/word_cloud#402]
#### Description
How can I install wordcloud for python3.7 in mac osx? I cant install wordcloud via pip3 install

#### Steps/Code to Reproduce
1. When I try `pip3 install --user wordcloud` on the command line in terminal, the installation failed. [link to the text of error](https://github.com/honhosing/forissues/blob/master/pip3%20install%20wordcloud%20does%20not%20work.txt) 
I have installed xcode-select so I try using `pip install --user wordcloud`. It works but the wordcloud is in the site-package of python2.7 and my codes is using python3.7.

2. Then I copy the folder 'wordcloud' from '/Users/***/Library/Python/2.7/lib/python/site-packages/wordcloud' to '/usr/local/lib/python3.7/site-packages/wordcloud', the wordcloud occurs in the PyCharm module.
![image](https://user-images.githubusercontent.com/18226870/42693380-8a14f898-86e1-11e8-9c3a-0851e3dfb808.png)
After that I run the code `import wordcloud; print("wordcoud", wordcloud.__version__)`, another error comes out.

#### Actual Results
1. 

[link to the text of error](https://github.com/honhosing/forissues/blob/master/pip3%20install%20wordcloud%20does%20not%20work.txt) 

2. 
```
Traceback (most recent call last):
  File "/Users/hanhaoxing/PycharmProjects/weibo_data/test.py", line 1, in <module>
    import wordcloud; print("wordcoud", wordcloud.__version__)
  File "/Users/hanhaoxing/Library/Python/3.7/lib/python/site-packages/wordcloud/__init__.py", line 1, in <module>
    from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
  File "/Users/hanhaoxing/Library/Python/3.7/lib/python/site-packages/wordcloud/wordcloud.py", line 24, in <module>
    from .query_integral_image import query_integral_image
ImportError: dlopen(/Users/hanhaoxing/Library/Python/3.7/lib/python/site-packages/wordcloud/query_integral_image.so, 2): Symbol not found: _PyInt_Type
  Referenced from: /Users/hanhaoxing/Library/Python/3.7/lib/python/site-packages/wordcloud/query_integral_image.so
  Expected in: flat namespace
 in /Users/hanhaoxing/Library/Python/3.7/lib/python/site-packages/wordcloud/query_integral_image.so
```

#### Versions
Platform : Darwin-17.6.0-x86_64-i386-64bit
IDLE : PyCharm
sys : Python 3.7.0 (default, Jun 29 2018, 20:13:13)  /  [Clang 9.1.0 (clang-902.0.39.2)]
Numpy : NumPy 1.14.5
matplotlib : matplotlib 2.2.2
wordcloud : no successful to import

**Comment by amueller** [comment]
Sorry I'm not very familiar with building on OS X. Right now I would recommend using anaconda. We might have binary wheels next week, which would mean you could install with pip without having to build.

**Comment by honhosing** [comment]
Thx. Now I cut my code into 2 pieces so that it could run python2.7 for wordcloud when I need to export the images. LOL. Hope to see the binary wheels ASAP !

**Comment by jcfr** [comment]
Closing. This will be fixed with the upcoming release proving [wheels](https://pythonwheels.com/) for python 2.7, 3.4, 3.5, 3.6 and 3.7.
