### ISSUE TITLE
github project settings: Add website URL

### ISSUE THREAD

**Issue by jcfr** [amueller/word_cloud#409]
The URL: http://amueller.github.io/word_cloud/ could be added to that it show up at the top:

![image](https://user-images.githubusercontent.com/219043/43218383-3dd0ee94-9012-11e8-96ef-d5f34b44992c.png)

**Comment by amueller** [comment]
done.

**Comment by jcfr** [comment]
Look like the link include an extra space at the end, it redirects to an invalid page
