### ISSUE TITLE
Can use different text but different stencil images fail

### ISSUE THREAD

**Issue by patrickbeatty** [amueller/word_cloud#41]
Hi.

Just playing around with your python code and could get the masked stuff to work on my mac book pro (not luck on linux server yet). However, I started experimenting with the masked file. Changing the text worked no problem for Alice. Then when I tried to use a different .png stencil (same site), I got the following error:

Traceback (most recent call last):
  File "trulia_home.py", line 27, in <module>
    wc.generate(text)
  File "/Library/Python/2.7/site-packages/wordcloud/wordcloud.py", line 313, in generate
    self.fit_words(self.words_)
  File "/Library/Python/2.7/site-packages/wordcloud/wordcloud.py", line 193, in fit_words
    box_size[0] + self.margin, random_state)
  File "wordcloud/query_integral_image.pyx", line 7, in wordcloud.query_integral_image.query_integral_image (wordcloud/query_integral_image.c:1342)
ValueError: Buffer has wrong number of dimensions (expected 2, got 3)

**Comment by amueller** [comment]
The image needs to be grayscale. I guess I should just convert to grayscale. Can you look at the fix at #37 and see if that works for you?

What is the problem on on the linux box?

**Comment by patrickbeatty** [comment]
Thanks! 

Locally, looks like it works with the greyscale trick and can now run new images with new text. As for text, I've tried some free online books, but going to practice with some other text files.

As for the server, I keep running into what looks like a Cython module error:

pbeatty@consumer-dev2:~/word_cloud-master$ sudo pip install -r requirements.txt
Downloading/unpacking Cython>=0.19.1 (from -r requirements.txt (line 1))
  Running setup.py egg_info for package Cython
    
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.h' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
Downloading/unpacking Image>=1.1.7 (from -r requirements.txt (line 2))
  Running setup.py egg_info for package Image
    
    warning: no files found matching '*.html' under directory 'image'
    warning: no files found matching '*.js' under directory 'image'
    warning: no files found matching '*.tff' under directory 'image'
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Downloading/unpacking pillow (from Image>=1.1.7->-r requirements.txt (line 2))
  Running setup.py egg_info for package pillow
    
Requirement already satisfied (use --upgrade to upgrade): django in /usr/local/lib/python2.7/dist-packages (from Image>=1.1.7->-r requirements.txt (line 2))
Installing collected packages: Cython, Image, pillow
  Running setup.py install for Cython
    building 'Cython.Plex.Scanners' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c /home/pbeatty/word_cloud-master/build/Cython/Cython/Plex/Scanners.c -o build/temp.linux-x86_64-2.7/home/pbeatty/word_cloud-master/build/Cython/Cython/Plex/Scanners.o
    /home/pbeatty/word_cloud-master/build/Cython/Cython/Plex/Scanners.c:16:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/home/pbeatty/word_cloud-master/build/Cython/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-8Ba0kx-record/install-record.txt:
    running install

running build

running build_py

running build_ext

building 'Cython.Plex.Scanners' extension

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c /home/pbeatty/word_cloud-master/build/Cython/Cython/Plex/Scanners.c -o build/temp.linux-x86_64-2.7/home/pbeatty/word_cloud-master/build/Cython/Cython/Plex/Scanners.o

/home/pbeatty/word_cloud-master/build/Cython/Cython/Plex/Scanners.c:16:20: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/home/pbeatty/word_cloud-master/build/Cython/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-8Ba0kx-record/install-record.txt failed with error code 1
Storing complete log in /root/.pip/pip.log
pbeatty@consumer-dev2:~/word_cloud-master$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build

**Comment by patrickbeatty** [comment]
...and found the issue, so the server needed to have developer tools installed:

sudo apt-get install python-dev

After that I redid the install in steps (the easy install has never worked for me):
wget https://github.com/amueller/word_cloud/archive/master.zip
unzip master.zip
rm master.zip
cd word_cloud-master

Install the requirements: sudo pip install -r requirements.txt
Install the package: sudo python setup.py install

Afterward, the only remaining issue was the font path and I worked around it my dropping the relevant .tff file into the wordcloud folder (in this case Verdana.tff). My final code using a free Charles Dickens text with a stencil of Bob Marley:

#!/usr/bin/env python2
"""
Masked wordcloud
================
Using a mask you can generate wordclouds in arbitrary shapes.
"""

from os import path
from scipy.misc import imread
import matplotlib.pyplot as plt
from PIL import Image

from wordcloud import WordCloud, STOPWORDS

d = path.dirname(__file__)

# Read the whole text.
text = open(path.join(d, 'marley.txt')).read()

# read the mask image and change to greyscale
# taken from
# http://www.stencilry.org/stencils/ and exported to a .png file 
image_file = Image.open(path.join(d,"marley_mask.png"))
image_file = image_file.convert("L") # convert image to black and white
image_file.mode = "L"
image_file = image_file.point(lambda x: 0 if x<128 else 255)
image_file.save(path.join(d,"marley_mask.png"))

marley_mask = imread(path.join(d, "marley_mask.png"))

wc = WordCloud(font_path='Verdana.ttf',background_color="white", max_words=2000, mask=marley_mask,
               stopwords=STOPWORDS.add("said"))
# Note that the Verdana.ttf is a truetype file that I saved to the same folder as the images

# generate word cloud
wc.generate(text)

# store to file
wc.to_file(path.join(d, "marley.png"))

# show
plt.imshow(wc)
plt.axis("off")
plt.figure()
plt.imshow(marley_mask, cmap=plt.cm.gray)
plt.axis("off")
plt.show()

**Comment by amueller** [comment]
Glad you worked it out :)
