### ISSUE TITLE
Error while installing wordcloud on Ubuntu 16.04 (Google Compute Engine)

### ISSUE THREAD

**Issue by alex-danilin** [amueller/word_cloud#410]
#### Description
While trying to install wordcloud on Google Compute Engine instance with Ubuntu 16.04 I constantly get this error:
error: command 'gcc' failed with exit status 1

#### Steps/Code to Reproduce
sudo pip3 install wordcloud

#### Expected Results
The module is installed successfully.

#### Actual Results
Collecting wordcloud
  Downloading https://files.pythonhosted.org/packages/bc/e8/cab8479b25297b3847cfb55e85a5014e8c53b80e513eaf1ba58c7b3a6acd/wordcloud-1.4.1.tar.gz (172kB)
    100% |████████████████████████████████| 174kB 4.4MB/s 
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/site-packages (from wordcloud) (2.2.2)
Requirement already satisfied: numpy>=1.6.1 in /usr/local/lib/python3.7/site-packages (from wordcloud) (1.14.5)
Requirement already satisfied: pillow in /usr/local/lib/python3.7/site-packages (from wordcloud) (5.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/site-packages (from matplotlib->wordcloud) (2.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/site-packages (from matplotlib->wordcloud) (1.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/site-packages (from matplotlib->wordcloud) (2.7.3)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/site-packages (from matplotlib->wordcloud) (2018.5)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/site-packages (from matplotlib->wordcloud) (0.10.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/site-packages (from matplotlib->wordcloud) (1.11.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->wordcloud) (39.0.1)
Installing collected packages: wordcloud
  Running setup.py install for wordcloud ... error
    Complete output from command /usr/local/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3q3_jbo2/wordcloud/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-iao70co5/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/wordcloud
    copying wordcloud/color_from_image.py -> build/lib.linux-x86_64-3.7/wordcloud
    copying wordcloud/tokenization.py -> build/lib.linux-x86_64-3.7/wordcloud
    copying wordcloud/__init__.py -> build/lib.linux-x86_64-3.7/wordcloud
    copying wordcloud/wordcloud.py -> build/lib.linux-x86_64-3.7/wordcloud
    copying wordcloud/wordcloud_cli.py -> build/lib.linux-x86_64-3.7/wordcloud
    copying wordcloud/stopwords -> build/lib.linux-x86_64-3.7/wordcloud
    copying wordcloud/DroidSansMono.ttf -> build/lib.linux-x86_64-3.7/wordcloud
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/wordcloud
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.7m -c wordcloud/query_integral_image.c -o build/temp.linux-
x86_64-3.7/wordcloud/query_integral_image.o
    wordcloud/query_integral_image.c: In function ‘__Pyx_ExceptionSave’:
    wordcloud/query_integral_image.c:14910:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         *type = tstate->exc_type;
                       ^
    wordcloud/query_integral_image.c:14911:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         *value = tstate->exc_value;
                        ^
    wordcloud/query_integral_image.c:14912:17: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         *tb = tstate->exc_traceback;
                     ^
    wordcloud/query_integral_image.c: In function ‘__Pyx_ExceptionReset’:
    wordcloud/query_integral_image.c:14924:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    wordcloud/query_integral_image.c:14925:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    wordcloud/query_integral_image.c:14926:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    wordcloud/query_integral_image.c:14927:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tstate->exc_type = type;
               ^
    wordcloud/query_integral_image.c:14928:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tstate->exc_value = value;
               ^
    wordcloud/query_integral_image.c:14929:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tstate->exc_traceback = tb;
               ^
wordcloud/query_integral_image.c: In function ‘__Pyx_GetException’:
    wordcloud/query_integral_image.c:14972:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    wordcloud/query_integral_image.c:14973:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    wordcloud/query_integral_image.c:14974:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    wordcloud/query_integral_image.c:14975:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tstate->exc_type = local_type;
               ^
    wordcloud/query_integral_image.c:14976:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tstate->exc_value = local_value;
               ^
    wordcloud/query_integral_image.c:14977:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tstate->exc_traceback = local_tb;
               ^
    wordcloud/query_integral_image.c: In function ‘__Pyx_ExceptionSwap’:
    wordcloud/query_integral_image.c:14999:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tmp_type = tstate->exc_type;
                          ^
    wordcloud/query_integral_image.c:15000:23: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tmp_value = tstate->exc_value;
                           ^
    wordcloud/query_integral_image.c:15001:20: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tmp_tb = tstate->exc_traceback;
                        ^
    wordcloud/query_integral_image.c:15002:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
         tstate->exc_type = *type;
               ^
    wordcloud/query_integral_image.c:15003:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
         tstate->exc_value = *value;
               ^
    wordcloud/query_integral_image.c:15004:11: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
         tstate->exc_traceback = *tb;
               ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-3q3_jbo2/wordcloud/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-iao70co5/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-3q3_jbo2/wordcloud/

**Comment by jcfr** [comment]
Thanks for reporting the issue. This will address as soon as we cut the next release.

Either today or tomorrow.

**Comment by jcfr** [comment]
Closing. This will be fixed with the upcoming release proving [wheels](https://pythonwheels.com/) for python 2.7, 3.4, 3.5, 3.6 and 3.7.
