### ISSUE TITLE
Upload to PyPI failing because of non-verified primary email address

### ISSUE THREAD

**Issue by jcfr** [amueller/word_cloud#422]
Hi @amueller , 

Release has been tagged but it looks like you haven't approved your PyPI account. On AppVeyor (where it is using your username/password), it reports:

```
wine : HTTPError: 400 Client Error: User '*****' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more 
information.for more information. for url: https://upload.pypi.org/legacy/
At line:4 char:3
+   twine upload -u $env:PYPI_USER -p $env:PYPI_PASSWORD --skip-existin ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (HTTPError: 400 ...ypi.org/legacy/:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Command executed with exception: HTTPError: 400 Client Error: User '*****' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.for more information. for url: https://upload.pypi.org/legacy/
```

**Comment by jcfr** [comment]
After this is fixed, would be great if you could re-trigger this build:

https://ci.appveyor.com/project/amueller/word-cloud/build/0.0.1.126

That would allow the wheels to be uploaded on PyPI

**Comment by amueller** [comment]
was that for test.pypi.org? My other definitely has confirmation.

**Comment by jcfr** [comment]
Here is the correct build: https://ci.appveyor.com/project/amueller/word-cloud/build/0.0.1.129

The other one was associated with test.pypi.org and we still get the same message:

```
if ($env:appveyor_repo_tag -eq $true -and $env:appveyor_repo_tag_name –match "^[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$") {
  Write-Host "deploy release"
  $env:PATH="$env:PYTHON_DIR/Scripts/;$env:PATH"
  twine upload -u $env:PYPI_USER -p $env:PYPI_PASSWORD --skip-existing dist/*
} elseif ($env:appveyor_repo_branch -eq "master") {
   Write-Host "deploy master (not implemented)"
} else {
  Write-Host "nothing to deploy"
}
deploy release
Uploading distributions to https://upload.pypi.org/legacy/
Uploading wordcloud-1.5.0-cp27-cp27m-win_amd64.whl
  0%|          | 0.00/157k [00:00<?, ?B/s]
  5%|5         | 8.00k/157k [00:00<00:03, 47.6kB/s]
100%|##########| 157k/157k [00:00<00:00, 410kB/s]  
twine : HTTPError: 400 Client Error: User '*****' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more 
information.for more information. for url: https://upload.pypi.org/legacy/
At line:4 char:3
+   twine upload -u $env:PYPI_USER -p $env:PYPI_PASSWORD --skip-existin ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (HTTPError: 400 ...ypi.org/legacy/:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Command executed with exception: HTTPError: 400 Client Error: User '*****' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.for more information. for url: https://upload.pypi.org/legacy/
```

**Comment by jcfr** [comment]
It would be great to address this since it is holding the release :disappointed:

**Comment by jcfr** [comment]
@amueller To finalize the windows release (and address issue like #134), it would be great if you could update or verify your AppVeyor credential.

If you grant me access to the AppVeyor of the project, I could also help. The issue with AppVeyor is that it is a all or nothing. After granting me access, I would have access to all of your appveyor based project associated with the `amueller` user ... 

To do this, you would click on "Add collaborator" after login in as "amueller" and going to Team settings.


![image](https://user-images.githubusercontent.com/219043/43463694-372e072c-94a7-11e8-9b3b-35328309a0d8.png)

**Comment by amueller** [comment]
Weird, it showed my address as being non-verified. I verified it. I have used this account for years without problem. Maybe registering with test.pypi.org changed something?

**Comment by amueller** [comment]
looks green now

**Comment by jcfr** [comment]
Sweet :clap: :v: :trophy: 

Windows package have been uploaded:

![image](https://user-images.githubusercontent.com/219043/43469009-3d44a51a-94b3-11e8-9666-d17e5dba6d04.png)
