### ISSUE TITLE
Is there an option to prevent final results with rotated words?

### ISSUE THREAD

**Issue by miguelwon** [amueller/word_cloud#427]
Is there an option to prevent final results with rotated words?

**Comment by jcfr** [comment]
Hi @miguelwon , 

The words are currently **NOT** rotated in the generated wordcloud. For example, see https://amueller.github.io/word_cloud/auto_examples/simple.html

Would it be possible to clarify your question ?

**Comment by miguelwon** [comment]
Ok, thanks.
