### ISSUE TITLE
Hi,This link cannot be opened here. http://amueller.github.io/word_cloud/

### ISSUE THREAD

**Issue by comeCU** [amueller/word_cloud#428]
#### Description

Maybe you should change it to https://amueller.github.io/word_cloud/

**Comment by jcfr** [comment]
Thanks for reporting the issue :+1: 

@amueller  should be able to update the link.

That said, using either https://amueller.github.io/word_cloud/  or http://amueller.github.io/word_cloud/ is expected to work.

**Comment by amueller** [comment]
should be fixed
