### ISSUE TITLE
pandas dataframe as source

### ISSUE THREAD

**Issue by intuitivetextmining** [amueller/word_cloud#432]
it would be really nice if wordcloud could create clouds from a pandas dataframe with the parameters specifying the words and frequency/count/size which could be column names and perhaps the index for the words too

eg

`wc = wordcloud.WordCloud.from_pandas_dafatrame(df['words'], df['count'])`

**Comment by amueller** [comment]
Thanks. Why don't you want to use ``generate_from_frequiencies``?
```python
wc = wordcloud.WordCloud().generate_from_frequencies(df.to_dict())
```
(untested)

**Comment by intuitivetextmining** [comment]
good question.

when I'm juggling large datasets, I want to avoid creating new instances / copies / dicts of that data.

if wordcloud could read directly the data it was passed as a reference that would be idea but I don't know if it internally creates a copy ... 

but creating a copy (dict) of a pandas frame isn't that great with huge datasets .. I'm already having to `del` variables to free up memory

**Comment by amueller** [comment]
But these are the frequencies so it only depends on the size of the
vocabulary, not the size of the documents, right? And how many words do you
render? I assume not more than 4000, which will basically take memory at
all.

**Comment by m3xw3ll** [comment]
> Thanks. Why don't you want to use `generate_from_frequiencies`?
> 
> ```python
> wc = wordcloud.WordCloud().generate_from_frequencies(df.to_dict())
> ```
> 
> (untested)

This is not working for me. I get the following error
`TypeError: '<' not supported between instances of 'dict' and 'dict'`

**Comment by amueller** [comment]
@m3xw3ll What does ``df.to_dict()``  look like?

**Comment by m3xw3ll** [comment]
@amueller I solved the issue by myself. I checked the output of `df.to_dict()` and noticed that per default the dict key is the columnname. I didn´t know that. 
Here the output:
`{'word': {0: 'house', 1: 'cat', 2: 'car'}, 'freq': {0: '4516', 1: '342', 2: '234'}}`
If someone runs in the same issue, here is the working example:
```
import wordcloud
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

frame = pd.DataFrame(np.array([['house', 4516], ['cat', 342], ['car', 234]]), columns=['word', 'freq'])
framedict = dict(zip(frame['word'], frame['freq'].astype(int)))
wc = wordcloud.WordCloud().generate_from_frequencies(framedict)
plt.figure()
plt.imshow(wc, interpolation="bilinear")
plt.axis("off")
plt.show()
```
