### ISSUE TITLE
How to set color sets for words

### ISSUE THREAD

**Issue by arronvera** [amueller/word_cloud#434]
I want to set color sets for words，because there are too many colors originaly

**Comment by amueller** [comment]
you can use any color map or a constant color using the color_func parameter.

**Comment by arronvera** [comment]
ValueError: ImageColorGenerator is smaller than the canvas

**Comment by amueller** [comment]
The colors should be according to the image you specified for the background.
Please provide a self-contained example so I can reproduce.

**Comment by arronvera** [comment]
Can't this image be another image which only has four colors？

**Comment by amueller** [comment]
yes is can be. It's hard to say what's wrong if you don't provide the output or a self-contained example that I can run.
