### ISSUE TITLE
using stopwords in CLI with python 2.7 throws casting error

### ISSUE THREAD

**Issue by NaanProphet** [amueller/word_cloud#436]
#### Description
Using the `--stopwords` flag with `wordcloud_cli` throws a casting error when running with Python 2.7 on Mac OS.

#### Steps/Code to Reproduce
* Run on Mac OS (where the default is Python 2.7)
* Create a non-empty plaintext file `echo "thee" > stopwords.txt`
* Run `wordcloud_cli --text input.txt --imagefile output.png --stopwords stopwords.txt`

#### Expected Results
No error is thrown.

#### Actual Results
```
Traceback (most recent call last):
  File "/usr/local/bin/wordcloud_cli", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/wordcloud/__main__.py", line 33, in main
    wordcloud_cli_main(*wordcloud_cli_parse_args(sys.argv[1:]))
  File "/usr/local/lib/python2.7/site-packages/wordcloud/wordcloud_cli.py", line 178, in parse_args
    args['stopwords'] = set(map(str.strip, f.readlines()))
TypeError: descriptor 'strip' requires a 'str' object but received a 'unicode'
```

#### Versions
```
Darwin-17.7.0-x86_64-i386-64bit
('Python', '2.7.15 (default, Aug 22 2018, 16:36:18) \n[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]')
('NumPy', '1.15.2')
Traceback (most recent call last):
  File "about.py", line 4, in <module>
    import matplotlib; print("matplotlib", matplotlib.__version__)
ImportError: No module named matplotlib
```

**Comment by NaanProphet** [comment]
I see https://github.com/amueller/word_cloud/pull/312 is already open for this issue

**Comment by amueller** [comment]
This is fixed now, right?

**Comment by NaanProphet** [comment]
Yup! Thanks to https://github.com/amueller/word_cloud/pull/438

**Comment by amueller** [comment]
Thanks for your help!
