### ISSUE TITLE
Thai character is missing from word cloud picture

### ISSUE THREAD

**Issue by elcolie** [amueller/word_cloud#448]
#### Description
Thai word contains multiple lines. The upper, upper most, and lower are gone.

#### Steps/Code to Reproduce
Get the Thai font from here. It is not commercialised license. Free for education purpose.
https://www.f0nt.com/download/book/Book_Akhanake.zip

Example:
```
import matplotlib as mpl

mpl.use('Agg')
import matplotlib.pyplot as plt
from wordcloud import WordCloud

a = 'เงิน ทอง ของ นอก กาย เงิน ทอง ของ มายา ข้าว ปลา นั้น ของ จริง'
wc = WordCloud(font_path='BLK-BangLi-Ko-Sa-Na.ttf').generate(a)
wc.to_file('wc.jpg')
plt.imshow(wc)
plt.axis('off')
plt.savefig('plt.png')
```

#### Expected Results
Thai word being lay down in the picture with out any missing

#### Actual Results
![wc](https://user-images.githubusercontent.com/18206728/47914888-c89d0700-ded3-11e8-9d5a-15ea045e51a0.jpg)

Word with upper character stop the next character from rendered
For example
เงิน => เง
จริง => จร

#### Versions
Darwin-18.0.0-x86_64-i386-64bit
Python 3.6.6 (default, Oct 19 2018, 17:40:52)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.2)]
NumPy 1.15.3
matplotlib 3.0.0
wordcoud 1.5.0

**Comment by amueller** [comment]
See #272. It's an issue with the regex and what unicode consideres word boundaries and whitespace.

**Comment by elcolie** [comment]
Thank you I will look into it
