### ISSUE TITLE
ImportError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by jaraco** [amueller/word_cloud#449]
#### Description

Attempting to troubleshoot #446, I tried installing wordcloud and constructing a WordCloud, but got an ImportError on matplotlib.

#### Steps/Code to Reproduce

`rwt wordcloud -- -c '__import__("wordcloud").WordCloud()'`

#### Expected Results

Process should run with an exit code of 0. Reading the other tickets, wordcloud is supposed to be usable without matplotlib, but it seems that simply constructing a WordCloud object requires matplotlib.

The CLI isn't subject to the issue because it supplies a value for color_func.

#### Actual Results

```
draft $ rwt wordcloud -- -c '__import__("wordcloud").WordCloud()'
Collecting wordcloud
  Using cached https://files.pythonhosted.org/packages/c7/07/e43a7094a58e602e85a09494d9b99e7b5d71ca4789852287386e21e74c33/wordcloud-1.5.0-cp37-cp37m-macosx_10_6_x86_64.whl
Collecting numpy>=1.6.1 (from wordcloud)
  Using cached https://files.pythonhosted.org/packages/3d/c3/a69406093c9a780a74964f41cd56b06c0346d686a9b3f392d123a663f5e0/numpy-1.15.4-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pillow (from wordcloud)
  Using cached https://files.pythonhosted.org/packages/99/c8/550f3416afe7b6726efc8a7f2249a38d6ae65c3514ef6c36bdc8485868b7/Pillow-5.3.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: numpy, pillow, wordcloud
Successfully installed numpy-1.15.4 pillow-5.3.0 wordcloud-1.5.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-n716ltxc/wordcloud/wordcloud.py", line 300, in __init__
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

#### Versions

```
>>> import platform; print(platform.platform())
Darwin-18.0.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28)
[Clang 6.0 (clang-600.0.57)]
```

**Comment by amueller** [comment]
Constructing a WordCloud with the default colormap requires matplotlib. It might be best to just add it to the dependencies. Wdyt?

**Comment by Jessime** [comment]
I have a package that requires `wordcloud`, and it's listed in my `requirements.txt` file. If I run:

```
$ pip install -r requirements.txt
```

everything works as expected, and it says wordcloud is installed. But when I go to execute my program, I get:

```
Traceback (most recent call last):
  File "youtube_history.py", line 298, in <module>
    analysis.run()
  File "youtube_history.py", line 288, in run
    self.start_analysis()
  File "youtube_history.py", line 276, in start_analysis
    self.make_wordcloud()
  File "youtube_history.py", line 174, in make_wordcloud
    relative_scaling=.5)
  File "/home/jessime/anaconda3/envs/youtube_history37_2/lib/python3.7/site-packages/wordcloud/wordcloud.py", line 300, in __init__
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

Personally, I can easily remedy this by doing a second `pip install matplotlib`. But this isn't ideal for end-users. Any thoughts on why it seems like `wordcloud` isn't installing `matplotlib` (even though it's listed in your `requirements.txt`)?

**Comment by amueller** [comment]
because it's not in the ``setup.py``, which is the only thing parsed by pip (there is not really a concept of requirement.txt in pip). We should probably add it to setup.py. PR welcome.

**Comment by Jessime** [comment]
PR submitted!

**Comment by amueller** [comment]
thanks, merged.
