### ISSUE TITLE
Mac OS X - IOError: cannot open resource

### ISSUE THREAD

**Issue by HommeDeJava** [amueller/word_cloud#45]
Greetings folks,

On a Mac OS X, I've got the « IOError: cannot open resource »

Then I've just changed the FONT_PATH in the file « wordcloud.py »

FONT_PATH = os.environ.get("FONT_PATH", "/Library/Fonts/Times New Roman.ttf")

Hoping that can help someone else.

**Comment by amueller** [comment]
There is also a ``font_path`` option to the ``WordCloud`` object, so you don't need to change any of the wordcloud code.

**Comment by amueller** [comment]
can you tell me what platform.system() gives you, so we could do something like #63?

**Comment by corcra** [comment]
I had the same problem (and solution). 
If it helps:
```
>>> platform.system()
'Darwin'
```
