### ISSUE TITLE
Bug when using stdout as imagefile?

### ISSUE THREAD

**Issue by lucbouge** [amueller/word_cloud#451]
#### Description
Error in PIL when writing to stdout

#### Steps/Code to Reproduce

Contents of file `words.txt`
> Hello!

Run `wordcount_cli`

> $ wordcloud_cli --text words.txt 
> Traceback (most recent call last):
>   File "/usr/local/bin/wordcloud_cli", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/site-packages/wordcloud/__main__.py", line 33, in main
>     wordcloud_cli_main(*wordcloud_cli_parse_args(sys.argv[1:]))
>   File "/usr/local/lib/python3.7/site-packages/wordcloud/wordcloud_cli.py", line 93, in main
>     image.save(imagefile, format='png', optimize=True)
>   File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 1969, in save
>     save_handler(self, fp, filename)
>   File "/usr/local/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 734, in _save
>     fp.write(_MAGIC)
> TypeError: write() argument must be str, not bytes

However, it works fine with an explicit output file.
> wordcloud_cli --text words.txt --imagefile words.png

#### Actual Results
See above

#### Versions

> $ python
> Python 3.7.1 (default, Nov  6 2018, 18:45:35) 
> [Clang 10.0.0 (clang-1000.11.45.5)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import platform; print(platform.platform())
> Darwin-17.7.0-x86_64-i386-64bit
> >>> import sys; print("Python", sys.version)
> Python 3.7.1 (default, Nov  6 2018, 18:45:35) 
> [Clang 10.0.0 (clang-1000.11.45.5)]
> >>> import numpy; print("NumPy", numpy.__version__)
> NumPy 1.15.4
> >>> import matplotlib; print("matplotlib", matplotlib.__version__)
> matplotlib 3.0.1
> >>> import wordcloud; print("wordcoud", wordcloud.__version__)
> wordcoud 1.5.0

**Comment by amueller** [comment]
Thanks for the report. It's likely that that's not currently supported. PR welcome :)
