### ISSUE TITLE
(utf-8) I think there is a problem.

### ISSUE THREAD

**Issue by vdemir** [amueller/word_cloud#454]
There are some Turkish characters. Used in some words. For example, it is used as in "bütün" and "çok". "Adding to the stopwords list. But there is a problem. Special letters are not stopped.

**Comment by amueller** [comment]
Are you using python2 or python 3?

**Comment by vdemir** [comment]
py2

**Comment by vdemir** [comment]
ok. thanks. God job. Well Done.
