### ISSUE TITLE
generate_from_frequencies() raise ZeroDivisionError when there're more than one zero in the data

### ISSUE THREAD

**Issue by BLKSerene** [amueller/word_cloud#456]
#### Description
Similar Issue: [Issue 308](https://github.com/amueller/word_cloud/issues/308)

At line 464 in wordcloud.py:
```
if rs != 0:
                font_size = int(round((rs * (freq / float(last_freq))
                                       + (1 - rs)) * font_size))
```

If last_freq == 0 (more than one zero in the data), ZeroDivisionError will be raised.

And I'm using generate_from_frequencies() for plotting not only frequency data, but other statistics, such as p-values, chi-square, etc. Decimals are fine, too many zeros would raise the error. I haven't tested negative values (in some cases negative values do make sense, for example in statistics), so I'm not sure whether using negative values as input data will cause any other problems. 

The workaround I'm using now is to manually remove all zeros in my data (and negative values too, I suppose), but there might be not enough words in the figure. Another workaround is to replace all zeros with a very small number, for example 0.0000000001, which produces better results.

Thanks in advance.

#### Steps/Code to Reproduce

Example:
```
import wordcloud

word_cloud = wordcloud.WordCloud()

word_cloud.generate_from_frequencies({'test': 1, 'test1': 0, 'test2': 2}) # OK
word_cloud.generate_from_frequencies({'test': 1, 'test1': 0, 'test2': 0}) # Error
```

#### Versions
Windows-10-10.0.17134-SP0
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
matplotlib 3.0.2
wordcoud 1.5.0

**Comment by amueller** [comment]
Thanks for the report and sorry for the slow reply. Fix in #470, which basically removes zeros.
I think given the semantics of frequencies it makes sense to skip the zeros.
You can always use custom logic for your code. Let me know if that works for you.

**Comment by BLKSerene** [comment]
Thanks, it works. Though I still prefer replacing the zeros with a very small number, since zeros do have some meaning in my data (otherwise the words will never appear in the figure).

And there's another edge case that if the data contain only zeros, `max_frequency` would be 0, and
```
frequencies = [(word, freq / max_frequency)
                       for word, freq in frequencies]
```
would raise `ZeroDivisionError`.

```
>>> import wordcloud
>>> word_cloud = wordcloud.WordCloud()
>>> word_cloud.generate_from_frequencies({'test1': 0, 'test2': 0, 'test3': 0})
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    word_cloud.generate_from_frequencies({'test': 0, 'test1': 0, 'test2': 0})
  File "D:\Python\lib\site-packages\wordcloud\wordcloud.py", line 390, in generate_from_frequencies
    for word, freq in frequencies]
  File "D:\Python\lib\site-packages\wordcloud\wordcloud.py", line 390, in <listcomp>
    for word, freq in frequencies]
ZeroDivisionError: float division by zero
```

But I'm not sure whether `wordcloud` should check for this, or the users of `wordcloud` themselves should check if their data contain only zeros.

**Comment by amueller** [comment]
That's a good point. I think wordcloud should raise an error in this case. As usually 0 means nothing, I think it's more appropriate to ignore zeros. It's very easy for you to just add a small number to all of your counts with a single line if you want to keep the zeros.
```python
freq_eps = [(w, f + e1-5) for w, f in frequencies]

**Comment by guptaashray** [comment]
Can you please help me, what should I do?

def wordcloud(data,title):
  wc = WordCloud(width=600, height=530, max_words=150,colormap="Dark2").generate_from_frequencies(data)
  plt.figure(figsize=(10,8))
  plt.imshow(wc, interpolation='bilinear')
  plt.axis("off")
  plt.title('\n'.join(wrap(title,60)),fontsize=13)
  plt.show()
  
titletext_dtm=titletext_dtm.transpose()

for index,product in enumerate(titletext_dtm.columns):
  wordcloud(titletext_dtm[product].sort_values(ascending=False),product)

This is my code, and I'm getting the same error.

**Comment by amueller** [comment]
Sorry for the slow reply. What version of wordcloud are you using, and can you please provide a self-contained example to reproduce? Ideally open a new issue to track it.

**Comment by rebecca-foreflight** [comment]
I am still getting the zerodivision error after add `e1-5` to everywhere there would be zero divison.  How was this officially resolved?  Are we encouraged to modify our code or do we use a new library?  I am unsure of how to get out of this exception.
