### ISSUE TITLE
Hebrew word cloud

### ISSUE THREAD

**Issue by ronyarmon** [amueller/word_cloud#458]
I'm not able to produce word cloud from a Hebrew text. 
The code builds on a standard example for producing English clouds

`from wordcloud import WordCloud, STOPWORDS 
import matplotlib.pyplot as plt
text = open('health_example-liver.txt', 'r').read()
`

The text seems to be decoded well:
`print (text)`

Gives:

> 'דלקת כבד נגיפית היא דלקת של הכבד , הנגרמת על ידי נגיפים וגורמים שונים .\nהדלקת פוגעת בכבד , הורסת אותו ועלולה להוביל לאשפוז ואף לגרום למוות .\nקיימים לפחות שישה זנים שונים של נגיף דלקת הכבד , לרבות הזנים A , B ו - C .\nהזנים B ו - C נחשבים לזנים הקשים ביותר , הפוגעים במספר הרב ביותר של אנשים .\nדלקת כבד נגיפית C נחשבת למגפה שקטה , מכיוון שהתסמינים מתפתחים בפחות ממחצית מהאנשים הנגועים ופחות prefix=מ - 30 % מהחולים הנגועים בנגיף HCV , יודעים כי הם נושאים את הזיהום .\n80 % מהנפגעים במחלה הופכים להיות חולים כרוניים ואילו 5 % מחולי הפטיטיס C יפתחו סרטן הכבד .\nגורמי prefix=סיכון 1 .\nשימוש במזרקים מזוהמים : גורם הסיכון הנפוץ ביותר לזיהום בדלקת כבד נגיפית מסוג C הנו הזרקת סמים תוך ורידית .\nאנשים המזריקים סמים נמצאים בסיכון גבוה להידבק , זאת משום שצרכני סמים נוטים לחלוק ביניהם את המחטים העלולות להיות מזוהמות בדם הנגוע בנגיף HCV .\n60 % - 80 מכל המשתמשים בסמים תוך ורידיים נגועים בנגיף .\n2 .\nקעקועים ופירסינג : הזיהום עלול לעבור מאדם אחד למשנהו , אם מכון הקעקועים / פירסינג אינו מקפיד על ביצוע חיטוי נאות של הציוד .\nכאשר הציוד מזוהם , חלקיקי דם מיקרוסקופיים עלולים להישאר בצבע ובמחטים שנעשה בהם שימוש בכל סוג של פעולה .\nתסמיניםהתסמינים לדלקת כבד נגיפית C הם בדרך כלל שקטים ועשויים לכלול : • עייפות .\n• אובדן תאבון .\n• כאב בטן .\n• שתן כהה .\n• הצהבת העור או העיניים ( צהבת ) במקרים נדירים .\nרופא יכול לבצע שתי בדיקות דם ספציפיות לנגיף HCV : בדיקת ElISA ( ניסיון ספיגה חיסונית קשור - אנזים ) או בדיקת נוגדנים , ובדיקת PCR ( תגובת שרשרת של אנזים פולים ) .\nאנשים הנמצאים בסיכון ורוצים להיבדק , צריכים לשוחח עם הרופא המטפל שלהם ולבקש בדיקת דם ל - HCV .\nטיפול רפואיכיום , אין חיסון לדלקת כבד נגיפית C .\nהדרך הטובה ביותר להישמר מנגיף ה - HCV הינה הימנעות מפעילויות המסווגות כבעלות סיכון גבוה .\nאם נודע לך שנדבקת בנגיף , עליך לפעול בשיתוף עם הרופא וצוות הטיפול שלך באופן מיידי לפיתוח תוכנית טיפול המתאימה לך .\nהמידע באדיבות חברת שרינג פלאו .\nשבוע המודעות לפטיטיס C ייערך prefix=ב - 17 - 21 ביוני .\nבואו לדבר על זה בפורום כירורגיה של הכבד ודרכי המרה .\n'

But the cloud produced includes only the English words:
`# Create the wordcloud object
wordcloud = WordCloud(width=480, height=480, margin=0).generate(text)
 
# Display the generated image:
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.margins(x=0, y=0)
plt.show()`

The result is: 
![heb_word_cloud](https://user-images.githubusercontent.com/30949452/50545504-70a62680-0c1e-11e9-93be-dd714024f523.png)

I consulted with the previous foreign language support issues but did not find a solution. 
Your help will be appreciated

**Comment by techtonik** [comment]
Looks like a problem with font.

**Comment by amueller** [comment]
Yes, make sure you select a font that has the characters you want to show.

**Comment by ronyarmon** [comment]
Thanks, the issue was fixed after setting up font-path. I'm placing the script in case it may be useful:
`#packages
from wordcloud import WordCloud, STOPWORDS 
import matplotlib.pyplot as plt
from bidi import algorithm as bidialg

#data
text2=open('health_example-liver.txt', 'r').read()

#left_right transform
lr_text=bidialg.get_display(text2)

#path to Hebrew font: DavidCLM-Medium.otf
font_path = '/usr/share/fonts/truetype/culmus/DavidCLM-Medium.otf'

# Create the wordcloud object
wordcloud = WordCloud(font_path=font_path,width=480, height=480, margin=0).generate(lr_text)

# Display the generated image:
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.margins(x=0, y=0)
plt.show()`

![heb_wc_example](https://user-images.githubusercontent.com/30949452/50556276-9cd5ac00-0cdf-11e9-876d-4201ef95841a.png)

**Comment by amueller** [comment]
glad you worked it out!
