### ISSUE TITLE
Missing C++ Build tools on Windows 10

### ISSUE THREAD

**Issue by nwtnsqrd** [amueller/word_cloud#460]
#### Steps/Code to Reproduce

Install wordcloud via pip on Windows.
Example:
```
pip install wordcloud
```

#### Expected Results
Installation completes with no errors.

#### Actual Results

```
c:\users\me\appdata\local\programs\python\python37-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'test_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\wordcloud
    copying wordcloud\color_from_image.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\tokenization.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\wordcloud.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\wordcloud_cli.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\_version.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\__init__.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\__main__.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\stopwords -> build\lib.win32-3.7\wordcloud
    copying wordcloud\DroidSansMono.ttf -> build\lib.win32-3.7\wordcloud
    UPDATING build\lib.win32-3.7\wordcloud/_version.py
    set build\lib.win32-3.7\wordcloud/_version.py to '1.5.0'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
```

#### Versions

```
>>> import platform; print(platform.platform())
Windows-10-10.0.17134-SP0
>>> import sys; print("Python", sys.version)
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.15.4
>>> import matplotlib; print("matplotlib", matplotlib.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'matplotlib'
>>> import wordcloud; print("wordcoud", wordcloud.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'wordcloud'
```

**Comment by amueller** [comment]
I'm not quite sure what the issue is that your reporting. That we should
document that build tools are required to build?
I think the main issue is that we might not be building 32 bit windows
binaries, only 64, which is why you have to build yourself.
We could make that more explicit.
Is there a specific reason why you are on 32 bit?

**Comment by jcfr** [comment]
Happy new year !

> we might not be building 32 bit windows

I confirm that we are not. After sorting this out, if this is still needed, it would be a matter of un-commenting the matrix entries in https://github.com/amueller/word_cloud/blob/master/appveyor.yml

**Comment by nwtnsqrd** [comment]
> I'm not quite sure what the issue is that your reporting. That we should document that build tools are required to build? I think the main issue is that we might not be building 32 bit windows binaries, only 64, which is why you have to build yourself. We could make that more explicit. Is there a specific reason why you are on 32 bit?

I just opened this issue because in the README it says:

Before installing a compiler, report an issue describing the version of python and operating system being used.

**Comment by amueller** [comment]
ah, sorry I didn't realize that is there, make sense.

**Comment by abrajuder** [comment]
I happend to have the same issue installing on Windows 7/64 bits and python 3.7.  I finished build tools instalation but can install wordclouds yet

**Comment by amueller** [comment]
hm that's weird because we're actually building these wheels:
https://pypi.org/project/wordcloud/#files

How did you install @abrajuder ?

**Comment by abrajuder** [comment]
I installed using pip install wordcloud. Finally I had to install build
tools but also change the standard options to include CLI support, VC tools
and also make some tweaking afterwards.

Now I have wordcloud again... I love it

Thanks

Juan.

**Comment by jcfr** [comment]
@abrajuder  What is the output of `import sys; print("Python", sys.version)` in your terminal ?

If you are using Python 32-bit, that would explain the report behavior. And this is the case, would you have the option to use Python 64-bit instead ?

**Comment by abrajuder** [comment]
You are right! I didn´t realized I had installed a 32 bit version last time
I reinstalled it! I will install a 64 bit version of python right away...
thanks!

**Comment by amueller** [comment]
I think the new setup actually build the 32bit wheels: https://pypi.org/project/wordcloud/#files
