### ISSUE TITLE
Regexp from cli

### ISSUE THREAD

**Issue by anishmittal2020** [amueller/word_cloud#464]
I passed the standard regex you used in the code `r"\w[\w']+"` at CLI as follows:

```bash
wordcloud_cli --no_collocations --regexp r"\w[\w']+" --stopwords="${TempStopWordP}" --text "${SourceP}" --width 800 --height 100 --imagefile "${TagP}"
```

But the forst letter of each word disappears from the wordcloud. What should I change here? I tried different quoting like `"r\"\w[\w\']+\""`, but this is not matching any word.

Also, could you please explain the regex. I know that `\w` means `[a-zA-Z0-9]` and `+` is 1 or more. what is `\w'` and `r`?

**Comment by amueller** [comment]
please use stackoverflow for usage questions, like regexp

**Comment by anishmittal2020** [comment]
But is it ok to use `--regexp r"\w[\w']+"` for CLI?
