### ISSUE TITLE
generate_from_frequencies not working

### ISSUE THREAD

**Issue by liron-navon** [amueller/word_cloud#468]
#### Description
`generate_from_frequencies` is not working as expected.
Here is an image:
<img width="1228" alt="screen shot 2019-02-18 at 11 15 34" src="https://user-images.githubusercontent.com/18119833/52944157-13516a80-336f-11e9-8901-59aed7052ac3.png">

#### Steps/Code to Reproduce
I use Jupyter notebook, this is the code:
```
from wordcloud import WordCloud
import matplotlib.pyplot as plt

%matplotlib inline

data = dict([ ('A',20),('B',100),('C',888),('D',14),('E',132) ])

wordcloud = WordCloud(max_font_size=100)

wordcloud.generate_from_frequencies(data)

plt.figure()
plt.imshow(wordcloud)
plt.axis("off")
plt.show()
```

#### Expected Results
The words should be duplicated by their frequencies

#### Actual Results
Each word appears only once, disregarding the frequency

#### Versions
```
Darwin-17.7.0-x86_64-i386-64bit
Python 3.7.1 (default, Dec 14 2018, 13:28:58) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.15.4
matplotlib 3.0.2
wordcoud 1.5.0
```

**Comment by amueller** [comment]
This is the expected behavior. I'm not entirely sure what you're expecting. You can repeat the same word if you want to create a shape but I'm not sure what it is that you're looking for.

**Comment by amueller** [comment]
closing as no reply

**Comment by jack4132** [comment]
I am facing an issue similar to this. import WordCloud was successful but later issued an error with generate_from_frequencies. The error is
 ImportError: The _imagingft C module is not installed
I have already installed this several times using solutions available in stackoverflow. @amueller
