### ISSUE TITLE
Ranking Algorithm

### ISSUE THREAD

**Issue by harelhan** [amueller/word_cloud#469]
Hi @amueller 

I am new to word cloud and saw that there is a way to calculate the relative importance which is further used in wordcloud generation. I wanted to see if there is a document/link you can share where I can read how the relative importance/rank is being calculated.

Thanks a lot for your help.
Hitesh

**Comment by savanmorya** [comment]
If you are asking about word cloud and how it works,
  Word Cloud -  an image composed of words used in a particular text, in which the size of each word 
indicates its frequency or importance.
There are three ways to calculate the importance/rank
**1. Frequency** - Basically number of times that tag has been applied to a single item.
**2. Significance** - size is used to represent the significance of words
**3. Categorization** -Tags are represented in a cloud where  larger tags represent the quantity of content  items in that category

Links: [wikipedia](https://en.wikipedia.org/wiki/Tag_cloud), [Medium blog](https://medium.com/@FILWD/taking-word-clouds-apart-alternative-designs-for-word-clouds-and-some-research-based-guidelines-df91129aa806)

I hope that helps :-)

**Comment by amueller** [comment]
It's "word frequency".
