### ISSUE TITLE
There has a mistake in file "examples/simple.py"

### ISSUE THREAD

**Issue by FrankKirin** [amueller/word_cloud#471]
#### Description

In the file "examples/simple.py" , the variable d will get None at line #15, if "path.dirname(__file__)" is executed.

**Comment by amueller** [comment]
Why? Can you give a minimal example?

**Comment by FrankKirin** [comment]
Like this, I got empty string of variable **d**, could you please explain the code:
![image](https://user-images.githubusercontent.com/23259946/54476443-83e98b00-4838-11e9-87ea-a7fbebd50b6e.png)

**Comment by amueller** [comment]
Looks like it's the empty string, not None (for my version of python). And that's because you're in the same path as the file, so an empty relative path is correct. Why do you think this is a mistake?

**Comment by FrankKirin** [comment]
Yes, I review the code, I found that I will get the empty string and this doesn't matter. I know the code is not an issue. But I am confused about that you use os.getcwd(). Now that you get the absolute path, why you still want to get the relative path? Could tell me the reason, thx:).

**Comment by amueller** [comment]
the ``os.getcwd()`` is a fallback if someone copies and pastes into a shell or jupyter notebook, I think.

**Comment by amueller** [comment]
And the ``os.getcwd()`` only works in this directory, so it's not a particularly good fallback.

**Comment by FrankKirin** [comment]
Well, I see, thanks for your patience:).
