### ISSUE TITLE
wordcloud has a right single quotes in picture

### ISSUE THREAD

**Issue by rawenlei** [amueller/word_cloud#473]
#### Description

![全唐诗+春风](https://user-images.githubusercontent.com/42257971/55218804-21cc5500-523e-11e9-86d2-937b2654308f.jpg)
![全唐诗+春风+1](https://user-images.githubusercontent.com/42257971/55218986-930c0800-523e-11e9-90d6-ff167d3e4b7b.jpg)

When generating a Chinese word cloud, the image has a right single quotation mark.
I can't use lcut because it always fails to correctly participle Chinese tang poetry.
I also can't use '.join(hanlp. Segment ()) because the word cloud is different when i spliced the string.
If I want a word cloud chart that has the same effect as pyecharts wordcloud, I must use str(list), but at this point each word is followed by a close single quotation mark.
Would you like to help me remove the single quotation mark?thank you very much.
rawen 
rawen0623@live.com

#### Steps/Code to Reproduce
def getTxtbyword(fn,word):
    fo=open(fn,'r',encoding='utf-8')
    txt=fo.readlines()#注意按行读取，以方便去除带有符号的标题。
    fo.close()
    ls=''
    for i in txt:
        if '【' in i:
            i='!'+i[i.find('】')+1:].replace(' ','').strip('\n')+i[i.find('【'):i.find('】')+1].strip('\n')#在标题前加上！符号，以用于后续的分隔
            ls+=i
        else:
            ls+=i.strip('\n')
    ms=ls.split('!')
    fl=[]
    for i in ms:#搜索带有指定字的行，并加入列表fl,列表的结构为作者+标题+文章
        if word in i:
            fl.append(i)
    qs = ''
    for i in fl:
        i = i.split('】', 2)[1].replace('，', '').replace('。', '')  #用将此首诗分为两部分并取后部分，前部分是作者+标题，后部分是诗的内容
        qs += i
    return qs

def getWordconnection(fn,word):
    qs=getTxtbyword(fn,word)#qs is a string
    HanLP.Config.ShowTermNature=False
    c=HanLP.segment(qs)
    ls=[]
    for i in c:
        ls.append(i.word)#i.word是单词,i.nature是词性（只有当hanlp.config.showtermnature为false时才有词性。
    mask=imread('tangmap.png')#用wordcloud中的词云
    w=WordCloud(width=1366,height=768,font_path='simkai.ttf',mask=mask,background_color='pink',max_words=400)
    w.generate(str(ls))
    w.to_file('{}+{}.jpg'.format(fn[0:-4],word))

#### Versions
<!--
Please run the following snippet and paste the output below.
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import matplotlib; print("matplotlib", matplotlib.__version__)
import wordcloud; print("wordcoud", wordcloud.__version__)
Windows-10-10.0.17763-SP0
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
NumPy 1.16.2
matplotlib 3.0.3
wordcoud 1.5.0

**Comment by amueller** [comment]
For Chinese you probably need to do all the parsing yourself. You should create a dictionary where the keys are tokens and the values are the counts.


Readability of your code can be greatly improved if you [format](https://help.github.com/articles/creating-and-highlighting-code-blocks/) your code snippets and complete error messages appropriately. For example:

    ```python
    print(something)
    ```
generates:
```python
print(something)
```
And:

    ```pytb
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: No module named 'hello'
    ```
generates:
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'hello'
```
You can edit your issue descriptions and comments at any time to improve readability. This helps maintainers a lot. Thanks!

**Comment by rawenlei** [comment]
thank you for your advice.
i will re-read PEP8 again and notice the code format during copying from pycharm.

**Comment by amueller** [comment]
the issue was more the formatting in github.

**Comment by abdoulsn** [comment]
Hello I've the same issue in french word. what's the problem? NB Some word has right quotes others no.

```
from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt
text = db_codenaf1.clean_nomComplet.values
wordcloud = WordCloud(
    width = 2000,
    height = 1000,
    background_color = 'white',
    stopwords = STOPWORDS).generate(str(text))
#Dsplaying words
fig = plt.figure(
    figsize = (10, 7),
    facecolor = 'k',
    edgecolor = 'k')
plt.imshow(wordcloud, interpolation = 'bilinear')
plt.axis('off')
plt.tight_layout(pad=0)
plt.show()
```

**Comment by amueller** [comment]
Please provide [self-contained example code](https://stackoverflow.com/help/mcve), including imports and data (if possible), so that other contributors can just run it and reproduce your issue. Ideally your example code should be minimal.
