### ISSUE TITLE
Consider adding example code for "Getting fancy with some colors: " example

### ISSUE THREAD

**Issue by matkoniecz** [amueller/word_cloud#476]
https://github.com/amueller/word_cloud/blob/master/examples/parrot.png is exactly what I want to achieve and this example seems to be published only as an image, without source code example

**Comment by matkoniecz** [comment]
dupe of  #352

**Comment by amueller** [comment]
The original image might have been copyright protected or I just can't find
it any more. If you find a nice creative Commons image of a parrot I can
try to recreate it.

**Comment by amueller** [comment]
see #506
