### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'repeat'

### ISSUE THREAD

**Issue by linrl3** [amueller/word_cloud#478]
For the most basic example in the blog:
```python
import numpy as np
import matplotlib.pyplot as plt
from wordcloud import WordCloud

text = "square"

x, y = np.ogrid[:300, :300]

mask = (x - 150) ** 2 + (y - 150) ** 2 > 130 ** 2
mask = 255 * mask.astype(int)


wc = WordCloud(background_color="white", repeat=True, mask=mask)
wc.generate(text)

plt.axis("off")
plt.imshow(wc, interpolation="bilinear")
plt.show()
```
I'm using mac os with anaconda python 3.5.6

**Comment by amueller** [comment]
Hey. How did you install wordcloud and which version are you using?

**Comment by jcfr** [comment]
After installing wordclound and matplotlib with `conda install -c conda-forge wordcloud matplotlib`, I am not able to reproduce the issue.

Could you check with version of wordcloud you are using ?

**Comment by jcfr** [comment]
To check the version:

```python
import wordcloud
print(wordcloud.__version__)
```

**Comment by linrl3** [comment]
I use conda install -c conda-forge wordcloud. 
Version is the default one after I install it.

**Comment by amueller** [comment]
@linrl3 are you sure you're using that environment when running your script? maybe put ``print(wordcloud.__version__)`` into the example that's failing.

**Comment by linrl3** [comment]
@amueller Yeah I'm running under ananconda python 3.5.6. And I also print the wordcloud version which is 1.4.1.

**Comment by amueller** [comment]
It might be that we didn't build a new package for 3.5 for this version.
Try updating to 1.5.0, and if you can't do that in your existing environment, create a new conda environment with a more recent version of python, and install 1.5.0 in that.

**Comment by linrl3** [comment]
@amueller Thank you for your answer. Problem solved. Finally I uninstall conda because it's kind of messy to manage python package. And I use pip now.
