### ISSUE TITLE
I can't install worldcloud with pip

### ISSUE THREAD

**Issue by kmahsi** [amueller/word_cloud#479]
I'm trying to install worldcloud with pip like this:
`pip install worldcloud`
But I get this error:

>  Could not find a version that satisfies the requirement worldcloud (from versions: )
No matching distribution found for worldcloud

I'm using Linux
And this is my pip:

> pip 19.0.3 from /home/kamran/workspace/UT/env/lib/python3.5/site-packages/pip (python 3.5)

**Comment by amueller** [comment]
Hm that's odd. @jcfr any idea?
Can you provide the output of ``uname -a``? Are you maybe using 32bit python?

**Comment by arame3333** [comment]
I had the same problem and then I discovered that the name of the package is wordcloud not worldcloud.

**Comment by amueller** [comment]
@arame3333 thanks I totally didn't register the typo!

**Comment by jcfr** [comment]
Good catch.
