### ISSUE TITLE
Problem Installing in Windows 7

### ISSUE THREAD

**Issue by pybokeh** [amueller/word_cloud#48]
Here's my conda virtual environment package list:
cython                    0.22                     py34_0
django                    1.7.7                     <pip>
image                     1.3.4                     <pip>
numpy                     1.9.2                    py34_0
pillow                    2.7.0                     <pip>
pip                       6.0.8                    py34_0
python                    3.4.3                         0
setuptools                14.3                     py34_0
wheel                     0.24.0                    <pip>

with Python version 3.4.3

I then tried to install wordcloud using:
pip install git+git://github.com/amueller/word_cloud.git

Here's the last 3 lines of my error message:
    
    running build_ext
    building 'wordcloud.query_integral_image' extension
    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat).

If I try to install using plain-vanilla pip or easy_install, I get the following error:
ValueError: 'wordcloud/query_integral_image.pyx' doesn't match any files

I checked the [unofficial windows binaries](http://www.lfd.uci.edu/~gohlke/pythonlibs/), but don't see pre-compiled binaries available for Windows.

**Comment by amueller** [comment]
Hi. Well do you have visual studio installed (or any other C compiler)?
The pip error is a bit weird, but since the package uses cython, you will not get around installing a c compiler. Sorry, I don't have the time to maintain windows binaries.

**Comment by pybokeh** [comment]
No problem.  Unfortunately at work, I'm on a very restricted environment
and so I can not install Visual Studio environment.  Maybe some day.
Thanks anyways.

**Comment by amueller** [comment]
You can create a binary (on another box) and upload it to binstar.
Sorry, I'm busy with scikit-learn and this is just a weekend hack ;)
