### ISSUE TITLE
wordcloud is not displying any thing for urdu language.

### ISSUE THREAD

**Issue by aziyamehboob** [amueller/word_cloud#481]
i am trying to display wordcloud for my topics but it is not showing any word in the cloud. i am using urdu language any my topics are as 
[(0, '0.068*"عدالت" + 0.066*"حکومت" + 0.053*"الیکشن" + 0.049*"مقدمے" + 0.049*"سربراہ" + 0.039*"سماعت" + 0.030*"مذہبی جماعتوں" + 0.030*"دھرنے" + 0.029*"خلاف" + 0.028*"حک..
i am not getting any idea how to solve this problem 
![Figure_1](https://user-images.githubusercontent.com/6000110/56793336-40b20d00-6825-11e9-808d-74176be8dfb5.png)

**Comment by amueller** [comment]
See #238. You need to use a font that supports the language.
