### ISSUE TITLE
requirements seemingly not met?

### ISSUE THREAD

**Issue by erobert98** [amueller/word_cloud#483]
So I pip install wordcloud. No worries. 

On my first attempt of running a simple word cloud i get the following error.
```

>>> from wordcloud import WordCloud
>>> wd = WordCloud().generate(P.text_comment)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "c:\users\emile\codes\4chans\venv\lib\site-packages\wordcloud\wordcloud.py", line 300, in __init__
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
```

From what i read in some other issues, im not even supposed to be using matplotlib, and its not in the requirements, whatever fine ill install that too and see what happens.

I try again after installing matplotlib, and get the following error.

```
>>> wd = WordCloud().generate(P.text_comment)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "c:\users\emile\codes\4chans\venv\lib\site-packages\wordcloud\wordcloud.py", line 317, in __init__
    self.color_func = color_func or colormap_color_func(colormap)
  File "c:\users\emile\codes\4chans\venv\lib\site-packages\wordcloud\wordcloud.py", line 100, in __init__
    import matplotlib.pyplot as plt
  File "c:\users\emile\codes\4chans\venv\lib\site-packages\matplotlib\pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "c:\users\emile\codes\4chans\venv\lib\site-packages\matplotlib\pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "C:\Users\emile\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\emile\codes\4chans\venv\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "c:\users\emile\codes\4chans\venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 5, in <module>
    import tkinter as Tk
ModuleNotFoundError: No module named 'tkinter'
```
So whats going on?

**Comment by amueller** [comment]
Actually, matplotlib is in the requirements now and should be automatically installed. Odd.

The problem with TK is a problem of your matplotlib configuration and not having a backend.
A google search finds several solutions:
https://stackoverflow.com/questions/36327134/matplotlib-error-no-module-named-tkinter

**Comment by erobert98** [comment]
Yeh not sure what happened with matplotlib not being installed but its not really an issue.

I found that solution but it seems this issue arises very commonly in users of this library. Maybe a notice somewhere in your readme would clear this confusion up?
I'm going to go ahead and close this issue.

Thanks for the awesome library btw!

**Comment by amueller** [comment]
Hmmm that hasn't come up before, maybe because people use conda? It's an issue with the pip install of matplotlib it seems. Which version did you install and what's your version of python and how did you install it? This should be fixed in matplotlib.

**Comment by erobert98** [comment]
pip install wordcloud then that error when i tried using it so i did pip
install matplotlib

I installed the most recent matplotlib (3.0.3). Pip is an old version,
10.0.1 and python 3.7.
Maybe something to do with 10.0.1?

I installed python through the
https://www.python.org/downloads/release/python-370/ and I'm running it on
windows.

from what ive gathered, you need a pretty specific download of python to
get TK installed like from activestate.com. I didnt want to go that route
since im working on web apps and im not sure heroku will be compatible/the
workaround to not use TK is simple enough.

For my case, in deployment ill just fork a version of matplotlib and use
the edited version with the specified backend in my requirements file.

**Comment by amueller** [comment]
you definitely don't need to change your matplotlib, you can just have a matplotlib.rc file that specifies your preferred backend.

**Comment by erobert98** [comment]
Wait sorry i mis-remembered the change i made, i actually did the
matplotlib.use('agg') change in the wordcloud.py file at line 100 in class
colormap_color_func().
Ill look into your suggestion as well though.

And it appears the people at matplotlib are aware of the issue arising and
were supposed to introduce a change to the backend fallback behaviour in
3.0.0 but apparently not. Ill post over there for some clarification.

https://github.com/matplotlib/matplotlib/issues/9017#issuecomment-422400771

**Comment by amueller** [comment]
I opened https://github.com/matplotlib/matplotlib/issues/14142
and there's also https://github.com/matplotlib/matplotlib/issues/14121

I feel like this has been discussed before recently...
