### ISSUE TITLE
Yelp demo on Kaggle - Very long time to render Wordcloud

### ISSUE THREAD

**Issue by thoughtsociety** [amueller/word_cloud#484]
#### Description

The code from the [Kaggle kernel](https://www.kaggle.com/kernels/scriptcontent/10578822/notebook) took 10 minutes to complete execution

yelp_allstars_text = yelp_text_allstars['Text'].values

wordcloud = WordCloud(
    width = 3000,
    height = 2000,
    background_color = 'black',
    stopwords = STOPWORDS).generate(str(yelp_allstars_text))

fig = plt.figure(
    figsize = (10, 7),
    facecolor = 'k',
    edgecolor = 'k')
plt.imshow(wordcloud, interpolation = 'bilinear')
plt.axis('off')
plt.tight_layout(pad=0)

But it did complete and render the wordcloud.

Should it take this long:

Jupyter notebook on 2014 quadcore osx-High Sierra.

**Comment by amueller** [comment]
yes, depending on the number of words. If the resolution is that high it might take that long. You can get a faster approximation by using ``scale``. Or you can limit the number of words with ``min_font_size`` or ``max_words``.
