### ISSUE TITLE
how to install in windows 32?

### ISSUE THREAD

**Issue by wangyizhen** [amueller/word_cloud#49]
C:\Users\Administrator\Desktop\word_cloud-master>python setup.py install
d:/program files/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: build\temp.win32-2.7\Release\wordcloud\query_integral_image.o: bad reloc address 0x0 in section `.data'
collect2.exe: error: ld returned 1 exit status
dllwrap: gcc exited with status 1
error: command 'dllwrap' failed with exit status 1
how can I solue it?

**Comment by amueller** [comment]
Sorry for the late reply. I have no idea what is happening here... have you tried google / stackoverflow?
