### ISSUE TITLE
ModuleNotFoundError: No module named 'wordcloud.query_integral_image'，help！！！

### ISSUE THREAD

**Issue by Jyeonha** [amueller/word_cloud#491]
#### Description
I am a completely new pythoner, I just want to plot some beautiful pictures for my report. I come accross some problem when studying "wordcloud".

I tried to install "wordcloud" under pycharm and it said I need to install visual c++ 14, I downloaded and installed but it still showed the same message. I then download the whl file from https://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud, change the "whl" to zip, then unzip, copy the file "wordcloud" and "wordcloud-1.5.0.dist-info" to python\Lib\site-packages. Then went to pycharm---file---settings---project interpreter add the "wordcloud", after a few moment,  it finally said installed successfully!!!

Then I tried to run the following code:

from wordcloud import WordCloud
f=open(r'D:\Data visualization\practice\mechtronics.txt', 'r').read()
wordcloud=WordCloud(background_color='white', width=1000, height=860, margin=2).generate(f)

import matplotlib.pyplot as plt
plt.imshow(wordcloud)
plt.axis('off')
plt.show()
wordcloud.to_file('test.png')

T-T
I got the error said:

Traceback (most recent call last):
  File "D:/Data visualization/practice_wordcloud/mechatronics.py", line 1, in <module>
    from wordcloud import WordCloud
  File "D:\soft\python\lib\site-packages\wordcloud\__init__.py", line 1, in <module>
    from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
  File "D:\soft\python\lib\site-packages\wordcloud\wordcloud.py", line 25, in <module>
    from .query_integral_image import query_integral_image
ModuleNotFoundError: No module named 'wordcloud.query_integral_image'

I have no idea how to fix it, hope anyone who had similar problem can give me some clue! Thanks!

**Comment by cgohlke** [comment]
> I then download the whl file from https://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud, change the "whl" to zip, then unzip, copy the file "wordcloud" and "wordcloud-1.5.0.dist-info" to python\Lib\site-packages.

Make sure to use the wheel that matches your Python version. E.g. `wordcloud-1.5.0-cp37-cp37m-win32.whl` is for Python 3.7, 32-bit.

**Comment by Jyeonha** [comment]
> > I then download the whl file from https://www.lfd.uci.edu/~gohlke/pythonlibs/#wordcloud, change the "whl" to zip, then unzip, copy the file "wordcloud" and "wordcloud-1.5.0.dist-info" to python\Lib\site-packages.
> 
> Make sure to use the wheel that matches your Python version. E.g. `wordcloud-1.5.0-cp37-cp37m-win32.whl` is for Python 3.7, 32-bit.

Thank you for the reply, it may sounds stupid, but how to know my python version?
I think it should be 3.7.something.....but not sure wether it is 32-bit or 64-bit.

**Comment by amueller** [comment]
```
python --version
```

**Comment by Jyeonha** [comment]
Thanks!!!!!!
After checking the whl version, I found that I made a stupid mistake, I downloaded cp36, which I should use cp37. That matches my Python version. I had been annouyed for whole day, can't believe that we can figure it out that soon, this is a really friendly community! I kinda giving up python, but I feel a little bit confident now.

**Comment by Jyeonha** [comment]
> ```
> python --version
> ```

Thanks!!! We figured ot out, just like you said, it had something to do with the whl version.
Didn't expect here is so responsive, thank you for your time again!

**Comment by amueller** [comment]
@cgohlke do you have a script that alerts you whenever your repo is mentioned on github? I'm also fascinated by your quick reply, in particular in a project you're not involved in. That's some dedication!

**Comment by jcfr** [comment]
@Jyeonha  it should be possible to install wordcloud by simply doing `pip install wordcloud`. Which version of pycharm are you using ? And on which platform ?

**Comment by Jyeonha** [comment]
> @Jyeonha it should be possible to install wordcloud by simply doing `pip install wordcloud`. Which version of pycharm are you using ? And on which platform ?

Yes! That's would be my next question, thank you for bring that out.
I am using pycharm community 2019.2, by platform, I think you are refering Windows 10, right?

I saw a lot of people mentioned this way to install wordcloud, but when I run the command on .py file, it said "SyntaxError: invalid syntax"
I see people are doing this on "cmd" window, so I tried, it said "pip is not an internal or external command, nor is it a runnable program", I tried to run this everywhere, including c disk and the route to pip.exe. When I type pip show pip, it shows the information for pip though.

It doesn't seem to work, then I thought maybe this way is too advanced for me, I was like opened cmd window for the first time in my life (laugh to tear).

**Comment by Meera2512** [comment]
> @cgohlke Thanks!!!!!!
> After checking the whl version, I found that I made a stupid mistake, I downloaded cp36, which I should use cp37. That matches my Python version. I had been annouyed for whole day, can't believe that we can figure it out that soon, this is a really friendly community! I kinda giving up python, but I feel a little bit confident now.

Thanks for posting this, you saved me!
