### ISSUE TITLE
No module named 'wordcloud.query_integral_image'

### ISSUE THREAD

**Issue by abdoulsn** [amueller/word_cloud#497]
#### Description
Hello I've installed wordcloud  (wordcloud-1.5.0-py36hfa6e2cd_1000.tar.bz2) offline as not able to do it by conda (prooxy!) when I import it, i got this error.

Conda version :  4.7.11

`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-dc1828f2a80e> in <module>
----> 1 import wordcloud

~\AppData\Local\Continuum\anaconda3\lib\site-packages\wordcloud\__init__.py in <module>
----> 1 from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
      2                         get_single_color_func)
      3 from .color_from_image import ImageColorGenerator
      4 
      5 __all__ = ['WordCloud', 'STOPWORDS', 'random_color_func',

~\AppData\Local\Continuum\anaconda3\lib\site-packages\wordcloud\wordcloud.py in <module>
     23 from PIL import ImageFont
     24 
---> 25 from .query_integral_image import query_integral_image
     26 from .tokenization import unigrams_and_bigrams, process_tokens
     27 

ModuleNotFoundError: No module named 'wordcloud.query_integral_image'`

**Comment by abdoulsn** [comment]
@amueller  any comment on this issues. I'm stuck since to use it. Thaks

**Comment by amueller** [comment]
did you resolve your issue? How did you install the module?
