### ISSUE TITLE
Citation preference

### ISSUE THREAD

**Issue by bersavosh** [amueller/word_cloud#498]
Hi there,

Thanks for the wonderful pacakge. I was wondering if there is any preferred method to cite/acknowledge use of this package in an article/presentation?

**Comment by amueller** [comment]
I think you can just cite the package or repository. There's no standard citation or paper describing the package (though I guess I could make one in JOSS).

**Comment by LuayD** [comment]
No issue, but wanted to say that this is a great package!!! I will acknowledge using it!

**Comment by bersavosh** [comment]
I think something in JOSS or some other service that would allow proper citation (and tracking reach of the package) would be really nice. Nevertheless, thanks for the response @amueller :-)

**Comment by abubelinha** [comment]
So finally what's the answer to this question?
> I think you can just cite the package or repository

That is still unclear to me. Would you mind dropping a line with your preferred way to do it? (not sure if that includes or not author, year ...).

BTW [github now provides a citation system](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) by simply adding a CITATION.cff file to repository root.
That would be easy for you to implement, I think

Thanks a lot for this package!
@abubelinha

**Comment by amueller** [comment]
I'll add the citation file soon, but you can just cite the package itself, with me as author. Adding a year seems non-sensical, but I guess I published it in 2012, so that would be the year.

**Comment by abubelinha** [comment]
And in documentation says "© Copyright 2020, Andreas Mueller".
So it's better for you to define a citation string in order to avoid inconsistent citations (and also to avoid being asked).

**Comment by amueller** [comment]
actually that seems to refer to the last time the docs were pushed, it seems I need to fix something there.
