### ISSUE TITLE
Wordcloud 1.5.0 fails to install with pip under Windows 10 Python 3.7.4

### ISSUE THREAD

**Issue by LegolasVzla** [amueller/word_cloud#499]
#### Description

I'm trying to install wordcloud 1.5.0 with pip under Windows 10 and Python 3.7.4, but it fails with the below error:

`  ERROR: Command errored out with exit status 1:
   command: 'c:\users\technifiser\desktop\<path_to_my_virtualenv>\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TECHNI~1\\AppData\\Local\\Temp\\pip-install-dc4sve7n\\wordcloud\\setup.py'"'"'; __file__='"'"'C:\\Users\\TECHNI~1\\AppData\\Local\\Temp\\pip-install-dc4sve7n\\wordcloud\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\TECHNI~1\AppData\Local\Temp\pip-wheel-fxymokpl' --python-tag cp37
       cwd: C:\Users\TECHNI~1\AppData\Local\Temp\pip-install-dc4sve7n\wordcloud\
  Complete output (28 lines):
  c:\users\technifiser\appdata\local\programs\python\python37-32\Lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'test_requires'`

`c:\users\technifiser\appdata\local\programs\python\python37-32\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory`

I tried in the Microsoft Visual Studio 2019 shell and also in Windows PowerShell.

#### Steps/Code to Reproduce

`pip install wordcloud==1.5.0`

#### Expected Results

Install wordcloud 1.5.0

#### Actual Results

`
Collecting wordcloud==1.5.0
  Using cached https://files.pythonhosted.org/packages/d4/95/d260ce89441d1f28192fa5a0a016f547829517b11cabe0079ab91c56f6cd/wordcloud-1.5.0.tar.gz
Requirement already satisfied: numpy>=1.6.1 in c:\users\<path_to_my_virtualenv>\env\lib\site-packages (from wordcloud==1.5.0) (1.17.1)
Requirement already satisfied: pillow in c:\users\<path_to_my_virtualenv>\env\lib\site-packages (from wordcloud==1.5.0) (6.1.0)
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\<path_to_my_virtualenv>\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TECHNI~1\\AppData\\Local\\Temp\\pip-install-2by5c5s8\\wordcloud\\setup.py'"'"'; __file__='"'"'C:\\Users\\TECHNI~1\\AppData\\Local\\Temp\\pip-install-2by5c5s8\\wordcloud\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\TECHNI~1\AppData\Local\Temp\pip-wheel-mnd6yslk' --python-tag cp37
       cwd: C:\Users\TECHNI~1\AppData\Local\Temp\pip-install-2by5c5s8\wordcloud\
  Complete output (28 lines):
  c:\users\technifiser\appdata\local\programs\python\python37-32\Lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'test_requires'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\wordcloud
  copying wordcloud\color_from_image.py -> build\lib.win32-3.7\wordcloud
  copying wordcloud\tokenization.py -> build\lib.win32-3.7\wordcloud
  copying wordcloud\wordcloud.py -> build\lib.win32-3.7\wordcloud
  copying wordcloud\wordcloud_cli.py -> build\lib.win32-3.7\wordcloud
  copying wordcloud\_version.py -> build\lib.win32-3.7\wordcloud
  copying wordcloud\__init__.py -> build\lib.win32-3.7\wordcloud
  copying wordcloud\__main__.py -> build\lib.win32-3.7\wordcloud
  copying wordcloud\stopwords -> build\lib.win32-3.7\wordcloud
  copying wordcloud\DroidSansMono.ttf -> build\lib.win32-3.7\wordcloud
  UPDATING build\lib.win32-3.7\wordcloud/_version.py
  set build\lib.win32-3.7\wordcloud/_version.py to '1.5.0'
  running build_ext
  building 'wordcloud.query_integral_image' extension
  creating build\temp.win32-3.7
  creating build\temp.win32-3.7\Release
  creating build\temp.win32-3.7\Release\wordcloud
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.20.27508\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\technifiser\appdata\local\programs\python\python37-32\include -Ic:\users\technifiser\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.20.27508\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.20.27508\include" /Tcwordcloud/query_integral_image.c /Fobuild\temp.win32-3.7\Release\wordcloud/query_integral_image.obj
  query_integral_image.c
  c:\users\technifiser\appdata\local\programs\python\python37-32\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.20.27508\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
`
` ----------------------------------------
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud
  Running setup.py install for wordcloud ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\<path_to_my_virtualenv>\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TECHNI~1\\AppData\\Local\\Temp\\pip-install-2by5c5s8\\wordcloud\\setup.py'"'"'; __file__='"'"'C:\\Users\\TECHNI~1\\AppData\\Local\\Temp\\pip-install-2by5c5s8\\wordcloud\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\TECHNI~1\AppData\Local\Temp\pip-record-boc85kwk\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\<path_to_my_virtualenv>\env\include\site\python3.7\wordcloud'
         cwd: C:\Users\TECHNI~1\AppData\Local\Temp\pip-install-2by5c5s8\wordcloud\
    Complete output (28 lines):
    c:\users\technifiser\appdata\local\programs\python\python37-32\Lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'test_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\wordcloud
    copying wordcloud\color_from_image.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\tokenization.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\wordcloud.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\wordcloud_cli.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\_version.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\__init__.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\__main__.py -> build\lib.win32-3.7\wordcloud
    copying wordcloud\stopwords -> build\lib.win32-3.7\wordcloud
    copying wordcloud\DroidSansMono.ttf -> build\lib.win32-3.7\wordcloud
    UPDATING build\lib.win32-3.7\wordcloud/_version.py
    set build\lib.win32-3.7\wordcloud/_version.py to '1.5.0'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\wordcloud
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.20.27508\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\technifiser\appdata\local\programs\python\python37-32\include -Ic:\users\technifiser\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.20.27508\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.20.27508\include" /Tcwordcloud/query_integral_image.c /Fobuild\temp.win32-3.7\Release\wordcloud/query_integral_image.obj
    query_integral_image.c
    c:\users\technifiser\appdata\local\programs\python\python37-32\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.20.27508\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\<path_to_my_virtualenv>\env\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\TECHNI~1\\AppData\\Local\\Temp\\pip-install-2by5c5s8\\wordcloud\\setup.py'"'"'; __file__='"'"'C:\\Users\\TECHNI~1\\AppData\\Local\\Temp\\pip-install-2by5c5s8\\wordcloud\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\TECHNI~1\AppData\Local\Temp\pip-record-boc85kwk\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\<path_to_my_virtualenv>\env\include\site\python3.7\wordcloud' Check the logs for full command output.
`

#### Versions

```
>>> import platform; print(platform.platform())
Windows-10-10.0.17134-SP0
>>> import sys; print("Python", sys.version)
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.17.1
>>> import matplotlib; print("matplotlib", matplotlib.__version__)
matplotlib 3.0.3

```

**Comment by amueller** [comment]
Hm there's no 32bit wheels, it looks like. You're using 32bit python, right? Any particular reason for that?

**Comment by LegolasVzla** [comment]
None reason, I uninstalled my 32 bit python and then install 64 bit python and it worked. Thanks

**Comment by amueller** [comment]
Cool. I don't think we want to expand our build matrix too much unless this is a common issue, so I'll close. Glad it worked out for you.
