### ISSUE TITLE
word cloud is not defined.

### ISSUE THREAD

**Issue by melvinwevers** [amueller/word_cloud#50]
Hi,

I get this error:
` wordcloud.fit_words`
 `NameError: name 'wordcloud' is not defined`

What could be wrong? The install seems to be correct.

**Comment by amueller** [comment]
Did you import it?

**Comment by melvinwevers** [comment]
Yes.
Installed it and imported it.

**Comment by amueller** [comment]
can you give the exact code please?

**Comment by melvinwevers** [comment]
from os import path
import matplotlib.pyplot as plt
from wordcloud import WordCloud



final_topics = open("yourfile.txt")




curr_topic = 0
for line in final_topics:
    #line = line.strip()[line.rindex("'") + 2:]
    scores = [float(x.split("*")[0]) for x in line.split(" + ")]
    words = [x.split("*")[1] for x in line.split(" + ")]
    freqs = []
    wordcloud.fit_words
    
    print(words)

    for word, score in zip(words, scores):
        freqs.append((word, score))
    elements = wordcloud.fit_words(freqs, width=120, height=120)
    wordcloud.draw(elements, "gs_topic_%d.png" % (curr_topic),
                   width=120, height=120)
    curr_topic += 1
final_topics.close()

**Comment by amueller** [comment]
you are not instantiating a WordCloud object. Somewhere there should be ``wordcloud = WordCloud()``
