### ISSUE TITLE
French stopwords [question]

### ISSUE THREAD

**Issue by abdoulsn** [amueller/word_cloud#502]
I noticed that wordcloud o not stripe out frenc stopwords, when I check STOPWORDS in repo git I saw only english one. Did this mean there no french one?

**Comment by yavalvas** [comment]
I see that there is an ability to specify another file with line separated stop words:
`wordcloud_cli --text mytext.txt --stopwords stopwords.txt --imagefile wordcloud.png`

You can find or generate the file stopwords.txt e.g. from [stop-words](https://pypi.org/project/stop-words/) library.

**Comment by abdoulsn** [comment]
> 
> 
> I see that there is an ability to specify another file with line separated stop words:
> `wordcloud_cli --text mytext.txt --stopwords stopwords.txt --imagefile wordcloud.png`
> 
> You can find or generate the file stopwords.txt e.g. from [stop-words](https://pypi.org/project/stop-words/) library.

Thanks i've finaly used another method.
