### ISSUE TITLE
Apostrophe added to the end of every word in word_cloud

### ISSUE THREAD

**Issue by T4rQu1N** [amueller/word_cloud#505]
#### Description
So I'm using the wordcloud package on some data to try and produce an interesting infographic, as you do. However, no matter the method, the resulting word cloud always has an apostrophe after the word. I have input some dummy data to test both methods however, the results are the same. Do you get the same odd image as a result? What is going on?

Example:
```python
from wordcloud import WordCloud
import string

test = {'a':12, 'b':10, 'c':1, 'd':5}
test2 = ['a','b','c', 'c', 'd', 'd','d']
# Generate a word cloud image
text = str(test)
print (text)
wordcloud = WordCloud().generate(text)

# Display the generated image:
# the matplotlib way:
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")

# lower max_font_size
wordcloud = WordCloud(max_font_size=40).generate(str(test2))
plt.figure()
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()
```

**Comment by T4rQu1N** [comment]
Hi amueller,
I'm feeding it a long list of words, i.e. tokens from the nltk package. No idea why an apostrophe is added to the end of every word, however a friend solved my issue by adding the .replace(" ' ",' ') function to the list within generate().
 
Perhaps the wordcloud function is not meant to take a list of words as an input, but it really should! 

Thanks for your speedy reply!

**Comment by amueller** [comment]
I'm not sure what you mean by "but it should". There's two input formats: a dictionary of counts and a single string.
It sounds like what you're doing is not what your example shows.
The most obvious way to solve the issue would be to do ``wc.generate(" ".join(list_of_strings))``

**Comment by amueller** [comment]
It's not "an apostrophe is added to the end of every word" as you said. **you** created a string where each word is bounded by apostrophes by casting a list to a string. The default regex assumes a trailing apostrophe can be within a word (so it can show "doesn't") but it doesn't allow initial apostrophes. So if you pass ``"'this' 'is' 'a' 'weird' 'string'"`` it will extract ``"this'", "is'", "a'", "weird'", "string'"``.

**Comment by T4rQu1N** [comment]
Sorry, by it should, I meant that wordclouds are common visualisations for people doing natural language processing, so accepting tokenized lists (array) of individual words (like those outputted by nltk) would be a sensible and logical capability for the package to have. I fully accept that one might be able to .join a list together in order to create one long string, but I tried this and for my own purposes this didn't work either.

**Comment by amueller** [comment]
basically this is the offending line:
```python
text = str(test)
```
in which you create the apostrophes.
If your replace that by
```python
text = " ".join(test)
```
then everything will be fine.

**Comment by amueller** [comment]
why doesn't that work for your purpose?

**Comment by T4rQu1N** [comment]
I think it didn't work because the list of words that I use in my actual program come from a filtered lambda function, so the list ended up coming out as an object of type filter, rather than the tokenised words. I'm afraid I'm a bit of a noob at python, and am learning as I go, so what might seem obvious to an experienced coder totally passes me by :).

In any case, the .replace method on the list worked a treat. No idea if this will cause issues in the future, but I thought it odd that an apostrophe showed up in the first place!

**Comment by amueller** [comment]
well you can go to stackoverflow with your issues maybe. If I'd support list of strings it would be just doing a " ".join() internally. And that's really the preferred solution.
And as i said, you added the apostrophes.

**Comment by T4rQu1N** [comment]
Fair enough. I did try the .join method and it didn't work, so perhaps my original code is not implemented in a way for which this package intends. I've seen a few posts from other people with similar issues, so hopefully this thread will give them a workaround too.

**Comment by amueller** [comment]
Can you point me towards their posts? And if you have a way to reproduce
the issue you're having I'm happy to look into it.

**Comment by T4rQu1N** [comment]
Hi again,

Having re-read your replies I now understand where the issue is and how it occurs. Consequently, I've managed to get your method to work using .join to detokenise the list (into one long string). Many thanks for the help!

This was one of the other posts that had a similar issue. [https://stackoverflow.com/questions/44810269/the-wordcloud-formed-is-showing-apostrophe-sign?noredirect=1&lq=1](url) . I think these issues occur from people following a similar method of tokenizing words for sentiment analysis etc, with a word cloud being a useful visualisation of tokenized words. Perhaps like me they aren't quite competent enough with Python to diagnose where and why the issue happens, thus the description of the problem doesn't quite capture what is going on.

Thanks again!

**Comment by amueller** [comment]
The issue you linked to is similar but not the same. There the user uses a counter, which is unnecessary. ``WordCloud`` does the counting internally. If you have counts, you need to use ``generate_from_frequencies``.
If you have counts of tokens you can also use that method.

**Comment by MahimasDS** [comment]
Hiya,

I'm not sure if you found the answer by I had the same issue and I was able to resolve it with this req = ','.join(list) and then str(list) in the word cloud generate
