### ISSUE TITLE
single_word.py terminates

### ISSUE THREAD

**Issue by ssandfeld** [amueller/word_cloud#508]
#### Description
The examples fail to run, e.g., single_word.py

#### Steps/Code to Reproduce
After having `pip install .`ed the package and all dependencies, running any example, e.g., `python single_word.py` aborts.

#### Expected Results
No error is thrown. 

#### Actual Results
```
❯ python single_word.py 
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

#### Versions
```
>>> import platform; print(platform.platform())
Linux-5.3.7-200.fc30.x86_64-x86_64-with-fedora-30-Thirty
>>> import sys; print("Python", sys.version)
Python 3.7.5 (default, Oct 17 2019, 12:09:47) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.17.2
>>> import matplotlib; print("matplotlib", matplotlib.__version__)
matplotlib 3.1.1
>>> import wordcloud; print("wordcoud", wordcloud.__version__)
wordcoud 1.5.0.post52+gf288fd5
```

**Comment by amueller** [comment]
Thanks for the report. that is very odd.
Do you know if the pip install installed a wheel or did it compile locally?

**Comment by amueller** [comment]
@jcfr can you help me interpret the version string?

**Comment by ssandfeld** [comment]
pip install installed a wheel; I cloned the repo today.

**Comment by jcfr** [comment]
> can you help me interpret the version string?

`wordcoud 1.5.0.post52+gf288fd5` indeed means that version https://github.com/amueller/word_cloud/commit/f288fd5 was installed locally.

**Comment by amueller** [comment]
@ssandfeld ah, that means you compiled locally. There are no wheels for the dev build.
@jcfr thanks! I got confused by the ``g`` when copy&pasting the hash.. d'oh.

**Comment by amueller** [comment]
@ssandfeld it's likely that something went wrong when compiling. But it's hard to say what.
Maybe try running ``python setup.py build_ext -i`` which should provide you with more output than the ``pip install -e .``

**Comment by jcfr** [comment]
> I got confused by the g when copy&pasting the hash.. d'oh.

The `g` is to indicate it is a git tag. More details at https://github.com/warner/python-versioneer#styles

**Comment by ssandfeld** [comment]
Well, the problem seems to be related to the pyenv virtual environment into which I installed the package. `pip install`ing the package without a pyenv into my user's home directory solves the problem (having exactly the version numbers for python, numpy etc). Interesting, I never had a similar problem with an pyenv...

**Comment by amueller** [comment]
Hm that is a bit mysterious. Not sure if I can help with that...

**Comment by ssandfeld** [comment]
Yes, I guess this is not a bug of wordcloud. Thanks for the quick responses.
