### ISSUE TITLE
Font size is not proportional to frequency

### ISSUE THREAD

**Issue by reflect9** [amueller/word_cloud#51]
Hello, 

I was expecting that each word's font size is proportional to count (if feasible).   
However, the fit_word method simply sets it MAX_SIZE and decreases by 1.

**Comment by amueller** [comment]
Actually it tries to scale the size logarithmically with frequency (with some heuristic that looked good): https://github.com/amueller/word_cloud/blob/master/wordcloud/wordcloud.py#L177
"if feasible" that is if it can draw it this big.
As my approach to wordclouds defines the size of the canvas before doing the placement, I don't think any other method is possible.

Do you have an idea how to be more faithful to the actual counts?

**Comment by reflect9** [comment]
Oh I'm sorry.  
I misunderstood that the log-based setting is active when rankonly is True.     
I guess it would be better to give an option to keep relative font size as consistent as possible.  To do that, it needs to either change canvas size dynamically or update size of processed words.   

I appreciate your effort for sharing the library.

**Comment by amueller** [comment]
both approaches would in principle be possible. Resizing the canvas would mean that the result is not as densely packed as it currently is, which I think is a nice feature of this implementation.
If you like, feel free to give it a try. I think that would be easier than rescaling the words.

**Comment by reflect9** [comment]
Yes you're right.   Resizing the canvas size would require more complicated techniques to pull words at center.     I want to clarify one thing.  Do other wordcloud algorithms also dynamically decrease font-size in rank-order?     

I wonder if I can say in my paper that this is a common way of building wordcloud.

**Comment by amueller** [comment]
I don't know, but I don't think it is. Other techniques are quite different from the one here.
Maybe have a look at the wordl paper:
http://static.mrfeinberg.com/bv_ch03.pdf

He first creates the layout in an abstract space and says how important it is to have a good heuristic to choose the size of the abstract canvas for the constraints.
My approach is a hybrid of the "random greedy" and the weight-based one.
If you set ``rank_only=True`` the strategy is simpler to explain and you can just say "more frequent words are larger", which I think is a good enough property.

**Comment by reflect9** [comment]
Thanks for explaining all!

**Comment by danielquinn** [comment]
It looks like this issue can be closed.

**Comment by amueller** [comment]
true
