### ISSUE TITLE
attempted relative import with no known parent package after running simple.py

### ISSUE THREAD

**Issue by ioxterminal** [amueller/word_cloud#510]
#### Description
Traceback (most recent call last):
  File "k:/python/word_cloud-master/simple.py", line 11, in <module>
    from wordcloud import WordCloud
  File "k:\python\word_cloud-master\wordcloud.py", line 26, in <module>
    from .query_integral_image import query_integral_image
ImportError: attempted relative import with no known parent package

#### Steps/Code to Reproduce
I am using visual studio code and extracted the word_cloud-master zip in one directory. I installed the following modules wordcloud numpy matplotlib and pillow. When running simple.py I get the 
following error:ImportError: attempted relative import with no known parent package

I am pretty new to python and normally just write PoSH code so I guess I am making a silly beginner mistake.

**Comment by amueller** [comment]
Unless you have a strong need to get the developer version and build from source, I'd recommend installing the latest release with ``pip install wordcloud``.

**Comment by EidrianGM** [comment]
Hi, I have found this same error. I am very interested in using the developer version since I want the function of svg. I thought that installing it via `pip install git+https://github.com/amueller/word_cloud` would be enough but, somehow I reach the very same error. As a temporary solution I am cloning and replacing the files within wordcloud folder.

**Comment by amueller** [comment]
the pip install should work. Can you make sure that when you're running the script you're not in a folder containing a download of the package?

**Comment by EidrianGM** [comment]
> the pip install should work. Can you make sure that when you're running the script you're not in a folder containing a download of the package?

Okey yes, it worked, I didn't notice a copy of 'wordcloud.py' in the working directory, I restarted and then I found it so I removed it and the installation went well, which includes the to_svg() method. Thanks for your quick answer.

**Comment by amueller** [comment]
Glad you worked it out :) i'll close the issue as the original poster didn't reply. I hope the thread will be useful for anyone that runs into this issue in the future.
