### ISSUE TITLE
Any chance of a new release? pip still has v 1.5.0

### ISSUE THREAD

**Issue by lhaig** [amueller/word_cloud#513]
#### Description
Is there any chance to create new release for pip installation? 
The current version does not have the latest changes and it wold be good to have them

#### Steps/Code to Reproduce
None
#### Versions

1.5.0

**Comment by jcfr** [comment]
@amueller Let me know if you need any help moving this forward.

**Comment by amueller** [comment]
I thought I did that but maybe not. Also see #482.

**Comment by amueller** [comment]
Looks like it's working:
https://pypi.org/project/wordcloud/1.6.0/#files

**Comment by jcfr** [comment]
:tada: 

I will submit a PR to tweak the [make_a_release](https://amueller.github.io/word_cloud/make_a_release.html) instructions to include updates of the ChangeLog.

**Comment by amueller** [comment]
@jcfr how do you mean? It's already included.

**Comment by lhaig** [comment]
Thank you for the release.
