### ISSUE TITLE
No Module

### ISSUE THREAD

**Issue by PEE8** [amueller/word_cloud#515]
keras_retinanet/preprocessing/generator.py", line 24, in
from .utils.anchors import anchor_targets_bbox

ModuleNotFoundError: No module named 'main.utils'; 'main' is not a package

Why am i getting error. I am trying to import anchor module which is in utils in keras_retinanet while the code generator.py is in preprocessing.
Please can you suggest if the path i gave is not correct.
I tried different ways like
from utils import anchors
from .utils.anchors import anchor_targets_bbox
or
import utils
from .utils.anchors import anchor_targets_bbox

it gives :

ModuleNotFoundError: No module named 'utils'

**Comment by amueller** [comment]
Seems like this is entirely unrelated to the Wordcloud package. Maybe try stackoverflow. I'd also suggest reading their guidelines on asking good questions.
