### ISSUE TITLE
Word Cloud export image show different color in the same code

### ISSUE THREAD

**Issue by JakinMiao** [amueller/word_cloud#518]
![one](https://user-images.githubusercontent.com/20729564/70609647-1dfe2880-1c3d-11ea-99f5-3460548024e8.jpg)
![two](https://user-images.githubusercontent.com/20729564/70609659-20f91900-1c3d-11ea-9672-77605c84ae1d.jpg)

I cannot solve this problem.

**Comment by amueller** [comment]
Please provide [self-contained example code](https://stackoverflow.com/help/mcve), including imports and data (if possible), so that other contributors can just run it and reproduce your issue. Ideally your example code should be minimal.
