### ISSUE TITLE
Defining Specific Text Colours

### ISSUE THREAD

**Issue by irn-bru** [amueller/word_cloud#52]
I'm a beginner to python so apologies for the noob question but I was wondering if there is a way to define the colours of the text instead of having random colours? I want my image to have a red background using black and white text only. Setting the bg colour was simple enough but have no clue of how to set the parameters to only use specific text colour.

Can this be done?

Thanks.

**Comment by amueller** [comment]
Look at the example here:
http://amueller.github.io/word_cloud/auto_examples/a_new_hope.html
And the references here:
http://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud

You can either pass a ``color_func`` to the constructor or recolor an existing word cloud.

The function must look like this:
```python
def red_color_func(word, font_size, position, orientation, random_state=None):
    return "hsl(10, 100%%, %d%%)" % random.randint(40, 100)
```
(this one will give you different lightnesses of a particular red hue)

**Comment by amueller** [comment]
Closing, let me know if you have additional questions.

**Comment by amueller** [comment]
![red_trooper](https://cloud.githubusercontent.com/assets/449558/6883780/1a6e8920-d594-11e4-8fcf-e8fafb565fa8.png) [example output]

**Comment by irn-bru** [comment]
Thanks for the reply, amueller.

Yes, that was the template I was working from and had successfully managed to adjust the colours like you described. What I wanted to do though, was be able to choose the exact individual colours (either via RGB, HEX values or another way) and your script would then use ONLY the colours I chose when rendering the final image instead of just applying a hue.

There is a word cloud generator over at http://www.wordle.net/create which lets you pick the colour(s) you wish to use and renders the image with those but the reason I prefer your script is because I can use a mask which for me is a must.

**Comment by amueller** [comment]
You can just define a list, and let the function return a random item of the list.

**Comment by irn-bru** [comment]
That sounds about right. Next question is how would I go about it?! (Sorry, I said I was new to Python)

**Comment by amueller** [comment]
Can you be more specific in your question?

**Comment by irn-bru** [comment]
Apologies, I was wondering what code I would use to define a list of specific colours I'd like the script to use. Like if I only wanted #FFFFFF and #000000 colours to be used in the text.

**Comment by amueller** [comment]
Not sure what color format PIL (which I use for drawing) accepts, but possibly just
np.random.choice(["red", "black"])

**Comment by irn-bru** [comment]
Thanks but I haven't a clue on how to get it working to test it. I added the 'import numpy as np' line and added ' np.random.choice(["red", "black"])' but nothing changed. This is in the 'a new hope' example script... am I right in thinking the code has to get added to there?!

Again, apologies for my severe lack of knowledge.

**Comment by markklick206** [comment]
@irn-bru @amueller  
Here is the code for what @irn-bru is looking for:  

```
def setListOfcolor_func(word=None, font_size=None,  
                     position=None, orientation=None,  
                     font_path=None, random_state=None):  
    #define the list of set colors  
    color_list = ["red", "#FFFFFF", "#000000", "skyblue", "yellow"]  

    #return a random color in the list  
    return np.random.choice(color_list)  

# visulaize wordcloud
wordcloud = WordCloud(color_func=setListOfcolor_func).generate(YOUR_TEXT)
```

Thanks for writing such a helpful package @amueller 
Cheers,
- @markklick206

**Comment by abubelinha** [comment]
It could be interesting that wordcloud directly accepts combined structured data (pandas, dictionaries or whatever) including word+frequency+color all at once, without having to deal with custom functions.

| word | frequency | color |
| - | - | - |
| USA | 25 | red |
| China | 25 | yellow |
| France | 8 | green |
| Kenia | 8 | black |
| Australia | 6 | blue |
| Brazil | 3 | red |
| ... | ... | ... |

(i.e. a long list of all world countries grouped by just 5 colors: i.e. the [Olympic ring colors](https://simple.wikipedia.org/wiki/Olympic_rings) for each continent)

I think there might be many similar datasets with a similar approach.  Pandas or database source lets you easily make joins to set colors depending on whatever criteria. 
It would be great to feed this directly to wordcloud.

Are there any documented examples already doing something similar?

Thanks
@abubelinha

**Comment by amueller** [comment]
@abubelinha what's the issue with the function, you can write a function that takes that dict, right?

**Comment by abubelinha** [comment]
> @abubelinha what's the issue with the function, you can write a function that takes that dict, right?

I didn't say there was an issue.  Basically it was a bit difficult for me to understand the [example](https://amueller.github.io/word_cloud/auto_examples/colored_by_group.html#sphx-glr-auto-examples-colored-by-group-py) I found.
"_you can_" might not be true: I have low programming skills.
"_you can try_" is more appropriate for dummies like me

I will probably come up with a non-efficient solution (wasting memory, using unnecessary loops, whatever).  
That's why I suggested it to be a good built-in feature

That said, I am already working on it. 
I am starting from `generate_from_frequencies()` [example](https://amueller.github.io/word_cloud/auto_examples/frequency.html?highlight=generate_from_frequencies) and try to adapt it for dataframe-extracted frequencies.
Does `generate_from_frequencies()` accept any other parameters than frequencies (i.e. to set colors) or do I need to apply them separately?

Thanks

**Comment by abubelinha** [comment]
OK, I ended up with something that works (at least with my first tests).
Probably not a good way of coding it, so I paste it here just in case somebody else can correct it or make suggestions.
@amueller I got specially confused about how to deal with `random_state` and pass it to inner function calls
(I don't even know if that makes any sense). 
The function should probably take many other parameters needed to configure wordcloud calls, so I would thank if anyone improves it as much as possible:

```Python
def df2wordcloud(df=None, colword=None, colfreq=None, colcolor='color', random_state=1, debug=False):
	""" This takes a pandas dataframe which contains at least two columns (you must pass their names):
		- one for words, 
		- another for word frequencies 
		- and another (optional) for using fixed colors per word 
		- plus any other columns you want (i.e. to define -or not- other coloring functions)
		If the 3rd column name is not passed, then default random colors are used instead.  
		
		Sorry about the odd debugging stuff. Please improve this code as much as you can:  
		- I wanted to count and output every color_function calls  
		  (couldn't figure out how to make that counter without using global statements).  
		- colordict is created for nothing (I didn't know if I would need it for color_function)  
		- To-do: I couldn't figure out how to pass a random_state to this function and 
		  propagate its value to inner function calls.  
		"""
	from wordcloud import WordCloud,random_color_func
	if df is None or colword is None or colfreq is None:
		return
	if debug: 
		# print("\nSOURCE DATAFRAME as a dict:\n\n", df.to_dict())
		# print("\nSOURCE DATAFRAME as a list of lists:\n\n")
		# print("pd.DataFrame(\n",df.values.tolist(),", \n columns = ",df.columns.tolist(), " )")
		print("\nSOURCE DATAFRAME:\n\n", df)
		
	wc = WordCloud(background_color="white", max_words=1000, scale=2, random_state=random_state)
	freqdict = dict(zip(df[colword], df[colfreq].astype(int)))
	if debug: 
		print("\nSOURCE FREQUENCES DICTIONARY (length={}):\n\n".format(len(freqdict)), freqdict)
	if colcolor is not None: 
		colordict = dict(zip(df[colword], df[colcolor]))
		if debug: print("\nSOURCE COLORS DICTIONARY (length={}):\n\n".format(len(colordict)), colordict)
	if debug: 
		print("\n","- "*50)
	wc.generate_from_frequencies(freqdict)
	global counter
	counter=0
	if colcolor is not None: # use color function that takes color from dataframe color column
		def my_color_func(word, font_size, position, orientation, font_path, random_state=1):
			color = df[df[colword]==word][colcolor].item()
			N = df[df[colword]==word][colfreq].item()
			if debug:
				global counter
				counter+=1
				print("{}. '{}' [N={}] to wordcloud with color --> '{}'".format(counter,word,N, color))
			return(color)
		wc.recolor(color_func=my_color_func)
	else: # use default random colors
		def my_color_func_default(word, font_size, position, orientation, font_path, random_state=1):
			N = df[df[colword]==word][colfreq].item()
			if debug:
				global counter
				counter+=1
				print("{}. '{}' [N={}] to wordcloud with default color".format(counter,word,N))
			return random_color_func(word, font_size, position, orientation, font_path, random_state)
		wc.recolor(color_func=my_color_func_default)
		pass 
	if debug: 
		print("\n --- I colored {} words out of {} --- \n".format(counter,len(df)))
	import matplotlib.pyplot as plt
	plt.imshow(wc, interpolation="bilinear")
	plt.axis("off")
	plt.show()
```

**Comment by amueller** [comment]
At this point, you can probably ask gpt-4 to write the code for you. The problem with creating a built-in function is that it would solve exactly your use-case, for a particular way of formatting the dataframe etc, while making the code for wordcloud even more complicated.

**Comment by amueller** [comment]
I was commenting on this:

> That's why I suggested it to be a good built-in feature, so people can quickly get using your library from pandas datasets.
