### ISSUE TITLE
readme.txt problem in examples

### ISSUE THREAD

**Issue by rsharifnasab** [amueller/word_cloud#531]
#### Description
`readme.txt` file in example folder seems to have a problem
because it doesn't contain any meaningful content and just exists 

#### Steps/Code to Reproduce
you can easily open [this link](https://github.com/amueller/word_cloud/blob/master/examples/README.txt) to view it :D

#### Expected Results
i excepted to exists a TOC or something there or a simple example 
or at least delete that file!

thank you

**Comment by amueller** [comment]
The sphinx-gallery package that is used for rendering the examples requires that each folder in the examples has a readme.txt file, so it can't be deleted.
I'm not sure if there's a point for having any content in it, it's a technical requirement (that we could change upstream if we wanted).

**Comment by rsharifnasab** [comment]
oOOo
thank you very much!
