### ISSUE TITLE
Can't generate correct word cloud based on character mask

### ISSUE THREAD

**Issue by zxdawn** [amueller/word_cloud#532]
#### Description
I want to generate word cloud based on a few characters like this mask:
![image](https://user-images.githubusercontent.com/30388627/75990455-e3501780-5f2f-11ea-8980-cce09c85000d.png)

#### Steps/Code to Reproduce
```python
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
from PIL import Image
import numpy as np 
from wordcloud import WordCloud

df = pd.read_csv("name.txt", header=None, names=['name'])
names = df['name']
names_dict=Counter(names)

test = np.array(Image.open('test.png'))

wc = WordCloud(background_color="white", mask=test,
               max_font_size=10)
wc.generate_from_frequencies(names_dict)

plt.imshow(wc, interpolation="bilinear")
plt.axis("off")
plt.show()
```

#### Expected Results
Generate `ABCDE` word cloud

#### Actual Results
![image](https://user-images.githubusercontent.com/30388627/75990500-f531ba80-5f2f-11ea-95bf-45b4133380f1.png)

#### Versions
Windows-10-10.0.18362-SP0
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 21:48:41) [MSC v.1916 64 bit (AMD64)]
NumPy 1.18.1
matplotlib 3.1.3
wordcoud 1.6.0

**Comment by amueller** [comment]
The problem is probably that the background in the image is not pure white.

**Comment by zxdawn** [comment]
@amueller Thanks! I find the problem: The background is transparent ... Filling it with white works well : 
![image](https://user-images.githubusercontent.com/30388627/76045225-66f11f00-5f97-11ea-8342-5ffda1e007c9.png)

**Comment by amueller** [comment]
Glad you could solve it!
