### ISSUE TITLE
Image Upload Unsuccessful | "FileNotFoundError: [Errno 2] No such file or directory:  "

### ISSUE THREAD

**Issue by SandeepAswathnarayana** [amueller/word_cloud#534]
Description:
Image Upload Unsuccessful | "FileNotFoundError: [Errno 2] No such file or directory:  " 

The example I am trying to reproduce using a "Jupyter Notebook":
https://amueller.github.io/word_cloud/auto_examples/a_new_hope.html

I used the same code as seen in the link above with the only changes including:
1. I used a column in a pandas data frame instead of text 
2. The image I am trying to upload and mask is: https://upload.wikimedia.org/wikipedia/commons/b/bb/London_plan_sub_regions_2004.png

Expected Results:
I am trying to create a word cloud with an intended column in a pandas data frame. I am trying to mask the words into a London borough map (https://upload.wikimedia.org/wikipedia/commons/b/bb/London_plan_sub_regions_2004.png).

Actual Results:
Please refer to the screenshot attached for the error message I have been dealing with.
![wordcloud error](https://user-images.githubusercontent.com/27179238/76409790-e7a78500-63b4-11ea-96eb-69876f648a80.JPG)

P.S. I understand I am missing something very basic here. I just couldn't wrap my head around in figuring this out. Any inputs are greatly appreciated. 

Thank you,
Sandeep Aswathnarayana

**Comment by amueller** [comment]
Remove the "join(d, " part and it should work.

**Comment by SandeepAswathnarayana** [comment]
Thanks for reverting, @amueller. I am getting the same error after having tried your suggestion.

**How do I successfully 'mask' using one of the following image paths?**
https://github.com/SandeepAswathnarayana/mooc/blob/master/coursera/IBM%20Data%20Science%20Professional%20Certificate/Applied%20Data%20Science%20Capstone/Final%20Capstone%20Project/London_plan_sub_regions_2004.png 
                                                  OR
https://upload.wikimedia.org/wikipedia/commons/b/bb/London_plan_sub_regions_2004.png

Would you mind a moment to help me with this?

**Comment by amueller** [comment]
I'm quite sure the error message has changed. And if you're using colab, you need to upload the image to colab and then provide the path to the image.

**Comment by SandeepAswathnarayana** [comment]
It worked after having uploaded the image to Colab. 
But, isn't the image upload on Colab temporary (only stays during runtime)? Just want to make sure!
Otherwise, everything seems fine.

**Comment by amueller** [comment]
I assume it's only temporary but I really can't help you with colab features.
