### ISSUE TITLE
Using wordcloud source without installing the module

### ISSUE THREAD

**Issue by simpsus** [amueller/word_cloud#541]
Because of #540 I clone the repo and want to run a development version from the source. 
I get the error:

`
import wordcloud
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
c:\Users\basti\Documents\GitHub\word_cloud\development.py in 
----> 2 import wordcloud

c:\Users\basti\Documents\GitHub\word_cloud\wordcloud\__init__.py in 
----> 1 from .wordcloud import (WordCloud, STOPWORDS, random_color_func,
      2                         get_single_color_func)
      3 from .color_from_image import ImageColorGenerator
      4 
      5 __all__ = ['WordCloud', 'STOPWORDS', 'random_color_func',

c:\Users\basti\Documents\GitHub\word_cloud\wordcloud\wordcloud.py in 
     28 from PIL import ImageFont
     29 
---> 30 from .query_integral_image import query_integral_image
     31 from .tokenization import unigrams_and_bigrams, process_tokens
     32 

ModuleNotFoundError: No module named 'wordcloud.query_integral_image'`

which makes sense as there is only a .c file and in the setup.py extensions this is mentioned, so I gues this gets translated by setuptools to something usable for the python interpreter.

So I guess my question is: Is there a way to use the source without executing setup.py?

**Comment by amueller** [comment]
no, there is not really. What's your motivation in doing so? You can do an inplace installation (``pip install -e .``) or you could create a virtual environment and install it in that. There is no way to use the package without compiling the C file and adding the library path to your python search path (the two things calling setup.py would do).

**Comment by simpsus** [comment]
I want to (try to) write another version of IntegralOccupancyMap as suggested and I do not want to have to run setup.py each time I made an edit to see which error message I now produced.

How do you have your development version setup?

**Comment by amueller** [comment]
If you do the in-place installation with the command I suggested above, you don't have to. It will use the current state of the code.

**Comment by simpsus** [comment]
thank you very much for your swift and helpfull answers
