### ISSUE TITLE
Problem installing wordcloud

### ISSUE THREAD

**Issue by johnnytorresm** [amueller/word_cloud#544]
#### Description
Cannot intall wordcloud on my PC

#### Steps/Code to Reproduce
conda install -c conda-forge wordcloud

#### Actual Results
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining wordcloud:   0%|  | 0/2 [00:00<?, ?it/s]|failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - wordcloud -> python[version='2.7.*|3.5.*|3.6.*|3.4.*']

Your python: python=3.7

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

#### Versions

I am using Windows 10 32bits, Python 3.7.

I installed Python using Anaconda 3.

JOHNNY

**Comment by amueller** [comment]
Thanks for reporting. This should probably be an issue on https://github.com/conda-forge/wordcloud-feedstock/
as it's related to the conda-forge channel.
It looks like there's no conda-forge package for 32bits on 3.7
Given that this is a recurring issue I might just add the 32 bits python to the recipe. Is there any reason you're using 32 bit Python instead of 64?

**Comment by johnnytorresm** [comment]
Thanks a lot for your quick reply.

My computer was migrated from Windows 7 (32bits) to Windows 10 32bits. However, the processor is 64bits and should be run win64. However, i cannot afford the migration process right now as I am in the middle of a project, and according to the documentation Windows 64 completely installs from scractch.

Good to know that I will be able to run it on 64 Machine.

Thanks again.

Johnny

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amueller** [comment]
no worries, I'll make sure to built the 32bit win package

**Comment by amueller** [comment]
You can get an older version of wordcloud by creating a virtual environment with python3.6. Conda-forge doesn't seem to support win32 any more. You can also try to install via pip, though that might be a mess because you need to compile from scratch.

**Comment by johnnytorresm** [comment]
Great idea. I guess I need to create a VM for that.

But soon I should migrate to Win64 anyways.

Cheers

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amueller** [comment]
good luck! closing, feel free to reopen or open a new issue if you run into trouble again.
