### ISSUE TITLE
Why not in Pypi?

### ISSUE THREAD

**Issue by danielquinn** [amueller/word_cloud#55]
This package appears to be mature enough to have on Pypi (so we can all just do `pip install wordcloud`), so is there a reason this hasn't been done yet?  If the `setup.py` file is written properly, this should be as easy as:

```bash
$ python setup.py sdist upload
```

If you need help on this front, I'm happy to give it a shot.

**Comment by amueller** [comment]
I thought about it at one point, but then didn't do it. maybe I should. Actually, someone just uploaded it: https://pypi.python.org/pypi/wordcloud/1.0.0

**Comment by danielquinn** [comment]
That's a little upsetting, if that account's not yours, who's keeping it up to date?  Maybe you should contact the owner and see about transferring ownership of the package?

**Comment by amueller** [comment]
maybe it was @lowks?

**Comment by lowks** [comment]
nope not me.

**Comment by amueller** [comment]
@danielquinn feel free to find out who the person is ^^

**Comment by livibetter** [comment]
According to [this page](https://warehouse.python.org/user/muncca/), muncca is also the owner of @weblyzard / [eWRT](https://github.com/weblyzard/ewrt), maybe it's one of the contributors?

**Comment by lowks** [comment]
It has also not been updated with the latest sources as it's `description` is still empty show it's description is shown as `UNKNOWN`, better thing to do ... rename the package to say `word-cloud` re-release it again.

**Comment by amueller** [comment]
I'd rather not have two versions on pypi. I want to upload current master as there have been some cool changes (image based coloring :) https://github.com/amueller/word_cloud/blob/master/examples/parrot.png

**Comment by muncca** [comment]
Please send me your pypi username @amueller.

**Comment by amueller** [comment]
it's t3kcit @muncca Thanks for the swift reply :)

**Comment by lowks** [comment]
Wow reply to all??

**Comment by amueller** [comment]
@lowks this is a github issue that you are subscribed to ;)

**Comment by muncca** [comment]
@amueller done.

**Comment by amueller** [comment]
thanks :)

**Comment by amueller** [comment]
updated pypi.
