### ISSUE TITLE
Stopword filtering seems off with version 1.7.0

### ISSUE THREAD

**Issue by freeIsa** [amueller/word_cloud#558]
#### Description
With version 1.7.0, wordclouds still include words I explicitly added to my stopwords list. Same code works fine with 1.6.0.

#### Steps/Code to Reproduce
Example:
```python
    add_stopwords = ['ciao', 'ovviamente']
    stopwords = open(INPUT_FOLDER + STOPWORDS_FILE, encoding="utf-8").readlines()
    stopwords += add_stopwords
    stopwords = set([s.rstrip() for s in stopwords])

    # generate wordcloud
    wordcloud = WordCloud(stopwords=stopwords, width=1200, height=600).generate(all_comments)
```
#### Versions
macOS-10.15.4-x86_64-i386-64bit
Python 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) 
[Clang 6.0 (clang-600.0.57)]
NumPy 1.18.4
matplotlib 3.2.1
wordcoud 1.7.0

**Comment by amueller** [comment]
Please provide [self-contained example code](https://stackoverflow.com/help/mcve), including imports and data (if possible), so that other contributors can just run it and reproduce your issue. Ideally your example code should be minimal.

I suspect this is a consequence of #557 and the stop words are included in collocations.

**Comment by freeIsa** [comment]
> Please provide [self-contained example code](https://stackoverflow.com/help/mcve), including imports and data (if possible), so that other contributors can just run it and reproduce your issue. Ideally your example code should be minimal.

I made this snippet, I hope this helps.

``` python
    stopwords = ['the', 'a', 'of', 'and', 'it', 'Lorem', 'Ipsum']
    all_text = 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. \
                    Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, \
                    when an unknown printer took a galley of type and scrambled it to make a type \
                    specimen book. It has survived not only five centuries, but also the leap \
                    into electronic typesetting, remaining essentially unchanged. \
                    It was popularised in the 1960s with the release of Letraset sheets containing \
                    Lorem Ipsum passages, and more recently with desktop publishing software \
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. \
                    Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, \
                    when an unknown printer took a galley of type and scrambled it to make a type \
                    specimen book. It has survived not only five centuries, but also the leap \
                    into electronic typesetting, remaining essentially unchanged. \
                    It was popularised in the 1960s with the release of Letraset sheets containing \
                    Lorem Ipsum passages, and more recently with desktop publishing software \
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry. \
                    Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, \
                    when an unknown printer took a galley of type and scrambled it to make a type \
                    specimen book. It has survived not only five centuries, but also the leap \
                    into electronic typesetting, remaining essentially unchanged. \
                    It was popularised in the 1960s with the release of Letraset sheets containing \
                    Lorem Ipsum passages, and more recently with desktop publishing software.'
    wordcloud = WordCloud(stopwords=stopwords, width=1200, height=600).generate(all_text)
```

> I suspect this is a consequence of #557 and the stop words are included in collocations.

I suspect it too. In the above example, I added both "Lorem" and "Ipsum" to the stop words list but they still are included in the wordcloud (I understand this is due to the fact the "Lorem Ipsum" pair is considered as a separate entity than just the two words separately - I am not sure this is always the desirable behavior though). 
Also, I think version 1.7.0 processes stop words in a case sensitive manner, which version 1.6.0 didn't (in the example above, the computed wordcloud includes "It" (upper case I) even though "it" (lower case I) was included in the stop word list. Am I wrong?

**Comment by amueller** [comment]
Thanks for that! Setting ``collocations=False`` removes the 'it' so there seems to be some interaction. I'll try to look into it, but feel free to investigate more.

**Comment by xuhdev** [comment]
I can also confirm that `wordcloud_cli` seems no longer filtering out stopwords.

**Comment by amueller** [comment]
@xuhdev I assume you mean it's no longer filtering out collocations where one of the collocations is a stopword?

**Comment by xuhdev** [comment]
Yes, that's what I meant. Sorry I wasn't clear enough.

**Comment by amueller** [comment]
Can you check if current master has this fixed the way you expected?

**Comment by freeIsa** [comment]
> Can you check if current master has this fixed the way you expected?

Hi, thanks for working on this! I've checked the new code but I'm still finding some undesirable behavior. For instance, in the italian text I am working on I get many "ciao" (hello) I want to exclude (so I added "ciao" to my stopword file). Still, I get "Ciao" in the resulting wordcloud.

I tried to change the code of function `unigrams_and_bigrams` to fix this:

```python
def unigrams_and_bigrams(words, stopwords, normalize_plurals=True, collocation_threshold=30):
    # We must create the bigrams before removing the stopword tokens from the words, or else we get bigrams like
    # "thank much" from "thank you very much".  But bigrams consisting entirely of stopwords are still invalid.
    bigrams = list(p for p in pairwise(words) if not any(w.lower() in stopwords for w in p))
    n_words = len(words)

                                       [...]
   
    for word, count in list(counts_unigrams.items()):
        # remove stopwords and empty / negative counts
        if all(w.lower() in stopwords for w in word.split(" ")) or count <= 0:
            del counts_unigrams[word]
    return counts_unigrams
```

In short, I've just applied `lower()` to each word before checking whether it is a stop word (in line 1 and in the final `if` statement). With these changes, the results seem to make sense to me. 

Do you see any negative side effect to these changes?

**Comment by amueller** [comment]
Hm indeed it seems easiest to add it to these two places. But we then also need to ensure that the stopwords are lowercase, because if someone passes ``Ciao`` as stopword it wouldn't get removed with your change, right?

**Comment by amueller** [comment]
Ah stopwords are already lowercased and the test is correct for the non-collocation case, your fix is indeed correct. Do you want to sent a PR with a non-regression test?

**Comment by freeIsa** [comment]
> Ah stopwords are already lowercased and the test is correct for the non-collocation case, your fix is indeed correct. Do you want to sent a PR with a non-regression test?

I just tried - my first time doing a PR, so bear with me :)

**Comment by amueller** [comment]
It can be a bit of a process sometimes, but looks like it all worked out!
