### ISSUE TITLE
Any idea for the generation of a good mask?

### ISSUE THREAD

**Issue by HeroadZ** [amueller/word_cloud#567]
I tried this picture for image-color wordcloud, but the result is not satisfying.
![pika](https://user-images.githubusercontent.com/17962682/85202214-c81ee180-b33f-11ea-992c-4bcafa8a510e.jpg)
![image](https://user-images.githubusercontent.com/17962682/85202241-f3a1cc00-b33f-11ea-9499-745fa73bc932.png)

Apparently, the numpy cannot get a good mask from this image.
Is there any idea for the improvement?

**Comment by amueller** [comment]
The background needs to be pure white to be masked out.

**Comment by HeroadZ** [comment]
@amueller yeah, I found that. And I use
```python
mask[mask > 230] = 255 # 230 is the threshold for binarization
```
I think a binarization is recommended before generating the mask.  
And would like to write this advice in document for beginner? It's helpful for them in my opinion
```python
def binary(mask, threshold):
    mask[mask > threshold) = 255
    return mask
```

**Comment by amueller** [comment]
I agree, this would be nice to add to the documentation. Actually,  right now there is no user guide, which is pretty bad. It would be good to write a user guide but that's obviously quite a bit of work.
Right now this is "documented" in this example:
http://amueller.github.io/word_cloud/auto_examples/parrot.html

Which is a bit more elaborate even (and if you use these techniques, it might give you even better results).

**Comment by HeroadZ** [comment]
that's great!
