### ISSUE TITLE
problems when pip install wordcloud package,but I have already installed visual c++tools

### ISSUE THREAD

**Issue by Henry-Lu96** [amueller/word_cloud#572]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\louis\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Louis\\AppData\\Local\\Temp\\pip-install-mihy4c03\\wordcloud\\setup.py'"'"'; __file__='"'"'C:\\Users\\Louis\\AppData\\Local\\Temp\\pip-install-mihy4c03\\wordcloud\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Louis\AppData\Local\Temp\pip-record-m8xr78w3\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\louis\appdata\local\programs\python\python38\Include\wordcloud'
         cwd: C:\Users\Louis\AppData\Local\Temp\pip-install-mihy4c03\wordcloud\
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\wordcloud
    copying wordcloud\color_from_image.py -> build\lib.win32-3.8\wordcloud
    copying wordcloud\tokenization.py -> build\lib.win32-3.8\wordcloud
    copying wordcloud\wordcloud.py -> build\lib.win32-3.8\wordcloud
    copying wordcloud\wordcloud_cli.py -> build\lib.win32-3.8\wordcloud
    copying wordcloud\_version.py -> build\lib.win32-3.8\wordcloud
    copying wordcloud\__init__.py -> build\lib.win32-3.8\wordcloud
    copying wordcloud\__main__.py -> build\lib.win32-3.8\wordcloud
    copying wordcloud\stopwords -> build\lib.win32-3.8\wordcloud
    copying wordcloud\DroidSansMono.ttf -> build\lib.win32-3.8\wordcloud
    UPDATING build\lib.win32-3.8\wordcloud/_version.py
    set build\lib.win32-3.8\wordcloud/_version.py to '1.7.0'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\louis\appdata\local\programs\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Louis\\AppData\\Local\\Temp\\pip-install-mihy4c03\\wordcloud\\setup.py'"'"'; __file__='"'"'C:\\Users\\Louis\\AppData\\Local\\Temp\\pip-install-mihy4c03\\wordcloud\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Louis\AppData\Local\Temp\pip-record-m8xr78w3\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\louis\appdata\local\programs\python\python38\Include\wordcloud' Check the logs for full command output.

**Comment by amueller** [comment]
How did you try to install? With ``pip install wordcloud``? It looks like you're using 32bit python for which we currently don't ship a wheel.
You can either try to compile yourself by installing the package that is linked in the error message, or you can move to 64 bit python.

**Comment by nihal-singh** [comment]
@Henry-Lu96 I was also facing the same issue when I tried installing wordcloud ( pip install wordcloud ). But Installing c++ build tools under VS build tools worked for me. [Windows 10][Python v3.9.2]
