### ISSUE TITLE
Unusable on AWS Lambda (Zappa + Flask)

### ISSUE THREAD

**Issue by JordanTreDaniel** [amueller/word_cloud#575]
#### Description
No module named 'wordcloud.query_integral_image' 

On a side note, I have been struggling with getting this to work for the past few days, mostly due to AWS size/package limitations. I feel like I am so close! I just have no idea how to solve a problem like this in the cloud (esp AWS Lambda) as I am new to both python development AND aws

#### Steps/Code to Reproduce
1. Made a virtual env with `python3 -m venv my-virtual-env`
2. pip install flask zappa wordcloud
3. pip freeze > requirements
4. zappa deploy dev

5. app.py runs and tries these imports
```
import matplotlib as mpl
import matplotlib.pyplot as plt
from wordcloud import WordCloud
```

#### Expected Results
That it load the libraries & perform same as locally

#### Actual Results
During deployment process (Zappa), gateway test fails with 502 because of this error (seen with `zappa tail`)
No module named 'wordcloud.query_integral_image' 

#### Versions
The version of wordcloud installed is 1.7.0

**Comment by JordanTreDaniel** [comment]
I was able to get around the problem above by adding `https://files.pythonhosted.org/packages/ed/1d/c6d942bc569df4ff1574633b159a68c75f79061fe279975d90f9d2180204/wordcloud-1.7.0-cp37-cp37m-manylinux1_x86_64.whl ; sys_platform == "linux"` to the `requirements.txt` file, but that just started another problem. 

The new problem is a `numpy` one. 

`Failed to find library: libmysqlclient.so.18...right filename?`

I didn't have numpy problems before, & I think this is still related to the wordcloud package, possibly in the way that the requirements/dependencies are listed?

**Comment by JordanTreDaniel** [comment]
The guys at Zappa helped me out

**Comment by amueller** [comment]
glad you worked it out and sorry for not replying earlier. Though tbh I probably couldn't have helped ;)

**Comment by JordanTreDaniel** [comment]
@amueller all good thank you anyway!
