### ISSUE TITLE
AppVeyor is using the wrong pip

### ISSUE THREAD

**Issue by GadgetSteve** [amueller/word_cloud#578]
#### Description

Looking at the AppVeyor output on https://ci.appveyor.com/project/amueller/word-cloud/builds/34384383/job/88xpa5dop85wsefb it looks to be using the wrong pip
#### Steps/Code to Reproduce

Look at https://ci.appveyor.com/project/amueller/word-cloud/builds/34384383/job/88xpa5dop85wsefb it has an evnironment of: Environment: PYTHON_DIR=C:\Python36, PYTHON_VERSION=3.6.x, PYTHON_ARCH=32, BLOCK=0 **but** the log starts with:
python -m pip install -U scikit-ci scikit-ci-addons
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting scikit-ci

This shows that the python being used it Python **2.7** not 3.6

**Comment by amueller** [comment]
That's shown before the environment is set up.
if you look at a current built, you can see it still at the top, but then further down you can see the environment it's actually running the code in is 3.6:
https://ci.appveyor.com/project/amueller/word-cloud/builds/34421150/job/8vfau6d8q0r4vk94#L122

Hope that clarifies it.

**Comment by amueller** [comment]
Everything is using github actions now, so this should no longer be relevant.
