### ISSUE TITLE
WordCloud() got an unexpected keyword argument 'stopwords'

### ISSUE THREAD

**Issue by kurasaiteja** [amueller/word_cloud#579]
#### Description

I ran pip install word cloud and this is happening in my macOS when I try to create a word cloud. 

#### Steps/Code to Reproduce

My code - 
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

text = " ".join(review for review in messages_df.Message)
stopwords = set(STOPWORDS)
stopwords.update(["ra", "ga", "na", "ani", "em", "ki", "ah","ha","la","eh","ne","le","ni","lo","Ma","Haa","ni"])
# Generate a word cloud image
wordcloud = WordCloud(stopwords=stopwords, background_color="white").generate(text)

#### Expected Results
Everything to Work fine.
#### Actual Results

![Screenshot 2020-08-02 at 8 05 55 PM](https://user-images.githubusercontent.com/39938013/89125377-9894f480-d4fb-11ea-8703-50c335131184.png)
![Screenshot 2020-08-02 at 8 00 56 PM](https://user-images.githubusercontent.com/39938013/89125379-a0549900-d4fb-11ea-91e8-aff1f99d1655.png)

**Comment by amueller** [comment]
Thanks for opening the issue. Can you please post the full traceback as text? It looks like your ``WordCloud`` class comes from ``uber.py`` not from the ``wordcloud`` module.

**Comment by kurasaiteja** [comment]
Hey there, sorry was a typo. I created another method WordCloud which had overwritten the imported method.

**Comment by amueller** [comment]
Does that mean you resolved the issue?

**Comment by kurasaiteja** [comment]
Yes. It’s done
