### ISSUE TITLE
Cannot install wordCloud for Python 3.8.5 64 bit windows 10

### ISSUE THREAD

**Issue by shderhami** [amueller/word_cloud#580]
When I try to install Word Cloud for Python 3.8.5 64 bit on Windows 10 using pip, I get the following error:
Defaulting to user installation because normal site-packages is not writeable
Collecting wordcloud
  Using cached wordcloud-1.7.0.tar.gz (216 kB)
Requirement already satisfied: numpy>=1.6.1 in c:\users\si\appdata\roaming\python\python38\site-packages (from wordcloud) (1.19.1)
Requirement already satisfied: pillow in c:\users\si\appdata\roaming\python\python38\site-packages (from wordcloud) (7.2.0)
Requirement already satisfied: matplotlib in c:\users\si\appdata\roaming\python\python38\site-packages (from wordcloud) (3.3.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\sii\appdata\roaming\python\python38\site-packages (from matplotlib->wordcloud) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\users\si\appdata\roaming\python\python38\site-packages (from matplotlib->wordcloud) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\si\appdata\roaming\python\python38\site-packages (from matplotlib->wordcloud) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\si\appdata\roaming\python\python38\site-packages (from matplotlib->wordcloud) (1.2.0)
Requirement already satisfied: six>=1.5 in c:\users\si\appdata\roaming\python\python38\site-packages (from python-dateutil>=2.1->matplotlib->wordcloud) (1.15.0)
Using legacy 'setup.py install' for wordcloud, since package 'wheel' is not installed.
Installing collected packages: wordcloud
    Running setup.py install for wordcloud ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\si\\AppData\\Local\\Temp\\pip-install-i2frna5z\\wordcloud\\setup.py'"'"'; __file__='"'"'C:\\Users\\si\\AppData\\Local\\Temp\\pip-install-i2frna5z\\wordcloud\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\si\AppData\Local\Temp\pip-record-t8sbvue_\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\si\AppData\Roaming\Python\Python38\Include\wordcloud'
         cwd: C:\Users\si\AppData\Local\Temp\pip-install-i2frna5z\wordcloud\
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\wordcloud
    copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.8\wordcloud
    copying wordcloud\tokenization.py -> build\lib.win-amd64-3.8\wordcloud
    copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.8\wordcloud
    copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.8\wordcloud
    copying wordcloud\_version.py -> build\lib.win-amd64-3.8\wordcloud
    copying wordcloud\__init__.py -> build\lib.win-amd64-3.8\wordcloud
    copying wordcloud\__main__.py -> build\lib.win-amd64-3.8\wordcloud
    copying wordcloud\stopwords -> build\lib.win-amd64-3.8\wordcloud
    copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.8\wordcloud
    UPDATING build\lib.win-amd64-3.8\wordcloud/_version.py
    set build\lib.win-amd64-3.8\wordcloud/_version.py to '1.7.0'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\si\\AppData\\Local\\Temp\\pip-install-i2frna5z\\wordcloud\\setup.py'"'"'; __file__='"'"'C:\\Users\\si\\AppData\\Local\\Temp\\pip-install-i2frna5z\\wordcloud\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\si\AppData\Local\Temp\pip-record-t8sbvue_\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\si\AppData\Roaming\Python\Python38\Include\wordcloud' Check the logs for full command output.

**Comment by amueller** [comment]
Thank you for reporting and sorry for the slow reply. We added 3.8 build support in #547 but haven't released since. I'll try to do that as soon as I can.

**Comment by amueller** [comment]
Can you please try again? Thanks!

**Comment by amueller** [comment]
closing, please let me know if the issue persists.
