### ISSUE TITLE
Unable to install wordcloud using `pip install wordcloud` for python 3.8.5 on MacOS Catalina

### ISSUE THREAD

**Issue by adityagarg7** [amueller/word_cloud#582]
Before trying to install wordcloud I had the following packages installed in my env:

<img width="851" alt="packages installed" src="https://user-images.githubusercontent.com/64764018/89868138-f39bab00-dbcf-11ea-8fbc-b92c62c75e9b.png">

Then, I tried installing wordcloud using pip:

`pip install  wordcloud`

And I am getting the following error log:

```
(test4) Apples-MacBook-Pro:whatapp-chat-analysis apple$ pip install wordcloud
Collecting wordcloud
  Using cached wordcloud-1.7.0.tar.gz (216 kB)
Collecting numpy>=1.6.1
  Using cached numpy-1.19.1-cp38-cp38-macosx_10_9_x86_64.whl (15.3 MB)
Collecting pillow
  Using cached Pillow-7.2.0-cp38-cp38-macosx_10_10_x86_64.whl (2.2 MB)
Collecting matplotlib
  Using cached matplotlib-3.3.0-1-cp38-cp38-macosx_10_9_x86_64.whl (11.4 MB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.2.0-cp38-cp38-macosx_10_9_x86_64.whl (60 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/apple/opt/anaconda3/envs/test4/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4c/_r8vg69s4bb61j6syx4sdj900000gn/T/pip-install-p_7tybc4/wordcloud/setup.py'"'"'; __file__='"'"'/private/var/folders/4c/_r8vg69s4bb61j6syx4sdj900000gn/T/pip-install-p_7tybc4/wordcloud/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/4c/_r8vg69s4bb61j6syx4sdj900000gn/T/pip-wheel-4fku53sy
       cwd: /private/var/folders/4c/_r8vg69s4bb61j6syx4sdj900000gn/T/pip-install-p_7tybc4/wordcloud/
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/_version.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/tokenization.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/wordcloud.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/color_from_image.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/__main__.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/stopwords -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  UPDATING build/lib.macosx-10.9-x86_64-3.8/wordcloud/_version.py
  set build/lib.macosx-10.9-x86_64-3.8/wordcloud/_version.py to '1.7.0'
  running build_ext
  building 'wordcloud.query_integral_image' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/wordcloud
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/apple/opt/anaconda3/envs/test4/include -arch x86_64 -I/Users/apple/opt/anaconda3/envs/test4/include -arch x86_64 -I/Users/apple/opt/anaconda3/envs/test4/include/python3.8 -c wordcloud/query_integral_image.c -o build/temp.macosx-10.9-x86_64-3.8/wordcloud/query_integral_image.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
DEPRECATION: Could not build wheels for wordcloud which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: numpy, pillow, kiwisolver, six, cycler, python-dateutil, pyparsing, matplotlib, wordcloud
    Running setup.py install for wordcloud ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/apple/opt/anaconda3/envs/test4/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4c/_r8vg69s4bb61j6syx4sdj900000gn/T/pip-install-p_7tybc4/wordcloud/setup.py'"'"'; __file__='"'"'/private/var/folders/4c/_r8vg69s4bb61j6syx4sdj900000gn/T/pip-install-p_7tybc4/wordcloud/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4c/_r8vg69s4bb61j6syx4sdj900000gn/T/pip-record-2saz08jg/install-record.txt --single-version-externally-managed --compile --install-headers /Users/apple/opt/anaconda3/envs/test4/include/python3.8/wordcloud
         cwd: /private/var/folders/4c/_r8vg69s4bb61j6syx4sdj900000gn/T/pip-install-p_7tybc4/wordcloud/
    Complete output (24 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/_version.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/tokenization.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/wordcloud.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/color_from_image.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/__main__.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/stopwords -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    UPDATING build/lib.macosx-10.9-x86_64-3.8/wordcloud/_version.py
    set build/lib.macosx-10.9-x86_64-3.8/wordcloud/_version.py to '1.7.0'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    creating build/temp.macosx-10.9-x86_64-3.8/wordcloud
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/apple/opt/anaconda3/envs/test4/include -arch x86_64 -I/Users/apple/opt/anaconda3/envs/test4/include -arch x86_64 -I/Users/apple/opt/anaconda3/envs/test4/include/python3.8 -c wordcloud/query_integral_image.c -o build/temp.macosx-10.9-x86_64-3.8/wordcloud/query_integral_image.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/apple/opt/anaconda3/envs/test4/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4c/_r8vg69s4bb61j6syx4sdj900000gn/T/pip-install-p_7tybc4/wordcloud/setup.py'"'"'; __file__='"'"'/private/var/folders/4c/_r8vg69s4bb61j6syx4sdj900000gn/T/pip-install-p_7tybc4/wordcloud/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4c/_r8vg69s4bb61j6syx4sdj900000gn/T/pip-record-2saz08jg/install-record.txt --single-version-externally-managed --compile --install-headers /Users/apple/opt/anaconda3/envs/test4/include/python3.8/wordcloud Check the logs for full command output.
```

I read through a similar closed issue #105, but found the solution was not applicable for me as I am facing this issue in a Mac OS. I am able to install using conda, but I want to install using pip since I want to deploy my app on Heroku remote server where all python dependencies have to be installed with pip.

Thank you!

**Comment by amueller** [comment]
Thanks for opening the issue. Both are a result of us not shipping Python 3.8 wheels right now. It was merged in #547 but we haven't released since then. I'll try to do that soon.

**Comment by amueller** [comment]
Can you please try again? Thanks!

**Comment by adityagarg7** [comment]
I just tried running `pip install wordcloud` by creating a new env and installing all dependencies. Its installing the package perfectly. Thank you very much.

**Comment by amueller** [comment]
Great, thank you for the quick reply!

**Comment by Uday-Shankar-Shanthamallu** [comment]
I am getting the wordcloud installation error on a fresh conda environment. I am on macOS Monterey version 12.0.1 

ERROR: Command errored out with exit status 1:
   command: /Users/udayshanthamallu/opt/anaconda3/envs/wc/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p0/cfvvwlr97ldgm6j9vngsl1pc0000gp/T/pip-install-xv_972qg/wordcloud_072658e5cdb44f6fbae0f8942a5b70a3/setup.py'"'"'; __file__='"'"'/private/var/folders/p0/cfvvwlr97ldgm6j9vngsl1pc0000gp/T/pip-install-xv_972qg/wordcloud_072658e5cdb44f6fbae0f8942a5b70a3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/p0/cfvvwlr97ldgm6j9vngsl1pc0000gp/T/pip-wheel-oxcdv6oq
       cwd: /private/var/folders/p0/cfvvwlr97ldgm6j9vngsl1pc0000gp/T/pip-install-xv_972qg/wordcloud_072658e5cdb44f6fbae0f8942a5b70a3/
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/_version.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/tokenization.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/wordcloud.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/color_from_image.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/__main__.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/stopwords -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
  UPDATING build/lib.macosx-10.9-x86_64-3.8/wordcloud/_version.py
  set build/lib.macosx-10.9-x86_64-3.8/wordcloud/_version.py to '1.8.1'
  running build_ext
  building 'wordcloud.query_integral_image' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/wordcloud
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/udayshanthamallu/opt/anaconda3/envs/wc/include -arch x86_64 -I/Users/udayshanthamallu/opt/anaconda3/envs/wc/include -arch x86_64 -I/Users/udayshanthamallu/opt/anaconda3/envs/wc/include/python3.8 -c wordcloud/query_integral_image.c -o build/temp.macosx-10.9-x86_64-3.8/wordcloud/query_integral_image.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: six, python-dateutil, pyparsing, pillow, numpy, kiwisolver, cycler, matplotlib, wordcloud
    Running setup.py install for wordcloud ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/udayshanthamallu/opt/anaconda3/envs/wc/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p0/cfvvwlr97ldgm6j9vngsl1pc0000gp/T/pip-install-xv_972qg/wordcloud_072658e5cdb44f6fbae0f8942a5b70a3/setup.py'"'"'; __file__='"'"'/private/var/folders/p0/cfvvwlr97ldgm6j9vngsl1pc0000gp/T/pip-install-xv_972qg/wordcloud_072658e5cdb44f6fbae0f8942a5b70a3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/p0/cfvvwlr97ldgm6j9vngsl1pc0000gp/T/pip-record-dekonuw0/install-record.txt --single-version-externally-managed --compile --install-headers /Users/udayshanthamallu/opt/anaconda3/envs/wc/include/python3.8/wordcloud
         cwd: /private/var/folders/p0/cfvvwlr97ldgm6j9vngsl1pc0000gp/T/pip-install-xv_972qg/wordcloud_072658e5cdb44f6fbae0f8942a5b70a3/
    Complete output (24 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/_version.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/tokenization.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/wordcloud.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/color_from_image.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/__main__.py -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/stopwords -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.9-x86_64-3.8/wordcloud
    UPDATING build/lib.macosx-10.9-x86_64-3.8/wordcloud/_version.py
    set build/lib.macosx-10.9-x86_64-3.8/wordcloud/_version.py to '1.8.1'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    creating build/temp.macosx-10.9-x86_64-3.8/wordcloud
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/udayshanthamallu/opt/anaconda3/envs/wc/include -arch x86_64 -I/Users/udayshanthamallu/opt/anaconda3/envs/wc/include -arch x86_64 -I/Users/udayshanthamallu/opt/anaconda3/envs/wc/include/python3.8 -c wordcloud/query_integral_image.c -o build/temp.macosx-10.9-x86_64-3.8/wordcloud/query_integral_image.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/udayshanthamallu/opt/anaconda3/envs/wc/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p0/cfvvwlr97ldgm6j9vngsl1pc0000gp/T/pip-install-xv_972qg/wordcloud_072658e5cdb44f6fbae0f8942a5b70a3/setup.py'"'"'; __file__='"'"'/private/var/folders/p0/cfvvwlr97ldgm6j9vngsl1pc0000gp/T/pip-install-xv_972qg/wordcloud_072658e5cdb44f6fbae0f8942a5b70a3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/p0/cfvvwlr97ldgm6j9vngsl1pc0000gp/T/pip-record-dekonuw0/install-record.txt --single-version-externally-managed --compile --install-headers /Users/udayshanthamallu/opt/anaconda3/envs/wc/include/python3.8/wordcloud Check the logs for full command output.

**Comment by amueller** [comment]
@Uday-Shankar-Shanthamallu you have to install gcc with conda, or potentially clang. I'm not super familiar with building on OS X.
