### ISSUE TITLE
How to get the words from WordCloud instead of saving as image

### ISSUE THREAD

**Issue by akarahim** [amueller/word_cloud#583]
#### Description
I want to get the word from word cloud as the list of string, which I can store in the Db and use it later, how can I access it from word cloud?

**Comment by amueller** [comment]
They are stored in the ``words_`` attribute. If you want also the position and size information, check out the ``layout_`` attribute:

https://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud

hth
