### ISSUE TITLE
Multiple fonts

### ISSUE THREAD

**Issue by yigithsyn** [amueller/word_cloud#584]
Is it possible to use multiple font files?

Thank you.

**Comment by amueller** [comment]
There's a pull request you can try here:
https://github.com/amueller/word_cloud/pull/494

Another option is to combine fonts using other tools.
There's some discussion in these issues:
https://github.com/amueller/word_cloud/pull/219#issuecomment-272301932
https://github.com/amueller/word_cloud/issues/238

**Comment by yigithsyn** [comment]
Thanks for quick response. I understand and prefer to combined fonts.
