### ISSUE TITLE
Words do not form within mask

### ISSUE THREAD

**Issue by forthrin** [amueller/word_cloud#587]
#### Description
Thanks a million for creating this, so I didn't have to -- horror of horrors -- [install Java](https://github.com/kennycason/kumo). Also, I can see you are very accommodating with issues, so here is another one :)

I can't get masks to work from the shell (see below), and the [help page](https://amueller.github.io/word_cloud/cli.html) didn't give away much more than `--help`. Didn't find any examples of shell usage anywhere.

#### Steps/Code to Reproduce
```
$ potrace logo.bmp
$ convert -density 600 logo.eps -monochrome -type bilevel logo.png
$ identify -verbose logo.png 
  Format: PNG
  Geometry: 3840x800
  Resolution: 600x600
  Colorspace: Gray
  Type: Bilevel
  Colors: 2
  Histogram:
    (0,0,0) #000000
    (255,255,255) #FFFFFF
  Background color: white
  Transparent color: none
$ wordcloud_cli --text text.txt --mask logo.png > cloud.png && open cloud.png
```

#### Expected Results
Cloud words only within logo (high resolution, solid `#000000` logo against a pure `#FFFFFF` background).

#### Actual Results
Cloud words everywhere in the output. Logo shape is not honored at all.

#### Versions
macOS-10.15.6-x86_64-i386-64bit
Python 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]
NumPy 1.19.1
matplotlib 3.3.2
wordcoud 1.8.0

**Comment by amueller** [comment]
Thanks for the report. I don't think we support gray level masks right now. Can you make it RGB?

**Comment by forthrin** [comment]
After some trial and error:

```
$ convert -density 600 logo.eps PNG32:logo.png
$ identify -verbose logo.png
  Colorspace: sRGB
```

**Comment by amueller** [comment]
Thanks for your thoughts. Did that fix the error?

I'm happy to accept PRs for 1 and 3.

For 2, this is really not the suggested input and I'm not sure why someone would sort their text. Can you maybe give some input on that? We could try to detect this special case and adjust the behavior. I haven't done that so far because I really don't understand why people sort their text.

re 4) indeed, clearly NP-hard, so it's just greedy. Actually not even optimally greedy but just pick a random place where it would fit. Basically the stupidest way possible.

**Comment by forthrin** [comment]
You're right. There is no upside to converting a regular text document to sorted one word per line, when the utility will build the word frequency table regardless of this. I started on 3, but didn't understand what this line does, which might be relevant to the implementation. I could send you the draft. It's just a few lines.

    pattern = r"\w[\w']*" if self.min_word_length <= 1 else r"\w[\w']+"

**Comment by amueller** [comment]
This changes the regular expression to require only a single letter when min_word_length is ``<=1``. Actually I'm not sure we need the ``else``. But I don't think this part is as relevant, I think the other use of ``min_word_length`` is probably where you'd want to filter by maximum word length. What's your use case for that btw?

**Comment by forthrin** [comment]
Use case: Document has overly long words or non-linguistic strings, and you want the cloud to be comprised by short words, for simplicity or aesthetic purposes.

Haven't been able to test the code since `python3 -m wordcloud` gives `ModuleNotFoundError: No module named 'wordcloud.query_integral_image'`, evidently a frequent issue. I installed with `pip3`.

```
diff --git a/wordcloud/wordcloud.py b/wordcloud/wordcloud.py
index 26b0d54..fedd156 100644
--- a/wordcloud/wordcloud.py
+++ b/wordcloud/wordcloud.py
@@ -276,2 +276,5 @@ class WordCloud(object):
 
+    max_word_length : int, default=24
+        Maximum number of letters a word can have to be included.
+
     collocation_threshold: int, default=30
@@ -314,3 +317,3 @@ class WordCloud(object):
                  contour_color='black', repeat=False,
-                 include_numbers=False, min_word_length=0, collocation_threshold=30):
+                 include_numbers=False, min_word_length=0, max_word_length=24, maxcollocation_threshold=30):
         if font_path is None:
@@ -365,2 +368,3 @@ class WordCloud(object):
         self.min_word_length = min_word_length
+        self.max_word_length = max_word_length
         self.collocation_threshold = collocation_threshold
@@ -583,3 +587,3 @@ class WordCloud(object):
         if self.min_word_length:
-            words = [word for word in words if len(word) >= self.min_word_length]
+            words = [word for word in words if len(word) >= self.min_word_length and len(word) <= self.max_word_length]
 
diff --git a/wordcloud/wordcloud_cli.py b/wordcloud/wordcloud_cli.py
index 125a86f..8a201a9 100644
--- a/wordcloud/wordcloud_cli.py
+++ b/wordcloud/wordcloud_cli.py
@@ -169,2 +169,9 @@ def make_parser():
         help='only include words with more than X letters')
+    parser.add_argument(
+        '--max_word_length',
+        type=int,
+        default=24, # /usr/share/dict/words
+        metavar='max_word_length',
+        dest='max_word_length',
+        help='only include words with less than X letters')
     parser.add_argument(
```

**Comment by amueller** [comment]
Sorry for the slow reply, I was moving. How did you install with pip? The error simply means you did not build the package that you are using. You can also send a pull request, and tests will be run automatically.

**Comment by forthrin** [comment]
I think it was just `pip3 install --user wordcloud`.

**Comment by amueller** [comment]
and how did you make the edit then?

Generally to make an edit, you need to clone from github and then run ``pip install -e .`` if you're using a conda environment or virtual environment, or ``pip3 install --user -e .`` if you're using a the system environment (which I would advise against).

**Comment by forthrin** [comment]
```
$ git clone ...
$ python3 -m wordcloud
ModuleNotFoundError: No module named 'wordcloud.query_integral_image'
$ pip3 install --user -e .
$ python3 -m wordcloud
ImportError: No module named PIL
$ pip3 install --user Pillow
$ python3 -m wordcloud --text README.md 
NameError: name 'collocation_threshold' is not defined
```

**Comment by amueller** [comment]
The first error is expected as I mentioned as you didn't built the package yet.
I'm surprised by the second error, as pillow is in the "install_requires". Are you sure the pip3 and python3 correspond to the same environment? Does ``pip3 install --user -e .`` install pillow?

I'm surprised that the last one does anything, the way to run the command line interface is
```
wordcloud_cli --text mytext.txt --imagefile wordcloud.png
```
as you can see from the readme.
Is the ``-m`` invocation recommended anywhere?
PR welcome to improve the error message in that case.

**Comment by forthrin** [comment]
```
To execute the CLI, instead consider running:
  wordcloud_cli --help
or
  python -m wordcloud --help
```

I just keep getting more and more "library missing" errors the more I try to install missing libraries, so for the sake of our respective spare time, let's just drop this :)

**Comment by amueller** [comment]
alright, that's fair. I'm not sure why you would get errors after running ``pip install`` but no worries.
