### ISSUE TITLE
Feature request: Use colours in mask image to colour word cloud text

### ISSUE THREAD

**Issue by harryjubb** [amueller/word_cloud#60]
Thank you for developing this fantastic package. I am currently writing a multi-chapter document and it is great to have an image masked word cloud at the beginning of each chapter that can be automatically updated.

The image masking is a fantastic feature, but I am wondering if it possible to extract the word cloud text colours from the underlying mask? I realise that currently it's a binary mask, but it would be great if possible to achieve this. Tagexdo http://www.tagxedo.com/ is currently the only service I know of that is capable of this, however it is of course not programmable.

**Comment by amueller** [comment]
That is a pretty cool idea! do you have an image and text that you can share, I'll code it up ;)

**Comment by amueller** [comment]
It should be easy by giving it a custom coloring function. That currently can't use the mask, though.

**Comment by amueller** [comment]
http://amueller.github.io/word_cloud/auto_examples/colored.html

**Comment by amueller** [comment]
also: damn you for nerd-sniping me ;)

**Comment by harryjubb** [comment]
Wow, that's so awesome! Amazing that you implemented it so quickly as well!




Apologies for the nerd-snipe :P but please take pride in the fact that you're making my thesis a lot cooler and will be getting a shout-out! :)



—

**Comment by amueller** [comment]
I'd love to see some nice images ;) I'm not happy with my current example :-/

**Comment by harryjubb** [comment]
Will have a play with it and see what I come up with, need to do some more writing first to fill the clouds :P



—
