### ISSUE TITLE
Installation fails on Python 3.9

### ISSUE THREAD

**Issue by dlukes** [amueller/word_cloud#604]
Caused by the [removal of the `PyTypeObject.tp_print` field](https://bugs.python.org/issue39361). Core dev Victor Stinner elsewhere suggests [making those parts of the code Python 2 only with `ifdef`s](https://bugzilla.redhat.com/show_bug.cgi?id=1791745#c2). Another option would be to drop Python 2 support altogether, as it has reached EOL.

**Comment by amueller** [comment]
Hi!

Thanks for opening the issue. Can you tell me how to reproduce? How did you install? There are no wheels so I assume you built from source. If so, did you re-cythonize the code? The repo currently has the generated C-code checked in, which used 0.28.4 (which probably predates this decision about the Python3.9 scope). So just calling Cython again with a current version will likely solve the issue.

It's probably not a good idea to check in the C code at all and cythonize when building, that would prevent similar issues in the future.

**Comment by dlukes** [comment]
Thanks for your reply :) And for creating and maintaining this library!

> Can you tell me how to reproduce? How did you install?

Just `pip install wordcloud` on a Python 3.9 compiled from source with `pyenv`. On Ubuntu/Linux/WSL2.

<details>
<summary><code>pip install wordcloud</code> output</summary>
<pre>
Collecting wordcloud
  Using cached wordcloud-1.8.0.tar.gz (217 kB)
Requirement already satisfied: numpy>=1.6.1 in ./venv/lib/python3.9/site-packages (from wordcloud) (1.19.2)
Requirement already satisfied: pillow in ./venv/lib/python3.9/site-packages (from wordcloud) (7.2.0)
Requirement already satisfied: matplotlib in ./venv/lib/python3.9/site-packages (from wordcloud) (3.3.2)
Requirement already satisfied: certifi>=2020.06.20 in ./venv/lib/python3.9/site-packages (from matplotlib->wordcloud) (2020.6.20)
Requirement already satisfied: kiwisolver>=1.0.1 in ./venv/lib/python3.9/site-packages (from matplotlib->wordcloud) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in ./venv/lib/python3.9/site-packages (from matplotlib->wordcloud) (2.4.7)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.9/site-packages (from matplotlib->wordcloud) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in ./venv/lib/python3.9/site-packages (from matplotlib->wordcloud) (2.8.1)
Requirement already satisfied: six in ./venv/lib/python3.9/site-packages (from cycler>=0.10->matplotlib->wordcloud) (1.15.0)
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/david/tmp/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-l2cibyei/wordcloud/setup.py'"'"'; __file__='"'"'/tmp/pip-install-l2cibyei/wordcloud/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-je6bxd82
       cwd: /tmp/pip-install-l2cibyei/wordcloud/
  Complete output (155 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/wordcloud
  copying wordcloud/__main__.py -> build/lib.linux-x86_64-3.9/wordcloud
  copying wordcloud/color_from_image.py -> build/lib.linux-x86_64-3.9/wordcloud
  copying wordcloud/tokenization.py -> build/lib.linux-x86_64-3.9/wordcloud
  copying wordcloud/wordcloud.py -> build/lib.linux-x86_64-3.9/wordcloud
  copying wordcloud/_version.py -> build/lib.linux-x86_64-3.9/wordcloud
  copying wordcloud/wordcloud_cli.py -> build/lib.linux-x86_64-3.9/wordcloud
  copying wordcloud/__init__.py -> build/lib.linux-x86_64-3.9/wordcloud
  copying wordcloud/stopwords -> build/lib.linux-x86_64-3.9/wordcloud
  copying wordcloud/DroidSansMono.ttf -> build/lib.linux-x86_64-3.9/wordcloud
  UPDATING build/lib.linux-x86_64-3.9/wordcloud/_version.py
  set build/lib.linux-x86_64-3.9/wordcloud/_version.py to '1.8.0'
  running build_ext
  building 'wordcloud.query_integral_image' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/wordcloud
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/david/tmp/venv/include -I/home/david/.local/pyenv/versions/3.9.0/include/python3.9 -c wordcloud/query_integral_image.c -o build/temp.linux-x86_64-3.9/wordcloud/query_integral_image.o
  wordcloud/query_integral_image.c: In function ‘__Pyx_modinit_type_init_code’:
  wordcloud/query_integral_image.c:16523:25: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
  16523 |   __pyx_type___pyx_array.tp_print = 0;
        |                         ^
  wordcloud/query_integral_image.c:16528:31: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
  16528 |   __pyx_type___pyx_MemviewEnum.tp_print = 0;
        |                               ^
  wordcloud/query_integral_image.c:16543:30: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
  16543 |   __pyx_type___pyx_memoryview.tp_print = 0;
        |                              ^
  wordcloud/query_integral_image.c:16556:35: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
  16556 |   __pyx_type___pyx_memoryviewslice.tp_print = 0;
        |                                   ^
  wordcloud/query_integral_image.c: In function ‘__Pyx_ParseOptionalKeywords’:
  wordcloud/query_integral_image.c:17126:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  17126 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  wordcloud/query_integral_image.c:17126:21: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  17126 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
    580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
        |                                             ^~~~~~~~~~~~~~~~~~~
  wordcloud/query_integral_image.c:17126:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  17126 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  wordcloud/query_integral_image.c:17126:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  17126 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  wordcloud/query_integral_image.c:17126:21: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  17126 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
    580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
        |                                             ^~~~~~~~~~~~~~~~~~~
  wordcloud/query_integral_image.c:17126:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  17126 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                     ^
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  wordcloud/query_integral_image.c:17142:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  17142 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                         ^
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  wordcloud/query_integral_image.c:17142:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  17142 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                         ^
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
    580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
        |                                             ^~~~~~~~~~~~~~~~~~~
  wordcloud/query_integral_image.c:17142:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  17142 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                         ^
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  wordcloud/query_integral_image.c:17142:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  17142 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                         ^
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  wordcloud/query_integral_image.c:17142:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]
  17142 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                         ^
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
    580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
        |                                             ^~~~~~~~~~~~~~~~~~~
  wordcloud/query_integral_image.c:17142:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]
  17142 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
        |                         ^
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
    446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
        |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  wordcloud/query_integral_image.c: In function ‘__Pyx_decode_c_string’:
  wordcloud/query_integral_image.c:18051:9: warning: ‘PyUnicode_FromUnicode’ is deprecated [-Wdeprecated-declarations]
  18051 |         return PyUnicode_FromUnicode(NULL, 0);
        |         ^~~~~~
  In file included from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/unicodeobject.h:1026,
                   from /home/david/.local/pyenv/versions/3.9.0/include/python3.9/Python.h:97,
                   from wordcloud/query_integral_image.c:4:
  /home/david/.local/pyenv/versions/3.9.0/include/python3.9/cpython/unicodeobject.h:551:42: note: declared here
    551 | Py_DEPRECATED(3.3) PyAPI_FUNC(PyObject*) PyUnicode_FromUnicode(
        |                                          ^~~~~~~~~~~~~~~~~~~~~
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
</pre>
</details>

> So just calling Cython again with a current version will likely solve the issue.

Would you happen to know if I can somehow trigger that when installing from PyPI? Or do I have to download the source repo for that?

But in general yes, it's likely; I encountered a similar issue with explosion/cymem, and when installing from source and re-generating the Cython output, it worked fine.

> It's probably not a good idea to check in the C code at all and cythonize when building, that would prevent similar issues in the future.

That's [the same conclusion the folks over at explosion/cymem reached](https://github.com/explosion/cymem/issues/19#issuecomment-704994400) :)

**Comment by amueller** [comment]
> Would you happen to know if I can somehow trigger that when installing from PyPI? Or do I have to download the source repo for that?

You'd have to download the source repo.
So a quick fix would be for me to release a new version with current Cython, maybe I can get to that today. And we could build 3.9 wheels as well.

**Comment by domdfcoding** [comment]
> And we could build 3.9 wheels as well.

Would be great if you could @amueller

**Comment by amueller** [comment]
Thanks for the ping, I'll try to do it within the next couple of days.

**Comment by amueller** [comment]
New Wheels should be available now.

**Comment by dlukes** [comment]
Thanks a lot! I confirm that installation now works on Python 3.9 :)

**Comment by amueller** [comment]
Thanks for testing @dlukes and sorry for the wait!

**Comment by dlukes** [comment]
No worries at all, on the contrary :)

**Comment by domdfcoding** [comment]
Wonderful, thanks 😃
