### ISSUE TITLE
Masking only considers the purest white as "white"

### ISSUE THREAD

**Issue by JordanTreDaniel** [amueller/word_cloud#606]
#### Description
When trying to use the mask feature with a mask that has a (human-interpreted) white background, like `rgb(247, 247, 247)`, the algorithm doesn't really respect that color as white. Can the threshold for what is considered "white" be loosened a bit?

I realize that the image can probably be manipulated to replace the semi-white with pure-white, but my Python (numpy?) skills aren't there yet. It would be easier for newcomers to just specify what the threshold for white is. (or for the alg to intelligently recognize backgrounds somehow?)

#### Steps/Code to Reproduce
I can place my code here upon request, but I think that this is a general problem/feature that has nothing to do with my code.

#### Expected Results
I would expect a mask like this to only place words on top of Drake's head. 
- ![Drake face](https://www.clipartkey.com/mpngs/m/146-1463643_download-drake-png-clipart-drake-nothing-was-the.png)

#### Actual Results
The algorithm considers the white background to **not** be white, so it simply places words over the whole image, and the end result is not recognizable as the original mask image.

#### Versions
macOS-10.15.6-x86_64-i386-64bit
Python 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)]
NumPy 1.19.1
matplotlib 3.3.0
wordcoud 1.7.0

**Comment by amueller** [comment]
Thanks for opening the issue. There's no one obvious way to change the threshold, and I would consider it easier to do this on the user side. How would you threshold? Using the l1 or l2 or l-infinity norm (i.e. the mean difference, absolute value difference or maximum difference)? 247 is quite not-white.
You can set the image to pure white by doing
```python
image[image.mean(axis=2) > 240] == 255
```
or something like that.
If you like we can change one of the existing examples to show this.
The parrot example actually has quite some tricks in it already:
https://github.com/amueller/word_cloud/blob/master/examples/parrot.py#L31

**Comment by JordanTreDaniel** [comment]
Hey @amueller, thanks for the quick, informative response. You're right, it is easier on my end. I am working on my skills, but even this response was enough to help me get past this problem. I will study your examples more closely.

Thanks for the great package & the help! I'd love for you to check out what you have helped me create later on this week. I'll tag you later on, or if you have an email/slack/whatever, I can send a link there! 👍

**Comment by amueller** [comment]
Glad my reply was helpful. Feel free to post your work here or email me (see github profile for example).
