### ISSUE TITLE
Error installing Wordcloud with Visual code studio (Python)

### ISSUE THREAD

**Issue by ClemPalf** [amueller/word_cloud#609]
Hi, 

I am having troubles installing the wordcloud package.
I spent a lot of time trying to solve the problem but without succes.
Here is the full "error message", its a bit long but as I am unsure which information are really useful... 

ERROR: Command errored out with exit status 1:
     command: 'c:\users\cpalf\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\cpalf\\AppData\\Local\\Temp\\pip-install-u8ckut5n\\wordcloud\\setup.py'"'"'; __file__='"'"'C:\\Users\\cpalf\\AppData\\Local\\Temp\\pip-install-u8ckut5n\\wordcloud\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\cpalf\AppData\Local\Temp\pip-record-pxo8qyrr\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\cpalf\appdata\local\programs\python\python39\Include\wordcloud'
         cwd: C:\Users\cpalf\AppData\Local\Temp\pip-install-u8ckut5n\wordcloud\
    Complete output (41 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\tokenization.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\_version.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\__init__.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\__main__.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\stopwords -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.9\wordcloud
    UPDATING build\lib.win-amd64-3.9\wordcloud/_version.py
    set build\lib.win-amd64-3.9\wordcloud/_version.py to '1.8.0'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\wordcloud
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\cpalf\appdata\local\programs\python\python39\include -Ic:\users\cpalf\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE -IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt -IC:\Program Files (x86)\Windows Kits\8.1\include\shared -IC:\Program Files (x86)\Windows Kits\8.1\include\um -IC:\Program Files (x86)\Windows Kits\8.1\include\winrt /Tcwordcloud/query_integral_image.c /Fobuild\temp.win-amd64-3.9\Release\wordcloud/query_integral_image.obj
    query_integral_image.c
    wordcloud/query_integral_image.c(2060): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    wordcloud/query_integral_image.c(2069): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    wordcloud/query_integral_image.c(16523): error C2039: 'tp_print': is not a member of '_typeobject'
    c:\users\cpalf\appdata\local\programs\python\python39\include\cpython/object.h(193): note: see declaration of '_typeobject'
    wordcloud/query_integral_image.c(16528): error C2039: 'tp_print': is not a member of '_typeobject'
    c:\users\cpalf\appdata\local\programs\python\python39\include\cpython/object.h(193): note: see declaration of '_typeobject'
    wordcloud/query_integral_image.c(16543): error C2039: 'tp_print': is not a member of '_typeobject'
    c:\users\cpalf\appdata\local\programs\python\python39\include\cpython/object.h(193): note: see declaration of '_typeobject'
    wordcloud/query_integral_image.c(16556): error C2039: 'tp_print': is not a member of '_typeobject'
    c:\users\cpalf\appdata\local\programs\python\python39\include\cpython/object.h(193): note: see declaration of '_typeobject'
    wordcloud/query_integral_image.c(17126): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
    c:\users\cpalf\appdata\local\programs\python\python39\include\cpython/unicodeobject.h(446): note: see declaration of '_PyUnicode_get_wstr_length'
    wordcloud/query_integral_image.c(17142): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
    c:\users\cpalf\appdata\local\programs\python\python39\include\cpython/unicodeobject.h(446): note: see declaration of '_PyUnicode_get_wstr_length'
    wordcloud/query_integral_image.c(18051): warning C4996: 'PyUnicode_FromUnicode': deprecated in 3.3
    c:\users\cpalf\appdata\local\programs\python\python39\include\cpython/unicodeobject.h(551): note: see declaration of 'PyUnicode_FromUnicode'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\cpalf\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\cpalf\\AppData\\Local\\Temp\\pip-install-u8ckut5n\\wordcloud\\setup.py'"'"'; __file__='"'"'C:\\Users\\cpalf\\AppData\\Local\\Temp\\pip-install-u8ckut5n\\wordcloud\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\cpalf\AppData\Local\Temp\pip-record-pxo8qyrr\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\cpalf\appdata\local\programs\python\python39\Include\wordcloud' Check the logs for full command output.

If you have any ideas regarding the origin of the problem, pls don't be shy ;)

Cheers,

**Comment by amueller** [comment]
Hi! are you meaning to compile from source or are you happy to just install?
Either way, this is likely related to #604. Right now there is no support for Python3.9. I'll try to fix it today.

**Comment by ClemPalf** [comment]
Hi Amueller, and thanks for your answer!

I'll be happy to just install it.
I will follow #604 too if you find something.

**Comment by amueller** [comment]
The PR in #610 should fix it, but I'm still waiting for CI

**Comment by amueller** [comment]
new wheels should be available, please try again to install via pip.

**Comment by ClemPalf** [comment]
Indeed, it's working well!

Thanks Andreas!
