### ISSUE TITLE
Incompatible with Python 3.9 in conda virtual environment

### ISSUE THREAD

**Issue by jackirvine97** [amueller/word_cloud#611]
In a conda virtual environment with Python 3.9.0, running:

```
conda install -c conda-forge wordcloud
```
raises an `UnsatisfiableError`. It indicates `word_cloud` is "somehow not available for the python version you are constrained to". This is resolved by rolling the virtual environment back to Python 3.8.5 .

Are there plans to make `word_cloud` Python 3.9 compatible on conda forge?

**Comment by amueller** [comment]
Thanks for reaching out.
Yes, looks like we don't have that yet:
https://anaconda.org/conda-forge/wordcloud/files

3.9 needs to be added to https://github.com/conda-forge/wordcloud-feedstock from what I see.
PR there welcome, I'm also trying to look into it.

**Comment by amueller** [comment]
CI needs to run here: https://github.com/conda-forge/wordcloud-feedstock/pull/23/ then it should be good.

**Comment by amueller** [comment]
should be there in a couple of minutes, please let me know if you're still running into issues.

**Comment by jackirvine97** [comment]
Fixed! Thank you so much for your help and thank you for this really cool repo.
