### ISSUE TITLE
Can not install on macOS 10.15.7 python 3.8.2

### ISSUE THREAD

**Issue by danmalone326** [amueller/word_cloud#613]
#### Description
Can not install on macOS 10.15.7 python 3.8.2
Got to this step in the documentation:
Before installing a compiler, report an issue describing the version of python and operating system being used.
/> uname -a
Darwin MACHINE-2 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
/> python3 -V
Python 3.8.2
/> pip3 -V
pip 19.2.3 from /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)

#### Steps/Code to Reproduce
~> pip3 install --user wordcloud

#### Expected Results
wordcloud installs

#### Actual Results
...
  Running setup.py install for wordcloud ... error
    ERROR: Command errored out with exit status 1:
     command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hn/kqwbj9_50nvc_s1nr18j3_6w0000gn/T/pip-install-exk3k3_9/wordcloud/setup.py'"'"'; __file__='"'"'/private/var/folders/hn/kqwbj9_50nvc_s1nr18j3_6w0000gn/T/pip-install-exk3k3_9/wordcloud/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/hn/kqwbj9_50nvc_s1nr18j3_6w0000gn/T/pip-record-tu2pfvd5/install-record.txt --single-version-externally-managed --compile --user --prefix=
         cwd: /private/var/folders/hn/kqwbj9_50nvc_s1nr18j3_6w0000gn/T/pip-install-exk3k3_9/wordcloud/
...         
	/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
...    
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/limits.h:8:2: error: architecture not supported
...
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
...

#### Versions
N/A

**Comment by amueller** [comment]
Thanks for opening the issue. This is indeed a bit weird. You're not using the new M1 chip, right?

It looks like something is broken with the mac installation:
https://travis-ci.org/github/amueller/word_cloud/jobs/743046463

I don't think I'll be able to fix it before the holidays, though, sorry!

**Comment by amueller** [comment]
a temporary work-around might be to install the older version, but that doesn't have python 3.8 support yet:
https://pypi.org/project/wordcloud/1.8.0/#files

**Comment by danmalone326** [comment]
Correct, this is on a 2019 Intel based mac.

**Comment by amueller** [comment]
3.9 wheels are also missing for several OSs: #614
Really need to look into this.

**Comment by amueller** [comment]
Wheel should finally be up now: https://pypi.org/project/wordcloud/#files
