### ISSUE TITLE
Package cannot be installed in Windows 64-bit operating system with Python 3.9 version. 

### ISSUE THREAD

**Issue by MadhusreeRana2001** [amueller/word_cloud#614]
Package cannot be installed in Windows 64-bit operating system with Python 3.9 version.

**Comment by EriKWDev** [comment]
Works for me with both `pip install wordcloud` and `pip install wordcloud --user`.
Is your pip up to date? What does it say when you try to install?

```yml
>>> pip --version
... pip 20.3.3 from C:\Users\ErikWG\AppData\Roaming\Python\Python39\site-packages\pip (python 3.9)
```
```yml
>>> python --version
... Python 3.9.0
```

**Comment by amueller** [comment]
Hm looks like the binary wheel is missing:
https://pypi.org/project/wordcloud/#files

So @EriKWDev you're probably building from source, right?
I need to fix the binary wheel.

As a workaround you can get it from here:
https://www.lfd.uci.edu/~gohlke/pythonlibs/

But I should really fix the current build :-/

**Comment by EriKWDev** [comment]
@amueller That's seems to be it yes!

**Comment by amueller** [comment]
@jcfr if you have any circles I'd appreciate your help ;) not sure what's up with the OS X build. I might move to github actions and wheelbuilder.

**Comment by jcfr** [comment]
Thanks for the ping, moving to github action might by sensible. In the meantime, I will have a look at this issue  tmrw or the day after.

**Comment by amueller** [comment]
@jcfr thanks, I really appreciate it. We are missing a bunch of wheels right now :-/

**Comment by amueller** [comment]
@jcfr any chance you get a minute for this? Otherwise I'll try to see if I can move to gh actions.

**Comment by amueller** [comment]
Potential work-around using Python3.8 and word_cloud 1.8.0. For Python 3.9 you would need to install a compiler. Hope to fix it soon, though.

**Comment by amueller** [comment]
Can you try again? Wheel should finally be up now: https://pypi.org/project/wordcloud/#files
