### ISSUE TITLE
Wheel file for cp39_win_amd_64 is missing?

### ISSUE THREAD

**Issue by elitist7** [amueller/word_cloud#617]
New Wheels should be available now.

_Originally posted by @amueller in https://github.com/amueller/word_cloud/issues/604#issuecomment-725686193_

**Comment by amueller** [comment]
Duplicate of #614, sorry I didn't get around to looking into the build issues yet, any help appreciated.

**Comment by amueller** [comment]
Wheel should finally be up now: https://pypi.org/project/wordcloud/#files
