### ISSUE TITLE
how to mark words that are part of phrases

### ISSUE THREAD

**Issue by moltra** [amueller/word_cloud#620]
I am creating the word list from the contents of a pandas DataFrame rows.  

The word list is coming out as one long string with a space between every word.

How can I specify what words should be kept as a phrase.  Some of these phrases are niche specific, so are not common.

**Comment by amueller** [comment]
Sorry for the slow reply. Did you figure it out? If you want to manually specify groups of words, you can use ``from_frequencies`` for arbitrary grouping. But if something is not common, then it's likely also not going to appear in the wordcloud usually.
