### ISSUE TITLE
Is there a way to view/count how many words are in a word cloud?

### ISSUE THREAD

**Issue by moltra** [amueller/word_cloud#623]
Is there a way to view/count how many words are in a word cloud?

**Comment by amueller** [comment]
Hey!
```python
len(wc.words_)
```
should do it: https://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud

**Comment by moltra** [comment]
works great.  Used 
`print(len(wc.words_))`

I am working on a Jupyter Notebook using your WordPress Cloud package.  Would you be interested in including it in your repository?

**Comment by amueller** [comment]
I think we already have many examples. If you demonstrate some new aspect that's not well documented yet, I'd be happy to include it, but otherwise I think we're all set.

**Comment by moltra** [comment]
I did not realize until I was working with smaller wordclouds that this is showing the total number of words in the file imported into the wordcloud process not the actual number of words used.

**Comment by meansoup** [comment]
It shows me frequency like 1.0, 0.18433753697649075.
Is there a way to get the actual count?

**Comment by CharlesYe8848** [comment]
您好，你发的邮件我已收到。
