### ISSUE TITLE
TypeError: Image data of dtype object cannot be converted to float

### ISSUE THREAD

**Issue by m3xw3ll** [amueller/word_cloud#634]
#### Description
I get the above error message after runing a very basic script

#### Steps/Code to Reproduce
```
import wordcloud
import matplotlib.pyplot as plt
otherdict = {"and": 54514, "or": 1654, "mouse": 45, "house":468576}
wc = wordcloud.WordCloud(max_font_size=40, max_words=100).generate_from_frequencies(otherdict)
plt.figure()
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()
```

#### Expected Results
A word cloud

#### Actual Results
Error: `TypeError: Image data of dtype object cannot be converted to float`

#### Versions

Linux-4.15.0-50-generic-x86_64-with-debian-buster-sid
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0]
NumPy 1.19.2
matplotlib 3.4.1
wordcoud 1.8.1

**Comment by amueller** [comment]
Hm I can reproduce...

**Comment by amueller** [comment]
You are passing the ``wordcloud`` module, not the ``wc`` object to ``imshow``.

**Comment by m3xw3ll** [comment]
> 
> 
> You are passing the `wordcloud` module, not the `wc` object to `imshow`. Replace `wordcloud` by `wc` in the `imshow` line and it'll work.

Thanks for the quick reply. You are right, I messed up with copy and paste. I replaced `worldcloud `by `wc `and everything is ok. 

```
import wordcloud
import matplotlib.pyplot as plt
otherdict = {"and": 54514, "or": 1654, "mouse": 45, "house":468576}
wc = wordcloud.WordCloud(max_font_size=40, max_words=100).generate_from_frequencies(otherdict)
plt.figure()
plt.imshow(wc, interpolation="bilinear")
plt.axis("off")
plt.show()
```

**Comment by SExpert12** [comment]
Hi, I am also getting the same error. My code is this:

import tensorflow
import keras
import random
import cv2, os
import numpy as np
import matplotlib.pyplot as plt

dir_data = 'C:/Users/student/PycharmProjects/errorsolve/Imagedata/'

dir_seg = dir_data + "/anote/"
dir_img = dir_data + "/training/"
#dir_seg_test = dir_data + "/annotations_prepped_test/"
#dir_img_test = dir_data + "/images_prepped_test/"

ldseg = np.array(os.listdir(dir_seg))
fnm =ldseg[0]
print(fnm)

seg = cv2.imread(dir_seg + fnm) # (360, 480, 3)
img_is = cv2.imread(dir_img + fnm )
plt.imshow(img_is)
plt.show()

mi, ma = np.min(seg), np.max(seg)
n_classes = ma - mi + 1
print("The total number of  classes =", n_classes)

fig = plt.figure(figsize=(6, 6))
ax = fig.add_subplot(1, 1, 1)
ax.imshow(img_is)
ax.set_title("original image")

I am getting this error. I have checked path and it is also showing name of first image. Where I am making mistake?

![floaterror](https://user-images.githubusercontent.com/113903215/209669404-b75616f3-b256-478d-aedc-2be238784312.png)

**Comment by amueller** [comment]
@SExpert12 your question is not related to the word_cloud module though, right?

**Comment by SExpert12** [comment]
Not related to word_cloud.
This code is from internet blog and it shown work perfectly fine. So I am not able to understand why it is not working in my case.

**Comment by amueller** [comment]
Please keep the issue tracker to problems with using ``word_cloud``. The most common issue are version mismatches or typos or missing code. Maybe check with the author of the blog post or stackoverflow.
