### ISSUE TITLE
when shall we have wordcloud for python 3.7/3.8/3.9 on mac os x?

### ISSUE THREAD

**Issue by cjs2019** [amueller/word_cloud#635]
I am used to do coding on a macbook pro and hardly find the wordcloud for python 3.7 on mac os x

when I type "pip3 install wordcloud" or some command like that in terminal,
I can only get "failed with initial frozen solve. Retrying with flexible solve."

Could you please help me? Thank you so much!

**Comment by amueller** [comment]
Hm that is strange, can you provide more details? Sorry for the slow reply.

**Comment by TAMustafa** [comment]
I get the following error text wall when attempting to pip install wordcloud on mac using Ptython 3.9.6

Collecting wordcloud
  Using cached wordcloud-1.8.1.tar.gz (220 kB)
Requirement already satisfied: numpy>=1.6.1 in ./venv/lib/python3.9/site-packages (from wordcloud) (1.21.1)
Requirement already satisfied: pillow in ./venv/lib/python3.9/site-packages (from wordcloud) (8.3.1)
Requirement already satisfied: matplotlib in ./venv/lib/python3.9/site-packages (from wordcloud) (3.4.3)
Requirement already satisfied: pyparsing>=2.2.1 in ./venv/lib/python3.9/site-packages (from matplotlib->wordcloud) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in ./venv/lib/python3.9/site-packages (from matplotlib->wordcloud) (1.3.1)
Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.9/site-packages (from matplotlib->wordcloud) (0.10.0)
Requirement already satisfied: python-dateutil>=2.7 in ./venv/lib/python3.9/site-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: six in ./venv/lib/python3.9/site-packages (from cycler>=0.10->matplotlib->wordcloud) (1.16.0)
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/Tarek/PythonApps/coinotify/venv/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3y/lvtk3s4n7mz38_kmh647gfc40000gn/T/pip-install-sgmpdjnc/wordcloud_7ed9df2304cc44e1a3dc074a3c199f42/setup.py'"'"'; __file__='"'"'/private/var/folders/3y/lvtk3s4n7mz38_kmh647gfc40000gn/T/pip-install-sgmpdjnc/wordcloud_7ed9df2304cc44e1a3dc074a3c199f42/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/3y/lvtk3s4n7mz38_kmh647gfc40000gn/T/pip-wheel-v6zx237l
       cwd: /private/var/folders/3y/lvtk3s4n7mz38_kmh647gfc40000gn/T/pip-install-sgmpdjnc/wordcloud_7ed9df2304cc44e1a3dc074a3c199f42/
  Complete output (26 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.15-x86_64-3.9
  creating build/lib.macosx-10.15-x86_64-3.9/wordcloud
  copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
  copying wordcloud/_version.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
  copying wordcloud/__init__.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
  copying wordcloud/tokenization.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
  copying wordcloud/wordcloud.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
  copying wordcloud/color_from_image.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
  copying wordcloud/__main__.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
  copying wordcloud/stopwords -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
  copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
  UPDATING build/lib.macosx-10.15-x86_64-3.9/wordcloud/_version.py
  set build/lib.macosx-10.15-x86_64-3.9/wordcloud/_version.py to '1.8.1'
  running build_ext
  building 'wordcloud.query_integral_image' extension
  creating build/temp.macosx-10.15-x86_64-3.9
  creating build/temp.macosx-10.15-x86_64-3.9/wordcloud
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/Tarek/PythonApps/coinotify/venv/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c wordcloud/query_integral_image.c -o build/temp.macosx-10.15-x86_64-3.9/wordcloud/query_integral_image.o
  xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
  Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
  See `man xcode-select` for more details.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud
    Running setup.py install for wordcloud ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/Tarek/PythonApps/coinotify/venv/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3y/lvtk3s4n7mz38_kmh647gfc40000gn/T/pip-install-sgmpdjnc/wordcloud_7ed9df2304cc44e1a3dc074a3c199f42/setup.py'"'"'; __file__='"'"'/private/var/folders/3y/lvtk3s4n7mz38_kmh647gfc40000gn/T/pip-install-sgmpdjnc/wordcloud_7ed9df2304cc44e1a3dc074a3c199f42/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/3y/lvtk3s4n7mz38_kmh647gfc40000gn/T/pip-record-ppvf3z8h/install-record.txt --single-version-externally-managed --compile --install-headers /Users/Tarek/PythonApps/coinotify/venv/include/site/python3.9/wordcloud
         cwd: /private/var/folders/3y/lvtk3s4n7mz38_kmh647gfc40000gn/T/pip-install-sgmpdjnc/wordcloud_7ed9df2304cc44e1a3dc074a3c199f42/
    Complete output (26 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.15-x86_64-3.9
    creating build/lib.macosx-10.15-x86_64-3.9/wordcloud
    copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
    copying wordcloud/_version.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
    copying wordcloud/__init__.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
    copying wordcloud/tokenization.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
    copying wordcloud/wordcloud.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
    copying wordcloud/color_from_image.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
    copying wordcloud/__main__.py -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
    copying wordcloud/stopwords -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
    copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.15-x86_64-3.9/wordcloud
    UPDATING build/lib.macosx-10.15-x86_64-3.9/wordcloud/_version.py
    set build/lib.macosx-10.15-x86_64-3.9/wordcloud/_version.py to '1.8.1'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    creating build/temp.macosx-10.15-x86_64-3.9
    creating build/temp.macosx-10.15-x86_64-3.9/wordcloud
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/Tarek/PythonApps/coinotify/venv/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c wordcloud/query_integral_image.c -o build/temp.macosx-10.15-x86_64-3.9/wordcloud/query_integral_image.o
    xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
    Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
    See `man xcode-select` for more details.
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/Tarek/PythonApps/coinotify/venv/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3y/lvtk3s4n7mz38_kmh647gfc40000gn/T/pip-install-sgmpdjnc/wordcloud_7ed9df2304cc44e1a3dc074a3c199f42/setup.py'"'"'; __file__='"'"'/private/var/folders/3y/lvtk3s4n7mz38_kmh647gfc40000gn/T/pip-install-sgmpdjnc/wordcloud_7ed9df2304cc44e1a3dc074a3c199f42/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/3y/lvtk3s4n7mz38_kmh647gfc40000gn/T/pip-record-ppvf3z8h/install-record.txt --single-version-externally-managed --compile --install-headers /Users/Tarek/PythonApps/coinotify/venv/include/site/python3.9/wordcloud Check the logs for full command output.

**Comment by xeruf** [comment]
1) please use code blocks for such output
2) does not seem related to the package but to your setup

**Comment by amueller** [comment]
Well it's related to the fact that there's currently no binary wheels, also see #642.

You can install if you set up a local compiler, but ideally it would work without one.

**Comment by mushabo101** [comment]
cannot install on mac os monterey, pyhton 3.9.7
