### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [amueller/word_cloud#639]
Problem
---------
On aarch64, pip install wordcloud builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install wordcloud should download the wheels from pypi

@amueller, Please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by amueller** [comment]
Hey! I'd be more than happy to add wheels for aarch64. Right now, no binary wheels are built because the CI setup broke (a while ago) and I haven't fixed it yet. See https://github.com/amueller/word_cloud/issues/614

**Comment by odidev** [comment]
@amueller, I added wheel build support for Linux x86_64 and aarch64 platform using GitHub Actions. Below are the changes and logs for the same:

**Changes**: https://github.com/odidev/word_cloud/commit/8a01dc40623a9122039c037c3447db314e51238c 
**Logs**: https://github.com/odidev/word_cloud/actions/runs/956889460 

Could you please have a look and share your feedback and let me know of your interest in raising a PR for the same?

**Comment by amueller** [comment]
Hey! sorry just saw this. Yes please send a PR. Can you also remove the old CI please?

**Comment by amueller** [comment]
oh, you're not building the windows wheels, right? Hm.... it would be great to do all the same way.

**Comment by odidev** [comment]
@amueller, May I know when is the release for Linux AArch64 wheel scheduled? Thanks.

**Comment by amueller** [comment]
Can you try again? Wheel should finally be up now: https://pypi.org/project/wordcloud/#files

**Comment by amueller** [comment]
Sorry for the slow response, there should be updated wheels now.

**Comment by amueller** [comment]
Closing, let me know if there's still an issue!
