### ISSUE TITLE
error: import in non-package

### ISSUE THREAD

**Issue by ZheWang711** [amueller/word_cloud#64]
Thanks for sharing, but I have a issue when running the /examples/simple.py, which is showed as follows
```Python
from .query_integral_image import query_integral_image
```
![2](https://cloud.githubusercontent.com/assets/11625541/7418200/a4fa209e-ef9e-11e4-9ae2-a405517d5247.png)
Then, I tried add two lines to import function in the /wordcloud/query_intergral_image.pyx, and it still don't work. (same problem as above)
```python
import pyximport
pyximport.install()
from .query_integral_image import query_integral_image
```
After that, I modified the line from .query_integral_image import query_integral_image
```Python
import pyximport
pyximport.install()
from query_integral_image import query_integral_image
```
and a new error occured:
![4](https://cloud.githubusercontent.com/assets/11625541/7418365/f7c7b25e-ef9f-11e4-8448-a9d1a81b825f.png)
It seems that Cython can detect the module now, but something wrong happens when building the module.

**Comment by amueller** [comment]
why are you using pyximport?
You just need to build the package using setup.py, either with ``python setup.py install`` or ``python setup.py build_ext -i`` for an inplace built.

**Comment by ZheWang711** [comment]
Oh... I forget to assign the font_path, things work now, thank you~
