### ISSUE TITLE
Low performance due to unnecessary font reloading

### ISSUE THREAD

**Issue by bzar** [amueller/word_cloud#643]
#### Description
I was having performance issues with wordcloud using relatively small workloads, so I profiled my call to `generate_from_frequencies`. Out of the total ~19 seconds running the function ~18 seconds were spent in `ImageFont.truetype`. The code seems to reload fonts from disk for every word printed.

I tested adding a trivial font caching load function to replace the calls to `ImageFont.truetype` with, which stores the loaded fonts by font path and size. This dropped the runtime to ~4 seconds, with repeated pre-cached runs closer to 1 second. This means that for my test case ~79% of the runtime is spent unnecessarily reloading fonts.

My trivial font caching code is attached below for reference.

```python
font_cache = {}


def get_font(path, size):
    font_id = (path, size)
    font = font_cache.get(font_id)
    if font is None:
        font = ImageFont.truetype(path, size)
        font_cache[font_id] = font
    return font
```
#### Steps/Code to Reproduce
- Generate a large word cloud, profile the run, note the cumulative time spent in `ImageFont.truetype`.

#### Expected Results
- Fonts are not loaded multiple times unnecessarily

#### Versions
Python 3.9.6 (default, Jun 30 2021, 10:22:16)
[GCC 11.1.0]
NumPy 1.21.1
matplotlib 3.4.2
wordcloud 1.8.1

**Comment by bzar** [comment]
I think this only actually happens when the font can't be found, so I'm closing the issue. My bad.

**Comment by amueller** [comment]
Interesting, I vaguely remember there were issues with font re-loading but I think my last profiling didn't show it was a big deal. Well if you do find issues there, please report!
