### ISSUE TITLE
Non breaking space

### ISSUE THREAD

**Issue by DannyBen** [amueller/word_cloud#648]
_My first issue here, so compliments to the chef. Love the tool, and its feature-rich command line interface._

#### Description

Would love to have a way to annotate a pair of words in the text so that they appear together always. Like "Goldman Sachs". 

I should mention I am using the CLI exclusively, not the library form.

I suspect there might be a way to do this, I just haven't found it.

I have tried using [unicode NBSP](https://www.compart.com/en/unicode/U+00A0), and tried playing with the `--regexp` parameter, but haven't succeeded.

I would love to...

1. Have word_cloud Automatically (with or without a flag) assume that *anything-with-hyphen* is one phrase (preferred).
2. Understand what character + regexp values I can use to achieve the same.

#### Steps/Code to Reproduce

```text
# test.txt
Goldman-Sachs slants research to help Democrats, top White House adviser says
```

```bash
$ wordcloud_cli \
  --text test.txt \
  --imagefile test.png \
  --repeat \
  --random_state 100
```

#### Expected Results

Have "Goldman Sachs" always appear as a phrase

#### Actual Results

![test](https://user-images.githubusercontent.com/2405099/134673083-a66b357c-5e31-4b88-8eee-289409b7423d.png)

#### Versions

Linux-5.4.0-86-generic-x86_64-with-glibc2.29
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0]
NumPy 1.21.2
matplotlib 3.4.3
wordcoud 1.8.1

**Comment by amueller** [comment]
Hey! What's the content of test.txt? By default common phrases (up to two words) are extracted as such, see "United States" here:
http://amueller.github.io/word_cloud/auto_examples/simple.html#sphx-glr-auto-examples-simple-py

If Goldman Sachs appears as two words, that probably means it appears more often alone than together in your input.

And the regex for allowing dashes in words would be something like ``[\w-]+``

**Comment by DannyBen** [comment]
The contents of the text file are in the original post, sorry - it is probably my fault for not highlighting it.

I tried with hyphen and with space:

```
Goldman Sachs slants research to help Democrats, top White House adviser says
```

I know that the library is smart enough to join words that appear **frequently** together, but I want to force some phrases, in some cases to **always** be together.

Ideally, I would love it if some intuitive way would work, like having a quoted string:

```
"Goldman Sachs" slants research to help Democrats, top White House adviser says
```

or, a hyphen (which will not be displayed, but serve as a guide for joining:

```
Goldman-Sachs slants research to help Democrats, top White House adviser says
```

**Comment by amueller** [comment]
Well you can do it two ways:
a) Adjust the regex. If you do that with the dash, you will get the dash in the text (see above for regex). You might be able to create a regex for the quotation marks so that the result doesn't include it, but I'm not entirely sure.
b) to tokenization yourself and call ``generate_from_frequencies``. That way you have full flexibility and can do whatever you like.

**Comment by DannyBen** [comment]
Well, I am using the CLI and not from within python.

Tried adjusting the regex, but it seems like the Unicode NBSP is still considered a space by the library, and it fails with some bigram related error. Any other invisible character that I found (like the brail blank character) is rendered as a square or an X, depending on the font.

**Comment by amueller** [comment]
Unfortunately the CLI doesn't support custom preprocessing so option b) is not available on the command line right now. You could probably adjust the regex so that nbsp is not considered a space. The easiest option would probably be to implement the custom preprocessing for the command line.

**Comment by DannyBen** [comment]
I think I am getting closer to a solution.

It would be nice if you can tell me what is the default regex, so that I can just amend it with NBSP. I was unable to find it in the code.

**Comment by amueller** [comment]
You can find it in the docs here:
https://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud

And in the code [here](https://github.com/amueller/word_cloud/blob/20dd15c2c9fb943eb72f383a81823144913360d0/wordcloud/wordcloud.py#L579).

It's `r"\w[\w']+"`.

**Comment by DannyBen** [comment]
Thanks. Then my regex is fine.
