### ISSUE TITLE
cli --colormap not working

### ISSUE THREAD

**Issue by ronstone2000** [amueller/word_cloud#653]
#### Description
Setting a color map from the command line has not effect.

#### Steps/Code to Reproduce

Set a color map override on the command line. eg:

Example:

`wordcloud_cli --text source/cloud-words.txt --regexp '"*([\/A-Za-z0-9_\./\\-]*)"*' --background white --colormap Greys --width 600 --height 400 --imagefile source/cloud.png`

#### Expected Results
A greyscale colormap is applied to the output.

#### Actual Results
Default colormap is applied.

#### Versions
word cloud_cli 1.8.1

**Comment by xeruf** [comment]
see #649

**Comment by amueller** [comment]
Closing as duplicate of #649.
