### ISSUE TITLE
Add more words to stopwords

### ISSUE THREAD

**Issue by cezar77** [amueller/word_cloud#654]
#### Description

There are many words that should or could be included in the stopwords list.

For example:
- another
- due
- either
- neither
- yet
- whose
- whilst
- without

#### Steps/Code to Reproduce

Whenever stopwords are used.

**Comment by amueller** [comment]
I think stopwords are pretty contextual, and I think maintaining a list is probably out of the scope for this library. We had a lengthy conversation about that in scikit-learn. The current list is a bit strange, but I don't think there's consensus really. you can always provide a custom list.
