### ISSUE TITLE
getting ERROR: Command errored out with exit status 1 when installing wordcloud with Python 3.9

### ISSUE THREAD

**Issue by bweill555** [amueller/word_cloud#656]
Apologies if the issue was already raised but I am getting the following error when installing wordcloud with Python 3.9

>pip install wordcloud

Collecting wordcloud
  Using cached wordcloud-1.8.1.tar.gz (220 kB)
Requirement already satisfied: numpy>=1.6.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from wordcloud) 
(1.21.3)
Requirement already satisfied: pillow in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from wordcloud) (8.4.0
)
Requirement already satisfied: matplotlib in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from wordcloud) (3
.4.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from mat
plotlib->wordcloud) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from matplot
lib->wordcloud) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from matplo
tlib->wordcloud) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from matplotlib-
>wordcloud) (0.10.0)
Requirement already satisfied: six in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from cycler>=0.10->matplo
tlib->wordcloud) (1.16.0)
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv
[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-p0ojzb9a\\wordcloud_b9edbff2d1364319bc24e6c2a50ef3df\\setup.py'"'"'; __fi
le__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-p0ojzb9a\\wordcloud_b9edbff2d1364319bc24e6c2a50ef3df\\setup.py'"'"';f = ge
tattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()
'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C
:\Users\User\AppData\Local\Temp\pip-wheel-jgfrh8ix'
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-p0ojzb9a\wordcloud_b9edbff2d1364319bc24e6c2a50ef3df\
  Complete output (20 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\tokenization.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\_version.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\__init__.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\__main__.py -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\stopwords -> build\lib.win-amd64-3.9\wordcloud
  copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.9\wordcloud
  UPDATING build\lib.win-amd64-3.9\wordcloud/_version.py
  set build\lib.win-amd64-3.9\wordcloud/_version.py to '1.8.1'
  running build_ext
  building 'wordcloud.query_integral_image' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/
visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud
    Running setup.py install for wordcloud ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.ar
gv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-p0ojzb9a\\wordcloud_b9edbff2d1364319bc24e6c2a50ef3df\\setup.py'"'"'; __
file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-p0ojzb9a\\wordcloud_b9edbff2d1364319bc24e6c2a50ef3df\\setup.py'"'"';f = 
getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup
()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --recor
d 'C:\Users\User\AppData\Local\Temp\pip-record-ito0hvsc\install-record.txt' --single-version-externally-managed --compile --install-hea
ders 'c:\users\user\appdata\local\programs\python\python39\Include\wordcloud'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-p0ojzb9a\wordcloud_b9edbff2d1364319bc24e6c2a50ef3df\
    Complete output (20 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\tokenization.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\_version.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\__init__.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\__main__.py -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\stopwords -> build\lib.win-amd64-3.9\wordcloud
    copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.9\wordcloud
    UPDATING build\lib.win-amd64-3.9\wordcloud/_version.py
    set build\lib.win-amd64-3.9\wordcloud/_version.py to '1.8.1'
    running build_ext
    building 'wordcloud.query_integral_image' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.co
m/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\user\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, 
sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-p0ojzb9a\\wordcloud_b9edbff2d1364319bc
24e6c2a50ef3df\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-p0ojzb9a\\wordcloud_b9edbff2d1364319bc2
4e6c2a50ef3df\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'fr
om setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, 
'"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-ito0hvsc\install-record.txt' --single-version-externall
y-managed --compile --install-headers 'c:\users\user\appdata\local\programs\python\python39\Include\wordcloud' Check the logs for full 
command output.
WARNING: You are using pip version 21.1.1; however, version 21.3.1 is available.
You should consider upgrading via the 'c:\users\user\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' co
mmand.

**Comment by Abeautifulsnow** [comment]
I meet the same error, and this is my error details:

```bash
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/dapeng/.virtualenvs/py39/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mq/kc_gdgd54rb08z8h4bbly5p40000gn/T/pip-install-uyc9m47v/wordcloud_30014422f9d34074a6a12a05f87b5d29/setup.py'"'"'; __file__='"'"'/private/var/folders/mq/kc_gdgd54rb08z8h4bbly5p40000gn/T/pip-install-uyc9m47v/wordcloud_30014422f9d34074a6a12a05f87b5d29/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/mq/kc_gdgd54rb08z8h4bbly5p40000gn/T/pip-wheel-_iua1jqg
       cwd: /private/var/folders/mq/kc_gdgd54rb08z8h4bbly5p40000gn/T/pip-install-uyc9m47v/wordcloud_30014422f9d34074a6a12a05f87b5d29/
  Complete output (72 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11-x86_64-3.9
  creating build/lib.macosx-11-x86_64-3.9/wordcloud
  copying wordcloud/wordcloud_cli.py -> build/lib.macosx-11-x86_64-3.9/wordcloud
  copying wordcloud/_version.py -> build/lib.macosx-11-x86_64-3.9/wordcloud
  copying wordcloud/__init__.py -> build/lib.macosx-11-x86_64-3.9/wordcloud
  copying wordcloud/tokenization.py -> build/lib.macosx-11-x86_64-3.9/wordcloud
  copying wordcloud/wordcloud.py -> build/lib.macosx-11-x86_64-3.9/wordcloud
  copying wordcloud/color_from_image.py -> build/lib.macosx-11-x86_64-3.9/wordcloud
  copying wordcloud/__main__.py -> build/lib.macosx-11-x86_64-3.9/wordcloud
  copying wordcloud/stopwords -> build/lib.macosx-11-x86_64-3.9/wordcloud
  copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-11-x86_64-3.9/wordcloud
  UPDATING build/lib.macosx-11-x86_64-3.9/wordcloud/_version.py
  set build/lib.macosx-11-x86_64-3.9/wordcloud/_version.py to '1.8.1'
  running build_ext
  building 'wordcloud.query_integral_image' extension
  creating build/temp.macosx-11-x86_64-3.9
  creating build/temp.macosx-11-x86_64-3.9/wordcloud
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/usr/local/opt/tcl-tk/include -I/Users/dapeng/.virtualenvs/py39/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c wordcloud/query_integral_image.c -o build/temp.macosx-11-x86_64-3.9/wordcloud/query_integral_image.o
  clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -L/usr/local/opt/tcl-tk/lib -I/usr/local/opt/tcl-tk/include build/temp.macosx-11-x86_64-3.9/wordcloud/query_integral_image.o -o build/lib.macosx-11-x86_64-3.9/wordcloud/query_integral_image.cpython-39-darwin.so
  installing to build/bdist.macosx-11-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-11-x86_64
  creating build/bdist.macosx-11-x86_64/wheel
  creating build/bdist.macosx-11-x86_64/wheel/wordcloud
  copying build/lib.macosx-11-x86_64-3.9/wordcloud/wordcloud_cli.py -> build/bdist.macosx-11-x86_64/wheel/wordcloud
  copying build/lib.macosx-11-x86_64-3.9/wordcloud/stopwords -> build/bdist.macosx-11-x86_64/wheel/wordcloud
  copying build/lib.macosx-11-x86_64-3.9/wordcloud/DroidSansMono.ttf -> build/bdist.macosx-11-x86_64/wheel/wordcloud
  copying build/lib.macosx-11-x86_64-3.9/wordcloud/_version.py -> build/bdist.macosx-11-x86_64/wheel/wordcloud
  copying build/lib.macosx-11-x86_64-3.9/wordcloud/__init__.py -> build/bdist.macosx-11-x86_64/wheel/wordcloud
  copying build/lib.macosx-11-x86_64-3.9/wordcloud/tokenization.py -> build/bdist.macosx-11-x86_64/wheel/wordcloud
  copying build/lib.macosx-11-x86_64-3.9/wordcloud/wordcloud.py -> build/bdist.macosx-11-x86_64/wheel/wordcloud
  copying build/lib.macosx-11-x86_64-3.9/wordcloud/query_integral_image.cpython-39-darwin.so -> build/bdist.macosx-11-x86_64/wheel/wordcloud
  copying build/lib.macosx-11-x86_64-3.9/wordcloud/color_from_image.py -> build/bdist.macosx-11-x86_64/wheel/wordcloud
  copying build/lib.macosx-11-x86_64-3.9/wordcloud/__main__.py -> build/bdist.macosx-11-x86_64/wheel/wordcloud
  running install_egg_info
  running egg_info
  writing wordcloud.egg-info/PKG-INFO
  writing dependency_links to wordcloud.egg-info/dependency_links.txt
  writing entry points to wordcloud.egg-info/entry_points.txt
  writing requirements to wordcloud.egg-info/requires.txt
  writing top-level names to wordcloud.egg-info/top_level.txt
  reading manifest file 'wordcloud.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'wordcloud.egg-info/SOURCES.txt'
  Copying wordcloud.egg-info to build/bdist.macosx-11-x86_64/wheel/wordcloud-1.8.1-py3.9.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/mq/kc_gdgd54rb08z8h4bbly5p40000gn/T/pip-install-uyc9m47v/wordcloud_30014422f9d34074a6a12a05f87b5d29/setup.py", line 9, in <module>
      setup(
    File "/Users/dapeng/.virtualenvs/py39/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/dapeng/.virtualenvs/py39/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 328, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/Users/dapeng/.virtualenvs/py39/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 252, in get_tag
      plat_name = get_platform(self.bdist_dir)
    File "/Users/dapeng/.virtualenvs/py39/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 48, in get_platform
      result = calculate_macosx_platform_tag(archive_root, result)
    File "/Users/dapeng/.virtualenvs/py39/lib/python3.9/site-packages/wheel/macosx_libfile.py", line 356, in calculate_macosx_platform_tag
      assert len(base_version) == 2
  AssertionError
  ----------------------------------------
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
```

**My Environment**

- Python: 3.9.7
- pip: 21.3.1

Thx for your help.

**Comment by andrevargas22** [comment]
I had the same issue, you can see this in the error message:

> > error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

Open the link and install Microsoft C++ Build Tools, after that restart and it should work.

It worked for me.

**Comment by Muhammad-Ahsan-Rasheed** [comment]
pip install matplotlib
pip install pandas
pip install wordcloud

Go with this.

**Comment by amueller** [comment]
I think just ``pip install wordcloud`` should work now since I pushed the wheels. Let me know if that gives you any error. Thanks!
