### ISSUE TITLE
request for happy-emoji.txt example :)

### ISSUE THREAD

**Issue by Alcampopiano** [amueller/word_cloud#662]
Hello! Love this library and I'm making a tutorial/template to be featured in [Deepnote](https://deepnote.com/).

I have two questions:
1. In the [emoji example](https://amueller.github.io/word_cloud/auto_examples/emoji.html?highlight=happy%20emoji%20txt), there is a reference to a file called happy-emoji.txt. Are you able to point me to that or provide the text here? (I just want to make sure I understand the raw contents of that file properly).

2. Suppose I had a text file with emojis as well as regular text (e.g., comments pulled from YouTube). Is it possible in word_cloud to create a cloud that has both the emoji images and the regular words in the same cloud?

Thank you so much!

**Comment by Alcampopiano** [comment]
Oooo! Okay, I can see that actually I can use an emoji directly in the text file (e.g., 😊). Or, I can use the [emoji](https://pypi.org/project/emoji/) library to convert the the CLDR short names (e.g., ":grinning_face_with_big_eyes:") into emojis. Word cloud can then read that result and displays emojis as expected. Awesome!

Lastly, yes indeed, regular words alongside emojis works perfectly fine in word_cloud!

**Comment by amueller** [comment]
Glad you figured it out so quickly! Happy to take any improvements to the documentation that makes the examples easier to follow!
