### ISSUE TITLE
cannot import wordcloud in Python 3.9, macOS

### ISSUE THREAD

**Issue by FLoraHtg** [amueller/word_cloud#675]
wordcloud cannot be installed via pip, so I tried:
conda install -c [https://conda.anaconda.org/conda-forge wordcloud

It seemed to be working:
pip freeze
...
wordcloud @ file:///Users/runner/miniforge3/conda-bld/wordcloud_1637007722518/work
...

or pip list:
...
wordcloud                          1.8.1
...

However, when importing:
import wordcloud
ModuleNotFoundError: No module named 'wordcloud'

#### Versions
macOS-12.3.1-x86_64-i386-64bit
Python 3.9.12 (v3.9.12:b28265d7e6, Mar 23 2022, 18:22:40) 
[Clang 13.0.0 (clang-1300.0.29.30)]
NumPy 1.22.3
matplotlib 3.5.1

import wordcloud; print("wordcoud", wordcloud.__version__)
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    import wordcloud; print("wordcoud", wordcloud.__version__)
ModuleNotFoundError: No module named 'wordcloud'
-->

Thank you for helping!

**Comment by amueller** [comment]
It should work using pip now, sorry I didn't reply earlier.
