### ISSUE TITLE
Can you upload wheels for Windows and Python 3.10 to PyPI

### ISSUE THREAD

**Issue by sulunemre** [amueller/word_cloud#676]
#### Description

This GitHub Action may help: https://github.com/pypa/cibuildwheel

**Comment by amueller** [comment]
I had trouble with my pypi token last time I tried, I'll have to give it another go...
The current config should work in theory:
https://github.com/amueller/word_cloud/blob/master/.github/workflows/publish_pypi.yml

**Comment by amueller** [comment]
Can you try again? Wheel should finally be up now: https://pypi.org/project/wordcloud/#files

**Comment by sulunemre** [comment]
Sorry for the late reply. It works perfectly, thanks
