### ISSUE TITLE
Diacritic characters not rendering in wordcloud image

### ISSUE THREAD

**Issue by kodymoodley** [amueller/word_cloud#679]
Hi, thanks for the nice wordcloud library! I am having trouble with certain diacritic characters. E.g., the diacritic marks in the word `Kṛṣṇa` are not recognized. I get the following output:

<img width="624" alt="wordcloud-diacritics-krsna" src="https://user-images.githubusercontent.com/13569029/166220625-92c169da-c159-4ab2-b48f-4dc5cf30f80a.png">

This is my code:

```
text = ""
with open("test.txt", "r", encoding="utf-8") as f:
    text = f.read()
    
import wordcloud
from wordcloud import WordCloud
import matplotlib.pyplot as plt

wordcloud = WordCloud(width = 800, height = 800,
                background_color ='white',
                min_font_size = 10).generate(text)
                  
plt.figure(figsize = (8, 8), facecolor = None)
plt.imshow(wordcloud)
plt.axis("off")
plt.tight_layout(pad = 0)
plt.show()
```

I attach the test file test.txt as well:

[test.txt](https://github.com/amueller/word_cloud/files/8602294/test.txt)

_Originally posted by @kodymoodley in https://github.com/amueller/word_cloud/issues/148#issuecomment-1114707204_

**Comment by kodymoodley** [comment]
The solution is here: https://github.com/python-pillow/Pillow/issues/6258

It is a problem with PIL (Pillow).

**Comment by amueller** [comment]
Glad you worked it out (and sorry for the delay in responding). Closing.
