### ISSUE TITLE
Unable to install via pip on Python 3.10.4

### ISSUE THREAD

**Issue by Marcus5408** [amueller/word_cloud#680]
#### Description
When attempting to install wordcloud using pip on python version 3.10.4, the install fails with a `subprocess-exited-with-error` error and a `legacy-install-failure` error.

#### Steps/Code to Reproduce
1.  Open a new Windows Powershell window (I'm using PowerShell 7.2.4 in Windows Terminal)
2. Ensure Python 3.10.4 is the default version
3. Attempt to install by typing `pip install wordcloud`

#### Expected Results
Library installs correctly.

#### Actual Results
`  Running setup.py install for wordcloud ... error
  error: subprocess-exited-with-error

  × Running setup.py install for wordcloud did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\wordcloud
      copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.10\wordcloud
      copying wordcloud\tokenization.py -> build\lib.win-amd64-3.10\wordcloud
      copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.10\wordcloud
      copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-3.10\wordcloud
      copying wordcloud\_version.py -> build\lib.win-amd64-3.10\wordcloud
      copying wordcloud\__init__.py -> build\lib.win-amd64-3.10\wordcloud
      copying wordcloud\__main__.py -> build\lib.win-amd64-3.10\wordcloud
      copying wordcloud\stopwords -> build\lib.win-amd64-3.10\wordcloud
      copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.10\wordcloud
      UPDATING build\lib.win-amd64-3.10\wordcloud/_version.py
      set build\lib.win-amd64-3.10\wordcloud/_version.py to '1.8.1'
      running build_ext
      building 'wordcloud.query_integral_image' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wordcloud

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

#### Versions
Windows-10-10.0.25115-SP0
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
NumPy 1.22.2
matplotlib 3.5.2
wordcloud version not applicable

**Comment by edurojasr** [comment]
Hi @Marcus5408!

I know you are in Windows, but maybe this help.

I fix the problem in Ubuntu by having the packages `sudo apt install build-essential python3-dev` which adds the gcc compiler and other tools, I don't know if there is necessary for Windows or you need equivalent packages for that!

**Comment by Marcus5408** [comment]
So I managed to fix it by installing Visual Studio (I don't know how it helped but somehow it did) and using the visual studio installer to install the build tools.

**Comment by AixPrime** [comment]
It works for me on MacOs. Is it a windows problem?

**Comment by andrey-mat** [comment]
Trying to install word cloud on MacOS - got this issue
`andreymat@192 Downloads % pip3 install wordcloud                               
Collecting wordcloud
  Using cached wordcloud-1.8.2.2.tar.gz (220 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.6.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from wordcloud) (1.24.1)
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from wordcloud) (9.3.0)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from wordcloud) (3.6.3)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib->wordcloud) (1.0.6)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib->wordcloud) (4.38.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib->wordcloud) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib->wordcloud) (22.0)
Requirement already satisfied: pyparsing>=2.2.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib->wordcloud) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-311
      creating build/lib.macosx-10.9-universal2-cpython-311/wordcloud
      copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.9-universal2-cpython-311/wordcloud
      copying wordcloud/_version.py -> build/lib.macosx-10.9-universal2-cpython-311/wordcloud
      copying wordcloud/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/wordcloud
      copying wordcloud/tokenization.py -> build/lib.macosx-10.9-universal2-cpython-311/wordcloud
      copying wordcloud/wordcloud.py -> build/lib.macosx-10.9-universal2-cpython-311/wordcloud
      copying wordcloud/color_from_image.py -> build/lib.macosx-10.9-universal2-cpython-311/wordcloud
      copying wordcloud/__main__.py -> build/lib.macosx-10.9-universal2-cpython-311/wordcloud
      copying wordcloud/stopwords -> build/lib.macosx-10.9-universal2-cpython-311/wordcloud
      copying wordcloud/DroidSansMono.ttf -> build/lib.macosx-10.9-universal2-cpython-311/wordcloud
      UPDATING build/lib.macosx-10.9-universal2-cpython-311/wordcloud/_version.py
      set build/lib.macosx-10.9-universal2-cpython-311/wordcloud/_version.py to '1.8.2.2'
      running build_ext
      building 'wordcloud.query_integral_image' extension
      creating build/temp.macosx-10.9-universal2-cpython-311
      creating build/temp.macosx-10.9-universal2-cpython-311/wordcloud
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c wordcloud/query_integral_image.c -o build/temp.macosx-10.9-universal2-cpython-311/wordcloud/query_integral_image.o
      wordcloud/query_integral_image.c:196:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud
  Running setup.py install for wordcloud ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for wordcloud did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running install
      /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-311
      creating build/lib.macosx-10.9-universal2-cpython-311/wordcloud
      copying wordcloud/wordcloud_cli.py -> build/lib.macosx-10.9-universal2-cpython-311/wordcloud
      copying wordcloud/_version.py -> build/lib.macosx-10.9-universal2-cpython-311/wordcloud`
