### ISSUE TITLE
DeprecationWarning: ROTATE_90 is deprecated and will be removed in Pillow 10

### ISSUE THREAD

**Issue by Guillaume-Fgt** [amueller/word_cloud#681]
#### Description
While running some test on my last project, I received this warning in the pytest console output:

> /home/user/Documents/Python/Wordcloud_Youtube/.venv/lib/python3.10/site-packages/wordcloud/wordcloud.py:513: DeprecationWarning: ROTATE_90 is deprecated and will be removed in Pillow 10 (2023-07-01). Use Transpose.ROTATE_90 instead.
    Image.ROTATE_90)

So apparently, an update is needed related to Pillow.

My package versions:
wordcloud = "^1.8.1"
Pillow = "^9.1.1"

**Comment by amueller** [comment]
This should be fixed now, thanks!
