### ISSUE TITLE
Failing to install wordcloud in a virtual env using Python3.8

### ISSUE THREAD

**Issue by mporwal011** [amueller/word_cloud#682]
#### Description
Failing to install `wordcloud` package in a venv using Python3.8.

#### Steps/Code to Reproduce
Have tried below commands. All fail with the same error.
`pip install wordcloud`
`pip3 install wordcloud==1.8.1 `
`pip3 install wordcloud`
`python3 -m pip install wordcloud`

#### Expected Results
Package installed successfully.

#### Actual Results

```
Installing collected packages: wordcloud
  Running setup.py install for wordcloud ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for wordcloud did not run successfully.
  │ exit code: 1
  ╰─> [123 lines of output]
...
...
 note: '__uint128_t' declared here
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
              ^
      note: '__uint128_t' declared here
      In file included from wordcloud/query_integral_image.c:4:
      In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
      typedef __uint32_t      __darwin_wctype_t;
              ^
      note: '__uint128_t' declared here
      In file included from wordcloud/query_integral_image.c:4:
      In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:
      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:31:
      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
      #error architecture not supported
       ^
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wordcloud

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

#### Versions
`Python 3.8.2`

**Comment by mporwal011** [comment]
I'm on Mac. The issue happens on Mac as well.

**Comment by jremb** [comment]
> I checked and the issue is happening on windows 11, it installs correctly on windows 10. Has anyone identified any fix so far?

I experienced this issue on Ubuntu 22.04 LTS with Python 3.10.4 and 3.10.5 in virtual environments and came here to see if there was a solution. After seeing the last two posts, I tried it on Windows and Mac. My results:

- Windows 11, Python 3.10.5 works for me
- Mac (M1) Monterey, Python 3.9.4 and 3.10.5 works for me.

This lead me to look closer at my Python install on Linux. Back on Linux mentioned above, `conda install -c conda-forge wordcloud` works in terminal and `%pip install wordcloud` works in a Jupyter Lab notebook. 

I had already followed the steps here: https://devguide.python.org/setup/#build-dependencies

But I was still missing the last three dependencies here: https://stackoverflow.com/a/49696062 (libgdm-dev, libdb4o-cil-dev, libpcap-dev). After installing them and rebuilding Python 3.10.5, I was able to install wordcloud with pip in virtual environment.

**Comment by amueller** [comment]
Hm the mac issue could be related to using clang? are you using Conda? Sorry I'm still behind on getting the wheels built.

**Comment by amueller** [comment]
Can you try again? Wheel should finally be up now: https://pypi.org/project/wordcloud/#files

**Comment by Muhammad-Ahsan-Rasheed** [comment]
I also encountered the same issue but after that when I installed the other packages like matplotlib then pandas and after that when I installed wordcloud it installed successfully. 

Python: 3.9, IDE: PyCharm, OS: Windows 10

**Comment by amueller** [comment]
@Muhammad-Ahsan-Rasheed Can you say what issue exactly you encounterd?

**Comment by ITHOL** [comment]
Do anyone have a solution for this issue? I am really new to python and pycharm and wanted to practice.

**Comment by amueller** [comment]
@ITHOL  can you say what your issue is exactly? What version of Python are you on?

**Comment by AM764733** [comment]
I am as well facing the error in virtual env in installing wordcloud, I am using python 3.9 and windows 11

error

  DEPRECATION: wordcloud is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for wordcloud ... error
  error: subprocess-exited-with-error

**Comment by doaa-altarawy** [comment]
I have the same issue also other members of my team. It previously used to work for python-3.8.16.

OS: Ubuntu (on GCP VertexAI, Pytorch image)
Python 3.11.0
conda env


```
× Running setup.py install for wordcloud did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running install
      /opt/conda/envs/nlp/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/color_from_image.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/_version.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/__init__.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/wordcloud_cli.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/tokenization.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/wordcloud.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/__main__.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/stopwords -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/DroidSansMono.ttf -> build/lib.linux-x86_64-cpython-311/wordcloud
      UPDATING build/lib.linux-x86_64-cpython-311/wordcloud/_version.py
      set build/lib.linux-x86_64-cpython-311/wordcloud/_version.py to '1.8.2.2'
      running build_ext
      building 'wordcloud.query_integral_image' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/wordcloud
      gcc -pthread -B /opt/conda/envs/nlp/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/envs/nlp/include -fPIC -O2 -isystem /opt/conda/envs/nlp/include -fPIC -I/opt/conda/envs/nlp/include/python3.11 -c wordcloud/query_integral_image.c -o build/temp.linux-x86_64-cpython-311/wordcloud/query_integral_image.o
      wordcloud/query_integral_image.c:196:12: fatal error: longintrepr.h: No such file or directory
         #include "longintrepr.h"
                  ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wordcloud

```

**Comment by banduoba** [comment]
I am macOS 13.1,M2 Max processor, have a solution?

**Comment by huawuque404** [comment]
God, at this point, I have the same problem
OS：windows 10
Python 3.11.2
Is there a solution?
Console output：
```
Collecting wordcloud
  Downloading wordcloud-1.8.2.2.tar.gz (220 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.8/220.8 kB 97.0 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.6.1 in d:\ruanjian\python3-11-2\lib\site-packages (from wordcloud) (1.24.2)
Requirement already satisfied: pillow in d:\ruanjian\python3-11-2\lib\site-packages (from wordcloud) (9.4.0)
Requirement already satisfied: matplotlib in d:\ruanjian\python3-11-2\lib\site-packages (from wordcloud) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in d:\ruanjian\python3-11-2\lib\site-packages (from matplotlib->wordcloud) (1.0.7)
Requirement already satisfied: cycler>=0.10 in d:\ruanjian\python3-11-2\lib\site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\ruanjian\python3-11-2\lib\site-packages (from matplotlib->wordcloud) (4.39.2)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\ruanjian\python3-11-2\lib\site-packages (from matplotlib->wordcloud) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\34933\appdata\roaming\python\python311\site-packages (from matplotlib->wordcloud) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\ruanjian\python3-11-2\lib\site-packages (from matplotlib->wordcloud) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in d:\ruanjian\python3-11-2\lib\site-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: six>=1.5 in d:\ruanjian\python3-11-2\lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)
Installing collected packages: wordcloud
  DEPRECATION: wordcloud is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for wordcloud ... error
  error: subprocess-exited-with-error

  × Running setup.py install for wordcloud did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      running install
      D:\ruanjian\Python3-11-2\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\wordcloud
      copying wordcloud\color_from_image.py -> build\lib.win-amd64-cpython-311\wordcloud
      copying wordcloud\tokenization.py -> build\lib.win-amd64-cpython-311\wordcloud
      copying wordcloud\wordcloud.py -> build\lib.win-amd64-cpython-311\wordcloud
      copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-cpython-311\wordcloud
      copying wordcloud\_version.py -> build\lib.win-amd64-cpython-311\wordcloud
      copying wordcloud\__init__.py -> build\lib.win-amd64-cpython-311\wordcloud
      copying wordcloud\__main__.py -> build\lib.win-amd64-cpython-311\wordcloud
      copying wordcloud\stopwords -> build\lib.win-amd64-cpython-311\wordcloud
      copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-cpython-311\wordcloud
      UPDATING build\lib.win-amd64-cpython-311\wordcloud/_version.py
      set build\lib.win-amd64-cpython-311\wordcloud/_version.py to '1.8.2.2'
      running build_ext
      building 'wordcloud.query_integral_image' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\wordcloud
      "D:\ruanjian\Visual Studio\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\ruanjian\Python3-11-2\include -ID:\ruanjian\Python3-11-2\Include "-ID:\ruanjian\Visual Studio\VC\Tools\MSVC\14.33.31629\include" "-ID:\ruanjian\Visual Studio\VC\Tools\MSVC\14.33.31629\ATLMFC\include" "-ID:\ruanjian\Visual Studio\VC\Auxiliary\VS\include" "-ID:\Windows Kits\10\include\10.0.19041.0\ucrt" "-ID:\Windows Kits\10\\include\10.0.19041.0\\um" "-ID:\Windows Kits\10\\include\10.0.19041.0\\shared" "-ID:\Windows Kits\10\\include\10.0.19041.0\\winrt" "-ID:\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" /Tcwordcloud/query_integral_image.c /Fobuild\temp.win-amd64-cpython-311\Release\wordcloud/query_integral_image.obj
      query_integral_image.c
      wordcloud/query_integral_image.c(196): fatal error C1083: 无法打开包括文件: “longintrepr.h”: No such file or directory
      error: command 'D:\\ruanjian\\Visual Studio\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wordcloud

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by Shargil** [comment]
Same here! Macbook pro Venture 13.1

**Comment by juliencatanese** [comment]
I have the problem when trying to install skater

I type in my MacBook Pro (macOS 13.3.1 ) Terminal :  
pip install skater
... 
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
      22 warnings and 20 errors generated.
      error: Setup script exited with error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for skater
  Running setup.py clean for skater
  Building wheel for pydotplus (setup.py) ... done
  Created wheel for pydotplus: filename=pydotplus-2.0.2-py3-none-any.whl size=24554 sha256=69d4d0e466fd2a2ae7a44748879255cb9f516aebb23b1f89279bb0e7b386b466
  Stored in directory: 
.../Library/Caches/pip/wheels/89/e5/de/6966007cf223872eedfbebbe0e074534e72e9128c8fd4b55eb
  Building wheel for scikit-image (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [959 lines of output]
      Partial import of skimage during the build process.
      running bdist_wheel
      running build
      running config_cc
....
     CCompilerOpt.cache_flush[809] : write cache to path -> /private/var/folders/fr/j3w14lqd18702_9chfn3vk580000gn/T/pip-install-pleqx_ze/scikit-image_0171d3d59ad94930ade73eaaf01d7e70/build/temp.macosx-10.9-x86_64-cpython-39/ccompiler_opt_cache_ext.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-image
  Running setup.py clean for scikit-image
  Building wheel for wordcloud (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [322 lines of output]
      running bdist_wheel
...
 fatal error: too many errors emitted, stopping now [-ferror-limit=]
      22 warnings and 20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
  Building wheel for ds-lime (setup.py) ... done
  Created wheel for ds-lime: filename=ds_lime-0.1.1.27-py3-none-any.whl size=261588 sha256=5724a56d418e53ade88282f44da4b4e89724c6599444dd5b0758f6de339d9e3f
  Stored in directory: 
... /Library/Caches/pip/wheels/6e/32/0b/7cea4430c887ca12f7dfc24ba4fc24e90906e8c1105b4e61c5
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1257 sha256=0975a26b32bc8c6a257de6b041767e88c5576b49d6b5faa4688fb0cc88899adb
  Stored in directory: 
..../Library/Caches/pip/wheels/73/2b/cb/099980278a0c9a3e57ff1a89875ec07bfa0b6fcbebb9a8cad3
Successfully built pydotplus ds-lime bs4
Failed to build skater scikit-image wordcloud
Installing collected packages: joblib, pydotplus, Jinja2, dill, multiprocess, bs4, wordcloud, ds-lime, scikit-image, skater
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
  Attempting uninstall: Jinja2
    Found existing installation: Jinja2 2.11.3
    Uninstalling Jinja2-2.11.3:
      Successfully uninstalled Jinja2-2.11.3
  Attempting uninstall: dill
    Found existing installation: dill 0.3.4
    Uninstalling dill-0.3.4:
      Successfully uninstalled dill-0.3.4
  Running setup.py install for wordcloud ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for wordcloud did not run successfully.
  │ exit code: 1
  ╰─> [324 lines of output]
      running install
 .../opt/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
...
      fatal error: too many errors emitted, stopping now [-ferror-limit=]
      22 warnings and 20 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wordcloud
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.



============================================
BUT THEN I did: 
pip install wordcloud
Collecting wordcloud

  Downloading wordcloud-1.8.2.2-cp39-cp39-macosx_10_9_x86_64.whl (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.5/160.5 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.6.1 in ./opt/anaconda3/lib/python3.9/site-packages (from wordcloud) (1.21.5)
Requirement already satisfied: matplotlib in ./opt/anaconda3/lib/python3.9/site-packages (from wordcloud) (3.5.2)
Requirement already satisfied: pillow in ./opt/anaconda3/lib/python3.9/site-packages (from wordcloud) (9.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in ./opt/anaconda3/lib/python3.9/site-packages (from matplotlib->wordcloud) (1.4.2)
Requirement already satisfied: python-dateutil>=2.7 in ./opt/anaconda3/lib/python3.9/site-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in ./opt/anaconda3/lib/python3.9/site-packages (from matplotlib->wordcloud) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in ./opt/anaconda3/lib/python3.9/site-packages (from matplotlib->wordcloud) (4.25.0)
Requirement already satisfied: cycler>=0.10 in ./opt/anaconda3/lib/python3.9/site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: packaging>=20.0 in ./opt/anaconda3/lib/python3.9/site-packages (from matplotlib->wordcloud) (21.3)
Requirement already satisfied: six>=1.5 in ./opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)
Installing collected packages: wordcloud
Successfully installed wordcloud-1.8.2.2

================
However if I try to install skater again (after having successfully install wordcloud)
i get the same error as before. 

 14 warnings and 4 errors generated.
      error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /...
3.9/numpy/distutils/include -I/ ... /opt/anaconda3/include/python3.9 -c skimage/_shared/transform.c -o build/temp.macosx-10.9-x86_64-cpython-39/skimage/_shared/transform.o -MMD -MF build/temp.macosx-10.9-x86_64-cpython-39/skimage/_shared/transform.o.d -msse -msse2 -msse3" failed with exit status 1
      
      ########### EXT COMPILER OPTIMIZATION ###########
      Platform      :
        Architecture: x64
        Compiler    : clang
      
      CPU baseline  :
        Requested   : 'min'
        Enabled     : SSE SSE2 SSE3
        Flags       : -msse -msse2 -msse3
        Extra checks: none
      
      CPU dispatch  :
        Requested   : 'max -xop -fma4'
        Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
        Generated   : none
      CCompilerOpt.cache_flush[809] : write cache to path -> /private/var/folders/fr/j3w14lqd18702_9chfn3vk580000gn/T/pip-install-rgqp59f2/scikit-image_653ba3bbc63b41afba09b79636c6a286/build/temp.macosx-10.9-x86_64-cpython-39/ccompiler_opt_cache_ext.py
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-image
  Running setup.py clean for scikit-image
  Building wheel for wordcloud (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [322 lines of output]



22 warnings and 20 errors generated.
error: command '/usr/bin/clang' failed with exit code 1
[end of output]
....
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> wordcloud


=============================================
sorry for the long error message butmaybe that can help to identify the problem  ...

**Comment by amueller** [comment]
Wheels have been updated, I'm closing this issue now, please open a new issue if you keep running into any issues.
