### ISSUE TITLE
pip install doesn't work?

### ISSUE THREAD

**Issue by amueller** [amueller/word_cloud#69]
pip install from pypi didn't fetch the cython file... damn.

**Comment by scls19fr** [comment]
I'm trying to install word_cloud using `pip` but I'm facing the following error

    $ pip install wordcloud
    Collecting wordcloud
      Using cached wordcloud-1.1.0.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-lE5125/wordcloud/setup.py", line 10, in <module>
            ext_modules=cythonize('wordcloud/query_integral_image.pyx'),
          File "//anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 754, in cythonize
            aliases=aliases)
          File "//anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 649, in create_extension_list
            for file in nonempty(extended_iglob(filepattern), "'%s' doesn't match any files" % filepattern):
          File "//anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 103, in nonempty
            raise ValueError(error_msg)
        ValueError: 'wordcloud/query_integral_image.pyx' doesn't match any files

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-lE5125/wordcloud

I'm using Mac OS X 10.10.3 and Anaconda Python.

Do you know a workaround ?

**Comment by amueller** [comment]
On 06/19/2015 09:01 AM, scls19fr wrote:
>
> I'm trying to install word_cloud using |pip| but I'm facing the 
> following error
>
> |$ pip install wordcloud
> Collecting wordcloud
>    Using cached wordcloud-1.1.0.tar.gz
>      Complete output from command python setup.py egg_info:
>      Traceback (most recent call last):
>        File "<string>", line 20, in <module>
>        File "/private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-lE5125/wordcloud/setup.py", line 10, in <module>
>          ext_modules=cythonize('wordcloud/query_integral_image.pyx'),
>        File "//anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 754, in cythonize
>          aliases=aliases)
>        File "//anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 649, in create_extension_list
>          for file in nonempty(extended_iglob(filepattern), "'%s' doesn't match any files" % filepattern):
>        File "//anaconda/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 103, in nonempty
>          raise ValueError(error_msg)
>      ValueError: 'wordcloud/query_integral_image.pyx' doesn't match any files
>
>      ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-build-lE5125/wordcloud
> |
>
> I'm using Mac OS X 10.10.3 and Anaconda Python.
>
> Do you know a workaround ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/amueller/word_cloud/issues/69#issuecomment-113508399>.
>
you can pip-install from the github repo. I have to fix the pipy package :-/

**Comment by scls19fr** [comment]
Thanks this is how I proceeded. It's working fine.

**Comment by amueller** [comment]
I fixed it, pip should be working now.
