### ISSUE TITLE
DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.

### ISSUE THREAD

**Issue by owocado** [amueller/word_cloud#690]
#### Description

While using `wordcloud.Wordcloud.generate` function with latest pillow version to date, I noticed these warnings in console logs:
```py
[WARNING] py.warnings: /opt/x/lib/python3.10/site-packages/wordcloud/wordcloud.py:508: DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  box_size = draw.textsize(word, font=transposed_font)
```

opening this issue for tracking purposes. similar issue I found is #681 in the sense of deprecation warning.
Pillow 10 is scheduled to release on July 2023, assuming from the warning traceback so either we would need to freeze the PIL version or make code changes to fix this.

#### Versions

wordcloud: `Version: 1.8.2.2`
pillow: `Version: 9.2.0`
python: `Python 3.10.4`

**Comment by amueller** [comment]
Thanks for reporting! Would you like to submit a PR to fix it?

**Comment by amueller** [comment]
it does! I'm just in the process of reviewing it! thanks for checking on the PRs before opening a new one!
