### ISSUE TITLE
Word colors assigned randomly, any way to make them ordered by frequency?

### ISSUE THREAD

**Issue by n3vrmr** [amueller/word_cloud#700]
#### Description
I wanted to create a word cloud where the frequency of the words decided their color, as if it was a heatmap of sorts, but I can't figure out how to do it.

> wc = WordCloud(background_color='black', stopwords=set(list(STOPWORDS)+additional_stopwords),
                                height=600, width=800, min_font_size=5, max_words=100,
                                colormap=sns.color_palette("Spectral", as_cmap=True), random_state=None)

 > wc.generate(text)
plt.imshow(wc)
plt.axis("off")
plt.show()

Does the random_state argument do anything? Or should I use a different argument for the colors?

**Comment by amueller** [comment]
Sorry for the slow response. You can pass a custom `color_func` that computes the frequency.

**Comment by xumxum** [comment]
It is right there, in examples/a_new_order.py

**Comment by amueller** [comment]
Closing, let me know if there's more questions.
