### ISSUE TITLE
Sizing in generate_from_frequencies

### ISSUE THREAD

**Issue by pcrutchl** [amueller/word_cloud#71]
This is incredibly helpful, thank you. Below: Some bug notes, some suggestions. Sorry to lump them all together.

I'm using `generate_from_frequencies` to lay out word clouds with relatively few words (~15). It seems like the input variable `frequencies` actually ignores the `count` in the tuple (I can't quite parse the purpose of `min(font_size, int(100 * np.log(count + 100)))`; seems like it should be relative to the canvas and/or use a normalized count?). Beyond that, it just goes by the given order of `frequencies`. I really only care about rank order sizing, so that's fine now that I've figured it out.

I did modify the function to force a reduction in font size each time; otherwise it tended to chunk them-- a few one size, a few a little smaller, etc. I think this is due to the small number of words? I wrote a simple optimization wrapper for `max_font_size` to make the words as large as possible, since I wanted them all to appear. I basically just set what I want the ratio of largest word to smallest word to be, and it chugs away, trying a few times to pack them in before reducing size by some percentage. (Takes a lot longer, unfortunately.)

Also modified to allow an optional color for each word in the `frequencies` tuples; couldn't figure out a way to give specific colors to specific words with `color_func`.

**Comment by amueller** [comment]
For the scaling in ``min(font_size, int(100 * np.log(count + 100)))`` yeah that is a bit strange and should probably be scaled by the image size. You should set ``rank_only=True`` for a more simple behavoir. Then the default ``max_font_size`` is as large as possible, that usually makes the words get smaller in basically every step. It could be that having few words does influence that.

``color_func`` gets as first argument the word, so if you just store a dictionary and let ``color_func`` look up the color of that word, it should work, right? Why doesn't that work for you?

**Comment by pcrutchl** [comment]
Good point. Slightly simpler parsing from my inputs, which tend to be given as `word:size:color`. Probably cleaner to have the normal case and fallback case in the `color_func` than the source. You can tell I'm a scientist and not a developer.

**Comment by amueller** [comment]
thinks are much more sensible in #91 in case you are interested.

**Comment by pcrutchl** [comment]
Rock. Thanks for the heads up
