### ISSUE TITLE
How many top % of words are taken for word cloud?

### ISSUE THREAD

**Issue by Abe410** [amueller/word_cloud#713]
Just curious, if we are generating words from text, then how many top words does the cloud use?

And if we generate the cloud using generate_from_frequencies, then how many top frequencies does it use?

**Comment by amueller** [comment]
Hi Abe. There's the "max_words" parameter that's 200 by default, so it'll use 200 words. If you set it higher, it might not actually show all of them if the font gets to small, which depends on the font settings.

**Comment by Abe410** [comment]
> Hi Abe. There's the "max_words" parameter that's 200 by default, so it'll use 200 words. If you set it higher, it might not actually show all of them if the font gets to small, which depends on the font settings.

Thank you.

One more question. If we use `generate`  to make a wordcloud, and then use `generate_from_frequencies` to create it using a count vectorizer with bigrams, is it the same thing?

**Comment by amueller** [comment]
Not entirely, since wordcloud uses collocation statistics to figure out which bigrams to use, so it doesn't just use the most frequent ones. The regex and normalization in wordcloud is also slightly different than in CountVectorizer, but the main difference is using collocation statistics.

**Comment by Abe410** [comment]
Thank you!
