### ISSUE TITLE
when will a new pypi version be released?

### ISSUE THREAD

**Issue by alexbarros** [amueller/word_cloud#714]
o/, we are trying to add wordcloud to ydata-profiling (also known as pandas-profiling) in this [PR](https://github.com/ydataai/ydata-profiling/pull/1282), but it failed on our tests because of incompatibility with python 3.11. Looking at the repo it seems that it already has support for python 3.11 it just does not have a new version release yet. So my question is there a new release planed for the package?

**Comment by amueller** [comment]
Hey! Should be released now. Please give it a try!

**Comment by alexbarros** [comment]
o/ thx it we tested it in the PR and worked for multiple Python versions (3.7+).
