### ISSUE TITLE
Only supported for TrueType font

### ISSUE THREAD

**Issue by mjcarter95** [amueller/word_cloud#722]
#### Description
`ValueError: Only supported for TrueType fonts` when trying to create a WorldCloud on Ubuntu 22.04 with Python 3.10.6.

#### Steps/Code to Reproduce
```
import matplotlib.pyplot as plt
from wordcloud import WordCloud
wc = WordCloud(background_color="white", font_path="./arial.ttf", width=800, height=400)
wc.generate("foo bar foo bar hello world")
plt.axis("off")
plt.imshow(wc)
plt.savefig("test.png")
plt.show()
```

`arial.ttf` is downloaded from https://www.freefontspro.com/14454/arial.ttf and placed in the same directory as the above Python code.

#### Expected Results
No error thrown, world cloud of "foo bar foo bar hello world" is produced and shown.

#### Actual Results
The following error:

```
Traceback (most recent call last):
  File "/mnt/6db3226b-5f96-4257-980d-bb8ec1dad8e7/test.py", line 4, in <module>
    wc.generate("foo bar foo bar hello world")
  File "/home/mjc/.local/lib/python3.10/site-packages/wordcloud/wordcloud.py", line 639, in generate
    return self.generate_from_text(text)
  File "/home/mjc/.local/lib/python3.10/site-packages/wordcloud/wordcloud.py", line 621, in generate_from_text
    self.generate_from_frequencies(words)
  File "/home/mjc/.local/lib/python3.10/site-packages/wordcloud/wordcloud.py", line 453, in generate_from_frequencies
    self.generate_from_frequencies(dict(frequencies[:2]),
  File "/home/mjc/.local/lib/python3.10/site-packages/wordcloud/wordcloud.py", line 508, in generate_from_frequencies
    box_size = draw.textbbox((0, 0), word, font=transposed_font, anchor="lt")
  File "/usr/lib/python3/dist-packages/PIL/ImageDraw.py", line 671, in textbbox
    raise ValueError("Only supported for TrueType fonts")
ValueError: Only supported for TrueType fonts
```

#### Versions
```
Linux-5.19.0-38-generic-x86_64-with-glibc2.35
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
NumPy 1.24.2
matplotlib 3.7.1
wordcoud 1.9.1.1
```

**Comment by zd178** [comment]
Did you solve this problem, please?I tried to fix this yesterday, but I spent a long time trying a lot of fonts and it didn't work...

**Comment by mjcarter95** [comment]
> Did you solve this problem, please?I tried to fix this yesterday, but I spent a long time trying a lot of fonts and it didn't work...

A suggestion on StackOverflow solved the issue for me, see [here](https://stackoverflow.com/questions/76129498/wordcloud-only-supported-for-truetype-fonts/76135510#76135510).

`libfreetype6` was installed on my system but (I assume) out of date, running 

```
sudo apt install libfreetype6
```

fixed the error for me!

**Comment by abubelinha** [comment]
@mjcarter95 your issue is still relevant: could you reopen it or should I open a new one?

I have the same exact error message but no options to try `apt`
I am on Windows 7, Python 3.8:

`python3 -m PIL` outputs: 
`--- FREETYPE2 support ok, loaded 2.12.1`

Thanks
@abubelinha

**Comment by abubelinha** [comment]
OK, the same problem reproduced also in a different Windows 10 machine, Python 3.9.9, Pillow 9.0.1.

So I tried this:
```Python
pip install --upgrade pillow
```
That upgraded Pillow to version 9.5.0 and solved my problem in both Windows machines

**Comment by kirtijain627** [comment]
Pillow version is 9.5.0, python- 3.10.5. Still the problem is not solved

**Comment by talha2k** [comment]
> OK, the same problem reproduced also in a different Windows 10 machine, Python 3.9.9, Pillow 9.0.1.
> 
> So I tried this ([alternative answer](https://stackoverflow.com/a/76135670/710788) to the same SO question above):
> 
> ```python
> pip install --upgrade pillow
> ```
> 
> That upgraded Pillow to version 9.5.0 and solved my problem in both Windows machines

This doesn't solve the problem on windows. Pillow version is 9.5.0, python- 3.10.0. Anaconda Enviornemnt Restarted. Windows Restarted. Double checked that font file exists and is ttf. Still the problem is not solved.
