### ISSUE TITLE
Could not build wheels for wordcloud - python 3.11.1 64 bit

### ISSUE THREAD

**Issue by scign** [amueller/word_cloud#725]
#### Description
Error installing wordcloud

#### Steps/Code to Reproduce
`pip install wordcloud`

#### Expected Results
Successful installation of the wordcloud package.

#### Actual Results
Collecting wordcloud
  Using cached wordcloud-1.9.1.1.tar.gz (222 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy>=1.6.1 in c:\temp\venvs\spacy\lib\site-packages (from wordcloud) (1.24.3)
Requirement already satisfied: pillow in c:\temp\venvs\spacy\lib\site-packages (from wordcloud) (9.5.0)
Requirement already satisfied: matplotlib in c:\temp\venvs\spacy\lib\site-packages (from wordcloud) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\temp\venvs\spacy\lib\site-packages (from matplotlib->wordcloud) (1.0.7)
Requirement already satisfied: cycler>=0.10 in c:\temp\venvs\spacy\lib\site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\temp\venvs\spacy\lib\site-packages (from matplotlib->wordcloud) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\temp\venvs\spacy\lib\site-packages (from matplotlib->wordcloud) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\temp\venvs\spacy\lib\site-packages (from matplotlib->wordcloud) (23.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\temp\venvs\spacy\lib\site-packages (from matplotlib->wordcloud) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\temp\venvs\spacy\lib\site-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\temp\venvs\spacy\lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py): started
  Building wheel for wordcloud (setup.py): finished with status 'error'
  Running setup.py clean for wordcloud
Failed to build wordcloud
  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [20 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-311
  creating build\lib.win-amd64-cpython-311\wordcloud
  copying wordcloud\color_from_image.py -> build\lib.win-amd64-cpython-311\wordcloud
  copying wordcloud\tokenization.py -> build\lib.win-amd64-cpython-311\wordcloud
  copying wordcloud\wordcloud.py -> build\lib.win-amd64-cpython-311\wordcloud
  copying wordcloud\wordcloud_cli.py -> build\lib.win-amd64-cpython-311\wordcloud
  copying wordcloud\_version.py -> build\lib.win-amd64-cpython-311\wordcloud
  copying wordcloud\__init__.py -> build\lib.win-amd64-cpython-311\wordcloud
  copying wordcloud\__main__.py -> build\lib.win-amd64-cpython-311\wordcloud
  copying wordcloud\stopwords -> build\lib.win-amd64-cpython-311\wordcloud
  copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-cpython-311\wordcloud
  UPDATING build\lib.win-amd64-cpython-311\wordcloud/_version.py
  set build\lib.win-amd64-cpython-311\wordcloud/_version.py to '1.9.1.1'
  running build_ext
  building 'wordcloud.query_integral_image' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wordcloud
ERROR: Could not build wheels for wordcloud, which is required to install pyproject.toml-based projects

#### Versions
Windows-10-10.0.19045-SP0
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
NumPy 1.24.3
matplotlib 3.7.1

**Comment by amueller** [comment]
Thanks for reporting. That's a bit strange, since there should be a wheel for 64 bit windows on python 3.11.
Can you maybe try downloading the wheel directly and see if it installs or why it's not working:
https://files.pythonhosted.org/packages/a5/b7/338f0555c0380469d80fcd558d77a121d63e86df27a75203b2d476b7fcbb/wordcloud-1.9.1.1-cp37-cp37m-win_amd64.whl

**Comment by Nextlvlanalytics** [comment]
Im having the same issue as above. I tried to grab the .whl as directed but had compatibility errors there too.

**Comment by 0x020B** [comment]
Perhaps, you can try this:
```shell
pip install --prefer-binary wordcloud
```

**Comment by amueller** [comment]
@Nextlvlanalytics can you say what the output for the commands I gave is?

**Comment by 0x020B** [comment]
> Thanks for reporting. That's a bit strange, since there should be a wheel for 64 bit windows on python 3.11. Can you maybe try downloading the wheel directly and see if it installs or why it's not working: https://files.pythonhosted.org/packages/a5/b7/338f0555c0380469d80fcd558d77a121d63e86df27a75203b2d476b7fcbb/wordcloud-1.9.1.1-cp37-cp37m-win_amd64.whl

Could it be a problem with the file name?
`wordcloud-1.9.1.1-cp311-cp311-win_amd64.whl`

**Comment by smatthys** [comment]
Hi, I have also the same problem on two systems I use. This one is a Fedora 28 with Python 3.11.

"Buildbuild/temp.linux-x86_64-cpython-311/wordcloud/query_integral_image.o
      wordcloud/query_integral_image.c:6:10: fatal error: Python.h: No such file or directory
          6 | #include "Python.h"ing wheel for wordcloud (pyproject.toml) did not run successfully."

[pip_wordcloud.txt](https://github.com/amueller/word_cloud/files/11449766/pip_wordcloud.txt)

**Comment by amueller** [comment]
@smatthys Can you please provide the output of
```python
from packaging.tags import sys_tags

tags = sys_tags()

print([str(tag) for tag in tags])
```
on both systems?

**Comment by smatthys** [comment]
Hi, thx. The one on Fedora38 looks a little artistic. ;-)

[fedora38_python_WordCloud.txt](https://github.com/amueller/word_cloud/files/11455304/fedora38_python_WordCloud.txt)
[windows11_python_WordCloud.txt](https://github.com/amueller/word_cloud/files/11455305/windows11_python_WordCloud.txt)

**Comment by smatthys** [comment]
Just to let you know I have a working WordCloud setup on my main Wind11 machine. This machine worked flawless from the start. It's only when I wanted it on my laptop and Linux PC I encountered the 'wheels' issue. 

[working_windows11_python_WordCloud.txt](https://github.com/amueller/word_cloud/files/11468879/working_windows11_python_WordCloud.txt)

**Comment by amohajerani** [comment]
@amueller I am trying to install this in a docker image, and get this error:
```
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py): started
Killed
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 137
```

**Comment by smatthys** [comment]
@amohajerani 

> ah there was some issue with the wheels for 3.11, it seems. I'll have to look into it.

Install python3.10 make a venv environment (If you want to keep python3.11) and select it, there it installs and works perfectly.

**Comment by CENFARG** [comment]
> @smatthys Can you please provide the output of
> 
> ```python
> from packaging.tags import sys_tags
> 
> tags = sys_tags()
> 
> print([str(tag) for tag in tags])
> ```
> 
> on both systems?

['cp313-cp313-win_amd64', 'cp313-abi3-win_amd64', 'cp313-none-win_amd64', 'cp312-abi3-win_amd64', 'cp311-abi3-win_amd64', 'cp310-abi3-win_amd64', 'cp39-abi3-win_amd64', 'cp38-abi3-win_amd64', 'cp37-abi3-win_amd64', 'cp36-abi3-win_amd64', 'cp35-abi3-win_amd64', 'cp34-abi3-win_amd64', 'cp33-abi3-win_amd64', 'cp32-abi3-win_amd64', 'py313-none-win_amd64', 'py3-none-win_amd64', 'py312-none-win_amd64', 'py311-none-win_amd64', 'py310-none-win_amd64', 'py39-none-win_amd64', 'py38-none-win_amd64', 'py37-none-win_amd64', 'py36-none-win_amd64', 'py35-none-win_amd64', 'py34-none-win_amd64', 'py33-none-win_amd64', 'py32-none-win_amd64', 'py31-none-win_amd64', 'py30-none-win_amd64', 'cp313-none-any', 'py313-none-any', 'py3-none-any', 'py312-none-any', 'py311-none-any', 'py310-none-any', 'py39-none-any', 'py38-none-any', 'py37-none-any', 'py36-none-any', 'py35-none-any', 'py34-none-any', 'py33-none-any', 'py32-none-any', 'py31-none-any', 'py30-none-any']
