### ISSUE TITLE
ImportError: cannot import name WordCloud

### ISSUE THREAD

**Issue by ahjohns** [amueller/word_cloud#74]
Hi, I'm getting this error when I run my code.

My module imports look like this
from os import path
import matplotlib.pyplot as plt
from wordcloud import WordCloud

**Comment by ahjohns** [comment]
I'll also mention I'm running OS X, and I've set the file_name to an existing font in word cloud.py

**Comment by amueller** [comment]
How did you install wordcloud?

**Comment by ahjohns** [comment]
I tried it a couple of ways. First by a fast install, and then by unzipping and installing through terminal. I thought perhaps it might have been an issue with the font_path, but I still get that import error.

**Comment by amueller** [comment]
what is fast install? and what do you mean by "installing through terminal"? It is likely an issue with where / how you installed it.

**Comment by ahjohns** [comment]
I fast installed by running "sudo pip install git+git://github.com/amueller/word_cloud.git" in terminal/command line. That was when I first got the issue, and I tried reinstalling it by installing the package as directed in the readme. I'm working from a non-ubuntu device, it seems to be recognizing the module but can not import the WordCloud class.

**Comment by amueller** [comment]
so that first one should work. Can you do ``import wordcloud``? What is ``wordcloud.__path__`` and can you check that folder?

**Comment by ahjohns** [comment]
I can do an import wordcloud, but when I'm running command line for wordcloud.__path__ 
I get
>>> import wordcloud
>>> wordcloud.__path__
Segmentation fault: 11

And terminal crashes. The error messages shows me a path for wordcloud, but I'm unable to check it. /Users/USER/Library/Python/2.7/lib/python/site-packages/wordcloud/query_integral_image.so

**Comment by amueller** [comment]
what do you mean, you are unable to check it?
Also that segfault looks very sketchy.

**Comment by ahjohns** [comment]
I figured out there was a bug in my version of python, but was able to upgrade. To answer you're original question, yes I've got the path and I'm able to check the folder.

**Comment by amueller** [comment]
so did the initial error go away? or is it still the same? and what is in the folder?

**Comment by ahjohns** [comment]
The error is still the same.

There are 4 files: __init__py, __init__.pyc, stopwords, and query_integral_image.so

**Comment by amueller** [comment]
interesting. That means the installation failed.

**Comment by amueller** [comment]
can you try to remove the folder and the associated egg file and do
``pip install git+git://github.com/amueller/word_cloud.git`` again? that works for me.

**Comment by ahjohns** [comment]
So, now I'm running into this problem: 
```
>>> import wordcloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wordcloud/__init__.py", line 1, in <module>
    from .wordcloud import WordCloud, STOPWORDS, random_color_func
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wordcloud/wordcloud.py", line 84, in <module>
    class WordCloud(object):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wordcloud/wordcloud.py", line 162, in WordCloud
    def __init__(self, font_path= none, width=400, height=200, margin=2,
NameError: name 'none' is not defined
>>> wordcloud.__path__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'wordcloud' is not defined
```

**Comment by ahjohns** [comment]
The installation seems to have worked though, the folder + files are there.

**Comment by ahjohns** [comment]
Scratch that, that was a code error that I was able to fix. But I'm now getting 
```
   wordcloud = WordCloud.generate(sentiment)
TypeError: unbound method generate() must be called with WordCloud instance as first argument (got str instance instead)
logout
```

**Comment by amueller** [comment]
You need to instantiate WordCloud. It should be ``wordcloud = WordCloud().generate(sentiment)``

**Comment by ahjohns** [comment]
While that worked, I was having trouble with PIL and after getting that up and running again, I have this now:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wordcloud/wordcloud.py", line 21, in <module>
    from .query_integral_image import query_integral_image
ValueError: Attempted relative import in non-package
logout
```

**Comment by amueller** [comment]
where did you place your script? and how do you call it? these errors are really unrelated to wordcloud and are just general python....

**Comment by ahjohns** [comment]
Alright, fixed. There was some general path issues with my own system. Removing the relative import fixed the issue.

**Comment by ahjohns** [comment]
Thanks for helping me out.
