### ISSUE TITLE
IOError: cannot open resource

### ISSUE THREAD

**Issue by scls19fr** [amueller/word_cloud#77]
Hello,

I'm facing a similar error than http://stackoverflow.com/questions/26738828/ioerror-cannot-open-resource

    wordcloud = WordCloud(width = 1000, height = 500).generate('australian american english french russian')

    ---------------------------------------------------------------------------
    IOError                                   Traceback (most recent call last)
    <ipython-input-12-6161f3de9aad> in <module>()
    ----> 1 wordcloud = WordCloud(width = 1000, height = 500).generate('australian american english french russian')

    //anaconda/lib/python2.7/site-packages/wordcloud/wordcloud.pyc in generate(self, text)
        400         self
        401         """
    --> 402         return self.generate_from_text(text)
        403 
        404     def _check_generated(self):

    //anaconda/lib/python2.7/site-packages/wordcloud/wordcloud.pyc in generate_from_text(self, text)
        386         """
        387         self.process_text(text)
    --> 388         self.fit_words(self.words_)
        389         return self
        390 

    //anaconda/lib/python2.7/site-packages/wordcloud/wordcloud.pyc in fit_words(self, frequencies)
        205         self
        206         """
    --> 207         return self.generate_from_frequencies(frequencies)
        208 
        209     def generate_from_frequencies(self, frequencies):

    //anaconda/lib/python2.7/site-packages/wordcloud/wordcloud.pyc in generate_from_frequencies(self, frequencies)
        263             while True:
        264                 # try to find a position
    --> 265                 font = ImageFont.truetype(self.font_path, font_size)
        266                 # transpose font optionally
        267                 if random_state.random() < self.prefer_horizontal:

    //anaconda/lib/python2.7/site-packages/PIL/ImageFont.pyc in truetype(font, size, index, encoding, filename)
        238 
        239     try:
    --> 240         return FreeTypeFont(font, size, index, encoding)
        241     except IOError:
        242         if font.endswith(".ttf"):

    //anaconda/lib/python2.7/site-packages/PIL/ImageFont.pyc in __init__(self, font, size, index, encoding, file)
        135 
        136         if isPath(font):
    --> 137             self.font = core.getfont(font, size, index, encoding)
        138         else:
        139             self.font_bytes = font.read()

    IOError: cannot open resource

I'm using Mac OS X 10.10 with Anaconda Python.

    $ conda info
    Current conda install:

                 platform : osx-64
            conda version : 3.14.0
      conda-build version : 1.13.0
           python version : 2.7.10.final.0
         requests version : 2.7.0
         root environment : //anaconda  (writable)
      default environment : //anaconda
         envs directories : //anaconda/envs
            package cache : //anaconda/pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/osx-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : None
        is foreign system : False

`word_cloud` was installed using:

    $ sudo pip install git+git://github.com/amueller/word_cloud.git

**Comment by amueller** [comment]
When creating the WordCloud object, you should give it a ``font_path`` to an existing font on your system.

**Comment by amueller** [comment]
fyi I'm just creating a version that includes a default font.

**Comment by scls19fr** [comment]
Thanks it will be easier.

**Comment by scls19fr** [comment]
I'm trying:

    font_path = "/Library/Fonts/Times New Roman.ttf"
