### ISSUE TITLE
Modify code create word cloud given word frequencies

### ISSUE THREAD

**Issue by ammhatre** [amueller/word_cloud#79]
I need help using the WordCloud package to create a word cloud based on a csv file containing the word and its frequency, rather than plain text. Can you please help me how to do this with your package.

**Comment by amueller** [comment]
Load the cvs, using either the cvs package, or pandas, and feed word and frequency to the  ``generate_from_frequency`` function. http://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud.generate_from_frequencies

There is unfortunately no command line interface yet.
