### ISSUE TITLE
Instillation failed with Python 2.7.5, Anaconda 3.14, Windows 7

### ISSUE THREAD

**Issue by joshlk** [amueller/word_cloud#81]
Hi,

The installation failed with Python 2.7.5, Anaconda 3.14, Windows 7. The fail message is:

```
running install
running build
running build_py
creating build
creating build\lib.win-amd64-2.7
creating build\lib.win-amd64-2.7\wordcloud
copying wordcloud\color_from_image.py -> build\lib.win-amd64-2.7\wordcloud
copying wordcloud\wordcloud.py -> build\lib.win-amd64-2.7\wordcloud
copying wordcloud\__init__.py -> build\lib.win-amd64-2.7\wordcloud
copying wordcloud\stopwords -> build\lib.win-amd64-2.7\wordcloud
copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-2.7\wordcloud
running build_ext
building 'wordcloud/query_integral_image' extension
creating build\temp.win-amd64-2.7
creating build\temp.win-amd64-2.7\Release
creating build\temp.win-amd64-2.7\Release\wordcloud
C:\strawberry\c\bin\gcc.exe -DMS_WIN64 -mdll -O -Wall -IC:\Anaconda\include -IC:\Anaconda\PC -c wordcloud/query_integral_image.c -o build\temp.win-amd64-2.7\Release\wordcloud\query_integral_image.o
wordcloud/query_integral_image.c: In function '__Pyx_RaiseArgtupleInvalid':
wordcloud/query_integral_image.c:13681:18: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:13681:18: warning: format '%s' expects argument of type 'char *', but argument 5 has type 'Py_ssize_t' [-Wformat]
wordcloud/query_integral_image.c:13681:18: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:13681:18: warning: too many arguments for format [-Wformat-extra-args]
wordcloud/query_integral_image.c: In function '__Pyx_BufFmt_ProcessTypeChunk':
wordcloud/query_integral_image.c:14052:26: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:14052:26: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:14052:26: warning: too many arguments for format [-Wformat-extra-args]
wordcloud/query_integral_image.c:14104:20: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:14104:20: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:14104:20: warning: too many arguments for format [-Wformat-extra-args]
wordcloud/query_integral_image.c: In function '__pyx_buffmt_parse_array':
wordcloud/query_integral_image.c:14166:25: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:14166:25: warning: format '%d' expects argument of type 'int', but argument 3 has type 'size_t' [-Wformat]
wordcloud/query_integral_image.c:14166:25: warning: too many arguments for format [-Wformat-extra-args]
wordcloud/query_integral_image.c: In function '__Pyx_GetBufferAndValidate':
wordcloud/query_integral_image.c:14351:7: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:14351:7: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'Py_ssize_t' [-Wformat]
wordcloud/query_integral_image.c:14351:7: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:14351:7: warning: too many arguments for format [-Wformat-extra-args]
wordcloud/query_integral_image.c: In function '__Pyx_RaiseTooManyValuesError':
wordcloud/query_integral_image.c:14882:18: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:14882:18: warning: too many arguments for format [-Wformat-extra-args]
wordcloud/query_integral_image.c: In function '__Pyx_RaiseNeedMoreValuesError':
wordcloud/query_integral_image.c:14888:18: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:14888:18: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'Py_ssize_t' [-Wformat]
wordcloud/query_integral_image.c:14888:18: warning: too many arguments for format [-Wformat-extra-args]
wordcloud/query_integral_image.c: In function '__Pyx_ValidateAndInit_memviewslice':
wordcloud/query_integral_image.c:15644:22: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:15644:22: warning: format '%s' expects argument of type 'char *', but argument 3 has type 'Py_ssize_t' [-Wformat]
wordcloud/query_integral_image.c:15644:22: warning: unknown conversion type character 'z' in format [-Wformat]
wordcloud/query_integral_image.c:15644:22: warning: too many arguments for format [-Wformat-extra-args]
writing build\temp.win-amd64-2.7\Release\wordcloud\query_integral_image.def
C:\strawberry\c\bin\gcc.exe -DMS_WIN64 -shared -s build\temp.win-amd64-2.7\Release\wordcloud\query_integral_image.o build\temp.win-amd64-2.7\Release\wordcloud\query_integral_image.def -LC:\Anaconda\libs -LC:\Anaconda\PCbuild\amd64 -lpython27 -lmsvcr90 -o build\lib.win-amd64-2.7\wordcloud\query_integral_image.pyd Cannot export initwordcloud/query_integral_image: symbol not defined
collect2.exe: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
```

Any ideas?

**Comment by amueller** [comment]
Hey.
How did you install / build? ``pip install wordcloud``?

**Comment by joshlk** [comment]
I tried two methods.
1. `pip install wordcloud` 
2. Download the source files and build using setup.py

Both gave the same error

**Comment by amueller** [comment]
A somewhat wild guess: can you try to replace the slashes by backslashes in ``setup.py`` in lines 10 and 11 in the paths.

**Comment by joshlk** [comment]
Nope, same error

**Comment by amueller** [comment]
hm, not really sure. I haven't tried on windows yet, and I'm not sure what is happening. I'm not sure I'll have time to compile on windows today / soon.

**Comment by amueller** [comment]
It looks like a linker error so I'd try to figure out which symbols are define and why that one is not. It might be a path issue.

**Comment by amueller** [comment]
related but no solution: http://grokbase.com/t/gg/cython-users/133jvy7f1f/cannot-export-initadvect-symbol-not-defined

**Comment by flipdazed** [comment]
I just got a similar error that may help...

    Collecting wordcloud
      Using cached wordcloud-1.1.2.tar.gz
    Installing collected packages: wordcloud
      Running setup.py install for wordcloud
        Complete output from command C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\cygwin64\\tmp\\pip-build-cigve2\\wordcloud\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\cygwin64\tmp\pip-_zxrhm-record\install-record.txt --single-version-externally-managed --compile:
        running install
        running build
        running build_py
        creating build
        creating build\lib.win-amd64-2.7
        creating build\lib.win-amd64-2.7\wordcloud
        copying wordcloud\color_from_image.py -> build\lib.win-amd64-2.7\wordcloud
        copying wordcloud\wordcloud.py -> build\lib.win-amd64-2.7\wordcloud
        copying wordcloud\__init__.py -> build\lib.win-amd64-2.7\wordcloud
        copying wordcloud\stopwords -> build\lib.win-amd64-2.7\wordcloud
        copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-2.7\wordcloud
        running build_ext
        building 'wordcloud/query_integral_image' extension
        creating build\temp.win-amd64-2.7
        creating build\temp.win-amd64-2.7\Release
        creating build\temp.win-amd64-2.7\Release\wordcloud
        C:\Users\MCFARL23\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tcwordcloud/query_integral_image.c /Fobuild\temp.win-amd64-2.7\Release\wordcloud/query_integral_image.obj
        query_integral_image.c
        wordcloud/query_integral_image.c(1411) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
        wordcloud/query_integral_image.c(1420) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', possible loss of data
        C:\Users\MCFARL23\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Python27\libs /LIBPATH:C:\Python27\PCbuild\amd64 /EXPORT:initwordcloud/query_integral_image build\temp.win-amd64-2.7\Release\wordcloud/query_integral_image.obj /OUT:build\lib.win-amd64-2.7\wordcloud\query_integral_image.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\wordcloud\query_integral_image.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\wordcloud\query_integral_image.pyd.manifest
        LINK : error LNK2001: unresolved external symbol initwordcloud/query_integral_image
        build\temp.win-amd64-2.7\Release\wordcloud\query_integral_image.lib : fatal error LNK1120: 1 unresolved externals
        error: command 'C:\\Users\\MCFARL23\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1120

        ----------------------------------------
    Command "C:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\cygwin64\\tmp\\pip-build-cigve2\\wordcloud\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\cygwin64\tmp\pip-_zxrhm-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\cygwin64\tmp\pip-build-cigve2\wordcloud

**Comment by flipdazed** [comment]
http://stackoverflow.com/questions/7410798/c-fatal-error-lnk1120-1-unresolved-externals
http://stackoverflow.com/questions/12573816/what-is-an-undefined-reference-unresolved-external-symbol-error-and-how-do-i-fix

**Comment by amueller** [comment]
Not sure how the links are relevant. They just explain what linking error are, right?
Sorry, I didn't have time to look into this yet.

**Comment by benSlash** [comment]
Hi, same problem as flipdazed here and  I still didn't figure out how to solve it neither .There are lot of stuff on internet about that kind of fatal error, but I couldn't find anything specific enough . 
I hope someone can help :)

**Comment by carlkl** [comment]
It does compile with a change in setup.py:

```python
    ext_modules=[Extension("query_integral_image",
                           ["wordcloud/query_integral_image.c"])],
```
then ```import query_integral_image``` has to be imported without a dot in ```wordcloud.py```

```python
from query_integral_image import query_integral_image
```

**Comment by amueller** [comment]
Can you try the fix in #83?

**Comment by amueller** [comment]
(merge to master now)

**Comment by carlkl** [comment]
https://github.com/amueller/word_cloud/pull/83 sucessfully tested with python-2.7!

**Comment by joshlk** [comment]
Pulled from master and using setup.py now getting the following output (not successfully installing):

```
D:\git\word_cloud>python setup.py install
running install
running build
running build_py
running build_ext
building 'wordcloud.query_integral_image' extension
error: Unable to find vcvarsall.bat
```

**Comment by flipdazed** [comment]
error: Unable to find vcvarsall.bat

I had this issue when I was installing LAPACK and BLAS on Windows 7. It is an issue to do with your native C++ distribution.

This post helped me fix my own issue with this same error: http://stackoverflow.com/a/10558328/4013571

**Comment by michael-rutherford** [comment]
I'm afraid I'm still getting the original error as the OP with the newest build 1.1.3 through both pip and local install. I'm using windows 7, Python 2.7.8, Anaconda 2.1.0.

I was able to get around the vcvarsall.bat error by installing the c++ compiler for p
https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by michael-rutherford** [comment]
Uninstalling libpython (conda uninstall libpython) allowed me to install wordcloud using pip. I was using a slightly modified wordcloud version, so I just needed to snag the query_integral_image.pyd and add it to my old version and comment out the pyximport functions in the wordcloud.py.

**Comment by amueller** [comment]
which pyximport? There shouldn't be any of these in any of my releases...

**Comment by michael-rutherford** [comment]
That must be an addition to the modified version I'm using which could be based on a really old version. Not sure. Disregard the pyximport issue as far as this bug report.

However, if anyone has problem installing using pip while using anaconda, uninstalling libpython should do the trick. If you run into the vcvarsall.bat error, install the compiler I have linked in previous comment.

**Comment by amueller** [comment]
what is the modification you are using? My guess is that using the current version you might not have issues.

**Comment by michael-rutherford** [comment]
The previous developer added the ability to highlight words in the tree. I was finally able to install the newest version but didn't have time to incorporate his code into the new.

I tried multiple times with the newest version through both pip and setup.py and got the same as the OP message until I uninstalled libpython using conda. It apparently sets the gcc incorrectly or something. Again...short on time so I couldn't thoroughly investigate. All I needed was the pyd after the newest version successfully installed to get his modified version to work.

Sorry for the confusion. When I get time, I may branch and try to include the highlight changes.

**Comment by amueller** [comment]
It sounds a bit odd but ok.
Maybe the cython config is not right.
I'm not sure what you mean by highlighting words in the tree.

**Comment by michael-rutherford** [comment]
Sorry. I had trees on the brain. He modified the code to send a list of words to highlight in the word cloud the we were specifically referring to so they would stand out.

**Comment by amueller** [comment]
Thats very easy to do by providing an appropriate ``color_func`` and doesn't require any modification.

**Comment by easimadi** [comment]
same error here... any help? Win10.
"building 'wordcloud.query_integral_image' extension
    error: Microsoft Visual C++ 10.0 is required (Unable to find vcvarsall.bat)."

**Comment by michael-rutherford** [comment]
I was able to get around the vcvarsall.bat error by installing the c++ compiler for python.

https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by amueller** [comment]
there is now an anaconda package: https://anaconda.org/amueller/wordcloud

**Comment by michael-rutherford** [comment]
Thanks Andreas. I'll test it out next time I need wordclouds.

**Comment by mesala** [comment]
Still same issue when using pip or setup.py:  
                  "error: Unable to find vcvarsall.bat"

My configuration: Python 3, Windows 8, win64, Anaconda

If I use "conda install wordcloud" I get the following error:
                  "Error: Package missing in current win-64 channels"

Thanks,

**Comment by mesala** [comment]
Since I didn't manage to install it using the suggested ways, I finally used the following file:
       wordcloud-1.2.1-cp35-cp35m-win_amd64.whl    Taken from (http://www.lfd.uci.edu/~gohlke/pythonlibs/)

I forgot to mention I have Anaconda3 in my configuration, and as I said Python 3, Windows 8, win64

Very happy to see it finally working on my computer. Thanks a lot for the great tool.

**Comment by amueller** [comment]
hm I guess the current config doesn't work for windows. I didn't realize the Gohlke binaries had wordcloud builds. wow ^^

**Comment by yorktronic** [comment]
For what it's worth, I had the same issue and it was resolved by uninstalling libpython (`conda uninstall libpython`), and installing the Visual C/C++ compiler supplied by Microsoft, per michael-rutherford's recommendation. I re-installed libpython after wordcloud successfully installed and everything is working fine now.

**Comment by amueller** [comment]
I recommend using conda-forge now.
