### ISSUE TITLE
installation failed with Windows 8.1

### ISSUE THREAD

**Issue by yangyangjuanjuan** [amueller/word_cloud#82]
Hi,
This work looks amazing, but I got frustrated after many failed installations... 
I downloaded from https://github.com/amueller/word_cloud/archive/master.zip, and then unzipped it. When I tried to run: python setup.py build, I got error messages:

running build
running build_py
creating build
creating build\lib.win32-3.4
creating build\lib.win32-3.4\wordcloud
copying wordcloud\color_from_image.py -> build\lib.win32-3.4\wordcloud
copying wordcloud\wordcloud.py -> build\lib.win32-3.4\wordcloud
copying wordcloud\__init__.py -> build\lib.win32-3.4\wordcloud
copying wordcloud\stopwords -> build\lib.win32-3.4\wordcloud
copying wordcloud\DroidSansMono.ttf -> build\lib.win32-3.4\wordcloud
running build_ext
building 'wordcloud\query_integral_image' extension
creating build\temp.win32-3.4
creating build\temp.win32-3.4\Release
creating build\temp.win32-3.4\Release\wordcloud
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python34\inc
lude -IC:\Python34\include /Tcwordcloud\query_integral_image.c /Fobuild\temp.win32-3.4\Release\wordcloud\query_integral_
image.obj
query_integral_image.c
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Python34\li
bs /LIBPATH:C:\Python34\PCbuild /EXPORT:PyInit_wordcloud\query_integral_image build\temp.win32-3.4\Release\wordcloud\que
ry_integral_image.obj /OUT:build\lib.win32-3.4\wordcloud\query_integral_image.pyd /IMPLIB:build\temp.win32-3.4\Release\w
ordcloud\query_integral_image.lib /MANIFESTFILE:build\temp.win32-3.4\Release\wordcloud\query_integral_image.pyd.manifest

LINK : error LNK2001: unresolved external symbol PyInit_wordcloud\query_integral_image
build\temp.win32-3.4\Release\wordcloud\query_integral_image.lib : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN\\link.exe' failed with exit status 1120

Any suggestion would be greatly appreciated.
BTW: install from pip gives same error

**Comment by yangyangjuanjuan** [comment]
It may caused by the Image package, which is not compatible to Python 3, but required by wordcloud. Any check?

**Comment by amueller** [comment]
Looks related to #81, though this is msvs and #81 was gcc. Both are linking issues, though:

    unresolved external symbol PyInit_wordcloud\query_integral_image

**Comment by amueller** [comment]
I don't know how to resolve this, unfortunately. Maybe we should ask on the cython mailing list.

**Comment by amueller** [comment]
https://groups.google.com/forum/#!topic/cython-users/Hrd4rbwnrsg

**Comment by yangyangjuanjuan** [comment]
Will keep an eye on that mailing list, thank you!
Would you mind introduce a little bit more about how to generate this complex and amazing picture?

**Comment by amueller** [comment]
which one? the parrot? It is the same technique as here: http://amueller.github.io/word_cloud/auto_examples/colored.html

**Comment by amueller** [comment]
I should probably post the actual parrot code

**Comment by amueller** [comment]
Can you try the fix in #83?

**Comment by amueller** [comment]
(merge to master now)

**Comment by carlkl** [comment]
@amueller, it works now with https://github.com/amueller/word_cloud/pull/83!

**Comment by yangyangjuanjuan** [comment]
@amueller Wonderful!! Now it works like a magic. I am a little curious why this change can fix this problem? Thank you!

**Comment by amueller** [comment]
The previous version was just wrong I think.
