### ISSUE TITLE
How to just use black and white colors

### ISSUE THREAD

**Issue by kobe2452** [amueller/word_cloud#84]
As the title says, I would like to use only white as background color and black as font color. Could anyone shed me some light on this? I already modified background attribute in __init__ function as "white", but still had no clue about the font color setting. I've tried to use "hsl(0, 0%, 0%)" to replace the random_color_func, but got the TypeError: 'str' object is not callable in generate_from_frequencies (line 304)
Any help is appreciated!

**Comment by amueller** [comment]
you need to replace ``random_color_func`` by a function that always returns black:
```python
def always_black(**kwargs):
    return "black"
```
(not sure if the ``black`` string works, try ``rgb(0, 0, 0)`` otherwise.)

**Comment by kobe2452** [comment]
black string works! Thanks! It was simpler than what I thought.

**Comment by varac** [comment]
I also like to get a black and white output. Is this possible without altering the code ?

**Comment by amueller** [comment]
@varac you don't need to change any of the wordcloud code but you can't easily pick the color map from the command line if that's what you're asking.
