### ISSUE TITLE
Install question with pip / W7, linkage issue (?)

### ISSUE THREAD

**Issue by keesskippy** [amueller/word_cloud#86]
Hi Andreas, I was having a look at your awesome word cloud generator and decided to try and play with some examples.

I am a novice with Python though and having issues with the installation of the wordcloud package.
I am on Windows 7, 64 bit.

By means of some installations of the Windows 7.1 SDK and also Microsoft Visual Studio 2010 Express I managed to get part of the installation process done. I am using pip. However my installation during this process now fails on this error:

python34.lib(python34.dll) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'   
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1112

(I have a copy of the messages during pip process available if desired) 

It looks like a linker problem and I am somehow mixing up a 32 and 64 bit version.
By doing some Google investigation it suggests that I need to change the machine target in the properties of the project to 64 bit.
However I have no clue how to do that, since I would expect the pip process to do that “automatically”.

Since, once again, I am a complete novice with Python (and to be honest programming in general has been a while ago…) I may be doing all the wrong things or explain myself wrongly. 

Hope you can help solving my issue or point me in the right direction,

Best regards,
keesskippy

**Comment by amueller** [comment]
Hey.
Which python do you have? 32 or 64 bit? And which version of Microsoft Visual Studio 2010 Express do you have? Also: 2010? Really? I think most decent python distributions for windows will come with gcc.

**Comment by keesskippy** [comment]
Hi Andreas, thanks very much for replying.

I have 64 bit version of Python 3.4

 

Microsoft Visual Studio 2010 Express  en the SDK 7.1 version.

I am sorry but I don’t know what the implication is of gcc.

Is it a different way of making use of the compiler, or a different compiler?

 

Below some more information of the messages during pip process.

 

Collecting wordcloud

  Using cached wordcloud-1.1.3.tar.gz

Installing collected packages: wordcloud

  Running setup.py install for wordcloud

    Complete output from command C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\aaa11111\\AppData\\Local\\Temp\\pip-build-f053veat\\wordcloud\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\aaa11111\AppData\Local\Temp\pip-sto524zy-record\install-record.txt --single-version-externally-managed --compile:

    running install

    running build

    running build_py

    creating build

    creating build\lib.win-amd64-3.4

    creating build\lib.win-amd64-3.4\wordcloud

    copying wordcloud\color_from_image.py -> build\lib.win-amd64-3.4\wordcloud

    copying wordcloud\wordcloud.py -> build\lib.win-amd64-3.4\wordcloud

    copying wordcloud\__init__.py -> build\lib.win-amd64-3.4\wordcloud

    copying wordcloud\stopwords -> build\lib.win-amd64-3.4\wordcloud

    copying wordcloud\DroidSansMono.ttf -> build\lib.win-amd64-3.4\wordcloud

    running build_ext

    building 'wordcloud.query_integral_image' extension

    creating build\temp.win-amd64-3.4

    creating build\temp.win-amd64-3.4\Release

    creating build\temp.win-amd64-3.4\Release\wordcloud

    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python34\include -IC:\Python34\include /Tcwordcloud/query_integral_image.c /Fobuild\temp.win-amd64-3.4\Release\wordcloud/query_integral_image.obj

    query_integral_image.c

    C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Python34\libs /LIBPATH:C:\Python34\PCbuild\amd64 /EXPORT:PyInit_query_integral_image build\temp.win-amd64-3.4\Release\wordcloud/query_integral_image.obj /OUT:build\lib.win-amd64-3.4\wordcloud\query_integral_image.pyd /IMPLIB:build\temp.win-amd64-3.4\Release\wordcloud\query_integral_image.lib /MANIFESTFILE:build\temp.win-amd64-3.4\Release\wordcloud\query_integral_image.pyd.manifest

    python34.lib(python34.dll) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86'

 

    error: command 'C:\\Program Files (x86)\\Microsoft <file:///\\Microsoft>  Visual Studio 10.0\\VC\\BIN\\link.exe' failed with exit status 1112

 

    ----------------------------------------

Command "C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\aaa11111\\AppData\\Local\\Temp\\pip-build-f053veat\\wordcloud\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\aaa11111\AppData\Local\Temp\pip-sto524zy-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\aaa11111\AppData\Local\Temp\pip-build-f053veat\wordcloud

 

Hope this information helps. If there is an easy way of using gcc that would also be fine of course.

 

Keesskippy

 

Van: Andreas Mueller [mailto:notifications@github.com] 
Verzonden: zaterdag 25 juli 2015 13:36
Aan: amueller/word_cloud
CC: keesskippy
Onderwerp: Re: [word_cloud] Install question with pip / W7, linkage issue (?) (#86)

 

Hey.
Which python do you have? 32 or 64 bit? And which version of Microsoft Visual Studio 2010 Express do you have? Also: 2010? Really? I think most decent python distributions for windows will come with gcc.

**Comment by amueller** [comment]
gcc is a different compiler.
Can your visual studio built 64bit binaries?

How did you install python?

**Comment by keesskippy** [comment]
For Python I installed the package python-3.4.3.amd64.msi

The gcc seems not to be included?

 

Indeed there are issues with using Visual Studio 2010 express, the Microsoft SDK also seems to be needed.

I followed the procedure described here (the 3.4 Pyhton part): http://blog.ionelmc.ro/2014/12/21/compiling-python-extensions-on-windows/ to get the build working properly.

But there a quite a few steps included, maybe I have overlooked something.

 

 

Van: Andreas Mueller [mailto:notifications@github.com] 
Verzonden: dinsdag 28 juli 2015 17:02
Aan: amueller/word_cloud
CC: keesskippy
Onderwerp: Re: [word_cloud] Install question with pip / W7, linkage issue (?) (#86)

 

gcc is a different compiler.
Can your visual studio built 64bit binaries?

How did you install python?

**Comment by keesskippy** [comment]
Well, you pointed me definitely in the right direction, thanks!

Retracing the needed steps, I looked at:

Step 6: Install  <http://www.microsoft.com/en-us/download/details.aspx?id=23691> Microsoft Visual Studio 2010 Service Pack 1.

Step 7:  <http://www.microsoft.com/en-us/download/details.aspx?id=4422> Microsoft Visual C++ 2010 Service Pack 1 Compiler Update for the Windows SDK 7.1

 

Although stated as optional, they appeared not to be optional for my setup but required.

After applying these updates, the wordcloud package installed without issues with pip!

 

 

Van: Andreas Mueller [mailto:notifications@github.com] 
Verzonden: dinsdag 28 juli 2015 17:02
Aan: amueller/word_cloud
CC: keesskippy
Onderwerp: Re: [word_cloud] Install question with pip / W7, linkage issue (?) (#86)

 

gcc is a different compiler.
Can your visual studio built 64bit binaries?

How did you install python?

**Comment by amueller** [comment]
great, glad you worked it out. sorry I couldn't be of more help.
