### ISSUE TITLE
color by term frequency

### ISSUE THREAD

**Issue by silviaegt** [amueller/word_cloud#88]
dear @amueller, 

first things first: thank you so much for making wordcloud, is so much fun to play around with!

I want to use wordcloud for my MA thesis to compare multiple Encyclopedic entries of the same subject. What I want to do at the end is to compare them visually in a mosaic view where each text is wordcloud-mosaic. 
However, in order to make pattern recognition easier **I was wondering if there was a way of assigning the same colours to words that come up in the same term-frequency range** ([tf values](https://en.wikipedia.org/wiki/Tf%E2%80%93idf#Term_frequency_2) are  always between 0 and 1)
I apologize in advance if the question is too dumb, my background is in literature but I am doing my best to learn python :)
what I am doing looks like this (any suggestions for improvement are super needed and welcome):

```python
from nltk.corpus import stopwords
import glob
filelist = glob.glob("*.txt")
for f in filelist:
    text = open(f).read()
    wc = WordCloud(background_color="white", max_words=2000,
               stopwords=stopwords.words('spanish'),
               max_font_size=40, random_state=42)
    wc.generate(text)
    plt.imshow(wc)
    plt.axis("off")
    plt.show() 
```

but I was wondering if I could use [generate_from_frequencies()](https://github.com/amueller/word_cloud/blob/master/wordcloud/wordcloud.py#L205), feed it with a term frequency list like the one below and then set the colours somehow?

```python
def tftuple(wc):
    """
    Takes a dictionary with word counts and returns
    a list of tuples with (word, freq)
    """
    l = len(wc)
    tf = []
    for w, c in wc.items():
        tf.append(w, c)
    return tf
```

**Comment by amueller** [comment]
Yes, you can do that.
Unfortunately coloring by the word frequency is not natively supported yet.
You can define your own color function to do that, though. Let's say you have your wc dictionary.
Then you can define your color function like this:

```python

def my_tf_color_func(word, **kwargs):
     return "hsl(%d, 80%%, 50%%)" % (360 * wc[word])
```

Then you can pass ``my_tf_color_func`` as ``color_func``.
This should give you hues based on the tf value.

**Comment by amueller** [comment]
closing as solved.

**Comment by nielsenrechia** [comment]
Hi @amueller , I new in python and I a using your wordcloud.

Can you give me an example of how can I pass the dict  `wc `to `my_tf_color_func `passing it by `color_func`?

My code 

```
wordcloud = WordCloud(background_color="white", max_words=1000, mask=motog3_coloring,
max_font_size=1000, random_state=1,  relative_scaling=.6, regexp="\w[\%\-\(\)\w']+",
collocations=False, color_func=color_function_words)
```


```
def my_tf_color_func(word, font_size, position, orientation, random_state=None, **kwargs):
     return "hsl(%d, 80%%, 50%%)" % (360 * wc[word])
```

But `wc ` has t be passed, how can I do that? 

 tried in some ways but I could not.

Many Thanks

**Comment by amueller** [comment]
@nielsenrechia sorry I don't understand the question. Please use stackoverflow for programming questions, not the issue tracker.

**Comment by nielsenrechia** [comment]
My mistake, thanks!
https://stackoverflow.com/questions/47143461/python-wordcloud-color-by-term-frequency
