### ISSUE TITLE
Font size of generate_from_frequencies

### ISSUE THREAD

**Issue by c-martinez** [amueller/word_cloud#89]
Apologies if this is almost a duplicate of #71 but... this might still be an issue -- it seems to me as if the frequency of the word is not really taken into account when ranks_only=False.

In my opinion, the following code should produce two different word clouds:
```
img1 = WordCloud(random_state=1, ranks_only=False).generate_from_frequencies(
        [('Hello', 0.80), ('word', 0.10), ('!!!', 0.10)])
img2 = WordCloud(random_state=1, ranks_only=False).generate_from_frequencies(
        [('Hello', 0.10), ('word', 0.80), ('!!!', 0.10)])

figure(figsize=(12,4))
subplot(1,2,1)
imshow(img1)
subplot(1,2,2)
imshow(img2)
```
But I think the resulting word clouds are actually the same.

Is this the case? Or have I missed something?

**Comment by amueller** [comment]
This really looks like a bug :-/ the second should clearly draw ``word`` first, no matter what ``ranks_only``.

**Comment by amueller** [comment]
"Fix" in #90.
quotation marks, as with the current formula for the font size, the relative differences will always be ignored, and ``ranks_only=False`` has no effect.
The formula should be changed. Your help is welcome.

Should scaling be always meaningful towards the next larger word? then we need to keep track of the frequency of the last word, and adjust the size of the next word accordingly. Actually that doesn't sound too bad....

**Comment by c-martinez** [comment]
That was quick! Thanks! Fix seems to work -- I guess it would be nice if font sizes were proportional to frequencies. I'll see what I can do...

**Comment by amueller** [comment]
see #91. (I'm soo easily nerd-sniped with this project)

**Comment by amueller** [comment]
semi-accidentally closed this by merging #90. Please let me know what you think of #91.

**Comment by c-martinez** [comment]
Looks great -- word looks tiny! but fiddling with the relative scaling helps. Many thanks! Keep up the good nerdy work :-)

**Comment by amueller** [comment]
with ``relative_scaling=1`` everything looks tiny :-/ which is the reason I added the parameter at all. meh

**Comment by c-martinez** [comment]
With `relative_scaling=0.5` it looks quite nice -- I think it is useful to have full control of scaling that way.
