### ISSUE TITLE
Requirement.txt doesn't include matplotlib?

### ISSUE THREAD

**Issue by Lw-Cui** [amueller/word_cloud#92]
Using `virtualenv` and `pip install -r Requirement.txt` , I still get an error message which said: 
**File "./simple.py", line 9, in <module>
    import matplotlib.pyplot as plt
ImportError: No module named matplotlib.pyplot**

So I believe `matplotlib` should be included in `Requirement.txt`, shouldn't it?
Thanks.

**Comment by amueller** [comment]
It's not really a requirement for the library, its used in the examples, though.
You can use wordcloud without matplotlib.

**Comment by Lw-Cui** [comment]
Here is my `pip list`:

```
Django (1.8.4)
funcsigs (0.4)
image (1.4.0)
matplotlib (1.4.3)
mock (1.3.0)
nose (1.3.7)
numpy (1.9.2)
pbr (1.6.0)
PIL (1.1.7)
Pillow (2.9.0)
pip (7.1.2)
pyparsing (2.0.3)
python-dateutil (2.4.2)
pytz (2015.4)
setuptools (18.0.1)
six (1.9.0)
wheel (0.24.0)
wordcloud (1.1.3)
```

I run `./simple.py` only after installing those.

And I still cannot run `./masked.py`. Error message said:
**File "./masked.py", line 9, in <module>
    from scipy.misc import imread
ImportError: No module named scipy.misc**

**Comment by amueller** [comment]
you can run ``simple.py`` and comment out the matplotlib commands and it will run. It will just not produce any output. you can write a numpy file to disk if you like. Or you can write a pil image to disk.

**Comment by amueller** [comment]
I could change the imread and display to PIL, I guess.

**Comment by amueller** [comment]
On the other hand, I feel users are more likely familiar with matplotlib then with pil, so showing the matplotlib interface seems more helpful?

**Comment by Lw-Cui** [comment]
YES! I think `PIL` is out of date and it's chanllenging for me to install `scipy` which depend on `PIL`.

**Comment by amueller** [comment]
no, it shouldn't depend on pil, and you have pillow. I'm just removing the scipy call.
but you can easily use ``Image`` which is in pillow.

**Comment by Lw-Cui** [comment]
Oh, maybe there is something different in new version.
And I'd appricate it if you update this [web](http://amueller.github.io/word_cloud/auto_examples/simple.html) to avoid misunderstanding :)

**Comment by amueller** [comment]
sorry, I'm not sure what you mean

**Comment by amueller** [comment]
I just added a comment on how to do the plot without matplotlib here:

https://github.com/amueller/word_cloud/blob/master/examples/simple.py

I'll rebuilt the website if there are major changes.

You can also just use ``wordcloud.to_file("some_file.png")`` which will totally work. I just like an image to pop up if you run an example.

**Comment by Lw-Cui** [comment]
In my laptop nothing pop up so I would like to export a file...

**Comment by sailordiary** [comment]
@Lw-Cui For the image to pop up you need matplotlib. To do without use wordcloud.to_file("some_file.png"), as was explained. They're just different ways of showing the result.

**Comment by Lw-Cui** [comment]
Thanks for your contribution and patience:)
 Generally it's an awesome word cloud generator!

**Comment by amueller** [comment]
dependency on pillow is fixed in master.
