### ISSUE TITLE
Importing wordCloud errors

### ISSUE THREAD

**Issue by lusomers** [amueller/word_cloud#93]
Hi, 

I am trying to create a wordcloud from a tweet textfile I streamed earlier this week.

When I try to install the wordcloud package, I get the error "No module named wordcloud"

My code is below, not sure if I've missed something here 

pip install wordcloud 
sudo pip install -r requirements.txt
python setup.py install

from wordcloud import WordCloud
from os import path
from scipy.misc import imread
import matplotlib.pyplot as plt
from PIL import Image
 
text=tweets_data 
wordcloud = WordCloud().generate(text)
img=plt.imshow(wordcloud)
plt.axis("off")
plt.show() 
 
#or save as png
img.write_png("wordcloud.png")

**Comment by amueller** [comment]
Th installation seems a bit redundant. Just pip install wordcloud should be enough.
What is the output of these commands?

**Comment by lusomers** [comment]
I managed to install the wordcloud. I was installing it with the incorrect syntax.
I just need to convert the tweets into a string in order for the wordcloud to read the string into the image 

thanks for your response!
