### ISSUE TITLE
Requirements.txt doesn't inclde PIL

### ISSUE THREAD

**Issue by mogthesprog** [amueller/word_cloud#94]
Hi,

Jut installed this the other day and noticed that PIL didn't install.

Cheers,

Morgan

**Comment by amueller** [comment]
Thanks for reporting.
It includes "Image". I thought that would work. Doesn't it?
Maybe I should add pillow instead?

**Comment by mogthesprog** [comment]
Hi, Sorry for the late reply.

You're right, that should have worked. Spent some time fixing this this morning. So basically, I had some issues with dependencies within CentOS. So I had to do a few extra yum installs.

First I removed all instances of PIL and PIllow installed by both pip and easy_install (just to make sur it was actually all gone), then i ran yum install python-pillow* seemed to fix the problem.

This creates some really neat masked wordclouds, nice one :) 

Cheers,

Morgan
