### ISSUE TITLE
Word_Cloud transforming txt file into string 

### ISSUE THREAD

**Issue by lusomers** [amueller/word_cloud#95]
I have attempted to create a word cloud from my tweets text file (.txt format)
I manage to get a wordcloud but the image consists of words such as false, null, pps, twitter, media, lang, resize etc. 

I don''t know if I have converted my text file into a string correctly as these words are not the words in my tweets. 
My code is as follows:

from wordcloud import WordCloud, STOPWORDS

with open("G:/2015 S2/STK 353/Louisa Textfiles/Collection.txt") as f:
    lines=f.readlines()                                                                            
text = "".join(lines) 

wordcloud=WordCloud(stopwords=STOPWORDS,
                    background_color='black',
                    width=1200,
                    height=1000,
                    ).generate(text)

plt.imshow(wordcloud)
plt.axis('off')
plt.show()

**Comment by lusomers** [comment]
![word cloud](https://cloud.githubusercontent.com/assets/14307998/9975951/c8ba1ab0-5ed0-11e5-9bfc-29f10f25693f.png)

**Comment by amueller** [comment]
I don't know the tweet text file format. But apparently it contains other items than just the tweets. What does the file look like?

**Comment by amueller** [comment]
closing for lack of response.
