### ISSUE TITLE
is there any way to feed the word cloud the words and their frequencies instead of the text doc?

### ISSUE THREAD

**Issue by nouramoubayed** [amueller/word_cloud#97]

**Comment by amueller** [comment]
http://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud.generate_from_frequencies

**Comment by irn-bru** [comment]
@amueller: Apologies for re-opening but I wanted to clarify if this method is to be used when you have a text file with, for example:

```
Rubbish:2321
Shot:1432
Superb:224
Goals:112
Meals:99
Rushing:45
Dropping:21
````

...contained within it? If so, can you give me an example of using ```generate_from_frequencies``` so I know what I'm to do? Thanks.

**Comment by amueller** [comment]
You read the file and make it into a list like
``[('Rubbish', 2312), ('Shot', 1432), ...]``
and then call ``generate_from_frequencies`` on this list.

**Comment by ma7555** [comment]
> You read the file and make it into a list like
> `[('Rubbish', 2312), ('Shot', 1432), ...]`
> and then call `generate_from_frequencies` on this list.

I want to point out that this won't work as a list, you need it in a dict format
```{'Rubbish': 2312, 'Shot' : 1432), ...}```
as generate_from_frequencies uses .items() to get the keys/values

**Comment by amueller** [comment]
@ma7555 indeed the interface has been changed since I posted the reply in 2016 ;)

**Comment by amueller** [comment]
You can find the full documentation here:
http://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud.WordCloud.generate_from_frequencies
