### ISSUE TITLE
PIL is deprecated, replace with Pillow

### ISSUE THREAD

**Issue by maxupp** [amueller/word_cloud#98]
For use under Linux, PIL should be replaced with Pillow, the successor.

**Comment by amueller** [comment]
You mean in the requirements?

**Comment by maxupp** [comment]
Exactly, if possible without rewriting the entire tool ;)

**Comment by amueller** [comment]
It works with either.

**Comment by amueller** [comment]
Pillow provides Image, just as PIL did.

**Comment by maxupp** [comment]
Yes, but wordcloud still requires PIL:
/usr/lib/python3.4/site-packages/wordcloud/wordcloud.py in <module>()
     14 from operator import itemgetter
     15 
---> 16 from PIL import Image
     17 from PIL import ImageDraw
     18 from PIL import ImageFont

ImportError: No module named 'PIL'

**Comment by amueller** [comment]
hm ok.
And you have pillow installed and that doesn't work?

**Comment by maxupp** [comment]
Yep.

**Comment by amueller** [comment]
That is odd, pillow contains the PIL module:
https://github.com/python-pillow/Pillow

You can try changing it to pillow, but I don't think that'll work.

**Comment by amueller** [comment]
Pillow is imported as PIL:
https://pillow.readthedocs.org/en/3.0.x/handbook/tutorial.html

**Comment by adalmieres** [comment]
Hi, there is an announcement at http://pillow.readthedocs.org/en/3.0.x/installation.html
Pillow >= 2.1.0 no longer supports “import _imaging”. Please use “from PIL.Image import core as _imaging” instead.

**Comment by amueller** [comment]
I'm not importing ``_imaging``, right? But I guess I shouldn't import ``Image`` either.
Pull request to use ``from PIL import Image`` welcome.

**Comment by jasonrhaas** [comment]
I'm running into this on Ubuntu 14.04 LTS.

`ImportError: No module named PIL`

Has anyone figured out a fix for this?  I am installing in a clean virtualenv and get that error.

**Comment by amueller** [comment]
Install PIL or Pillow.

**Comment by amueller** [comment]
setup.py uses pillow now. closing.
