### ISSUE TITLE
utf-8 issuse for Chinese Character

### ISSUE THREAD

**Issue by rylanchiu** [amueller/word_cloud#99]
I am using python 3.5 and I got the ValueError : unknown locale: UTF-8
The complete traceback is as below: 

Traceback:
File "/Users/yobichi/wi/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  119.                 resolver_match = resolver.resolve(request.path_info)
File "/Users/yobichi/wi/lib/python3.5/site-packages/django/core/urlresolvers.py" in resolve
  365.             for pattern in self.url_patterns:
File "/Users/yobichi/wi/lib/python3.5/site-packages/django/core/urlresolvers.py" in url_patterns
  401.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "/Users/yobichi/wi/lib/python3.5/site-packages/django/core/urlresolvers.py" in urlconf_module
  395.             self._urlconf_module = import_module(self.urlconf_name)
File "/Users/yobichi/wi/lib/python3.5/importlib/__init__.py" in import_module
  126.     return _bootstrap._gcd_import(name[level:], package, level)
File "/Users/yobichi/wi/raptle/raptle/urls.py" in <module>
  21.     url(r'^rap_song/', include('rap_song.urls', namespace = "rap_song")),
File "/Users/yobichi/wi/lib/python3.5/site-packages/django/conf/urls/__init__.py" in include
  33.         urlconf_module = import_module(urlconf_module)
File "/Users/yobichi/wi/lib/python3.5/importlib/__init__.py" in import_module
  126.     return _bootstrap._gcd_import(name[level:], package, level)
File "/Users/yobichi/wi/raptle/rap_song/urls.py" in <module>
  2. from . import views
File "/Users/yobichi/wi/raptle/rap_song/views.py" in <module>
  10. from .topicWords import update_topic
File "/Users/yobichi/wi/raptle/rap_song/topicWords.py" in <module>
  12. import matplotlib.pyplot as plt
File "/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py" in <module>
  1131. rcParams = rc_params()
File "/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py" in rc_params
  975.     return rc_params_from_file(fname, fail_on_error)
File "/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py" in rc_params_from_file
  1100.     config_from_file = _rc_params_in_file(fname, fail_on_error)
File "/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py" in _rc_params_in_file
  1018.     with _open_file_or_url(fname) as fd:
File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py" in __enter__
  59.             return next(self.gen)
File "/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py" in _open_file_or_url
  1000.         encoding = locale.getdefaultlocale()[1]
File "/Users/yobichi/wi/lib/python3.5/locale.py" in getdefaultlocale
  559.     return _parse_localename(localename)
File "/Users/yobichi/wi/lib/python3.5/locale.py" in _parse_localename
  487.     raise ValueError('unknown locale: %s' % localename)

Can you help me on this issue? Thanks in advance!

**Comment by amueller** [comment]
can you provide the code that returned this error?
I don't see wordcloud anywhere in there.

**Comment by rylanchiu** [comment]
nearly all are copied from your example:
rapper_mask = np.array(Image.open(path.join(d, "rap_song/rapper.png")))

	wc = WordCloud(background_color="white", max_words=2000, mask=rapper_mask)
	# generate word cloud
	wc.generate(user_topic.topic_word)

	# store to file
	wc.to_file(path.join(d, "rap_song/rapper1.png"))

	# show
	plt.imshow(wc)
	plt.axis("off")
	plt.figure()
	plt.imshow(rapper_mask, cmap=plt.cm.gray)
	plt.axis("off")
	plt.show()

Where user_topic.topic_word is string of Chinese character.
Thanks a lot!

**Comment by rylanchiu** [comment]
Actually, I think you are right. The problem is not caused by word_cloud but matplotlib. So I will go to close this issue. But I would be quite grateful if you have any ideas about it. Thanks!

**Comment by amueller** [comment]
If you have a minimum reproducing example, that would probably help debugging. The traceback seems to be in a django app.

**Comment by rylanchiu** [comment]
I copied the most common example form yours and tried it on ipython, the error is still exist. 
The traceback is as below:
ValueError                                Traceback (most recent call last)
<ipython-input-51-5cf9388b587b> in <module>()
      1 from os import path
      2 from wordcloud import WordCloud
----> 3 import matplotlib.pyplot as plt
      4 d = path.dirname(__file__)
      5 

/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py in <module>()
   1129 
   1130 # this is the instance used by the matplotlib classes
-> 1131 rcParams = rc_params()
   1132 
   1133 if rcParams['examples.directory']:

/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py in rc_params(fail_on_error)
    973         return ret
    974 
--> 975     return rc_params_from_file(fname, fail_on_error)
    976 
    977 

/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py in rc_params_from_file(fname, fail_on_error, use_default_template)
   1098         parameters specified in the file. (Useful for updating dicts.)
   1099     """
-> 1100     config_from_file = _rc_params_in_file(fname, fail_on_error)
   1101 
   1102     if not use_default_template:

/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py in _rc_params_in_file(fname, fail_on_error)
   1016     cnt = 0
   1017     rc_temp = {}
-> 1018     with _open_file_or_url(fname) as fd:
   1019         try:
   1020             for line in fd:

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py in __enter__(self)
     57     def __enter__(self):
     58         try:
---> 59             return next(self.gen)
     60         except StopIteration:
     61             raise RuntimeError("generator didn't yield") from None

/Users/yobichi/wi/lib/python3.5/site-packages/matplotlib/__init__.py in _open_file_or_url(fname)
    998     else:
    999         fname = os.path.expanduser(fname)
-> 1000         encoding = locale.getdefaultlocale()[1]
   1001         if encoding is None:
   1002             encoding = "utf-8"

/Users/yobichi/wi/lib/python3.5/locale.py in getdefaultlocale(envvars)
    557     else:
    558         localename = 'C'
--> 559     return _parse_localename(localename)
    560 
    561 

/Users/yobichi/wi/lib/python3.5/locale.py in _parse_localename(localename)
    485     elif code == 'C':
    486         return None, None
--> 487     raise ValueError('unknown locale: %s' % localename)
    488 
    489 def _build_localename(localetuple):

ValueError: unknown locale: UTF-8

**Comment by amueller** [comment]
http://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8

**Comment by rylanchiu** [comment]
@amueller  Thank you so much! The issue has been solved. But another error is raised: 

This application failed to start because it could not find or load the Qt platform plugin "cocoa".
Available platform plugins are: cocoa, minimal, offscreen.

Why does it happen?

Thanks for your work!
